objects/Account_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Competitor1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup field to object account for competitor</description>
        <label>Competitor 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans (Competitor 1)</relationshipLabel>
        <relationshipName>Account_Plans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <description>Lookup on Account</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CtrlCreateAccountPlan_Test.cls
/**
*	This test class is for CtrlCreateAccountPlan.
*
@author Di Chen
@created 2012-06-07
@version 1.0
@since 20.0
*
@changelog
* 2012-06-07 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 100%
*/
@isTest
private class CtrlCreateAccountPlan_Test {

    static testMethod void testMethods() {
        
        Account acc = ClsTestHelp.createTestAccounts();
        insert acc;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('accId',acc.Id);
        CtrlCreateAccountPlan ctrl = new CtrlCreateAccountPlan();
        
        ctrl.newOrViewAccountPlan();
        ctrl.createAccountPlan();
        ctrl.cancel();
        
        system.assert(true);
        Test.stopTest();
    }
	static testMethod void testMethods2() {
        
    	RecordType rt = ClsTestHelp.createTestRecordType6();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.Customer_Classification__c = 'A';
    	acc.Type = 'Competitor';
    	insert acc;
        
        Account_Plan__c ap = ClsTestHelp.createTestAccountPlan();
        ap.Customer__c = acc.Id;
        ap.Active__c = true;
        //ap.Competitor1__c = acc.Id;
        insert ap;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('accId',acc.Id);
        CtrlCreateAccountPlan ctrl = new CtrlCreateAccountPlan();
        
        ctrl.newOrViewAccountPlan();
        ctrl.createAccountPlan();
        ctrl.cancel();
        
        system.assert(true);
        Test.stopTest();
    }
}