objects/Account_Team__c.object
<CustomObject>
    <description>This custom object is used instead of standard object Account Team. Access to the accounts is given by Apex Managed Sharing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Customer team member is being added to</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>Account_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <description>This field defines the opportunity access level for the defined user.</description>
        <inlineHelpText>Defines the opportunity access level.</inlineHelpText>
        <label>Opportunity Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Access</fullName>
                </value>
                <value>
                    <fullName>Read-Only</fullName>
                </value>
                <value>
                    <fullName>Edit</fullName>
                    <default>true</default>
                    <label>Edit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>The values

•	Global Account Manager (GAM), 
•	Field Engineer 
•	FE &amp;Field Service Engineer (FSE).
•	Relay Specialist (IS)
•	Customer Service Rep (CSR)
•	Accounts Clerk
•	Account Manager (AM)
 
cannot be chosen, as they are system roles.</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Manager (AM)</fullName>
                </value>
                <value>
                    <fullName>Accounts Clerk</fullName>
                </value>
                <value>
                    <fullName>Core Team Leader (CTL)</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rep (CSR)</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Field Application Engineer (FAE)</fullName>
                </value>
                <value>
                    <fullName>Field Engineer (FE)</fullName>
                </value>
                <value>
                    <fullName>Field Service Engineer (FSE)</fullName>
                </value>
                <value>
                    <fullName>Global Account Manager (GAM)</fullName>
                </value>
                <value>
                    <fullName>Industry Marketing</fullName>
                </value>
                <value>
                    <fullName>Labels Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Market Manager (MM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Product Management (PM)</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Relay Specialist (IS)</fullName>
                </value>
                <value>
                    <fullName>Sales Engineer (SE)</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Distribution Application Engineer (DAE)</fullName>
                </value>
                <value>
                    <fullName>Distribution Market Manager (DMM)</fullName>
                </value>
                <value>
                    <fullName>ADM - Sales Team - System Generated</fullName>
                </value>
                <value>
                    <fullName>ADM - Sales Team - System Generated - A Terr</fullName>
                </value>
                <value>
                    <fullName>ADM - Sales Manager - System Generated</fullName>
                </value>
                <value>
                    <fullName>Industry Development</fullName>
                </value>
                <value>
                    <fullName>ADM Sales Team (B-Territory)</fullName>
                </value>
                <value>
                    <fullName>Alternative Territory 1 (AT1)</fullName>
                </value>
                <value>
                    <fullName>Alternative Territory 2 (AT2)</fullName>
                </value>
                <value>
                    <fullName>Alternative Territory Inside Sales (ATS)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Teams</relationshipLabel>
        <relationshipName>Account_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member_Formula__c</fullName>
        <description>This field is used to show the team members name in the related list. If a user is related the users name is shown, if a contact is related the contacts name is shown.

IF(
	NOT(
		ISBLANK(Team_Member__c)
	), 
	HYPERLINK(&quot;/&quot; &amp; Team_Member__c, Team_Member__r.FirstName &amp; &quot; &quot; &amp; Team_Member__r.LastName), 
	HYPERLINK(&quot;/&quot; &amp; Team_Member_Contact__c, Team_Member_Contact__r.FirstName  &amp; &quot; &quot; &amp; Team_Member_Contact__r.LastName)
)</description>
        <formula>IF(
	NOT(
		ISBLANK(Team_Member__c)
	), 
	HYPERLINK(&quot;/&quot; &amp; Team_Member__c, Team_Member__r.FirstName &amp; &quot; &quot; &amp; Team_Member__r.LastName), 
	Team_Member_txt__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member_Key__c</fullName>
        <description>External Key for upserting account team members with their appropriate roles</description>
        <externalId>true</externalId>
        <inlineHelpText>Because there may be &gt; 1 Account Manager per account, need to include User Id as shown in Team Member text as part of the external Id.  Otherwise, uses team member reference, as this will be null for any team member who is not a salesforce user.</inlineHelpText>
        <label>Team Member Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Look-up to the user being added to the team</inlineHelpText>
        <label>Team Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member_txt__c</fullName>
        <description>This field is used to define non SFDC users as Account Team Members. Just put the members name in there.</description>
        <inlineHelpText>Type the name of the person being added to the team that does not have a Salesforce.com account</inlineHelpText>
        <label>Team Member</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <description>This field is used to replace the standard record name field from related list.</description>
        <formula>HYPERLINK(&quot;/&quot; &amp; Id,IMAGE(&quot;/img/icon/tasks16.gif&quot;,&quot;View&quot;),&quot;_parent&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>View</label>
        <type>Text</type>
    </fields>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>CFT-{000000}</displayFormat>
        <label>Account Team Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <recordTypes>
        <fullName>SFDC_User</fullName>
        <active>true</active>
        <description>This record type is used for SFDC Users.</description>
        <label>SFDC User</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClsBatch_initStdAccountTeam.cls
/**
 *  Contains a set of static methods used in invoice creation triggers and VF pages
 *
 @author Bin Yuan
 @created 2012-01-05
 @version 1.0
 @since 25.0 (Force.com ApiVersion)
 *
 @changelog
 * 2014-04-17 Bin Yu <bin.yu@itbconsult.com>
 * - excluded the Chatter free user from account team
 * 2012-01-05 Bin Yuan <bin.yuan@itbconsult.com>
 * - Created
 */

global class ClsBatch_initStdAccountTeam implements Database.Batchable<SObject> {

    /**
     * the email address to tell people the status of the batch class after run the batch class
     * before run the batch class, we can define the email manual
     * if not define email address, after the batch completed, will not send email
     */ 
    public String email;
    Public String chatterFreeUser = 'Chatter Free User';
    
    /**
     * the sql query statement that will select the data will be used in this batch class
     */ 
    public String query;

    /**
     * the record type id for gam account, the value get from custom setting
     */     
    global final Id rt_cis_gam = ClsSharingUtil.gamCustomSetting();
    global final set<String> set_role = new set<String>{'Account Manager (AM)','Relay Specialist (IS)','Field Engineer (FE)','Global Account Manager (GAM)','Tubing FE (MM)','Field Service Engineer (FSE)'};
    global map<string,integer>  map_access_int = new  map<string,integer>{
        'Edit' => 3,
        'Read-Only' => 2,
        'No Access' => 1
    } ; 
    global Database.QueryLocator start(Database.BatchableContext BC){ 
        if (query == '' || query == null){
            query = 'Select Id, ParentId, RecordTypeId, Public_Group_Id__c from Account'; // where Id = \'001E000000BzPdwIAF\'' ;
        }
        return Database.getQueryLocator(query);  
    }

    global void execute(Database.BatchableContext BC, List<Account> list_accounts){
        set<Id> set_accountIds = new set<Id>();
        map<Id, Account_Team__c> map_acctTeamId_acctTeam = new map<Id, Account_Team__c>();
        map<Id,map<Id,Account_Team__c>> map_accId_uId_atm = new map<Id,map<Id,Account_Team__c>>();
        for(Account acct : list_accounts) {
            set_accountIds.add(acct.Id);
        }
        
        for(Account_Team__c acctTeam : [SELECT Account__c, Name, Opportunity_Access__c, ConnectionReceivedId, Id, RecordTypeId, 
                                               Role__c, ConnectionSentId, Team_Member_Contact__c, Team_Member_Formula__c, 
                                               Team_Member__c, Team_Member_txt__c, Team_Member_Key__c, View__c 
                                        FROM   Account_Team__c
                                        WHERE  Account__c IN : set_accountIds 
                                        AND    RecordType.DeveloperName = 'SFDC_User' and Team_Member__r.IsActive = true and Team_Member__r.Profile.Name != :chatterFreeUser]) { //added ' and Team_Member__r.Profile.Name != :chatterFreeUser' by BYU at 2014-04-17 
            
            // check opportunity access
            if(!map_accId_uId_atm.containsKey(acctTeam.Account__c)){
                map_accId_uId_atm.put(acctTeam.Account__c, new map<Id,Account_Team__c>());
            }
            
            if(map_accId_uId_atm.get(acctTeam.Account__c).containsKey(acctTeam.Team_Member__c)){
                Account_Team__c temp = map_accId_uId_atm.get(acctTeam.Account__c).get(acctTeam.Team_Member__c);
                if(!set_role.contains(temp.Role__c)){
                    if(map_access_int.get(temp.Opportunity_Access__c) < map_access_int.get(acctTeam.Opportunity_Access__c)){
                        map_accId_uId_atm.get(acctTeam.Account__c).put(acctTeam.Team_Member__c,acctTeam);
                    }   
                }
            }else{
                map_accId_uId_atm.get(acctTeam.Account__c).put(acctTeam.Team_Member__c,acctTeam);
            }
                                        
        }

        
        list<Account_Team__c> list_tmp = new list<Account_Team__c>();
        for(Id accId: map_accId_uId_atm.keyset()){
            list_tmp.addAll(map_accId_uId_atm.get(accId).values());
        }
        //Delete old standard account team members by using set_accountIds.
        ClsAccountTeamUtil.deleteOldStdAccountTeam(set_accountIds);
        //Copy custom account team members' information to create new standard account team members.
        if(!list_tmp.isEmpty()){
            ClsAccountTeamUtil.generateStdAcctTeamFromCustomAcctTeam(list_tmp);
        }           
        
    }

    global void finish(Database.BatchableContext BC){ 
        if(email != null) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[] {email});
            mail.setReplyTo(Email);
            mail.setSenderDisplayName('Cleanup job');
            mail.setSubject('Batch Processing ClsBatch_AccountSharing Completed');
            mail.setPlainTextBody('Batch Processing ClsBatch_AccountSharing has completed');
            //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
        } 
    }   
    
}