objects/Account_Plan__c.object
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Plan_Attachment__c.object
<CustomObject>
    <description>This object is used to link attachment to the Account Plan.</description>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <description>Master Detail Relation to Account Plan</description>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Account Plan Attachments</relationshipLabel>
        <relationshipName>Account_Plan_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AttachmentId__c</fullName>
        <description>This field contains the attachment Id.</description>
        <label>AttachmentId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>This field contains the content type.</description>
        <label>Content Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attachment</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plan Attachment</label>
    <nameField>
        <label>Account Plan Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plan Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CtrlAccountPlanAttachment.cls
/**
 *  Controller class for page CtrlAccountPlanAttachment_generateAttach
 * 
 * @author Yuanyuan Zhang
 * @created 2012-05-18
 * @version 1.0
 * @since 23.0(ForceIDE Version)
 * 
 * 
 *
 * @changelog
 * 2012-05-18 Yuanyuan Zhang <yuanyuan.zhang@itbconsult.com>
 * - Created   
 *
 */

public class CtrlAccountPlanAttachment {

    public String accountPlanId{get;set;}
    public String parentName{get;set;}
    public Account_Plan_Attachment__c accountPlanAttachment{get;set;}
    public Attachment att{get;set;}
    Public String attachmentName{get;set;}
    Public Blob attachmentBody{get;set;}
    Public Blob attachmentSize{get;set;}
    Public Boolean finishedInsert{get;set;}
    Public Boolean error{get;set;}
    Public Boolean errorTwo{get;set;}
    
    //constructor
    public CtrlAccountPlanAttachment(){
        error = false;
        //finishedInsert = false;
        accountPlanAttachment = new Account_Plan_Attachment__c();
        att = new Attachment();
        accountPlanId = ApexPages.CurrentPage().getParameters().get('id');
        parentName = ApexPages.CurrentPage().getParameters().get('parentName');
        finishedInsert = false;
    }
             
    public pagereference save(){        
        if(att.Body == null){
            error = true;
            finishedInsert = false;
            return null;
        }  
        if(att.BodyLength > 3){
            error = true;
            finishedInsert = false;
            return null;
        }       
        else if(attachmentName == 'Logo.jpg'){
            errorTwo = true;
            finishedInsert = false;
            return null;
        }
        else if(attachmentName == 'VoiceOverview.wav'){
            errorTwo = true;
            finishedInsert = false;
            return null;
        }
        else if(attachmentName == 'Photo.jpg'){
            errorTwo = true;
            finishedInsert = false;
            return null;
        }
        else if(attachmentName.startsWith('Picture')){
        	errorTwo = true;
            finishedInsert = false;
            return null;
        }
        else{     
          att.Name = attachmentName;
          att.ParentId = accountPlanId;     
          try{      
            insert att;
          }
          catch(Exception ex){
            accountPlanAttachment = new Account_Plan_Attachment__c();
            att = new Attachment();
            error = true;
            finishedInsert = false;
            return null;
          }
        
          accountPlanAttachment.Name = att.Name;
          accountPlanAttachment.Account_Plan__c = accountPlanId;
          accountPlanAttachment.AttachmentId__c = att.Id;
          accountPlanAttachment.Type__c = 'Attachment';
          accountPlanAttachment.Content_Type__c = att.ContentType;
          insert accountPlanAttachment;       
        
          finishedInsert = true;
          error = false;
          accountPlanAttachment = new Account_Plan_Attachment__c();
          att = new Attachment();
        }
        return null;
    }
}