objects/Account_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Unlocked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU_Revenue_CY_Forecast_M__c</fullName>
        <inlineHelpText>Current Year WIP BU Forecast in Millions</inlineHelpText>
        <label>BU Revenue CY Forecast M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BU_Revenue_Fcst_Plan_Yr_1_M__c</fullName>
        <inlineHelpText>Plan Year+1 Forecasted Revenue for this BU in Millions</inlineHelpText>
        <label>BU Revenue Fcst Plan Yr+1 M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BU_Revenue_Fcst_Plan_Yr_4_M__c</fullName>
        <inlineHelpText>Plan Year+4 Forecasted Revenue for this BU in Millions</inlineHelpText>
        <label>BU Revenue Fcst Plan Yr+4 M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BU_Revenue_Fcst_Plan_Yr_M__c</fullName>
        <inlineHelpText>Plan Year Forecasted Revenue for this BU in Millions</inlineHelpText>
        <label>BU Revenue Fcst Plan Yr M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BU_Revenue_Prior_Yr_Actual_M__c</fullName>
        <inlineHelpText>Prior Year Actual BU Revenue in Millions (direct and/or indirect based on the Sales Figure Makeup specified in the account plan definition section) .</inlineHelpText>
        <label>BU Revenue Prior Yr Actual M</label>
        <precision>7</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BU_Revenue_YTD_Actual_M__c</fullName>
        <inlineHelpText>YTD Actual BU Revenue in Millions</inlineHelpText>
        <label>BU Revenue YTD Actual M</label>
        <precision>7</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup field to object account for competitor</description>
        <label>Competitor 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans (Competitor 1)</relationshipLabel>
        <relationshipName>Account_Plans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <description>Lookup on Account</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gross_Margin_Pct_Plan_Yr_1__c</fullName>
        <label>Gross Margin Pct Plan Yr+1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Margin_Pct_Plan_Yr_4__c</fullName>
        <label>Gross Margin Pct Plan Yr+4</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Margin_Pct_Plan_Yr__c</fullName>
        <label>Gross Margin Pct Plan Yr</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Margin_Pct_Prior_Yr__c</fullName>
        <label>Gross Margin Pct Prior Yr</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Update__c</fullName>
        <inlineHelpText>Provide a recap of key changes such as won/lost orders or opportunities, milestones achieved on programs, info about the customer (e.g. completed acquisition, financials, etc) and, if nothing has changed, state that.  State essence quickly and concisely.</inlineHelpText>
        <label>Monthly Update</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Replicate_to_Central_Org__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ture, generate a ACustomerProfile record from this Account Plan</description>
        <label>Replicate to Central Org</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue_TAM_SAM__c</fullName>
        <description>Indicate whether you will be supplying figures for TAM or for SAM.</description>
        <label>Revenue TAM/SAM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TAM</fullName>
                </value>
                <value>
                    <fullName>SAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Initiative_5_Status__c</fullName>
        <label>Strategic Initiative 5 Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On target</fullName>
                </value>
                <value>
                    <fullName>In process with delays possible</fullName>
                </value>
                <value>
                    <fullName>Not on target</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TAM_Plan_Year_M__c</fullName>
        <inlineHelpText>TAM (Total Available Market) for the Plan Year in
			Millions</inlineHelpText>
        <label>TAM Plan Yr M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TAM_Plan_Yr_1_M__c</fullName>
        <inlineHelpText>TAM (Total Available Market) for the Plan Year+1 in
			Millions</inlineHelpText>
        <label>TAM Plan Yr+1 M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TAM_Plan_Yr_4_M__c</fullName>
        <inlineHelpText>TAM (Total Available Market) for the Plan Year+4 in
			Millions</inlineHelpText>
        <label>TAM Plan Yr+4 M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TAM_Prior_Yr_M__c</fullName>
        <inlineHelpText>TAM (Total Available Market) for the Year prior to the
			Plan Year in Millions</inlineHelpText>
        <label>TAM Prior Yr M</label>
        <precision>7</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TE_Performance_Status__c</fullName>
        <label>TE Performance Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Solid, holding</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TE_Revenue_CY_Forecast_M__c</fullName>
        <inlineHelpText>Current Year WIP TE Forecast in Millions</inlineHelpText>
        <label>TE Revenue CY Forecast M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TE_Revenue_Fcst_Plan_Yr_1_M__c</fullName>
        <inlineHelpText>Plan Year+1 Forecasted TE Revenue in Millions</inlineHelpText>
        <label>TE Revenue Fcst Plan Yr+1 M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TE_Revenue_Fcst_Plan_Yr_4_M__c</fullName>
        <inlineHelpText>Plan Year+4 Forecasted TE Revenue in Millions</inlineHelpText>
        <label>TE Revenue Fcst Plan Yr+4 M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TE_Revenue_Fcst_Plan_Yr_M__c</fullName>
        <inlineHelpText>Plan Year Forecasted TE Revenue in Millions</inlineHelpText>
        <label>TE Revenue Fcst Plan Yr M</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TE_Revenue_Prior_Yr_Actual_M__c</fullName>
        <inlineHelpText>Prior Year Actual TE Revenue in Millions (direct and/or indirect based on the Sales Figure Makeup specified in the account plan definition section) .</inlineHelpText>
        <label>TE Revenue Prior Yr Actual M</label>
        <precision>7</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TE_Revenue_YTD_Actual_M__c</fullName>
        <inlineHelpText>YTD Actual TE Revenue in Millions</inlineHelpText>
        <label>TE Revenue YTD Actual M</label>
        <precision>7</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrgAccountPlan_BIU_updateModifier_Test.cls
/**
*   This test class is for AccountPlan_BIU_updateModifier.
*
@author Di Chen
@created 2012-06-25
@version 1.0
@since 20.0
*
@changelog
* 2012-06-25 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 98%
*/
@isTest
private class TrgAccountPlan_BIU_updateModifier_Test {

    static testMethod void myUnitTest() {
        
        RecordType rt = ClsTestHelp.createTestRecordType6();
         RecordType rt2 = ClsTestHelp.createTestRecordType8();
        
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt2.Id;
        acc.Customer_Classification__c = 'B';
        acc.Type = 'Competitor';
        acc.GAMCD__c = '1000';
        insert acc;
        
        Account_Plan__c apOld = ClsTestHelp.createTestAccountPlan();
        apOld.Customer__c = acc.Id;
        //apOld.Competitor1__c = acc.Id;
        apOld.Replicate_to_Central_Org__c = false;
        apOld.Replicate_to_Central_Org__c = true;
        apOld.Strategic_Initiative_5_Status__c = 'On target';
        apOld.Approval_Status__c = 'Not Submitted';
        apOld.Monthly_Update__c = 'test';
        apOld.TE_Performance_Status__c = 'Positive';
        apOld.TE_Revenue_Prior_Yr_Actual_M__c = 12;
        apOld.TE_Revenue_YTD_Actual_M__c = 12;
        apOld.TE_Revenue_CY_Forecast_M__c = 12;
        apOld.TE_Revenue_Fcst_Plan_Yr_M__c = 12;
        apOld.TE_Revenue_Fcst_Plan_Yr_1_M__c = 12;
        apOld.TE_Revenue_Fcst_Plan_Yr_4_M__c = 12;
        apOld.BU_Revenue_Prior_Yr_Actual_M__c = 12;
        apOld.BU_Revenue_YTD_Actual_M__c = 12;
        apOld.BU_Revenue_CY_Forecast_M__c = 12;
        apOld.BU_Revenue_Fcst_Plan_Yr_M__c = 12;
        apOld.BU_Revenue_Fcst_Plan_Yr_1_M__c = 12;
        apOld.BU_Revenue_Fcst_Plan_Yr_4_M__c = 12;
        apOld.Revenue_TAM_SAM__c = 'TAM';
        apOld.TAM_Prior_Yr_M__c = 12;
        apOld.TAM_Plan_Year_M__c = 12;
        apOld.TAM_Plan_Yr_1_M__c = 12;
        apOld.TAM_Plan_Yr_4_M__c = 12;
        apOld.Gross_Margin_Pct_Prior_Yr__c = 12;
        apOld.Gross_Margin_Pct_Plan_Yr__c = 12;
        apOld.Gross_Margin_Pct_Plan_Yr_1__c = 12;
        apOld.Gross_Margin_Pct_Plan_Yr_4__c = 12;
        Test.startTest();
        
        insert apOld;
        
        apOld.Monthly_Update__c = 'tttt';
        apOld.TE_Performance_Status__c = 'Solid, holding';
        apOld.TE_Revenue_Prior_Yr_Actual_M__c = 14;
        apOld.TE_Revenue_YTD_Actual_M__c = 14;
        apOld.TE_Revenue_CY_Forecast_M__c = 14;
        apOld.TE_Revenue_Fcst_Plan_Yr_M__c = 14;
        apOld.TE_Revenue_Fcst_Plan_Yr_1_M__c = 14;
        apOld.TE_Revenue_Fcst_Plan_Yr_4_M__c = 14;
        apOld.BU_Revenue_Prior_Yr_Actual_M__c = 14;
        apOld.BU_Revenue_YTD_Actual_M__c = 14;
        apOld.BU_Revenue_CY_Forecast_M__c = 14;
        apOld.BU_Revenue_Fcst_Plan_Yr_M__c = 14;
        apOld.BU_Revenue_Fcst_Plan_Yr_1_M__c = 14;
        apOld.BU_Revenue_Fcst_Plan_Yr_4_M__c = 14;
        apOld.Revenue_TAM_SAM__c = 'SAM';
        apOld.TAM_Prior_Yr_M__c = 14;
        apOld.TAM_Plan_Year_M__c = 14;
        apOld.TAM_Plan_Yr_1_M__c = 14;
        apOld.TAM_Plan_Yr_4_M__c = 14;
        apOld.Gross_Margin_Pct_Prior_Yr__c = 14;
        apOld.Gross_Margin_Pct_Plan_Yr__c = 14;
        apOld.Gross_Margin_Pct_Plan_Yr_1__c = 14;
        apOld.Gross_Margin_Pct_Plan_Yr_4__c = 14;
        update apOld;
        
        system.assert(true);
        Test.stopTest();
    }
}