objects/Account_Team__c.object
<CustomObject>
    <description>This custom object is used instead of standard object Account Team. Access to the accounts is given by Apex Managed Sharing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Customer team member is being added to</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>Account_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>The values

•	Global Account Manager (GAM), 
•	Field Engineer 
•	FE &amp;Field Service Engineer (FSE).
•	Relay Specialist (IS)
•	Customer Service Rep (CSR)
•	Accounts Clerk
•	Account Manager (AM)
 
cannot be chosen, as they are system roles.</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Manager (AM)</fullName>
                </value>
                <value>
                    <fullName>Accounts Clerk</fullName>
                </value>
                <value>
                    <fullName>Core Team Leader (CTL)</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rep (CSR)</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Field Application Engineer (FAE)</fullName>
                </value>
                <value>
                    <fullName>Field Engineer (FE)</fullName>
                </value>
                <value>
                    <fullName>Field Service Engineer (FSE)</fullName>
                </value>
                <value>
                    <fullName>Global Account Manager (GAM)</fullName>
                </value>
                <value>
                    <fullName>Industry Marketing</fullName>
                </value>
                <value>
                    <fullName>Labels Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Market Manager (MM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Product Management (PM)</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Relay Specialist (IS)</fullName>
                </value>
                <value>
                    <fullName>Sales Engineer (SE)</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Distribution Application Engineer (DAE)</fullName>
                </value>
                <value>
                    <fullName>Distribution Market Manager (DMM)</fullName>
                </value>
                <value>
                    <fullName>ADM - Sales Team - System Generated</fullName>
                </value>
                <value>
                    <fullName>ADM - Sales Team - System Generated - A Terr</fullName>
                </value>
                <value>
                    <fullName>ADM - Sales Manager - System Generated</fullName>
                </value>
                <value>
                    <fullName>Industry Development</fullName>
                </value>
                <value>
                    <fullName>ADM Sales Team (B-Territory)</fullName>
                </value>
                <value>
                    <fullName>Alternative Territory 1 (AT1)</fullName>
                </value>
                <value>
                    <fullName>Alternative Territory 2 (AT2)</fullName>
                </value>
                <value>
                    <fullName>Alternative Territory Inside Sales (ATS)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Look-up to the user being added to the team</inlineHelpText>
        <label>Team Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>CFT-{000000}</displayFormat>
        <label>Account Team Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClsBatch_AccountTeamMemberSharing_Test.cls
/**
*	This test class is for ClsBatch_AccountTeamMemberSharing.
*
@author Di Chen
@created 2012-03-13
@version 1.0
@since 20.0
*
@changelog
* 2012-03-13 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 90%
*/
@isTest
private class ClsBatch_AccountTeamMemberSharing_Test {

    static testMethod void testIf() {
    	
    	RecordType rt = ClsTestHelp.createTestRecordType2();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	insert acc;

    	Account_Team__c aTeam = new Account_Team__c();
    	aTeam.Account__c = acc.Id;
    	aTeam.Role__c = 'Field Engineer (FE)';
    	aTeam.RecordTypeId = rt.Id;
    	aTeam.Team_Member__c = UserInfo.getUserId();
    	insert aTeam;
    	
        list<Account> list_acc = new list<Account>();
    	list_acc.add(acc);
        Test.startTest();
        
        ClsBatch_AccountTeamMemberSharing clsBatch = new ClsBatch_AccountTeamMemberSharing();
        clsBatch.query = 'Select Id, ParentId, RecordTypeId, Public_Group_Id__c from Account limit 1';
        clsBatch.email = 'OK@testitbconsult7891.com';
        
        Database.BatchableContext bc;
		clsBatch.start(bc);
        clsBatch.execute(bc, list_acc);
        clsBatch.finish(bc); 
        system.assert(true);
        Test.stopTest();
    }
	static testMethod void testElse() {
    	
    	RecordType rt = ClsTestHelp.createTestRecordType2();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	insert acc;

    	Account_Team__c aTeam = new Account_Team__c();
    	aTeam.Account__c = acc.Id;
    	aTeam.Role__c = 'Customer Service Rep (CSR)';
    	aTeam.RecordTypeId = rt.Id;
    	aTeam.Team_Member__c = UserInfo.getUserId();
    	insert aTeam;
    	
        list<Account> list_acc = new list<Account>();
    	list_acc.add(acc);
        Test.startTest();
        
        ClsBatch_AccountTeamMemberSharing clsBatch = new ClsBatch_AccountTeamMemberSharing();
        clsBatch.query = 'Select Id, ParentId, RecordTypeId, Public_Group_Id__c from Account limit 1';
        clsBatch.email = 'OK@testitbconsult7891.com';
        
        Database.BatchableContext bc;
		clsBatch.start(bc);
        clsBatch.execute(bc, list_acc);
        clsBatch.finish(bc); 
        system.assert(true);
        Test.stopTest();
    }
}