objects/ACP_Account_Plan__c.object
<CustomObject>
    <description>Hari 04/24/17 – Created for Account Plan</description>
    <fields>
        <fullName>ACP_Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Hari 04/24/17 – Created for Account Plan</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACP Account Plans</relationshipLabel>
        <relationshipName>Account_Plans7</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACP_GAMCode__c</fullName>
        <formula>ACP_Account_Name__r.GAMCD__c</formula>
        <label>GAM Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_KAMCode__c</fullName>
        <formula>ACP_Account_Name__r.IND_KAM_Code__c</formula>
        <label>KAM Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_WWAcNo__c</fullName>
        <formula>ACP_Account_Name__r.WWCORPACCT__c</formula>
        <label>WW Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>This is used when the Account Plan is created to denote the type of Account Plan being created. The Sold-to type is for one Account Record, the other types are collection of Account Records.</description>
        <inlineHelpText>Select the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sold-to Account</fullName>
                </value>
                <value>
                    <fullName>GAM Account</fullName>
                </value>
                <value>
                    <fullName>KAM Account</fullName>
                </value>
                <value>
                    <fullName>WW Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ACP Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACP Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ACP_Revenue_Growth_Perf__c.object
<CustomObject>
    <description>Alka 04/24/17 Created For Account Plan 
Object to capture information on Revenue Growth for Account Plan Performance review and plan</description>
    <fields>
        <fullName>ACP_Account_Plan__c</fullName>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Account Plan</label>
        <referenceTo>ACP_Account_Plan__c</referenceTo>
        <relationshipLabel>Revenue Growth</relationshipLabel>
        <relationshipName>Revenue_Growths</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACP_Current_Year_1_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Current Year + 1 Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Current_Year_3_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Year + 3 Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Current_Year_5_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Current Year + 5 Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Current_Year_to_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Current Year to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Fiscal_Year__c</fullName>
        <description>Hari Created for Account Plan to store Fiscal Year</description>
        <label>Fiscal Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_Past_Year_1_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Past Year - 1 Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Past_Year_to_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Past Year to Date</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Past_year_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Past year Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Refresh_Based_on__c</fullName>
        <description>Alka 04/24/17 – Account Plan Performance review and plan
Based on this value the data on the Reveunue Growth will be changed.</description>
        <label>Refresh Based on</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                    <default>true</default>
                    <label>Billing</label>
                </value>
                <value>
                    <fullName>Booking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACP_Sales_Mode__c</fullName>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Sales Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CMA</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>Combined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Revenue Growth</label>
    <nameField>
        <displayFormat>RG-{00000000}</displayFormat>
        <label>Revenue Growth Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Growth</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BBB_Month_Bill_Book_Cust__c.object
<CustomObject>
    <description>Monthly bookings and billings by customer (Account), includes Direct Sales / Distribution POS / CMA (Contract Manufacturer&apos;s Allocation)</description>
    <fields>
        <fullName>Bill_Type__c</fullName>
        <inlineHelpText>Direct Sales / Distribution POS / CMA (Contract Manufacturer&apos;s Allocation)</inlineHelpText>
        <label>Bill Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                    <default>true</default>
                    <label>Direct</label>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>CMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <inlineHelpText>Identifies the TE Fiscal Month of the Sales</inlineHelpText>
        <label>Fiscal Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <inlineHelpText>Identifies the TE Fiscal Month of the Sale</inlineHelpText>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Monthly Billings/Bookings by Account</label>
    <nameField>
        <displayFormat>MBBB-{0}</displayFormat>
        <label>Monthly BBB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Billings/Bookings by Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ACP_Revenue_Growth_Ctrl.cls
/******************************************************************************************************************
Name: ACP_Revenue_Growth_Ctrl
Copyright @ 2017 TE Connectivity
=============================================================================
Requirement:
ACP_Revenue_Growth_Ctrl for ACP_Performance_Analytics_Page
=============================================================================
Purpose:
Controller to add and edit ACP_Revenue_Growth_Perf__c records and display data on 
Revenue and Growth table on ACP_Performance_Analytics_Page
Test class:
ACP_Revenue_Growth_Ctrl_Test
=============================================================================
History
-------
VERSION   AUTHOR        DATE         DETAIL
1.0 -    Anushka Bansal 10/06/17     INITIAL DEVELOPMENT
2.0 -    Anushka Bansal 11/02/17     Added comments 
********************************************************************************************************************/
public with sharing class ACP_Revenue_Growth_Ctrl {
 public String acpId {
  get;
  set;
 }
 public String refreshBasedOn {
  get;
  set;
 }
 public String revType {
  get;
  set;
 }
 public ACP_Revenue_Growth_Perf__c revenueGrowthTotal {
  get;
  set;
 }
 private final ACP_Account_Plan__c Act;
 public Map < String, List < Reports.SummaryValue >> mapReport1;
 public Map < String, List < Reports.SummaryValue >> mapReport2;
 public List < String > keySet;
 public LIST < Reports.SummaryValue > summaryValues = new LIST < Reports.SummaryValue > ();
 public ACP_Account_Plan__c accplan {
  get;
  set;
 }
 public List < ACP_Revenue_Growth_Perf__c > revenueGrowthList {
  get;
  set;
 }
 public List < ACP_Revenue_Growth_Perf__c > businessPerfList {
  get;
  set;
 }
 public Map < String, ACP_Revenue_Growth_Perf__c > revenueGrowthMap = new Map < String, ACP_Revenue_Growth_Perf__c > ();
 // public String fieldSetStr{get;set;}
 public Integer fiscalyr {
  get;
  set;
 }
 public Integer pastyr {
  get;
  set;
 }
 public Integer pastyr_1 {
  get;
  set;
 }
 String fy = '';
 FiscalYearSettings fiscalYear;
 public ACP_Revenue_Growth_Ctrl() {



  acpid = ApexPages.currentPage().getParameters().get('acpId');

  ACP_Account_Plan__c acntPlan = new ACP_Account_Plan__c();
  fiscalYear = [select name, StartDate from FiscalYearSettings where StartDate <= : date.today() AND EndDate >= : date.today()];
  if (fiscalYear != null) {
   fy = fiscalYear.name;
   fiscalyr = Integer.valueOf(fy);
   pastyr = fiscalyr - 1;
   pastYr_1 = pastyr - 1;
  }

 }
 public Pagereference runReport() {
  try {
   ACP_Account_Plan__c accplan = [select id, Account_Plan_Type__c, ACP_GAMCode__c, ACP_KAMCode__c, ACP_WWAcNo__c, ACP_Account_Name__c from ACP_Account_Plan__c where id = : acpId];

   String acctId = accplan.ACP_Account_Name__c;
   List < Period > p2 = [SELECT Id, PeriodLabel, StartDate, Type FROM Period WHERE StartDate <= today AND StartDate >= : fiscalYear.StartDate and type = 'month'];
    
   String fiscalMonth = '';
   for (Integer i = 1; i < p2.size(); i++) {
    fiscalMonth = fiscalMonth + i + ',';
   }
   if(fiscalMonth.length() > 1)
   fiscalMonth = fiscalMonth.substring(0, fiscalMonth.length() - 1);
   else
   fiscalMonth = '0';
    system.debug('month =-=-=-=-=-=-=-=- '+ fiscalMonth);

   // ------------- Fetching reports and report metadata----------------//
   String reportId = 'ACP_Revenue_Growth_Report1';
   Report report = Database.query('SELECT Id, Developername, format FROM Report WHERE developerName =: reportId');
   Reports.ReportDescribeResult describe = Reports.ReportManager.describeReport((String) report.Id);
   Reports.ReportMetadata reportMd = describe.getReportMetadata();
   Reports.reportResults results;


   String reportId2 = 'ACP_Revenue_Growth_Report2';
   Report report2 = Database.query('SELECT Id, Developername, format FROM Report WHERE developerName =: reportId2');
   Reports.ReportDescribeResult describe2 = Reports.ReportManager.describeReport((String) report2.Id);
   Reports.ReportMetadata reportMd2 = describe2.getReportMetadata();
   Reports.reportResults results2;

   List < Reports.ReportFilter > filters = new List < Reports.ReportFilter > ();
   List < Reports.ReportFilter > filters2 = new List < Reports.ReportFilter > ();

   Map < String, Reports.ReportFilter > filterMap = new Map < String, Reports.ReportFilter > ();

   //--------- setting filters for report 1 -----------------//
   for (Integer i = 0; i < 5; i++) {
    String key = reportMd.getReportFilters()[i].getColumn();
    filterMap.put(key, reportMd.getReportFilters()[i]);
   }
   filterMap.get('BBB_Month_Bill_Book_Cust__c.Fiscal_Year__c').setValue(String.valueof(pastyr) + ',' + String.valueof(pastyr_1));

   if (accplan.Account_Plan_Type__c == 'Gam Account')
    filterMap.get('Account.GAMCD__c').setValue(accplan.ACP_GAMCode__c);

   else if (accplan.Account_Plan_Type__c == 'Kam Account')
    filterMap.get('Account.IND_KAM_Code__c').setValue(accplan.ACP_KAMCode__c);

   else if (accplan.Account_Plan_Type__c == 'WW Account')
    filterMap.get('Account.WWCORPACCT__c').setValue(accplan.ACP_WWAcNo__c);

   else
    filterMap.get('ACCOUNT_ID').setValue(acctId.left(15));


   for (Reports.ReportFilter f: filterMap.values())
    filters.add(f);

   reportMd.setReportFilters(filters);

   results = Reports.ReportManager.runReport((String) report.Id, reportMd, true);
   //--------- setting filters for report 2 -----------------//
   filterMap.clear();
   for (Integer i = 0; i < 6; i++) {
    String key = reportMd2.getReportFilters()[i].getColumn();
    filterMap.put(key, reportMd2.getReportFilters()[i]);
    //filterMap.get(key).setValue('');
   }
   // filterMap.get('BBB_Month_Bill_Book_Cust__c.Bill_Type__c').setValue(revType);
   filterMap.get('BBB_Month_Bill_Book_Cust__c.Fiscal_Year__c').setValue(fy + ',' + String.valueof(pastyr));
   filterMap.get('BBB_Month_Bill_Book_Cust__c.Fiscal_Month__c').setValue(fiscalMonth);

   if (accplan.Account_Plan_Type__c == 'Gam Account')
    filterMap.get('Account.GAMCD__c').setValue(accplan.ACP_GAMCode__c);

   else if (accplan.Account_Plan_Type__c == 'Kam Account')
    filterMap.get('Account.IND_KAM_Code__c').setValue(accplan.ACP_KAMCode__c);

   else if (accplan.Account_Plan_Type__c == 'WW Account')
    filterMap.get('Account.WWCORPACCT__c').setValue(accplan.ACP_WWAcNo__c);

   else
    filterMap.get('ACCOUNT_ID').setValue(acctId.left(15));

   for (Reports.ReportFilter f: filterMap.values())
    filters2.add(f);

   reportMd2.setReportFilters(filters2);
   system.debug('filters  -- ' + reportMd2.getReportFilters());
   results2 = Reports.ReportManager.runReport((String) report2.Id, reportMd2, true);

   Reports.Dimension dim = results.getGroupingsDown(); // fetching column labels from report 1 
   Reports.Dimension dim2 = results.getGroupingsAcross(); // fetching row labels from report 1 
   Reports.Dimension dim3 = results2.getGroupingsDown(); // fetching column labels from report 2
   Reports.Dimension dim4 = results2.getGroupingsAcross(); // fetching row labels from report 2 

   mapReport1 = new Map < String, List < Reports.SummaryValue >> ();
   mapReport2 = new Map < String, List < Reports.SummaryValue >> ();

   keyset = new List < String > ();
   keyset.add('CMA');
   keyset.add('Direct');
   keyset.add('POS');
   //keyset = revType.split(';');
   keyset.add('Combined');

   /* ----------- putting values from report 1 into a map wih key as 'rowLabel-ColumnLabel' eg 'CMA-2017' 
   and value as Reports.SummaryValue since the report contains summarizable fields ---- */
   for (Reports.GroupingValue down: dim2.getGroupings()) {
    String mapkey = '';
    String key = '';
    for (Reports.GroupingValue across: dim.getGroupings()) {
     mapkey = across.getLabel() + '-' + down.getLabel();
     key = across.getKey() + '!' + down.getKey();
     Reports.ReportFactWithDetails factDetails = (Reports.ReportFactWithDetails) results.getFactMap().get(key);
     summaryValues = factDetails.getAggregates();
     mapReport1.put(mapkey, summaryValues);
    }
    key = 'T!' + down.getKey();
    Reports.ReportFactWithDetails factDetails = (Reports.ReportFactWithDetails) results.getFactMap().get(key);
    summaryValues = factDetails.getAggregates();
    mapReport1.put(down.getLabel(), summaryValues);
   }

   /* ----------- putting values from report 2 into a map wih key as 'rowLabel-ColumnLabel' eg 'CMA-2017' 
      and value as Reports.SummaryValue since the report contains summarizable fields ---- */
   for (Reports.GroupingValue down: dim4.getGroupings()) {
    for (Reports.GroupingValue across: dim3.getGroupings()) {
     String mapkey = across.getLabel() + '-' + down.getLabel();
     String key = across.getKey() + '!' + down.getKey();
     //keyset.add(key);
     Reports.ReportFactWithDetails factDetails = (Reports.ReportFactWithDetails) results2.getFactMap().get(key);
     summaryValues = factDetails.getAggregates();
     mapReport2.put(mapkey, summaryValues);
    }

    String key = 'T!' + down.getKey();
    Reports.ReportFactWithDetails factDetails = (Reports.ReportFactWithDetails) results2.getFactMap().get(key);
    summaryValues = factDetails.getAggregates();
    mapReport2.put(down.getLabel(), summaryValues);

   }

   List < String > revTypeList = revType.split(';');

    system.debug('hhh --'  + revTypeList);
   // -- Adding existing revenue n growth records into a map with key as a combination of refresh based on and sales mode eg. 'Billing-CMA' ---//
   revenueGrowthList = [Select id, ACP_Past_Year_to_Date__c, ACP_Past_Year_1_Revenue__c, ACP_Past_Year_Revenue__c, ACP_Refresh_Based_on__c, ACP_Sales_Mode__c, ACP_Account_Plan__c, ACP_Current_Year_1_Plan__c, ACP_Current_Year_3_Plan__c, ACP_Current_Year_5_Plan__c, ACP_Current_Year_to_Date__c from ACP_Revenue_Growth_Perf__c where ACP_Account_Plan__c = : acpid order by createdDate];

   // businessPerfList = [Select id, ACP_Past_Year_1_Revenue__c, ACP_Past_Year_to_Date__c, ACP_Past_Year_Revenue__c, ACP_Refresh_Based_on__c, ACP_Sales_Mode__c, ACP_Account_Plan__c, ACP_Current_Year_1_Plan__c, ACP_Current_Year_3_Plan__c,ACP_Current_Year_5_Plan__c, ACP_Current_Year_to_Date__c from ACP_Revenue_Growth_Perf__c where ACP_Account_Plan__c = : acpid and ACP_Sales_Mode__c in :revTypeList  order by createdDate];

   for (ACP_Revenue_Growth_Perf__c r: revenueGrowthList) {
    String mapkey = r.ACP_Refresh_Based_on__c + '-' + r.ACP_Sales_Mode__c;
    revenueGrowthMap.put(mapkey, r);

   }

   // creating or updating a billing and a booking record for each sales mode ie.; CMA, POS, Direct ---//
   for (String s: keyset) {
    ACP_Revenue_Growth_Perf__c revenueBilling = revenueGrowthMap.get('Billing-' + s); //fetching the existing records from the above map
    ACP_Revenue_Growth_Perf__c revenueBooking = revenueGrowthMap.get('Booking-' + s);
    // creating a new record if there is no existing record 
    if (revenueBilling == null) {
     system.debug('null billing ---');
     revenueBilling = new ACP_Revenue_Growth_Perf__c();
     revenueBilling.ACP_Refresh_Based_on__c = 'Billing';
     revenueBilling.ACP_Sales_Mode__c = s;
     revenueBilling.ACP_Account_Plan__c = acpid;
     revenueBilling.ACP_Current_Year_to_Date__c = 0;
     revenueBilling.ACP_Past_Year_1_Revenue__c = 0;
    revenueBilling.ACP_Past_Year_to_Date__c = 0;
    revenueBilling.ACP_Past_Year_Revenue__c = 0;
    revenueBilling.ACP_Current_Year_1_Plan__c = 0;
    revenueBilling.ACP_Current_Year_3_Plan__c = 0;
    revenueBilling.ACP_Current_Year_5_Plan__c = 0; 
    }
    else 
    revenueBilling = revGrowth(revenueBilling);
    if (revenueBooking == null) {
     system.debug('null booking---');
     revenueBooking = new ACP_Revenue_Growth_Perf__c();
     revenueBooking.ACP_Refresh_Based_on__c = 'Booking';
     revenueBooking.ACP_Sales_Mode__c = s;
     revenueBooking.ACP_Account_Plan__c = acpid;
     revenueBooking.ACP_Current_Year_to_Date__c = 0;
    revenueBooking.ACP_Past_Year_1_Revenue__c = 0;
    revenueBooking.ACP_Past_Year_to_Date__c = 0;
    revenueBooking.ACP_Past_Year_Revenue__c = 0;
    revenueBooking.ACP_Current_Year_1_Plan__c = 0;
    revenueBooking.ACP_Current_Year_3_Plan__c = 0;
    revenueBooking.ACP_Current_Year_5_Plan__c = 0; 
    }
    else 
    revenueBooking = revGrowth(revenueBooking);
    
    revenueBilling.ACP_Fiscal_Year__c = String.valueOf(fiscalyr);
    revenueBooking.ACP_Fiscal_Year__c = String.valueOf(fiscalyr);

    //Fetching values from reports and storing them in the respective fields.
    if(s != 'Combined')
    {
         if (mapReport1.get(s + '-' + String.valueof(pastyr_1)) != null) {
     LIST < Reports.SummaryValue > summaryValues = mapReport1.get(s + '-' + String.valueof(pastyr_1));
     revenueBilling.ACP_Past_Year_1_Revenue__c = (Decimal) summaryValues[1].getValue();
     revenueBooking.ACP_Past_Year_1_Revenue__c = (Decimal) summaryValues[0].getValue();
    }

    if (mapReport1.get(s + '-' + String.valueof(pastyr)) != null) {
     LIST < Reports.SummaryValue > summaryValues = mapReport1.get(s + '-' + String.valueof(pastyr));
     revenueBilling.ACP_Past_year_Revenue__c = (Decimal) summaryValues[1].getValue();
     revenueBooking.ACP_Past_year_Revenue__c = (Decimal) summaryValues[0].getValue();
    }

    if (mapReport2.get(s + '-' + String.valueof(fiscalyr)) != null) {
     LIST < Reports.SummaryValue > summaryValues = mapReport2.get(s + '-' + String.valueof(fiscalyr));
     revenueBilling.ACP_Current_Year_to_Date__c = (Decimal) summaryValues[1].getValue();
     system.debug('current yr to date -- '+ s + ' value --' + revenueBilling.ACP_Current_Year_to_Date__c);
     revenueBooking.ACP_Current_Year_to_Date__c = (Decimal) summaryValues[0].getValue();
    }

    if (mapReport2.get(s + '-' + String.valueof(pastyr)) != null) {
     LIST < Reports.SummaryValue > summaryValues = mapReport2.get(s + '-' + String.valueof(pastyr));
     revenueBilling.ACP_Past_Year_to_Date__c = (Decimal) summaryValues[1].getValue();
     system.debug('past yr to date -- '+ s + ' value --' + revenueBilling.ACP_Past_Year_to_Date__c);
     revenueBooking.ACP_Past_Year_to_Date__c = (Decimal) summaryValues[0].getValue();

    }
    }
   
    revenueGrowthMap.put('Billing-' + s, revenueBilling);
    revenueGrowthMap.put('Booking-' + s, revenueBooking);


   }
   
     ACP_Revenue_Growth_Perf__c revenueBilling = revenueGrowthMap.get('Billing-Combined');
     revenueBilling = revGrowthTotal(revenueBilling);
     ACP_Revenue_Growth_Perf__c revenueBooking = revenueGrowthMap.get('Booking-Combined');
     revenueBooking = revGrowthTotal(revenueBooking);
  
   
   for (String s: revTypeList) {
       
    ACP_Revenue_Growth_Perf__c revBilling = revenueGrowthMap.get('Billing-' + s);
    ACP_Revenue_Growth_Perf__c revBooking = revenueGrowthMap.get('Booking-' + s);
    
    
    revenueBilling.ACP_Past_Year_1_Revenue__c += revBilling.ACP_Past_Year_1_Revenue__c;
    revenueBilling.ACP_Past_Year_Revenue__c += revBilling.ACP_Past_Year_Revenue__c;
    revenueBilling.ACP_Current_Year_to_Date__c += revBilling.ACP_Current_Year_to_Date__c;
    revenueBilling.ACP_Current_Year_1_Plan__c += revBilling.ACP_Current_Year_1_Plan__c;
    revenueBilling.ACP_Current_Year_3_Plan__c += revBilling.ACP_Current_Year_3_Plan__c;
    revenueBilling.ACP_Current_Year_5_Plan__c += revBilling.ACP_Current_Year_5_Plan__c;
    revenueBilling.ACP_Past_Year_to_Date__c += revBilling.ACP_Past_Year_to_Date__c;

    revenueBooking.ACP_Past_Year_1_Revenue__c += revBooking.ACP_Past_Year_1_Revenue__c;
    revenueBooking.ACP_Past_Year_Revenue__c += revBooking.ACP_Past_Year_Revenue__c;
    revenueBooking.ACP_Current_Year_to_Date__c += revBooking.ACP_Current_Year_to_Date__c;
    revenueBooking.ACP_Current_Year_1_Plan__c += revBooking.ACP_Current_Year_1_Plan__c;
    revenueBooking.ACP_Current_Year_3_Plan__c += revBooking.ACP_Current_Year_3_Plan__c;
    revenueBooking.ACP_Current_Year_5_Plan__c += revBooking.ACP_Current_Year_5_Plan__c;
    revenueBooking.ACP_Past_Year_to_Date__c += revBooking.ACP_Past_Year_to_Date__c;

   }
   
   revenueGrowthMap.put('Billing-Combined', revenueBilling);
   revenueGrowthMap.put('Booking-Combined', revenueBooking);
   upsert revenueGrowthMap.values();
  } catch (Exception e) {
   ErrorLogging.Log(e, 'ACP_Revenue_Growth_Ctrl', 'runReport', acpId);
  }
  return pageRedirectWithDivId('businessPerf');
 }

 public ACP_Revenue_Growth_Perf__c revGrowthTotal(ACP_Revenue_Growth_Perf__c totalRevenue)
 {
    totalRevenue.ACP_Past_Year_1_Revenue__c = 0;
    totalRevenue.ACP_Past_Year_to_Date__c = 0;
    totalRevenue.ACP_Past_Year_Revenue__c = 0;
    totalRevenue.ACP_Current_Year_to_Date__c = 0;
    totalRevenue.ACP_Current_Year_1_Plan__c = 0;
    totalRevenue.ACP_Current_Year_3_Plan__c = 0;
    totalRevenue.ACP_Current_Year_5_Plan__c = 0;
    
     return totalRevenue;
 }
 public ACP_Revenue_Growth_Perf__c revGrowth(ACP_Revenue_Growth_Perf__c totalRevenue)
 {
    totalRevenue.ACP_Past_Year_1_Revenue__c = 0;
    totalRevenue.ACP_Past_Year_to_Date__c = 0;
    totalRevenue.ACP_Past_Year_Revenue__c = 0;
    totalRevenue.ACP_Current_Year_to_Date__c = 0;
    return totalRevenue;
 }
 

 //Method to update records when Update from Reports button is clicked on the VF page
 public void updatePerformance() {
  try {
       update revenueGrowthList;
       runReport();
   
  }
  Catch(Exception e) {
   ErrorLogging.Log(e, 'ACP_Revenue_Growth_Ctrl', 'updatePerformance', acpId);
  }
  
  // return pageRedirectWithDivId('businessPerf');
 }
 
 public pagereference pageRedirectWithDivId(String divId) {
  PageReference savePageRef = new PageReference('/apex/ACP_Performance_Analytics_page?acpId=' + acpId + '#' + divId);
  savePageRef.setRedirect(true);
  return savePageRef;
 }

}