objects/ACP_Account_Plan__c.object
<CustomObject>
    <description>Hari 04/24/17 – Created for Account Plan</description>
    <fields>
        <fullName>ACP_Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Hari 04/24/17 – Created for Account Plan</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACP Account Plans</relationshipLabel>
        <relationshipName>Account_Plans7</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACP_Customer_Strategy_Summary__c</fullName>
        <description>Hari 04/24/17 – Created for Account Plan</description>
        <label>Customer Strategy Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>This is used when the Account Plan is created to denote the type of Account Plan being created. The Sold-to type is for one Account Record, the other types are collection of Account Records.</description>
        <inlineHelpText>Select the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sold-to Account</fullName>
                </value>
                <value>
                    <fullName>GAM Account</fullName>
                </value>
                <value>
                    <fullName>KAM Account</fullName>
                </value>
                <value>
                    <fullName>WW Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ACP Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACP Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ACP_Market_and_Competition__c.object
<CustomObject>
    <fields>
        <fullName>ACP_Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>ACP_Account_Plan__c</referenceTo>
        <relationshipLabel>Markets and Competition</relationshipLabel>
        <relationshipName>Markets_and_Competition</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACP_CBC__c</fullName>
        <label>Product(CBC)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_CY_YTD__c</fullName>
        <label>CY YTD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_LY_Bill__c</fullName>
        <label>LY Bill</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_LY_YTD__c</fullName>
        <label>LY YTD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Main_Competitor_Share__c</fullName>
        <label>Main Competitor Share %</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ACP_Market_Share__c</fullName>
        <description>Market Share is a calculation of Revenue divided by TAM.</description>
        <label>Market Share %</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ACP_NY_Fcst__c</fullName>
        <label>NY Fcst</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_PAM__c</fullName>
        <label>PAM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_SAM__c</fullName>
        <label>SAM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_TAM_CYRR__c</fullName>
        <label>TAM CY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_TAM_LY_Bill__c</fullName>
        <label>TAM LY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_TAM_NY_Fcst__c</fullName>
        <label>TAM NY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_TAM__c</fullName>
        <description>Total Addressable Market</description>
        <label>TAM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_TE_Position__c</fullName>
        <label>TE Position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>Up</fullName>
                </value>
                <value>
                    <fullName>Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Market and Competition</label>
    <nameField>
        <displayFormat>MNC-{000000}</displayFormat>
        <label>Market and Competition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets and Competition</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BBB_Year_Bill_Book_Cust_PN__c.object
<CustomObject>
    <description>Yearly bookings and billings by customer (Account) and part, includes direct and POS (indirect)</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Booking/Billings By Parts (Customer)</relationshipLabel>
        <relationshipName>Yearly_BBB_by_Part_and_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Yearly Booking/Billings By Part</label>
    <nameField>
        <displayFormat>YBBB-{0}</displayFormat>
        <label>Yearly BBB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking/Billings By Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ACP_Perf_Analytics_Report_Ctrl_Test.cls
/***************************************************************************************
Name:ACP_Perf_Analytics_Report_Ctrl_Test
Class:ACP_Performance_Analytics_ctrl
Copyright © 2017 TE Connectivity
=========================================================================================
Requirement:
Test Class for Performance and analytic tab.
=========================================================================================
Purpose:
Used for performance analytics functionality.
=========================================================================================
History
-------
Version      Author                     Date              Detail
1.0          Esther Ethelbert           04/25/17          Covering methods of class
2.0          Anushka Bansal             04/25/17          Covering methods of class
****************************************************************************************/
@isTest(SeeAllData = true)
Private Class ACP_Perf_Analytics_Report_Ctrl_Test {
  static testMethod void MarketComp_RunReport_Method() {
    Test.startTest();
    Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Grouped Accounts').getRecordTypeId();

    Account acct = new Account();
    acct.Name = 'TestAccount1PlanAccount289';
    acct.GAMCD__c = 'G0004';
    if (recType != null)
      acct.RecordTypeId = recType;
    acct.IND_KAM_Code__c = 'K0004';
    Insert acct;

    system.debug('account ---- ' + acct);
    ACP_Account_Plan__c accplan = new ACP_Account_Plan__c(
      Name = 'TestAcc4',
      ACP_Account_Name__c = acct.Id,
      Account_Plan_Type__c = 'GAM Account',
      ACP_Customer_Strategy_Summary__c = 'TestAccountPlan3546');
    insert accplan;

    List < ACP_Market_and_Competition__c > Mark = ACP_TestDataFactory.createMarketCompetition(1, 'General Market and Competition');
    List < ACP_Market_and_Competition__c > markList = new List < ACP_Market_and_Competition__c > ();
    for (ACP_Market_and_Competition__c obj: mark) {
      obj.ACP_Account_Plan__c = accplan.id;
      obj.ACP_CBC__c = 'CBC1 - 30007 - Appliances';
      obj.ACP_LY_Bill__c = 200;
      obj.ACP_CY_YTD__c = 300;
      obj.ACP_LY_YTD__c = 400;
      markList.add(obj);
    }
    insert markList;
    system.debug('mark' + Mark);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBBList = ACP_TestDataFactory.createYearlyBBB('13333', 'GAM Account', acct.id);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBB = new List < BBB_Year_Bill_Book_Cust_PN__c > ();
    for (BBB_Year_Bill_Book_Cust_PN__c ybb: yearlyBBBList) {
      ybb.Customer__c = acct.id;
      yearlyBBB.add(ybb);
    }
    insert yearlyBBB;

    system.debug('yearlyBBBList' + yearlyBBBList);
    String reportName1 = 'ACP_Yearly_Billing_Report';
    Report report1 = Database.query('SELECT Id, Developername FROM Report WHERE Developername =: reportName1');

    Apexpages.currentPage().getParameters().put('acpid', accplan.id);
    ACP_Performance_Analytics_ctrl ctrlObj = new ACP_Performance_Analytics_ctrl(new ApexPages.StandardController(accplan));
    ctrlObj.acpId = accPlan.id;
    ctrlObj.getCBC1();
    ctrlObj.getCBC2();
    ctrlObj.getCBC3();
    List < SelectOption > optionsCBC1 = ctrlObj.getCBC1;
    List < SelectOption > optionsCBC2 = ctrlObj.getCBC2;
    List < SelectOption > optionsCBC3 = ctrlObj.getCBC3;
    ctrlObj.cbc1Value = 'Appliances--30007';
    ctrlObj.cbc2Value = 'TUBING--30017';
    ctrlObj.cbc3Value = 'Tubing Materials--30049';
    ACP_Opportunity_Data_Automation_Ctrl.marketRunReport('CBC1', '13333', 'GAM Account', '00000', acct.id, report1.id);

    ctrlObj.YBBReportValue();
    ctrlObj.saveCommonMark();
    ctrlObj.saveMarkComp();
    ctrlObj.saveAndNewMark();
    ctrlObj.actionSaveMark();
    ctrlObj.DeleteMark();
    System.assertEquals(ctrlObj.cbc1Value, 'Appliances--30007');
    System.assertEquals(ctrlObj.cbc2Value, 'TUBING--30017');
    System.assertEquals(ctrlObj.cbc3Value, 'Tubing Materials--30049');
    Test.stopTest();
  }

  /******************************** 1st Test for report*************************************************************************************/
  static testMethod void MarketComp_RunReport_Method1() {
    Test.startTest();
    Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Grouped Accounts').getRecordTypeId();

    Account acct = new Account();
    acct.Name = 'TestAccount1PlanAccount289';
    acct.GAMCD__c = 'G0004';
    if (recType != null)
      acct.RecordTypeId = recType;
    acct.IND_KAM_Code__c = 'K0004';
    Insert acct;

    system.debug('account ---- ' + acct);
    ACP_Account_Plan__c accplan = new ACP_Account_Plan__c(
      Name = 'TestAcc4',
      ACP_Account_Name__c = acct.Id,
      Account_Plan_Type__c = 'KAM Account',
      ACP_Customer_Strategy_Summary__c = 'TestAccountPlan3546');
    insert accplan;

    List < ACP_Market_and_Competition__c > Mark = ACP_TestDataFactory.createMarketCompetition(1, 'General Market and Competition');
    List < ACP_Market_and_Competition__c > markList = new List < ACP_Market_and_Competition__c > ();
    for (ACP_Market_and_Competition__c obj: mark) {
      obj.ACP_Account_Plan__c = accplan.id;
      obj.ACP_CBC__c = 'CBC1 - 30007 - Appliances';
      obj.ACP_LY_Bill__c = 200;
      obj.ACP_CY_YTD__c = 300;
      obj.ACP_LY_YTD__c = 400;
      markList.add(obj);
    }
    insert markList;
    system.debug('mark' + Mark);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBBList = ACP_TestDataFactory.createYearlyBBB('13333', 'KAM Account', acct.id);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBB = new List < BBB_Year_Bill_Book_Cust_PN__c > ();
    for (BBB_Year_Bill_Book_Cust_PN__c ybb: yearlyBBBList) {
      ybb.Customer__c = acct.id;
      yearlyBBB.add(ybb);
    }
    insert yearlyBBB;

    system.debug('yearlyBBBList' + yearlyBBBList);
    String reportName1 = 'ACP_Yearly_Billing_Report';
    Report report1 = Database.query('SELECT Id, Developername FROM Report WHERE Developername =: reportName1');

    Apexpages.currentPage().getParameters().put('acpid', accplan.id);
    ACP_Performance_Analytics_ctrl ctrlObj = new ACP_Performance_Analytics_ctrl(new ApexPages.StandardController(accplan));
    ctrlObj.acpId = accPlan.id;
    ctrlObj.getCBC1();
    ctrlObj.getCBC2();
    ctrlObj.getCBC3();
    List < SelectOption > optionsCBC1 = ctrlObj.getCBC1;
    List < SelectOption > optionsCBC2 = ctrlObj.getCBC2;
    List < SelectOption > optionsCBC3 = ctrlObj.getCBC3;
    ctrlObj.cbc1Value = 'Appliances--30007';
    ctrlObj.cbc2Value = 'TUBING--30017';
    ctrlObj.cbc3Value = 'Tubing Materials--30049';
    ACP_Opportunity_Data_Automation_Ctrl.marketRunReport('CBC2', '13332', 'KAM Account', '00000', acct.id, report1.id);




    // ctrlObj.YBBReportValue();
    ctrlObj.saveCommonMark();
    ctrlObj.saveMarkComp();
    ctrlObj.saveAndNewMark();
    ctrlObj.actionSaveMark();
    ctrlObj.DeleteMark();
    System.assertEquals(ctrlObj.cbc1Value, 'Appliances--30007');
    System.assertEquals(ctrlObj.cbc2Value, 'TUBING--30017');
    System.assertEquals(ctrlObj.cbc3Value, 'Tubing Materials--30049');
    Test.stopTest();
  }
  /********************************2nd Test for report*************************************************************************************/
  static testMethod void MarketComp_RunReport_Method2() {
    Test.startTest();
    Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Grouped Accounts').getRecordTypeId();

    Account acct = new Account();
    acct.Name = 'TestAccount1PlanAccount289';
    acct.GAMCD__c = 'G0004';
    if (recType != null)
      acct.RecordTypeId = recType;
    acct.IND_KAM_Code__c = 'K0004';
    Insert acct;

    system.debug('account ---- ' + acct);
    ACP_Account_Plan__c accplan = new ACP_Account_Plan__c(
      Name = 'TestAcc4',
      ACP_Account_Name__c = acct.Id,
      Account_Plan_Type__c = 'WW Account',
      ACP_Customer_Strategy_Summary__c = 'TestAccountPlan3546');
    insert accplan;

    List < ACP_Market_and_Competition__c > Mark = ACP_TestDataFactory.createMarketCompetition(1, 'General Market and Competition');
    List < ACP_Market_and_Competition__c > markList = new List < ACP_Market_and_Competition__c > ();
    for (ACP_Market_and_Competition__c obj: mark) {
      obj.ACP_Account_Plan__c = accplan.id;
      obj.ACP_CBC__c = 'CBC1 - 30007 - Appliances';
      obj.ACP_LY_Bill__c = 200;
      obj.ACP_CY_YTD__c = 300;
      obj.ACP_LY_YTD__c = 400;
      markList.add(obj);
    }
    insert markList;
    system.debug('mark' + Mark);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBBList = ACP_TestDataFactory.createYearlyBBB('13331', 'WW Account', acct.id);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBB = new List < BBB_Year_Bill_Book_Cust_PN__c > ();
    for (BBB_Year_Bill_Book_Cust_PN__c ybb: yearlyBBBList) {
      ybb.Customer__c = acct.id;
      yearlyBBB.add(ybb);
    }
    insert yearlyBBB;

    system.debug('yearlyBBBList' + yearlyBBBList);
    String reportName1 = 'ACP_Yearly_Billing_Report';
    Report report1 = Database.query('SELECT Id, Developername FROM Report WHERE Developername =: reportName1');

    Apexpages.currentPage().getParameters().put('acpid', accplan.id);
    ACP_Performance_Analytics_ctrl ctrlObj = new ACP_Performance_Analytics_ctrl(new ApexPages.StandardController(accplan));

    ctrlObj.acpId = accPlan.id;
    ctrlObj.acpId = accPlan.id;
    ctrlObj.getCBC1();
    ctrlObj.getCBC2();
    ctrlObj.getCBC3();
    List < SelectOption > optionsCBC1 = ctrlObj.getCBC1;
    List < SelectOption > optionsCBC2 = ctrlObj.getCBC2;
    List < SelectOption > optionsCBC3 = ctrlObj.getCBC3;
    ctrlObj.cbc1Value = 'Appliances--30007';
    ctrlObj.cbc2Value = 'TUBING--30017';
    ctrlObj.cbc3Value = 'Tubing Materials--30049';
    ACP_Opportunity_Data_Automation_Ctrl.marketRunReport('CBC3', '13331', 'KAM Account', '00000', acct.id, report1.id);



    //  ctrlObj.YBBReportValue();
    ctrlObj.saveCommonMark();
    ctrlObj.saveMarkComp();
    ctrlObj.saveAndNewMark();
    ctrlObj.actionSaveMark();
    ctrlObj.DeleteMark();
    System.assertEquals(ctrlObj.cbc1Value, 'Appliances--30007');
    System.assertEquals(ctrlObj.cbc2Value, 'TUBING--30017');
    System.assertEquals(ctrlObj.cbc3Value, 'Tubing Materials--30049');
    Test.stopTest();
  }
  /********************************3rd Test for report*************************************************************************************/
  static testMethod void MarketComp_RunReport_Method3() {
    Test.startTest();
    Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();

    Account acct = new Account();
    acct.Name = 'TestAccount1PlanAccount289';
    acct.GAMCD__c = 'G0004';
    if (recType != null)
      acct.RecordTypeId = recType;
    acct.IND_KAM_Code__c = 'K0004';
    Insert acct;

    system.debug('account ---- ' + acct);
    ACP_Account_Plan__c accplan = new ACP_Account_Plan__c(
      Name = 'TestAcc4',
      ACP_Account_Name__c = acct.Id,
      Account_Plan_Type__c = 'Sold-to Account',
      ACP_Customer_Strategy_Summary__c = 'TestAccountPlan3546');
    insert accplan;

    List < ACP_Market_and_Competition__c > Mark = ACP_TestDataFactory.createMarketCompetition(1, 'General Market and Competition');
    List < ACP_Market_and_Competition__c > markList = new List < ACP_Market_and_Competition__c > ();
    for (ACP_Market_and_Competition__c obj: mark) {
      obj.ACP_Account_Plan__c = accplan.id;
      obj.ACP_CBC__c = 'CBC1 - 30007 - Appliances';
      obj.ACP_LY_Bill__c = 200;
      obj.ACP_CY_YTD__c = 300;
      obj.ACP_LY_YTD__c = 400;
      markList.add(obj);
    }
    insert markList;
    system.debug('mark' + Mark);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBBList = ACP_TestDataFactory.createYearlyBBB('13331', 'Sold-to Account', acct.id);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBB = new List < BBB_Year_Bill_Book_Cust_PN__c > ();
    for (BBB_Year_Bill_Book_Cust_PN__c ybb: yearlyBBBList) {
      ybb.Customer__c = acct.id;
      yearlyBBB.add(ybb);
    }
    insert yearlyBBB;

    system.debug('yearlyBBBList' + yearlyBBBList);
    String reportName1 = 'ACP_Yearly_Billing_Report';
    Report report1 = Database.query('SELECT Id, Developername FROM Report WHERE Developername =: reportName1');

    Apexpages.currentPage().getParameters().put('acpid', accplan.id);
    ACP_Performance_Analytics_ctrl ctrlObj = new ACP_Performance_Analytics_ctrl(new ApexPages.StandardController(accplan));
    ctrlObj.acpId = accPlan.id;
    ctrlObj.getCBC1();
    ctrlObj.getCBC2();
    ctrlObj.getCBC3();
    List < SelectOption > optionsCBC1 = ctrlObj.getCBC1;
    List < SelectOption > optionsCBC2 = ctrlObj.getCBC2;
    List < SelectOption > optionsCBC3 = ctrlObj.getCBC3;
    ctrlObj.cbc1Value = 'Appliances--30007';
    ctrlObj.cbc2Value = 'TUBING--30017';
    ctrlObj.cbc3Value = 'Tubing Materials--30049';
    ACP_Opportunity_Data_Automation_Ctrl.marketRunReport('CBC3', '13331', 'Sold-to Account', '000000000000000', acct.id, report1.id);


    // ctrlObj.YBBReportValue();
    ctrlObj.saveCommonMark();
    ctrlObj.saveMarkComp();
    ctrlObj.saveAndNewMark();
    ctrlObj.actionSaveMark();
    ctrlObj.DeleteMark();
    System.assertEquals(ctrlObj.cbc1Value, 'Appliances--30007');
    System.assertEquals(ctrlObj.cbc2Value, 'TUBING--30017');
    System.assertEquals(ctrlObj.cbc3Value, 'Tubing Materials--30049');
    Test.stopTest();
  }
  /*********************************************4th Test for report************************************************************************/
  static testMethod void MarketComp_RunReport_Method4() {
    Test.startTest();
    Id recType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
    Test.setCurrentPageReference(new PageReference('Page.ACP_Edit_Mkt_Product_CBC'));

    Account acct = new Account();
    acct.Name = 'TestAccount1PlanAccount289';
    acct.GAMCD__c = 'G0004';
    if (recType != null)
      acct.RecordTypeId = recType;
    acct.IND_KAM_Code__c = 'K0004';
    Insert acct;

    system.debug('account ---- ' + acct);
    ACP_Account_Plan__c accplan = new ACP_Account_Plan__c(
      Name = 'TestAcc4',
      ACP_Account_Name__c = acct.Id,
      Account_Plan_Type__c = 'Sold-to Account',
      ACP_Customer_Strategy_Summary__c = 'TestAccountPlan3546');
    insert accplan;

    RecordType rcdType = [Select Id, name from RecordType where Name = 'General Market and Competition'];
    Id recordId = rcdType.Id;

    ACP_Market_and_Competition__c Mark = new ACP_Market_and_Competition__c();
    Mark.RecordTypeId = recordId;
    Mark.ACP_Account_Plan__c = accPlan.id;
    Mark.ACP_Main_Competitor_Share__c = 14;
    Mark.ACP_Market_Share__c = 12;
    Mark.ACP_NY_Fcst__c = 20;
    Mark.ACP_PAM__c = 200;
    Mark.ACP_SAM__c = 200;
    Mark.ACP_TAM__c = 200;
    Mark.ACP_TE_Position__c = 'Flat';
    Mark.ACP_CBC__c = 'CBC3 - 30017 - Tubing Materials';
    Mark.ACP_TAM_LY_Bill__c = 20.00;
    Mark.ACP_TAM_CYRR__c = 20.00;
    Mark.ACP_TAM_NY_Fcst__c = 20.00;
    Mark.ACP_LY_Bill__c = 200;
    Mark.ACP_CY_YTD__c = 300;
    Mark.ACP_LY_YTD__c = 400;

    insert Mark;
    system.debug('mark' + Mark);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBBList = ACP_TestDataFactory.createYearlyBBB('13331', 'Sold-to Account', acct.id);
    List < BBB_Year_Bill_Book_Cust_PN__c > yearlyBBB = new List < BBB_Year_Bill_Book_Cust_PN__c > ();
    for (BBB_Year_Bill_Book_Cust_PN__c ybb: yearlyBBBList) {
      ybb.Customer__c = acct.id;
      yearlyBBB.add(ybb);
    }
    insert yearlyBBB;

    system.debug('yearlyBBBList' + yearlyBBBList);
    String reportName1 = 'ACP_Yearly_Billing_Report';
    Report report1 = Database.query('SELECT Id, Developername FROM Report WHERE Developername =: reportName1');


    Apexpages.currentPage().getParameters().put('acpid', accplan.id);
    Apexpages.currentPage().getParameters().put('macid', Mark.id);
    ACP_Performance_Analytics_ctrl ctrlObj = new ACP_Performance_Analytics_ctrl(new ApexPages.StandardController(accplan));

    ctrlObj.acpId = accPlan.id;
    ctrlObj.getCBC1();
    ctrlObj.getCBC2();
    ctrlObj.getCBC3();

    List < SelectOption > optionsCBC1 = ctrlObj.getCBC1;
    List < SelectOption > optionsCBC2 = ctrlObj.getCBC2;
    List < SelectOption > optionsCBC3 = ctrlObj.getCBC3;
    ctrlObj.cbc1Value = 'Appliances--30007';
    ctrlObj.cbc2Value = 'TUBING--30017';
    ctrlObj.cbc3Value = 'Tubing Materials--30049';
    ACP_Opportunity_Data_Automation_Ctrl.marketRunReport('CBC3', '13331', 'Sold-to Account', '000000000000000', acct.id, report1.id);


    ctrlObj.YBBReportValue();
    ctrlObj.saveCommonMark();
    ctrlObj.saveMarkComp();
    ctrlObj.saveAndNewMark();
    ctrlObj.actionSaveMark();
   // ctrlObj.updateCommonCBC();
   // ctrlObj.saveCBCProd();
    System.assertEquals(ctrlObj.cbc1Value, 'Appliances--30007');
    System.assertEquals(ctrlObj.cbc2Value, 'TUBING--30017');
    System.assertEquals(ctrlObj.cbc3Value, 'Tubing Materials--30049');
    Test.stopTest();
  }

}