objects/ACP_Account_Plan__c.object
<CustomObject>
    <description>Hari 04/24/17 – Created for Account Plan</description>
    <fields>
        <fullName>ACP_Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Hari 04/24/17 – Created for Account Plan</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACP Account Plans</relationshipLabel>
        <relationshipName>Account_Plans7</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACP_Customer_Strategy_Summary__c</fullName>
        <description>Hari 04/24/17 – Created for Account Plan</description>
        <label>Customer Strategy Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ACP Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACP Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ACP_Revenue_Growth_Perf__c.object
<CustomObject>
    <description>Alka 04/24/17 Created For Account Plan 
Object to capture information on Revenue Growth for Account Plan Performance review and plan</description>
    <fields>
        <fullName>ACP_Account_Plan__c</fullName>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Account Plan</label>
        <referenceTo>ACP_Account_Plan__c</referenceTo>
        <relationshipLabel>Revenue Growth</relationshipLabel>
        <relationshipName>Revenue_Growths</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACP_Current_Year_Run_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Current Year Run Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Current_Year_to_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Current Year to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Past_Year_1_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Past Year - 1 Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Past_year_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Past year Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ACP_Project_1__c</fullName>
        <description>Shashi 07/20/17 – Account Plan Growth tree</description>
        <label>Project 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACP_Refresh_Based_on__c</fullName>
        <description>Alka 04/24/17 – Account Plan Performance review and plan
Based on this value the data on the Reveunue Growth will be changed.</description>
        <label>Refresh Based on</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                    <default>true</default>
                    <label>Billing</label>
                </value>
                <value>
                    <fullName>Booking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACP_Sales_Mode__c</fullName>
        <description>Alka 04/24/17 – Account Plan Performance review and plan</description>
        <label>Sales Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CMA</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>Combined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Revenue Growth</label>
    <nameField>
        <displayFormat>RG-{00000000}</displayFormat>
        <label>Revenue Growth Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Growth</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ACP_Section_Detail__c.object
<CustomObject>
    <fields>
        <fullName>ACP_Application__c</fullName>
        <description>To define values for Application field in top open opportunity</description>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                    <label>Application</label>
                </value>
                <value>
                    <fullName>Application Segment</fullName>
                </value>
                <value>
                    <fullName>DND Application</fullName>
                </value>
                <value>
                    <fullName>Platform Name</fullName>
                </value>
                <value>
                    <fullName>Project Platform</fullName>
                </value>
                <value>
                    <fullName>Tender</fullName>
                    <isActive>false</isActive>
                    <label>Tender</label>
                </value>
                <value>
                    <fullName>Tender Name</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACP_Conversion_current_YTD__c</fullName>
        <description>To Store Conversion - (current YTD) Report</description>
        <inlineHelpText>Please add report ID</inlineHelpText>
        <label>Conversion - (current YTD) Report Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_Field_Set_1__c</fullName>
        <inlineHelpText>Fieldset name for Supplier Evaluation table</inlineHelpText>
        <label>Field Set for Rating Table</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_Field_Set_Name__c</fullName>
        <defaultValue>$User.Alias</defaultValue>
        <description>To store Field set name to display a different set of fields in the account plan pages.</description>
        <label>Field Set Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_Header_BG_Color__c</fullName>
        <description>Ritika 06/19/17 – Created for Account Plan</description>
        <label>Header Background Color</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_Header_Font_Color__c</fullName>
        <description>Ritika 06/19/17 – Created for Account Plan</description>
        <label>Header Font Color</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_Header_Label__c</fullName>
        <description>Ritika 06/19/17 – Created for Account Plan</description>
        <label>Header Label</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_L12M_Lost_1Yvalue__c</fullName>
        <description>To Store L12M Lost - (1Yvalue) Report Id</description>
        <inlineHelpText>Please add report Id</inlineHelpText>
        <label>L12M Lost - (1Yvalue) Report Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_L12M_Won_1Y_Value__c</fullName>
        <description>To store L12M Won - (1Y Value) report Id</description>
        <inlineHelpText>To store report Id</inlineHelpText>
        <label>L12M Won - (1Y Value) Report Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_No_Of_Records__c</fullName>
        <description>Ritika 06/19/17 – Created for Account Plan</description>
        <label>Number of Records To show</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACP_No_Reds_Exe_Rel__c</fullName>
        <description>To store max no of records for executive relationship table.</description>
        <label>No of Records Executive Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACP_Num_Rerds_Eng_Rel__c</fullName>
        <label>Num of Records Engineering Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACP_Num_of_Rcds_Pur_Rel__c</fullName>
        <description>To Store max no of records for purchasing relationship.</description>
        <label>Num of Records Purchasing Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACP_Pipeline_4Q_Rolling__c</fullName>
        <description>To store Pipeline 4Q Rolling Report Id</description>
        <inlineHelpText>Please add the report Id.</inlineHelpText>
        <label>Pipeline 4Q Rolling Report Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACP_Setting__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Ritika 06/19/17 – Created for Account Plan</description>
        <label>ACP_Setting</label>
        <referenceTo>ACP_Setting__c</referenceTo>
        <relationshipName>ACP_Section_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACP_Show_TAM_LY_CY_NY__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show TAM LY,CY,NY</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Overview_2nd_Row__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To determine whether the 2nd row of Customer Overview is shown on the Account Plan</description>
        <label>Customer Overview 2nd Row</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Sort_Order__c</fullName>
        <inlineHelpText>API Name - Example - createdDate desc</inlineHelpText>
        <label>Default Sort Order</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>CMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_and_Growth_Plan_Year_1__c</fullName>
        <label>Revenue and Growth Plan Year 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ACP Section Detail</label>
    <nameField>
        <label>ACP Section Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACP Section Details</pluralLabel>
    <recordTypes>
        <fullName>Strategy</fullName>
        <active>true</active>
        <description>To Define settings for Strategy Block in account plan</description>
        <label>Strategy</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ACP_Setting__c.object
<CustomObject>
    <fields>
        <fullName>ACP_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ritika 06/19/17 – Created for Account Plan</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DND</fullName>
                    <isActive>false</isActive>
                    <label>DND</label>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ACP Setting</label>
    <nameField>
        <label>ACP_Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACP Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ACP_RGUpdation_Page_ctrl_Test.cls
@isTest
Private Class ACP_RGUpdation_Page_ctrl_Test{
    static ACP_Section_Detail__c businessPerformance = createSectionSettings('TE Business Performance Settings','','TE Business Performance','ACP_Sales_Mode__c','ACP_Revenue_Growth_Fieldset','TE Business Performance');
    ACP_Setting__c acpsetting = createACPSetting('');        
        String UserBU= acpsetting.Business_Unit__c;        
         String AcpSectionDetail='ACP_Section_Detail__c';
         // ACP_AccountPlan_Helper.getAcctPlanFields(acpsetting, 'Account Plan Header');
    
     /************************Test Market and Competition details ***********************************/ 
       public static ACP_Setting__c createACPSetting(String BusinessUnit) {
        ACP_Setting__c acpSetting = new ACP_Setting__c();
        acpSetting.Business_Unit__c = BusinessUnit;
        acpSetting.ACP_Is_Active__c = true;
        try{
            insert acpSetting;
            system.debug('ACPSetting Record'+acpSetting);
            return acpSetting;
        }Catch(Exception e){
            System.debug('Exception occured inside ACP_TestDataFactory:'+e.getMessage());
            return null;
        }
    }
      
      public static ACP_Section_Detail__c createSectionSettings(String name,String GIBU,String headerLabel,String sortOrder, String fieldSetNm, String recTypeName) {
        Id recordtypeid = Schema.SObjectType.ACP_Section_Detail__c.getRecordTypeInfosByName().get(recTypeName).getRecordTypeId();
        system.debug('recordtypeid ======>'+recordtypeid);
        system.debug('recTypeName======>'+recTypeName);
        
        ACP_Setting__c acpSetting = createACPSetting(GIBU);
        ACP_Section_Detail__c sectionSetting = new ACP_Section_Detail__c();
        sectionSetting.Name = name;
        sectionSetting.ACP_Setting__r = acpSetting;
        sectionSetting.ACP_Header_Label__c = headerLabel;
        sectionSetting.Default_Sort_Order__c = sortOrder;
        sectionSetting.ACP_Field_Set_Name__c = fieldSetNm;
        sectionSetting.ACP_Header_BG_Color__c = 'orange';
        sectionSetting.ACP_Header_Font_Color__c = 'white';
       sectionSetting.ACP_Setting__c = acpSetting.id;
        sectionSetting.RecordTypeId = recordtypeid;
        if(recTypeName == 'Stakeholder and Relationship'){
            sectionSetting.ACP_No_Reds_Exe_Rel__c = 2;
            sectionSetting.ACP_Num_of_Rcds_Pur_Rel__c = 2;
            sectionSetting.ACP_Num_Rerds_Eng_Rel__c = 2;
        }
        if(recTypeName == 'Market and Competition'){
          sectionSetting.ACP_Show_TAM_LY_CY_NY__c =false;
          sectionSetting.ACP_No_Of_Records__c  =5;
        }
        if(recTypeName == 'Opportunity TAM Revenue'){
            sectionSetting.ACP_Pipeline_4Q_Rolling__c ='00O0S000000JQvH';
            sectionSetting.ACP_Conversion_current_YTD__c ='00O0S000000JQvH';
            sectionSetting.ACP_L12M_Lost_1Yvalue__c ='00O0S000000JQvH';
            sectionSetting.ACP_L12M_Won_1Y_Value__c ='00O0S000000JQvH';
            sectionSetting.ACP_No_Of_Records__c  =5;
        }
         if(recTypeName == 'Market and Competition Summary'){
            sectionSetting.ACP_No_Of_Records__c  =5;
            system.debug('Market&Comp Sum'+sectionSetting);
        }
        if(recTypeName == 'TE Business Performance'){
            sectionSetting.Revenue_and_Growth_Plan_Year_1__c = '2017';
            sectionSetting.Revenue_and_Growth_Plan_Year_1__c = '2018';
            sectionSetting.Revenue_and_Growth_Plan_Year_1__c = '2020';
            sectionSetting.Revenue_Type__c = 'Direct; POS; CMA';
        }
        
        if(recTypeName == 'Top Open Opportunities'){
        sectionSetting.ACP_Application__c = 'Platform Name';
        sectionSetting.ACP_No_Of_Records__c  =5;
        }
        if(recTypeName == 'TE Supplier Evaluation'){
        sectionSetting.ACP_Field_Set_1__c = 'ACP_Suppl_Rating_Fieldset';
        sectionSetting.ACP_No_Of_Records__c  =5;
        }
       
        if(recTypeName == 'Strategy'){
        
        sectionSetting.ACP_No_Of_Records__c  =5;
        }
        
        if(recTypeName == 'Customer Overview'){
        
        sectionSetting.Customer_Overview_2nd_Row__c  = true;
        }
        
        try{
            insert sectionSetting;
            system.debug('sectionSetting======>'+sectionSetting);
            return sectionSetting;
        }Catch(Exception e){
            System.debug('Exception occured inside ACP_TestDataFactory:'+e.getMessage());
            return null;
        }
    }
    static testMethod void RGT_TestMethod() {
    
    Test.startTest();
    Test.setCurrentPageReference(new PageReference('Page.ACP_RGEdit_Page'));
   ClsTestCustomSettingHelper.getTrigger_Configuration();
       ClsTestCustomSettingHelper.getProfitBUCenterMapping();
      ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();     
        ClsTestCustomSettingHelper.getOpportunity_Team_Default_Permission();
        ClsTestCustomSettingHelper.getADMTerritoryCode();
 Account acct = ClsTestHelp.createtestAccounts();
                
            insert acct;
    
    ACP_Account_Plan__c accPlan = new ACP_Account_Plan__c(
         Name = 'TestAccountPlan3564',
         ACP_Account_Name__c = acct.Id,              
         ACP_Customer_Strategy_Summary__c = 'TestAccountPlan3564');
      insert accPlan;
      
     ACP_Revenue_Growth_Perf__c acprev = new ACP_Revenue_Growth_Perf__c();
            acprev.ACP_Past_year_Revenue__c = 58217;
            acprev.ACP_Past_Year_1_Revenue__c = 58889;
            acprev.ACP_Current_Year_to_Date__c = 23705;
            acprev.ACP_Current_Year_Run_Rate__c =26251;
            acprev.ACP_Account_Plan__c = accPlan.id;
            acprev.ACP_Sales_Mode__c = 'Direct';
            acprev.ACP_Refresh_Based_on__c ='Billing'; 
             acprev.ACP_Project_1__c = 20;
              acprev.ACP_Project_2__c = 10;
                acprev.ACP_Project_3__c = 30;
              acprev.ACP_Project_4__c = 40;
              acprev.ACP_Project_5__c = 25;
              acprev.ACP_LY_Market_Growth__c= 25;
              acprev.ACP_LY_Price_Erosion__c= 25;
           acprev.ACP_Current_FY_Close__c= 25;
            acprev.ACP_Current_Year_1_Plan__c= 25;
             acprev.ACP_Current_Year_3_Plan__c= 25;
              acprev.ACP_Current_Year_5_Plan__c = 25;
               acprev.ACP_Current_FY_Base__c= 25;

     insert(acprev);

    Apexpages.currentPage().getParameters().put('acpid', accplan.id);  
    ApexPages.StandardController scm = new ApexPages.StandardController(acprev);         
    ACP_RGUpdation_Page_ctrl revGrow = new ACP_RGUpdation_Page_ctrl(scm); 
   
    revGrow.saveGrowthRevenue();
    revGrow.masterPageRedirection();
 
    Test.stopTest();
    System.assertEquals(accplan.id, revGrow.acpId);
 
  }
  
  
 }