objects/ADM_Custom_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADM Custom Setting</label>
</CustomObject>

objects/ADMTerritoryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADMTerritoryCode</label>
</CustomObject>

objects/Opportunity_Forecast__c.object
<CustomObject>
    <description>This object contains the project forecast numbers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <description>Populated by forecasting component in opportunity page to store fiscal year. Used in PLM integration to aggregate monthly data by quarter.</description>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSG1__c</fullName>
        <label>MSG1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NPS1__c</fullName>
        <label>NPS1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Forecast</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Forecasts</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Part</fullName>
        <active>true</active>
        <label>Part</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ADMSOPOppWarning_Test.cls
/**********************************************************************
Name: ADMSOPOppWarning_Test
Copyright © 2017
======================================================
======================================================
Purpose: Test class for ADMSOPOppWarning is used for displaying the custom message on a page for opportinities and its 
child forecast records which have Relevant for S&OP marked true, but opportunity is below 90% probability
-------                                                             
======================================================
======================================================
History                                                            
-------                                                            
VERSION      AUTHOR               DATE             DETAIL Description
0.1         akshay dhopey      10/8/2017           INITIAL DEVELOPMENT
***********************************************************************/
@isTest
public class ADMSOPOppWarning_Test{
    static testMethod void testOppWarning(){
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> ForecastRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = ForecastRecordTypeInfo.get('ADM').getRecordTypeId();
        Id accId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Id oppFrcastId = Schema.SObjectType.Opportunity_Forecast__c.getRecordTypeInfosByName().get('Part').getRecordTypeId();
    
        ClsTestCustomSettingHelper.getAllSettings();
        ClsTestCustomSettingHelper.getPMV_Sales_Stage_Setting();
        ChannelinsightData_test.ChannelinsightData_test();
        ClsTestCustomSettingHelper.getTrigger_Configuration();
             
        ADMTerritoryCode__c ADMTeritoryCode = new ADMTerritoryCode__c();
        ADMTeritoryCode.Name = 'ADMTerritoryCode';
        ADMTeritoryCode.Territory_Code__c ='101485';
        insert ADMTeritoryCode;
      
        ADM_Custom_Setting__c admConfig = new ADM_Custom_Setting__c();
        admConfig.Name = 'ADM_JDA_Probability';
        admConfig.Value__c = '90';
        insert admConfig;
        
     Test.startTest();    
        Account acc = ADMTestDataFactory.createTestAccounts();
        acc.RecordTypeId = accId;
        insert acc; 
     
        Opportunity oppNew = new Opportunity();
        oppNew.Name = 'Opportunity1';
        oppNew.Account = acc;
        oppNew.accountId = acc.id;
        oppNew.Type = 'New Business';
        oppNew.Primary_Market_Type__c = 'Commercial Aerospace: Business Jets';
        oppNew.CurrencyIsoCode = 'USD';
        oppNew.Currency_Confirm__c = True;
        oppNew.CloseDate = system.today();
        //oppNew.Phase__c = 'Design';
        oppNew.Amount = 1;
        oppNew.Opportunity_Health__c = 'Caution';
        //oppNew.Relevant_for_S_OP__c = True;
        oppNew.RecordTypeId = rtId;
        //oppNew.Level__c ='Monthly';
       /// oppNew.Method__c = 'Manual';
        oppNew.Probability = 80.00;
        oppNew.StageName = 'Test';
        insert oppNew;
        System.debug('oppNew----'+oppNew);
    
         
        Opportunity_Forecast__c oppFrcast = new Opportunity_Forecast__c();
        oppFrcast.RecordTypeId = oppFrcastId;
        oppFrcast.CurrencyIsoCode = 'USD';
        oppFrcast.Amount__c = 50.00;
        oppFrcast.NPS1__c = 10;
        oppFrcast.MSG1__c = 40;
        oppFrcast.Opportunity__c = oppNew.id;
        //oppFrcast.RecordTypeId=oppForecastRecordTypeId;
        oppFrcast.Fiscal_Month__c='01';
        oppFrcast.Fiscal_Year__c='2019';
        oppFrcast.Amount__c=10;
        //oppFrcast.Part__c = opppart.id;
        insert oppFrcast; 
    
        oppNew.Relevant_for_S_OP__c = True;
        oppNew.Level__c ='Monthly';
        oppNew.Method__c = 'Manual';
        update oppNew;
    
     
        PageReference pageRef = Page.ADMOppSOPWarning;
        Test.setCurrentPage(pageRef);
        //ID pageId = pageRef.getParameters().put('id', String.valueOf(oppNew.Id));
        ApexPages.CurrentPage().getparameters().put('id', oppNew.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(oppNew);
        ADMSOPOppWarning sopOpp = new ADMSOPOppWarning(sc); 
     Test.stopTest();
}
}