objects/ADM_Forecast_Page_Customization__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ADM_Forecasting Page Latest Comment column configurable Width &amp; Color Coding.</description>
    <fields>
        <fullName>Color_Coding__c</fullName>
        <description>ADM_Forecasting Page Forecast values configurable color coding.</description>
        <inlineHelpText>Standard Colors
WHITE	#FFFFFF
SILVER	#C0C0C0
GRAY	#808080
BLACK	#000000
RED	#FF0000
MAROON	#800000
YELLOW	#FFFF00
OLIVE	#808000
LIME	#00FF00
GREEN	#008000
AQUA	#00FFFF
TEAL	#008080
BLUE	#0000FF
NAVY	#000080
FUCHSIA	#FF00FF
PURPLE	#800080</inlineHelpText>
        <label>Color Coding</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Width__c</fullName>
        <description>ADM_Forecasting Page Latest Comment column configurable width with numbers.</description>
        <inlineHelpText>ADM_Forecasting Page Latest Comment column configurable width with numbers.
Min width : 150</inlineHelpText>
        <label>Comment Width</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GuiFcstDay__c</fullName>
        <label>GuiFcstDay</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>ADM_Forecast_Page_Customization</label>
</CustomObject>

classes/ADMForecastingLoad_Controller_Test.cls
/**********************************************************************
Name:  ADMForecastingLoad_Controller_Test
Copyright © 2017
======================================================
======================================================
Purpose: Test Class for ADMForecastingLoad_Controller
-------                                                             
======================================================
======================================================
History                                                            
-------                                                            
VERSION      AUTHOR                DATE             DETAIL               	Description
 1.0        Altaf ur Rahman      10/12/2017      INITIAL DEVELOPMENT
***********************************************************************/

@isTest
public class ADMForecastingLoad_Controller_Test {

    Public static testmethod void ADMforecasting_Load(){       
        
        ADM_Forecast_Page_Customization__c d= new ADM_Forecast_Page_Customization__c();
          d.name ='CommentWidthandColorCoding';
          d.Color_Coding__c ='#008000';
          d.Comment_Width__c = '150';  
          d.GuiFcstDay__c = '88';
          insert d; 
        
        ADMForecastingLoad_Controller adm_LoadController = new ADMForecastingLoad_Controller();
        adm_LoadController.LatestCommentWidth = '';
        adm_LoadController.FrstColorCoding = '';
        adm_LoadController.nonPortfolioTab();
    }
}