objects/ADM_Forecast_Page_Customization__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ADM_Forecasting Page Latest Comment column configurable Width &amp; Color Coding.</description>
    <fields>
        <fullName>Color_Coding__c</fullName>
        <description>ADM_Forecasting Page Forecast values configurable color coding.</description>
        <inlineHelpText>Standard Colors
WHITE	#FFFFFF
SILVER	#C0C0C0
GRAY	#808080
BLACK	#000000
RED	#FF0000
MAROON	#800000
YELLOW	#FFFF00
OLIVE	#808000
LIME	#00FF00
GREEN	#008000
AQUA	#00FFFF
TEAL	#008080
BLUE	#0000FF
NAVY	#000080
FUCHSIA	#FF00FF
PURPLE	#800080</inlineHelpText>
        <label>Color Coding</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Width__c</fullName>
        <description>ADM_Forecasting Page Latest Comment column configurable width with numbers.</description>
        <inlineHelpText>ADM_Forecasting Page Latest Comment column configurable width with numbers.
Min width : 150</inlineHelpText>
        <label>Comment Width</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GuiFcstDay__c</fullName>
        <label>GuiFcstDay</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>ADM_Forecast_Page_Customization</label>
</CustomObject>

classes/ADMGuidanceForecastDetails_Schedule_Test.cls
/**********************************************************************
Name: ADMGuidanceForecastDetails_Schedule_Test
Copyright © 2017
======================================================
======================================================
Purpose: Test Class for ADMGuidanceForecastDetails_Schedule
-------                                                             
======================================================
======================================================
History                                                            
-------                                                            
VERSION      AUTHOR                DATE             DETAIL              
0.1        Kartik G          9/20/2017         INITIAL DEVELOPMENT
***********************************************************************/
@isTest
public class ADMGuidanceForecastDetails_Schedule_Test {
    
    public static testmethod void schedulerBatchGuiFcstTest(){
        Test.startTest();
        
        ADMGuidanceForecastDetails_Schedule bc = new  ADMGuidanceForecastDetails_Schedule();
        
            ADM_Forecast_Page_Customization__c GuiFcstDay = new  ADM_Forecast_Page_Customization__c();
        GuiFcstDay.Name ='CommentWidthandColorCoding';
        System.debug(' GuiFcstDay.Name...'+ GuiFcstDay.Name);
        GuiFcstDay.GuiFcstDay__c='15';
        GuiFcstDay.Color_Coding__c='#008000';
        GuiFcstDay.Comment_Width__c='150';
        insert GuiFcstDay;
        
        String sch = '0  00 1 3 * ?';
        string jobid = system.schedule('Test',sch,bc);
        
        Test.stopTest();
        
    }
}