objects/ADM_Custom_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADM Custom Setting</label>
</CustomObject>

objects/ADM_Region__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Region_Label__c</fullName>
        <label>Region Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Value__c</fullName>
        <label>Region Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADM_Region</label>
</CustomObject>

objects/ADMTerritoryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADMTerritoryCode</label>
</CustomObject>

objects/Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Forecast_Level__c</fullName>
        <description>Picklist identifying what level of forecast specific Account Forecast is being forecast on.</description>
        <label>Forecast Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Part Level</fullName>
                </value>
                <value>
                    <fullName>GPL Level</fullName>
                </value>
                <value>
                    <fullName>CBC3 Level</fullName>
                </value>
                <value>
                    <fullName>CBC2 Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Forecast</label>
    <nameField>
        <displayFormat>FCN-{000}</displayFormat>
        <label>Forecast Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <recordTypes>
        <fullName>ADM</fullName>
        <active>true</active>
        <description>Business Unit Specific ADM</description>
        <label>ADM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Forecast_Detail__c.object
<CustomObject>
    <label>Forecast Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Forecast Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ADMJDABookingForecastDisty_Batch_Test.cls
@isTest
public class ADMJDABookingForecastDisty_Batch_Test{
    @TestSetup
    public static void testDataSetup() 
    {
        Forecast__c frCast = new Forecast__c();
        //frCast= ADMTestDataFactory.createForecastObj('TestForecastExtid001','CON','BA','CAM','TestComments','Australia','Part Level',null,'Australiaregion','Portfolio'); 
        
        ClsTestCustomSettingHelper.getAllSettings();
        ClsTestCustomSettingHelper.getPMV_Sales_Stage_Setting();
        ChannelinsightData_test.ChannelinsightData_test();
        ClsTestCustomSettingHelper.getTrigger_Configuration();
        
        List<Forecast_Detail__c> frcDetailsList = new List<Forecast_Detail__c>();
        frcDetailsList=ADMTestDataFactory.createForCastDetails(frCast.id,'Forecast');              
         
        ADM_Region__c setting = new ADM_Region__c();
        setting.Name = 'Test Setting';
        setting.Region_Label__c = 'Test Setting';
        setting.Region_Value__c = 'Test Region';
        insert setting;
                
        ADMTerritoryCode__c ADMTeritoryCode = new ADMTerritoryCode__c();
        ADMTeritoryCode.Name = 'ADMTerritoryCode';
        ADMTeritoryCode.Territory_Code__c ='101485';
        insert ADMTeritoryCode;
   
        ADM_Custom_Setting__c admConfig = new ADM_Custom_Setting__c();
        admConfig.Name = 'ADM_DISTYForecastLevel';
        admConfig.Value__c = 'CBC3 Level';
        insert admConfig;
        
  }  
    
    static testMethod void testJDABooking(){
        
       Test.startTest();
        Id ForecastRecordTypeId = Schema.SObjectType.Forecast__c.getRecordTypeInfosByName().get('ADM').getRecordTypeId();      
        
        Product_Hierarchy__c prod = new Product_Hierarchy__c();
        prod.Name = 'Hierarchy1';
        insert prod;
        
        Account acc1 = new Account();
        acc1.Name = 't'+system.now().millisecond()+math.round(math.random()*10000);
        insert acc1; 
        
        Forecast__c frCast= ADMTestDataFactory.createForecastObj('TestForecastExtid001','CON','BA','CAM','TestComments','Australia','Part Level',null,'Australiaregion','Portfolio');
        frCast.Forecast_Level__c = 'CBC3 Level';
        frCast.RecordTypeId = ForecastRecordTypeId;
        update frCast;
        
        List<Forecast_Detail__c> frcDetailsList = new List<Forecast_Detail__c>();        
        frcDetailsList=ADMTestDataFactory.createForCastDetails(frCast.id,'Forecast');       
        
        ADMJDABookingForecastDisty_Batch bookJDA = new  ADMJDABookingForecastDisty_Batch();
        Database.executeBatch(bookJDA);
        
       Test.stopTest();
    }   
    
}