objects/ADMTerritoryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADMTerritoryCode</label>
</CustomObject>

objects/Opportunity_Forecast__c.object
<CustomObject>
    <description>This object contains the project forecast numbers.</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Status__c</fullName>
        <description>This field contains the process status of related oppy part.</description>
        <formula>TEXT(Part__r.Process_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <label>Opportunity Forecast</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Forecasts</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Part</fullName>
        <active>true</active>
        <label>Part</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Initial_Billing_Date__c</fullName>
        <label>Initial Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Order_Date__c</fullName>
        <label>Initial Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type__c</fullName>
        <formula>Opportunity__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Status__c</fullName>
        <label>Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concept</fullName>
                    <default>true</default>
                    <label>Concept</label>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Designed</fullName>
                </value>
                <value>
                    <fullName>Prototyped/Sampled</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Pre-prod</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Ramp-down</fullName>
                </value>
                <value>
                    <fullName>EOL</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Similar_TE_Part_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Similar TE Part Number</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts (Similar TE Part Number)</relationshipLabel>
        <relationshipName>Opportunity_Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <recordTypes>
        <fullName>Extension</fullName>
        <active>true</active>
        <label>Extension</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Record_Type_Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>RecordTypeID__c</fullName>
        <label>RecordTypeID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Record Type Groups</label>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>GIBU__c</fullName>
        <description>Used to help with tallying license counts and things like that.</description>
        <inlineHelpText>Select the GIBU/BU this user is from.</inlineHelpText>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>GATD</fullName>
                </value>
                <value>
                    <fullName>ICT (Ind Comm Transport)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIC</fullName>
                </value>
                <value>
                    <fullName>Sensors</fullName>
                </value>
                <value>
                    <fullName>TEIS</fullName>
                </value>
                <value>
                    <fullName>TEIS Engineering Portfolio Mgmt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PMV_Type_Initialization__c</fullName>
        <formula>IF( Country  = &apos;China&apos;, &apos;China&apos;, &apos;Standard&apos;)</formula>
        <label>PMV Type Initialization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <inlineHelpText>Please enter a sub-vertical BU for each user. This is used for BBB and opportunity reporting by profit center.</inlineHelpText>
        <label>Sub-Vertical BU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aero Def &amp; Marine</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data and Devices</fullName>
                </value>
                <value>
                    <fullName>DataComm</fullName>
                </value>
                <value>
                    <fullName>Devices</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Enterprise Networks</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>M/A-Com WSB</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Non-TE/Divested Prod</fullName>
                </value>
                <value>
                    <fullName>NS Central Services</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Solar</fullName>
                </value>
                <value>
                    <fullName>Systems</fullName>
                </value>
                <value>
                    <fullName>TEBS</fullName>
                </value>
                <value>
                    <fullName>Telecom Networks</fullName>
                </value>
                <value>
                    <fullName>Touch Solutions</fullName>
                </value>
                <value>
                    <fullName>Unident Customers</fullName>
                </value>
                <value>
                    <fullName>Wireless</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <description>This field contains the territory code of the user.</description>
        <externalId>true</externalId>
        <label>Territory Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ClsBatch_recalculateNPSForAPLTest.cls
/**
 * Test class for ClsBatch_recalculateNPSForAPL
 * Created by Nelson Zheng 06/12/2015
 *
 *
 */
@isTest
private class ClsBatch_recalculateNPSForAPLTest {

    static testMethod void myUnitTest() {
        User tempUser = [select id from user where GIBU__c = 'Industrial' and Sub_Vertical__c = 'A&C' and isactive = true and PMV_Type_Initialization__c = 'Standard' limit 1];
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getOpportunity_Record_Type_Groups();
        //ClsTestCustomSettingHelper.getPMV_Sales_Process_Settings();
        ClsTestCustomSettingHelper.getPMV_Language_Config();
        ClsTestCustomSettingHelper.getPMV_Sales_Stage_Setting();
        ClsTestCustomSettingHelper.getPMV_Stage_Config();
        ClsTestCustomSettingHelper.getPMV_Sales_Process_Settings();
        ClsTestCustomSettingHelper.getTriggerConfigurationSettings();
        
        list<Group> list_pgs = [select Name from Group where id in (select GroupId from GroupMember where userorgroupid = :UserInfo.getUserId())];
        
        ADMTerritoryCode__c ADMTerritoryCode = new ADMTerritoryCode__c(Name='ADMTerritoryCode', Territory_Code__c='101485');
        insert ADMTerritoryCode;
        
        RecordType rt = ClsTestHelp.createTestRecordType6();
        RecordType rt2 = ClsTestHelp.createTestRecordType16();
        RecordType rt3 = ClsTestHelp.createTestRecordType23();
        
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt.Id;
        acc.Account_Manager__c = UserInfo.getUserId();
        insert acc;
        
        Account acc2 = ClsTestHelp.createTestAccounts();
        acc2.RecordTypeId = rt.Id;
        acc2.Account_Manager__c = UserInfo.getUserId();
        insert acc2;
            
        Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
        oppy2.Program_level_Forecasting__c =true; 
        oppy2.Name = 'Pain of Queen';
        oppy2.Type = 'CM';
        oppy2.Request_Type__c = 'Extension';
        oppy2.RecordTypeId = rt3.Id;
        //oppy2.RecordTypeId = oppyRtId;
        oppy2.accountid = acc2.Id;
        insert oppy2;  
    
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial'; 
        insert ph;
        
        Part__c part = new Part__c();
        part.Description__c = 'Sniper';
        part.Product_Hierarchy__c = ph.Id;
        insert part;
        
        Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
        oppypart.Opportunity__c = oppy2.Id;
        oppypart.Part__c = oppypart.Id;
        oppypart.Similar_TE_Part_Number__c = part.Id;
        oppypart.initial_billing_date__c = date.today();
        oppypart.Initial_Order_Date__c = date.today();
        oppypart.Process_Status__c = 'Production';
        //oppypart.Opportunity_Record_Type__c = Opportunity_Record_Type_Groups__c.getInstance('DND Opportunity').RecordTypeID__c;
        insert oppypart;
        
        Date d = date.today();
        String month = d.month()+'';
        month = month.length() == 2 ? month : '0'+month;
        
        Opportunity_Forecast__c oppyForecast = ClsTestHelp.createTestOpportunityForecasts();
        oppyForecast.Opportunity__c = oppy2.Id;
        oppyForecast.Quantity__c = 12;
        oppyForecast.Part__c = oppypart.Id;
        oppyForecast.Date__c = date.today();
        oppyForecast.Sales_Price__c = 123;
        oppyForecast.Fiscal_Month__c = month;
        oppyForecast.Fiscal_Year__c = d.year()+'';
        oppyForecast.Amount__c = 1;
        //insert oppyForecast;
        
        List<Opportunity_Forecast__c> list_fcs = new List<Opportunity_Forecast__c>{oppyForecast};
        insert list_fcs;
        
        Test.startTest();
            ClsBatch_recalculateNPSForAPL bb = new ClsBatch_recalculateNPSForAPL(list_fcs);
            Database.executeBatch(bb);
        Test.stopTest();
    }
    
    static testMethod void test_DndOppy() {
        User tempUser = [select id from user where GIBU__c = 'Industrial' and Sub_Vertical__c = 'A&C' and isactive = true and PMV_Type_Initialization__c = 'Standard' limit 1];
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getOpportunity_Record_Type_Groups();
        //ClsTestCustomSettingHelper.getPMV_Sales_Process_Settings();
        ClsTestCustomSettingHelper.getPMV_Language_Config();
        ClsTestCustomSettingHelper.getPMV_Sales_Stage_Setting();
        ClsTestCustomSettingHelper.getPMV_Stage_Config();
        ClsTestCustomSettingHelper.getPMV_Sales_Process_Settings();
        ClsTestCustomSettingHelper.getTriggerConfigurationSettings();
        
        list<Group> list_pgs = [select Name from Group where id in (select GroupId from GroupMember where userorgroupid = :UserInfo.getUserId())];
        
        ADMTerritoryCode__c ADMTerritoryCode = new ADMTerritoryCode__c(Name='ADMTerritoryCode', Territory_Code__c='101485');
        insert ADMTerritoryCode;
        
        RecordType rt = ClsTestHelp.createTestRecordType6();
        RecordType rt2 = ClsTestHelp.createTestRecordType16();
        RecordType rt3 = ClsTestHelp.createTestRecordType23();
        
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt.Id;
        acc.Account_Manager__c = UserInfo.getUserId();
        insert acc;
        
        Account acc2 = ClsTestHelp.createTestAccounts();
        acc2.RecordTypeId = rt.Id;
        acc2.Account_Manager__c = UserInfo.getUserId();
        insert acc2;

        Opportunity oppy = ClsTestHelp.createTestOpportunity();
        oppy.Program_level_Forecasting__c =true; 
        oppy.Name = 'Pain of Queen';
        oppy.Type = 'CM';
        oppy.Request_Type__c = 'Extension';
        oppy.RecordTypeId = rt3.Id;
        oppy.accountid = acc2.Id;
        insert oppy;  
        
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial'; 
        insert ph;
        
        Part__c part = new Part__c();
        part.Description__c = 'Sniper';
        part.Product_Hierarchy__c = ph.Id;
        insert part;    
        
        Opportunity_Part__c oppypartDnd = ClsTestHelp.createTestOpportunityPart();
        oppypartDnd.Opportunity__c = oppy.Id;
        oppypartDnd.Part__c = oppypartDnd.Id;
        oppypartDnd.Similar_TE_Part_Number__c = part.Id;
        oppypartDnd.initial_billing_date__c = date.today();
        oppypartDnd.Initial_Order_Date__c = date.today();
        oppypartDnd.Process_Status__c = 'Production';
        //oppypartDnd.Opportunity_Record_Type__c = Opportunity_Record_Type_Groups__c.getInstance('DND Opportunity').RecordTypeID__c;
        insert oppypartDnd;
        
        Date d = date.today();
        String month = d.month()+'';
        month = month.length() == 2 ? month : '0'+month;
        
        Opportunity_Forecast__c fc1 = ClsTestHelp.createTestOpportunityForecasts();
        fc1.Opportunity__c = oppy.Id;
        fc1.Quantity__c = 12;
        fc1.Part__c = oppypartDnd.Id;
        fc1.Date__c = date.today();
        fc1.Sales_Price__c = 123;
        fc1.Fiscal_Month__c = month;
        fc1.Fiscal_Year__c = d.year()+'';
        fc1.Amount__c = 1;
        
        List<Opportunity_Forecast__c> list_fcs = new List<Opportunity_Forecast__c>{fc1};
        insert list_fcs;
        
        Test.startTest();
            ClsBatch_recalculateNPSForAPL bb = new ClsBatch_recalculateNPSForAPL(list_fcs);
            Database.executeBatch(bb);
        Test.stopTest();
    }
}