objects/ADMTerritoryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADMTerritoryCode</label>
</CustomObject>

objects/Consumer_Device_Opportunity_Record_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Consumer Device Opportunity Record Types</description>
    <fields>
        <fullName>Record_Type_Id__c</fullName>
        <label>Record_Type_Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Consumer Device Opportunity Record Types</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Currency_Confirm__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Currency Confirm</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Response</fullName>
        <active>true</active>
        <businessProcess>Central Lead Process</businessProcess>
        <description>An unqualified lead created by Eloqua in order to capture campaign responses</description>
        <label>Response</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The custom setting is used for defend trigger operations.</description>
    <fields>
        <fullName>isRun__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The field is used to determine whether a trigger should run.</description>
        <label>isRun</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CSD_Region__c</fullName>
        <label>CSD Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taiwan</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>South Asia(Pacific)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GIBU__c</fullName>
        <description>Used to help with tallying license counts and things like that.</description>
        <inlineHelpText>Select the GIBU/BU this user is from.</inlineHelpText>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>GATD</fullName>
                </value>
                <value>
                    <fullName>ICT (Ind Comm Transport)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIC</fullName>
                </value>
                <value>
                    <fullName>Sensors</fullName>
                </value>
                <value>
                    <fullName>TEIS</fullName>
                </value>
                <value>
                    <fullName>TEIS Engineering Portfolio Mgmt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <description>This field contains the territory code of the user.</description>
        <externalId>true</externalId>
        <label>Territory Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UpdateAccountSharing_Opportunity_Test.cls
@isTest
(SeeAllData=false)
private class UpdateAccountSharing_Opportunity_Test{
    
    public static testMethod void MytestTrigger() {
    
        Profile p =new Profile();
         for(profile oProfile : [SELECT Id, name FROM Profile WHERE Name='DND Engineering User w/Cost']) 
              p=oProfile ;
        User u = new User(GIBU__c='Consumer Devices', Alias = 'standt', Email='test432@testorg.com', EmailEncodingKey='UTF-8', LastName='Test432', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='test432@testorg.com', CSD_Region__c='Taiwan');
        insert u;
        
         //* Added by Archana...code changes start
        List<Trigger_Configuration__c> lstTriggerConfig = new  List<Trigger_Configuration__c>();
       
        Trigger_Configuration__c tc = new Trigger_Configuration__c(); 
        tc.Name='Avoid Duplicate PLM Id';
        tc.isRun__c=true;
        lstTriggerConfig .add(tc);
               
        Trigger_Configuration__c tc2 = new Trigger_Configuration__c(); 
        tc2.Name='DND Lead Conversion Initialization';
        tc2.isRun__c=true;
        lstTriggerConfig .add(tc2);
        
        Trigger_Configuration__c tc3 = new Trigger_Configuration__c(); 
        tc3.Name='Identify Fiscal Year';
        tc3.isRun__c=true;
        lstTriggerConfig .add(tc3);
        
        Trigger_Configuration__c tc4 = new Trigger_Configuration__c(); 
        tc4.Name='Populate Opportunity Partner';
        tc4.isRun__c=true;
        lstTriggerConfig .add(tc4);
        
        Trigger_Configuration__c tc5 = new Trigger_Configuration__c(); 
        tc5.Name='updateAccountBusinessUnit';
        tc5.isRun__c=true;
        lstTriggerConfig .add(tc5);
        
        insert lstTriggerConfig ;
        
        ADMTerritoryCode__c admTerritoryCode= new ADMTerritoryCode__c();
        admTerritoryCode.Name='ADMTerritoryCode';
        admTerritoryCode.Territory_Code__c='101485';
        insert admTerritoryCode;
        
                //* Added by Archana...code changes end
       
        
        //Account Record Type
        Schema.DescribeSObjectResult cfrSchema1 = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema1.getRecordTypeInfosByName(); 
        //Opportunity Record types
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> OpportunityRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        
       ClsTestCustomSettingHelper.getApex_Helper_Settings();
       ClsTestCustomSettingHelper.getOpportunity_Approvers();       
       ClsTestCustomSettingHelper.getOpportunity_Record_Type_Groups();
       ClsTestCustomSettingHelper.getProfit_BU_Center_Mapping_Rule2();     
       ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        
       Id CSDrtId = Consumer_Device_Opportunity_Record_Types__c.getInstance('Sales Opportunity-CSD').Record_Type_Id__c;
        Id EnggrtId = Consumer_Device_Opportunity_Record_Types__c.getInstance('Engineering Opportunity-CSD').Record_Type_Id__c;
        Id CSDAccrtId = Consumer_Device_Opportunity_Record_Types__c.getInstance('OEM').Record_Type_Id__c;
        //Account Records        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.ownerId = UserInfo.getUserId();        
        acc.Account_Manager__c = U.Id;
        acc.BillingCountry = 'CN';
        acc.billingstate='LA';
        acc.AccountNumber = '0451:01319551';
       acc.Website='www.salesforce.com';
        acc.Type='CM';
        acc.SicDesc='test';
        acc.Sic='test';
        acc.Shippingcity='test';
        acc.Shippingstate='test';
        acc.Shippingcountry='test';
        //acc.pincode=522301;
        acc.Rating='hot';
        acc.Phone='22090099';
        acc.Ownership='Public';
        acc.Industry='Appliance';
        acc.Fax='900900';
        acc.NumberOfEmployees=10;
        acc.Description='test';
        acc.Jigsaw='00kiludgsj';
        //acc.BillingAddress='test';
        acc.AnnualRevenue=4;
        acc.Site='www.google.com';
        acc.CurrencyIsoCode='USD';       
        acc.RecordTypeId = CSDAccrtId;
        insert acc;
        
        Opportunity opp = new Opportunity(Currency_Confirm__c = true,isFromCode__c = true, Mass_prod_Status__c=true, Description = 'Test', Type = 'New Business', AccountId = acc.id, Name = 'Test', RecordTypeId = CSDrtId, CloseDate = system.today() , StageName = 'New', Probability = 0,Fulfillment_Region__c = userinfo.getuserid(), OEM_Name__c = acc.id, Amount = 100, Two_Years_Revenue__c = 100, Provide_to_customer_Quotation_Date__c = system.today(), Lost_Rejected_Dead_On_Hold_Reason__c = 'Awaiting customer response');
        insert opp;
        acc.Account_Manager__c =UserInfo.getUserId();
        update acc;        
    }
}