objects/ADMTerritoryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADMTerritoryCode</label>
</CustomObject>

objects/Apex_Helper_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for e.g. record type ids, profile ids, ... That no hardcodings in apex codes are needed.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is custom setting record active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Describes the custom setting record.</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>This field contains Ids, developer names, ...</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Helper Settings</label>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Initial_Billing_Date__c</fullName>
        <label>Initial Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Order_Date__c</fullName>
        <label>Initial Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Status__c</fullName>
        <label>Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concept</fullName>
                    <default>true</default>
                    <label>Concept</label>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Designed</fullName>
                </value>
                <value>
                    <fullName>Prototyped/Sampled</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Pre-prod</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Ramp-down</fullName>
                </value>
                <value>
                    <fullName>EOL</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <recordTypes>
        <fullName>Sales_Parts</fullName>
        <active>true</active>
        <label>Sales Parts</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Record_Type_Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeID__c</fullName>
        <label>RecordTypeID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Record Type Groups</label>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry_Code__c</fullName>
        <label>Industry Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Profit_BU_Center_Mapping_Rule1__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>rule1</description>
    <label>Profit BU Center Mapping Rule1</label>
</CustomObject>

objects/Profit_BU_Center_Mapping_Rule2__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>rule2</description>
    <label>Profit BU Center Mapping Rule2</label>
</CustomObject>

objects/Profit_BU_Center_Mapping_Rule3__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>rule3</description>
    <label>Profit BU Center Mapping Rule3</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>GIBU__c</fullName>
        <description>Used to help with tallying license counts and things like that.</description>
        <inlineHelpText>Select the GIBU/BU this user is from.</inlineHelpText>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>GATD</fullName>
                </value>
                <value>
                    <fullName>ICT (Ind Comm Transport)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIC</fullName>
                </value>
                <value>
                    <fullName>Sensors</fullName>
                </value>
                <value>
                    <fullName>TEIS</fullName>
                </value>
                <value>
                    <fullName>TEIS Engineering Portfolio Mgmt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Vertical__c</fullName>
        <inlineHelpText>Please enter a sub-vertical BU for each user. This is used for BBB and opportunity reporting by profit center.</inlineHelpText>
        <label>Sub-Vertical BU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aero Def &amp; Marine</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data and Devices</fullName>
                </value>
                <value>
                    <fullName>DataComm</fullName>
                </value>
                <value>
                    <fullName>Devices</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Enterprise Networks</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>M/A-Com WSB</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Non-TE/Divested Prod</fullName>
                </value>
                <value>
                    <fullName>NS Central Services</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Solar</fullName>
                </value>
                <value>
                    <fullName>Systems</fullName>
                </value>
                <value>
                    <fullName>TEBS</fullName>
                </value>
                <value>
                    <fullName>Telecom Networks</fullName>
                </value>
                <value>
                    <fullName>Touch Solutions</fullName>
                </value>
                <value>
                    <fullName>Unident Customers</fullName>
                </value>
                <value>
                    <fullName>Wireless</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <description>This field contains the territory code of the user.</description>
        <externalId>true</externalId>
        <label>Territory Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ClsOppyTrgRefreshBUProfit_Test.cls
@isTest
public class ClsOppyTrgRefreshBUProfit_Test{

static testMethod void test_123() {
  ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();

        RecordType rt31 = ClsTestHelp.createTestRecordType31();
        insert (new Opportunity_Record_Type_Groups__c(name = 'ADM sales',RecordTypeID__c = rt31.Id, Group__c = 'ADM Group', active__c = true));
        insert (new Opportunity_Record_Type_Groups__c(name = 'ADM',RecordTypeID__c = rt31.Id, Group__c = 'Engineering Milestones Opportunities', active__c = true));
        //insert (new Opportunity_Record_Type_Groups__c(name = 'DND Opportunity',RecordTypeID__c = '012E0000000NIlV', Group__c = 'Process Status Display', active__c = true));
   //   Profit_BU_Center_Mapping_Rule1__c pb1 = ClsTestHelp.createTestProfitBUCenterMapping1();
       // Profit_BU_Center_Mapping_Rule2__c pb2 = ClsTestHelp.createTestProfitBUCenterMapping2();
     //   Profit_BU_Center_Mapping_Rule3__c pb3 = ClsTestHelp.createTestProfitBUCenterMapping3();
        
  //  ClsTestCustomSettingHelper.getOpportunity_Record_Type_Groups();      
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getTrigger_Configuration();
        ClsTestCustomSettingHelper.getPMV_Sales_Process_Settings();
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ChannelinsightData_test.ChannelinsightData_test();
      //  ClsTestCustomSettingHelper.getPMV_Sales_Process_Settings();
       // ClsTestCustomSettingHelper.getPMV_Sales_Stage_Setting();

  ADMTerritoryCode__c admTerritory= new ADMTerritoryCode__c();
        admTerritory.Name='ADMTerritoryCode';
        admTerritory.Territory_Code__c='101485';
        
        insert admTerritory;
       
         list<Opportunity_Record_Type_Groups__c> lstORTG = new list<Opportunity_Record_Type_Groups__c>();
        lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'Opportunity - Sales Project',RecordTypeID__c = '012E0000000XrBY', Group__c = 'Change Channel Opportunities at header level', active__c = true));
        lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'NDR Opportunity',RecordTypeID__c = '012E0000000egdDIAQ', active__c = true));
        lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'CCR Opportunity',RecordTypeID__c = '0123C000000065gQAA', active__c = true));
        lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'Part Std Price Display on Forecast',RecordTypeID__c = '012E0000000eR0c', Group__c = 'Part Std Price Display on Forecast', active__c = true));
        lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'Change Channel Oppy header level',RecordTypeID__c = '012E0000000eR0c', Group__c = 'Change Channel Opportunities at header level', active__c = true));
        lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'IND_Sales_Project',RecordTypeID__c = '012E0000000fCzm', active__c = true));
        lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'IND_Engineering_project',RecordTypeID__c = '012E0000000fCzr', active__c = true)); 
        
            lstORTG.add(new Opportunity_Record_Type_Groups__c(name = 'DND Opportunity',RecordTypeID__c = '012E0000000NIlV', Group__c = 'Process Status Display', active__c = true)); //Archana : Added
     
        insert lstORTG; 
        
        
        
        Profile p = [Select Id, Name From Profile where Name ='System Administrator' or Name ='Systemadministrator' limit 1];
       
       User u = [Select Id, Name,Email , country,GIBU__c,Sub_Vertical__c  From User where ProfileId =:p.id and isactive=true limit 1];
       //User u = [Select Id, Name,Email , country,GIBU__c,Sub_Vertical__c  From User where ProfileId =:p.id  and GIBU__c='Industrial' and Sub_Vertical__c='Industrial'  and isactive=true limit 1];
       /*              
        User u = ClsTestHelp.createTestUsers();
        u.Email = 'hellEFD@testCompany1233423.com';
        u.Alias = 'dpED';
        u.CommunityNickname = 'NNDU';
        u.ProfileId = p.Id;
        u.LocaleSidKey= 'de';
        u.country='India';
        u.GIBU__c='Industrial';
                u.Sub_Vertical__c='Industrial';
        insert u;
     */         
       system.runAs(u){  
       ClsTestCustomSettingHelper.getApex_Helper_Settings();  
        RecordType rt = ClsTestHelp.createTestRecordType();
      //  RecordType rt1 = ClsTestHelp.createTestRecordType11();
      RecordType rt1=ClsTestHelp.createPMVTestRecordType1();
        RecordType rt2 = ClsTestHelp.createTestRecordType16();     
        Account acc = ClsTestHelp.createTestAccounts();
        acc.Industry_Code_Description__c='Appliances';
        RecordType  oppy_part_sales_part_rt= [select Id,Name from RecordType where SobjectType = 'Opportunity_Part__c' and DeveloperName = 'Sales_Parts'];
        acc.Type = 'CM';
        insert acc;

        Apex_Helper_Settings__c ah =new Apex_Helper_Settings__c(name='Exclude Oppy Revenue Phase',value__c='Dead,Lost,Dead - Closed,Lost - Closed',active__c=true);
        insert ah;

        Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
        oppy2.Program_level_Forecasting__c =true; 
        oppy2.Name = 'Pain of Queen';
        oppy2.Type = 'CM';
        oppy2.Request_Type__c = 'IND_Sales_Project';
        oppy2.RecordTypeId = rt2.Id;
        oppy2.stagename= 'Exploring Needs';
        oppy2.PMV_Type__c ='IND Standard Sales opp';
        oppy2.Manufacturing_Start_Date__c=System.today();
      //  oppy2.Industry_Code__c='Appliances';
        insert oppy2;  
          
        Opportunity oppy = ClsTestHelp.createTestOpportunity();
        oppy.Program__c = oppy2.Id;   
        oppy.Type = 'CM';
        oppy.Request_Type__c = 'IND_Sales_Project';
        oppy.Method__c = 'BOM';
        oppy.Level__c = 'Yearly';
        oppy.Amount = 1;
        oppy.CurrencyIsoCode = 'EUR';
        oppy.Five_Year_Revenue__c = 1;
        oppy.RecordTypeId = rt1.Id;
        oppy.stagename= 'Exploring Needs';
        oppy.PMV_Type__c ='IND Standard Sales opp';
                oppy.Manufacturing_Start_Date__c=System.today();
      //  oppy.Industry_Code__c='Appliances';
       // insert oppy;
        
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial'; 
        insert ph;
        
        Part__c part = new Part__c();
        part.Description__c = 'Sniper';
        part.Product_Hierarchy__c = ph.Id;
         part.name='Sales Part';
         part.Standard_Price__c=120.34;
          insert part;
        
        Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
        oppypart.Opportunity__c = oppy2.Id;
        oppypart.Part__c = part.Id;   
        oppypart.Process_Status__c = 'Production';
        oppypart.initial_billing_date__c = Date.today();
        oppypart.initial_order_date__c = Date.today(); 
        oppypart.CurrencyIsoCode='USD';         
        
        oppypart.RecordTypeId = oppy_part_sales_part_rt.id;//'012E0000000XrBg';
//                oppypart.RecordType.Name = 'Sales Part';
        insert oppypart;
        
        Opportunity_Part__c oppypart1 = ClsTestHelp.createTestOpportunityPart();
        oppypart1.Opportunity__c = oppy2.Id;
        oppypart1.Part__c = part.Id;
        oppypart1.Process_Status__c = 'Production';
        oppypart1.initial_billing_date__c = Date.today();
        oppypart1.initial_order_date__c = Date.today();            
        oppypart1.RecordTypeId = '012E0000000XrBg';
          oppypart1.CurrencyIsoCode='USD';  
              
        insert oppypart1;
        
        set<Id> oppId =new Set<Id>();
        oppId.add(oppy2.id);
        Test.startTest();
        ClsOppyTrgRefreshBUProfit.UpdateBUProfit(oppId );
        Test.stopTest();
        
        }
            
}
}