objects/ADMTerritoryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADMTerritoryCode</label>
</CustomObject>

objects/Apex_Helper_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for e.g. record type ids, profile ids, ... That no hardcodings in apex codes are needed.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is custom setting record active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>This field contains Ids, developer names, ...</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Helper Settings</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Currency_Confirm__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Currency Confirm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Start_Date__c</fullName>
        <inlineHelpText>Date when orders begin shipping to the customer for general acceptance</inlineHelpText>
        <label>Manufacturing Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>CM, Distributor, OEM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Role__c</fullName>
        <label>Partner Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>CM</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Associate</fullName>
                </value>
                <value>
                    <fullName>Contractor (Electrical)</fullName>
                </value>
                <value>
                    <fullName>Contractor (General)</fullName>
                </value>
                <value>
                    <fullName>Owner / Developer</fullName>
                </value>
                <value>
                    <fullName>Engineer / Architect</fullName>
                </value>
                <value>
                    <fullName>Engineer / Procurement / Construction</fullName>
                </value>
                <value>
                    <fullName>Rep Firm</fullName>
                </value>
                <value>
                    <fullName>VAD (Value Added Distributor)</fullName>
                </value>
                <value>
                    <fullName>Utility - IOU</fullName>
                </value>
                <value>
                    <fullName>Utility - Municipal</fullName>
                </value>
                <value>
                    <fullName>Utility - Cooperative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Opportunity Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Record_Type_Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecordTypeID__c</fullName>
        <label>RecordTypeID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Record Type Groups</label>
</CustomObject>

objects/Opportunity_Team_Default_Permission__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>By BU</description>
    <fields>
        <fullName>Permission__c</fullName>
        <description>Enter value &quot;Read&apos; or &quot;Edit&quot;</description>
        <label>Permission</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Team Default Permission</label>
</CustomObject>

objects/Partner_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click the magnifying glass to look up an account.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Roles</relationshipLabel>
        <relationshipName>Partner_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>Click the magnifying glass to look up an Opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partner Roles</relationshipLabel>
        <relationshipName>Partner_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Partner Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Hierarchy__c.object
<CustomObject>
    <description>Reflects the Sales Hierarchy.</description>
    <fields>
        <fullName>Level_2_Territory_Code__c</fullName>
        <label>Level 2 Territory Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_7_Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Account Owner</description>
        <label>Level 7 Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Hierarchies_Level7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Level 7 territory code</inlineHelpText>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sales Hierarchy</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The custom setting is used for defend trigger operations.</description>
    <fields>
        <fullName>isRun__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The field is used to determine whether a trigger should run.</description>
        <label>isRun</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>GIBU__c</fullName>
        <description>Used to help with tallying license counts and things like that.</description>
        <inlineHelpText>Select the GIBU/BU this user is from.</inlineHelpText>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>GATD</fullName>
                </value>
                <value>
                    <fullName>ICT (Ind Comm Transport)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIC</fullName>
                </value>
                <value>
                    <fullName>Sensors</fullName>
                </value>
                <value>
                    <fullName>TEIS</fullName>
                </value>
                <value>
                    <fullName>TEIS Engineering Portfolio Mgmt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Te_Network_Id__c</fullName>
        <description>This field contains the users TE Network Id.</description>
        <label>Te Network Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <description>This field contains the territory code of the user.</description>
        <externalId>true</externalId>
        <label>Territory Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SharingUtilsTest.cls
@isTest
private class SharingUtilsTest {

    static testMethod void myUnitTest1 () {
    
            Test.startTest();
            
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        //* Added by Archana...code changes start
        List<Trigger_Configuration__c> lstTriggerConfig = new  List<Trigger_Configuration__c>();
       
        Trigger_Configuration__c tc = new Trigger_Configuration__c(); 
        tc.Name='Avoid Duplicate PLM Id';
        tc.isRun__c=true;
        lstTriggerConfig .add(tc);
               
        Trigger_Configuration__c tc2 = new Trigger_Configuration__c(); 
        tc2.Name='DND Lead Conversion Initialization';
        tc2.isRun__c=true;
        lstTriggerConfig .add(tc2);
        
        Trigger_Configuration__c tc3 = new Trigger_Configuration__c(); 
        tc3.Name='Identify Fiscal Year';
        tc3.isRun__c=true;
        lstTriggerConfig .add(tc3);
        
        Trigger_Configuration__c tc4 = new Trigger_Configuration__c(); 
        tc4.Name='Populate Opportunity Partner';
        tc4.isRun__c=true;
        lstTriggerConfig .add(tc4);
        
        Trigger_Configuration__c tc5 = new Trigger_Configuration__c(); 
        tc5.Name='updateAccountBusinessUnit';
        tc5.isRun__c=true;
        lstTriggerConfig .add(tc5);
        
        insert lstTriggerConfig ;
        
        ADMTerritoryCode__c admTerritoryCode= new ADMTerritoryCode__c();
        admTerritoryCode.Name='ADMTerritoryCode';
        admTerritoryCode.Territory_Code__c='101485';
        insert admTerritoryCode;
        
                //* Added by Archana...code changes end
        

         

        
        Opportunity_Record_Type_Groups__c a = new Opportunity_Record_Type_Groups__c();
        a.name= 'DND Opportunity';
        a.Active__c = true;
        a.RecordTypeID__c = '012c00000008oxY';
        insert a;
        RecordType rt8 = ClsTestHelp.createTestRecordType8();
        
       Profile p = [Select Id, Name From Profile 
                                    where Name = 'Production Support'
                                    or Name ='System Administrator' limit 1];
        Opportunity_Team_Default_Permission__c per = new Opportunity_Team_Default_Permission__c();
        per.Name = 'ProfileNotSendEmail';
        per.permission__c = 'Channel insight app;';
        insert per;
        
        List<User> uList = new List<User>();
        User u = ClsTestHelp.createTestUsers();
        u.Email = 'helloSand0728@testCompany1407281004.com';
        u.FirstName ='Test0728';
        u.LastName = 'User0728';
        u.Alias = 'dpse0728';
        u.CommunityNickname = 'TMD0711';
        u.ProfileId = p.Id;
        u.GIBU__c = 'Appliances';
        u.Username = 'helloSand0728@testCompany1407281004.com';
        uList.add(u);
        
        User u1 = ClsTestHelp.createTestUsers();
        u1.Email = 'helloSand0728@testCompany1407281004.com';
        u1.FirstName ='Test0728';
        u1.LastName = 'User0728';
        u1.Alias = 'dpse012';
        u1.CommunityNickname = 'TMD071';
        u1.ProfileId = p.Id;
        u1.GIBU__c = 'Appliances';
        u1.Te_Network_Id__c = 'TE111111';
        u1.Username = 'helloSand01111@testCompany1407281004.com';
        uList.add(u1);
        
        User u2 = ClsTestHelp.createTestUsers();
        u2.Email = 'helloSand0728@testCompany1407281004.com';
        u2.FirstName ='Test07281';
        u2.LastName = 'User07281';
        u2.Alias = 'dpse44';
        u2.CommunityNickname = 'TMD04';
        u2.ProfileId = p.Id;
        u2.GIBU__c = 'Appliances';
        u2.Te_Network_Id__c = 'TE222222';
        u2.Username = 'helloSand02222@testCompany1407281004.com';
        uList.add(u2);
        insert uList;
        
        RecordType rt2 = ClsTestHelp.createTestRecordType10();
        RecordType rt = ClsTestHelp.createTestRecordType14();
        
        Sales_Hierarchy__c sh = ClsTestHelp.createTestSalesHierarchy();
        sh.Level_2_Territory_Code__c = '103004';
        sh.Level_7_Default_Owner__c = u1.Id;
        sh.Level_7_Territory_Code__c = '123456';
        insert sh;
        
        List<Account> accList = new List<Account>();
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt.Id;
        acc.Type = 'Global Account';
        acc.Industry_Code_Description__c = 'Appliances';
        acc.LEVEL_1_INDUSTRY_CDE__c = '0283';
        acc.owner = u;
        acc.Account_Manager__c = u.Id;
        accList.add(acc); 
        
        Account acc1 = ClsTestHelp.createTestAccounts();
        acc1.RecordTypeId = rt.Id;
        acc1.Type = 'Global Account';
        acc1.Industry_Code_Description__c = 'Appliances';
        acc1.LEVEL_1_INDUSTRY_CDE__c = '0283';
        acc1.owner = u1;
        acc1.Account_Manager__c = u1.Id;
        accList.add(acc1); 
        
        insert accList;
       //
        SharingUtils.CreateAccountTeamMember(acc1.Id,u.Id,'Test');
        Set<String> teNetworkIdSet = new Set<String>();
        teNetworkIdSet.add('TE111111');
        teNetworkIdSet.add('TE222222');
        
        Set<Id> accSet = new Set<Id>();
        accSet.add(acc1.Id);
        
        List<User> userList = SharingUtils.GetSFUserIdNameByNetworkId(teNetworkIdSet);
        SharingUtils.GetSFUserByNetworkIdMap(userList);
        SharingUtils.CreateAccountShare(acc1.Id,u.Id);
        SharingUtils.CreateGlobalAccountShare(acc1.Id,u.Id);
        SharingUtils.CreateMarketShare(acc1.Id,u.Id);
        SharingUtils.GetSalesHierarchy('123456');
        SharingUtils.GetCFTMembersMap(accSet);
        SharingUtils.GetMarketTeamMembersMap(accSet);
        SharingUtils.GetAcctTeamMembersMap(accSet);
        
             
        Test.stopTest();
    }
    
        
        static testMethod void myUnitTest2 () {
    
            Test.startTest();
            
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        //* Added by Archana...code changes start
        List<Trigger_Configuration__c> lstTriggerConfig = new  List<Trigger_Configuration__c>();
       
        Trigger_Configuration__c tc = new Trigger_Configuration__c(); 
        tc.Name='Avoid Duplicate PLM Id';
        tc.isRun__c=true;
        lstTriggerConfig .add(tc);
               
        Trigger_Configuration__c tc2 = new Trigger_Configuration__c(); 
        tc2.Name='DND Lead Conversion Initialization';
        tc2.isRun__c=true;
        lstTriggerConfig .add(tc2);
        
        Trigger_Configuration__c tc3 = new Trigger_Configuration__c(); 
        tc3.Name='Identify Fiscal Year';
        tc3.isRun__c=true;
        lstTriggerConfig .add(tc3);
        
        Trigger_Configuration__c tc4 = new Trigger_Configuration__c(); 
        tc4.Name='Populate Opportunity Partner';
        tc4.isRun__c=true;
        lstTriggerConfig .add(tc4);
        
        Trigger_Configuration__c tc5 = new Trigger_Configuration__c(); 
        tc5.Name='updateAccountBusinessUnit';
        tc5.isRun__c=true;
        lstTriggerConfig .add(tc5);
        
        insert lstTriggerConfig ;
        
        ADMTerritoryCode__c admTerritoryCode= new ADMTerritoryCode__c();
        admTerritoryCode.Name='ADMTerritoryCode';
        admTerritoryCode.Territory_Code__c='101485';
        insert admTerritoryCode;
        
                //* Added by Archana...code changes end
        
        Apex_Helper_Settings__c ah =new Apex_Helper_Settings__c(name='Exclude Oppy Revenue Phase',value__c='Dead,Lost,Dead - Closed,Lost - Closed',active__c=true);
        insert ah;        
         

        
        Opportunity_Record_Type_Groups__c a = new Opportunity_Record_Type_Groups__c();
        a.name= 'DND Opportunity';
        a.Active__c = true;
        a.RecordTypeID__c = '012c00000008oxY';
        insert a;
        RecordType rt8 = ClsTestHelp.createTestRecordType8();
        
       Profile p = [Select Id, Name From Profile 
                                    where Name = 'Production Support'
                                    or Name ='System Administrator' limit 1];
        Opportunity_Team_Default_Permission__c per = new Opportunity_Team_Default_Permission__c();
        per.Name = 'ProfileNotSendEmail';
        per.permission__c = 'Channel insight app;';
        insert per;
        
        List<User> uList = new List<User>();
        User u = ClsTestHelp.createTestUsers();
        u.Email = 'helloSand0728@testCompany1407281004.com';
        u.FirstName ='Test0728';
        u.LastName = 'User0728';
        u.Alias = 'dpse0728';
        u.CommunityNickname = 'TMD0711';
        u.ProfileId = p.Id;
        u.GIBU__c = 'Appliances';
        u.Username = 'helloSand0728@testCompany1407281004.com';
        uList.add(u);
        
        User u1 = ClsTestHelp.createTestUsers();
        u1.Email = 'helloSand0728@testCompany1407281004.com';
        u1.FirstName ='Test0728';
        u1.LastName = 'User0728';
        u1.Alias = 'dpse012';
        u1.CommunityNickname = 'TMD071';
        u1.ProfileId = p.Id;
        u1.GIBU__c = 'Appliances';
        u1.Te_Network_Id__c = 'TE111111';
        u1.Username = 'helloSand01111@testCompany1407281004.com';
        uList.add(u1);
        
        User u2 = ClsTestHelp.createTestUsers();
        u2.Email = 'helloSand0728@testCompany1407281004.com';
        u2.FirstName ='Test07281';
        u2.LastName = 'User07281';
        u2.Alias = 'dpse44';
        u2.CommunityNickname = 'TMD04';
        u2.ProfileId = p.Id;
        u2.GIBU__c = 'Appliances';
        u2.Te_Network_Id__c = 'TE222222';
        u2.Username = 'helloSand02222@testCompany1407281004.com';
        uList.add(u2);
        insert uList;
        
        RecordType rt2 = ClsTestHelp.createTestRecordType10();
        RecordType rt = ClsTestHelp.createTestRecordType14();
        
        Sales_Hierarchy__c sh = ClsTestHelp.createTestSalesHierarchy();
        sh.Level_2_Territory_Code__c = '103004';
        sh.Level_7_Default_Owner__c = u1.Id;
        sh.Level_7_Territory_Code__c = '123456';
        insert sh;
        
        List<Account> accList = new List<Account>();
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt.Id;
        acc.Type = 'Global Account';
        acc.Industry_Code_Description__c = 'Appliances';
        acc.LEVEL_1_INDUSTRY_CDE__c = '0283';
        acc.owner = u;
        acc.Account_Manager__c = u.Id;
        accList.add(acc); 
      
        insert accList;
       /*
        SharingUtils.CreateAccountTeamMember(acc1.Id,u.Id,'Test');
        Set<String> teNetworkIdSet = new Set<String>();
        teNetworkIdSet.add('TE111111');
        teNetworkIdSet.add('TE222222');
        */
       
      
        
        Opportunity oppy = new Opportunity();
        oppy.StageName = 'New';
        oppy.AccountId = acc.Id;
        oppy.Account = acc;
        oppy.Name = 'SandKing';
        oppy.CloseDate = date.today();
        oppy.Manufacturing_Start_Date__c = date.today().addMonths(1);
        oppy.RecordTypeId = rt2.Id;            
        oppy.currency_confirm__c = true;
        oppy.Mass_prod_Status__c = true;
        oppy.owner = u; 
        insert oppy;
        
        
        
        SharingUtils.CreateOpptyTeamMember(oppy.Id,u.Id,'Partner SE');
        
        
           Test.stopTest();
    }
        static testMethod void myUnitTest3 () {
    
            Test.startTest();
            
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        //* Added by Archana...code changes start
        List<Trigger_Configuration__c> lstTriggerConfig = new  List<Trigger_Configuration__c>();
       
        Trigger_Configuration__c tc = new Trigger_Configuration__c(); 
        tc.Name='Avoid Duplicate PLM Id';
        tc.isRun__c=true;
        lstTriggerConfig .add(tc);
               
        Trigger_Configuration__c tc2 = new Trigger_Configuration__c(); 
        tc2.Name='DND Lead Conversion Initialization';
        tc2.isRun__c=true;
        lstTriggerConfig .add(tc2);
        
        Trigger_Configuration__c tc3 = new Trigger_Configuration__c(); 
        tc3.Name='Identify Fiscal Year';
        tc3.isRun__c=true;
        lstTriggerConfig .add(tc3);
        
        Trigger_Configuration__c tc4 = new Trigger_Configuration__c(); 
        tc4.Name='Populate Opportunity Partner';
        tc4.isRun__c=true;
        lstTriggerConfig .add(tc4);
        
        Trigger_Configuration__c tc5 = new Trigger_Configuration__c(); 
        tc5.Name='updateAccountBusinessUnit';
        tc5.isRun__c=true;
        lstTriggerConfig .add(tc5);
        
        insert lstTriggerConfig ;
        
        ADMTerritoryCode__c admTerritoryCode= new ADMTerritoryCode__c();
        admTerritoryCode.Name='ADMTerritoryCode';
        admTerritoryCode.Territory_Code__c='101485';
        insert admTerritoryCode;
        
                //* Added by Archana...code changes end
        
        Apex_Helper_Settings__c ah =new Apex_Helper_Settings__c(name='Exclude Oppy Revenue Phase',value__c='Dead,Lost,Dead - Closed,Lost - Closed',active__c=true);
        insert ah;        
         

        
        Opportunity_Record_Type_Groups__c a = new Opportunity_Record_Type_Groups__c();
        a.name= 'DND Opportunity';
        a.Active__c = true;
        a.RecordTypeID__c = '012c00000008oxY';
        insert a;
        RecordType rt8 = ClsTestHelp.createTestRecordType8();
        
       Profile p = [Select Id, Name From Profile 
                                    where Name = 'Production Support'
                                    or Name ='System Administrator' limit 1];
        Opportunity_Team_Default_Permission__c per = new Opportunity_Team_Default_Permission__c();
        per.Name = 'ProfileNotSendEmail';
        per.permission__c = 'Channel insight app;';
        insert per;
        
        List<User> uList = new List<User>();
        User u = ClsTestHelp.createTestUsers();
        u.Email = 'helloSand0728@testCompany1407281004.com';
        u.FirstName ='Test0728';
        u.LastName = 'User0728';
        u.Alias = 'dpse0728';
        u.CommunityNickname = 'TMD0711';
        u.ProfileId = p.Id;
        u.GIBU__c = 'Appliances';
        u.Username = 'helloSand0728@testCompany1407281004.com';
        uList.add(u);
        
        User u1 = ClsTestHelp.createTestUsers();
        u1.Email = 'helloSand0728@testCompany1407281004.com';
        u1.FirstName ='Test0728';
        u1.LastName = 'User0728';
        u1.Alias = 'dpse012';
        u1.CommunityNickname = 'TMD071';
        u1.ProfileId = p.Id;
        u1.GIBU__c = 'Appliances';
        u1.Te_Network_Id__c = 'TE111111';
        u1.Username = 'helloSand01111@testCompany1407281004.com';
        uList.add(u1);
        
        User u2 = ClsTestHelp.createTestUsers();
        u2.Email = 'helloSand0728@testCompany1407281004.com';
        u2.FirstName ='Test07281';
        u2.LastName = 'User07281';
        u2.Alias = 'dpse44';
        u2.CommunityNickname = 'TMD04';
        u2.ProfileId = p.Id;
        u2.GIBU__c = 'Appliances';
        u2.Te_Network_Id__c = 'TE222222';
        u2.Username = 'helloSand02222@testCompany1407281004.com';
        uList.add(u2);
        insert uList;
        
        RecordType rt2 = ClsTestHelp.createTestRecordType10();
        RecordType rt = ClsTestHelp.createTestRecordType14();
        
        Sales_Hierarchy__c sh = ClsTestHelp.createTestSalesHierarchy();
        sh.Level_2_Territory_Code__c = '103004';
        sh.Level_7_Default_Owner__c = u1.Id;
        sh.Level_7_Territory_Code__c = '123456';
        insert sh;
        
        List<Account> accList = new List<Account>();
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt.Id;
        acc.Type = 'Global Account';
        acc.Industry_Code_Description__c = 'Appliances';
        acc.LEVEL_1_INDUSTRY_CDE__c = '0283';
        acc.owner = u;
        acc.Account_Manager__c = u.Id;
        accList.add(acc); 
      
        insert accList;
       /*
        SharingUtils.CreateAccountTeamMember(acc1.Id,u.Id,'Test');
        Set<String> teNetworkIdSet = new Set<String>();
        teNetworkIdSet.add('TE111111');
        teNetworkIdSet.add('TE222222');
        
        Set<Id> accSet = new Set<Id>();
        accSet.add(acc1.Id);
        
      */
        
        Opportunity oppy = new Opportunity();
        oppy.StageName = 'New';
        oppy.AccountId = acc.Id;
        oppy.Account = acc;
        oppy.Name = 'SandKing';
        oppy.CloseDate = date.today();
        oppy.Manufacturing_Start_Date__c = date.today().addMonths(1);
        oppy.RecordTypeId = rt2.Id;            
        oppy.currency_confirm__c = true;
        oppy.Mass_prod_Status__c = true;
        oppy.owner = u; 
        insert oppy;
        
        
        
        SharingUtils.CreateOpportunityShare(oppy.Id,u.Id);
        
        
        Test.stopTest();
    }
        
       static testMethod void myUnitTest4 () {
    
            Test.startTest();
            
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        //* Added by Archana...code changes start
        List<Trigger_Configuration__c> lstTriggerConfig = new  List<Trigger_Configuration__c>();
       
        Trigger_Configuration__c tc = new Trigger_Configuration__c(); 
        tc.Name='Avoid Duplicate PLM Id';
        tc.isRun__c=true;
        lstTriggerConfig .add(tc);
               
        Trigger_Configuration__c tc2 = new Trigger_Configuration__c(); 
        tc2.Name='DND Lead Conversion Initialization';
        tc2.isRun__c=true;
        lstTriggerConfig .add(tc2);
        
        Trigger_Configuration__c tc3 = new Trigger_Configuration__c(); 
        tc3.Name='Identify Fiscal Year';
        tc3.isRun__c=true;
        lstTriggerConfig .add(tc3);
        
        Trigger_Configuration__c tc4 = new Trigger_Configuration__c(); 
        tc4.Name='Populate Opportunity Partner';
        tc4.isRun__c=true;
        lstTriggerConfig .add(tc4);
        
        Trigger_Configuration__c tc5 = new Trigger_Configuration__c(); 
        tc5.Name='updateAccountBusinessUnit';
        tc5.isRun__c=true;
        lstTriggerConfig .add(tc5);
        
        insert lstTriggerConfig ;
        
        ADMTerritoryCode__c admTerritoryCode= new ADMTerritoryCode__c();
        admTerritoryCode.Name='ADMTerritoryCode';
        admTerritoryCode.Territory_Code__c='101485';
        insert admTerritoryCode;
        
                //* Added by Archana...code changes end
        
        
         

        
        Opportunity_Record_Type_Groups__c a = new Opportunity_Record_Type_Groups__c();
        a.name= 'DND Opportunity';
        a.Active__c = true;
        a.RecordTypeID__c = '012c00000008oxY';
        insert a;
        RecordType rt8 = ClsTestHelp.createTestRecordType8();
        
       Profile p = [Select Id, Name From Profile 
                                    where Name = 'Production Support'
                                    or Name ='System Administrator' limit 1];
        Opportunity_Team_Default_Permission__c per = new Opportunity_Team_Default_Permission__c();
        per.Name = 'ProfileNotSendEmail';
        per.permission__c = 'Channel insight app;';
        insert per;
        
        List<User> uList = new List<User>();
        User u = ClsTestHelp.createTestUsers();
        u.Email = 'helloSand0728@testCompany1407281004.com';
        u.FirstName ='Test0728';
        u.LastName = 'User0728';
        u.Alias = 'dpse0728';
        u.CommunityNickname = 'TMD0711';
        u.ProfileId = p.Id;
        u.GIBU__c = 'Appliances';
        u.Username = 'helloSand0728@testCompany1407281004.com';
        uList.add(u);
        
        User u1 = ClsTestHelp.createTestUsers();
        u1.Email = 'helloSand0728@testCompany1407281004.com';
        u1.FirstName ='Test0728';
        u1.LastName = 'User0728';
        u1.Alias = 'dpse012';
        u1.CommunityNickname = 'TMD071';
        u1.ProfileId = p.Id;
        u1.GIBU__c = 'Appliances';
        u1.Te_Network_Id__c = 'TE111111';
        u1.Username = 'helloSand01111@testCompany1407281004.com';
        uList.add(u1);
        
        User u2 = ClsTestHelp.createTestUsers();
        u2.Email = 'helloSand0728@testCompany1407281004.com';
        u2.FirstName ='Test07281';
        u2.LastName = 'User07281';
        u2.Alias = 'dpse44';
        u2.CommunityNickname = 'TMD04';
        u2.ProfileId = p.Id;
        u2.GIBU__c = 'Appliances';
        u2.Te_Network_Id__c = 'TE222222';
        u2.Username = 'helloSand02222@testCompany1407281004.com';
        uList.add(u2);
        insert uList;
        
        RecordType rt2 = ClsTestHelp.createTestRecordType10();
        RecordType rt = ClsTestHelp.createTestRecordType14();
      /*  
        Sales_Hierarchy__c sh = ClsTestHelp.createTestSalesHierarchy();
        sh.Level_2_Territory_Code__c = '103004';
        sh.Level_7_Default_Owner__c = u1.Id;
        sh.Level_7_Territory_Code__c = '123456';
        insert sh;
        */
        List<Account> accList = new List<Account>();
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt.Id;
        acc.Type = 'Global Account';
        acc.Industry_Code_Description__c = 'Appliances';
        acc.LEVEL_1_INDUSTRY_CDE__c = '0283';
        acc.owner = u;
        acc.Account_Manager__c = u.Id;
        accList.add(acc); 
      
        insert accList;
       /*
        
        Opportunity oppy = new Opportunity();
        oppy.StageName = 'New';
        oppy.AccountId = acc.Id;
        oppy.Account = acc;
        oppy.Name = 'SandKing';
        oppy.CloseDate = date.today();
        oppy.Manufacturing_Start_Date__c = date.today().addMonths(1);
        oppy.RecordTypeId = rt2.Id;            
        oppy.currency_confirm__c = true;
        oppy.Mass_prod_Status__c = true;
        oppy.owner = u; 
        insert oppy;
        
        
        Opportunity_Partner__c oppPartner = new Opportunity_Partner__c();
        oppPartner.Opportunity__c = oppy.Id;
        oppPartner.Account__c = acc.Id;
        oppPartner.Allocation__c = 0;
        oppPartner.Partner_Role__c = 'Distributor';
        insert oppPartner;
        
       
        Opportunity_Partner__c oppPartner1 = new Opportunity_Partner__c();
        oppPartner1.Opportunity__c = oppy.Id;
        oppPartner1.Account__c = acc.Id;
        oppPartner1.Allocation__c = 0;
        oppPartner1.Partner_Role__c = 'Distributor';
        insert oppPartner1;
        */
        acc.Account_Manager__c = u2.Id;
        update acc;
        Map<Id,Id> newMap = new Map<Id,Id>();
        newMap .put(acc.Id,u1.id);
        Map<Id,Id> oldMap = new Map<Id,Id>();
        newMap .put(acc.Id,u.id);
        SharingUtils.updateOppyTeamWhenAccountAMChanged(newMap ,oldMap );
       // delete oppPartner1;
       
        
        
        Test.stopTest();
    }
        static testMethod void myUnitTest5 () {
    
            Test.startTest();
            
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        //* Added by Archana...code changes start
        List<Trigger_Configuration__c> lstTriggerConfig = new  List<Trigger_Configuration__c>();
       
        Trigger_Configuration__c tc = new Trigger_Configuration__c(); 
        tc.Name='Avoid Duplicate PLM Id';
        tc.isRun__c=true;
        lstTriggerConfig .add(tc);
               
        Trigger_Configuration__c tc2 = new Trigger_Configuration__c(); 
        tc2.Name='DND Lead Conversion Initialization';
        tc2.isRun__c=true;
        lstTriggerConfig .add(tc2);
        
        Trigger_Configuration__c tc3 = new Trigger_Configuration__c(); 
        tc3.Name='Identify Fiscal Year';
        tc3.isRun__c=true;
        lstTriggerConfig .add(tc3);
        
        Trigger_Configuration__c tc4 = new Trigger_Configuration__c(); 
        tc4.Name='Populate Opportunity Partner';
        tc4.isRun__c=true;
        lstTriggerConfig .add(tc4);
        
        Trigger_Configuration__c tc5 = new Trigger_Configuration__c(); 
        tc5.Name='updateAccountBusinessUnit';
        tc5.isRun__c=true;
        lstTriggerConfig .add(tc5);
        
        insert lstTriggerConfig ;
        
        ADMTerritoryCode__c admTerritoryCode= new ADMTerritoryCode__c();
        admTerritoryCode.Name='ADMTerritoryCode';
        admTerritoryCode.Territory_Code__c='101485';
        insert admTerritoryCode;
        
                //* Added by Archana...code changes end
        
        Apex_Helper_Settings__c ah =new Apex_Helper_Settings__c(name='Exclude Oppy Revenue Phase',value__c='Dead,Lost,Dead - Closed,Lost - Closed',active__c=true);
        insert ah;        
         

        
        Opportunity_Record_Type_Groups__c a = new Opportunity_Record_Type_Groups__c();
        a.name= 'DND Opportunity';
        a.Active__c = true;
        a.RecordTypeID__c = '012c00000008oxY';
        insert a;
        RecordType rt8 = ClsTestHelp.createTestRecordType8();
        
       Profile p = [Select Id, Name From Profile 
                                    where Name = 'Production Support'
                                    or Name ='System Administrator' limit 1];
        Opportunity_Team_Default_Permission__c per = new Opportunity_Team_Default_Permission__c();
        per.Name = 'ProfileNotSendEmail';
        per.permission__c = 'Channel insight app;';
        insert per;
        
        List<User> uList = new List<User>();
        User u = ClsTestHelp.createTestUsers();
        u.Email = 'helloSand0728@testCompany1407281004.com';
        u.FirstName ='Test0728';
        u.LastName = 'User0728';
        u.Alias = 'dpse0728';
        u.CommunityNickname = 'TMD0711';
        u.ProfileId = p.Id;
        u.GIBU__c = 'Appliances';
        u.Username = 'helloSand0728@testCompany1407281004.com';
        uList.add(u);
        
        User u1 = ClsTestHelp.createTestUsers();
        u1.Email = 'helloSand0728@testCompany1407281004.com';
        u1.FirstName ='Test0728';
        u1.LastName = 'User0728';
        u1.Alias = 'dpse012';
        u1.CommunityNickname = 'TMD071';
        u1.ProfileId = p.Id;
        u1.GIBU__c = 'Appliances';
        u1.Te_Network_Id__c = 'TE111111';
        u1.Username = 'helloSand01111@testCompany1407281004.com';
        uList.add(u1);
        
        User u2 = ClsTestHelp.createTestUsers();
        u2.Email = 'helloSand0728@testCompany1407281004.com';
        u2.FirstName ='Test07281';
        u2.LastName = 'User07281';
        u2.Alias = 'dpse44';
        u2.CommunityNickname = 'TMD04';
        u2.ProfileId = p.Id;
        u2.GIBU__c = 'Appliances';
        u2.Te_Network_Id__c = 'TE222222';
        u2.Username = 'helloSand02222@testCompany1407281004.com';
        uList.add(u2);
        insert uList;
        
        RecordType rt2 = ClsTestHelp.createTestRecordType10();
        RecordType rt = ClsTestHelp.createTestRecordType14();
      /*  
        Sales_Hierarchy__c sh = ClsTestHelp.createTestSalesHierarchy();
        sh.Level_2_Territory_Code__c = '103004';
        sh.Level_7_Default_Owner__c = u1.Id;
        sh.Level_7_Territory_Code__c = '123456';
        insert sh;
        */
        List<Account> accList = new List<Account>();
        Account acc = ClsTestHelp.createTestAccounts();
        acc.RecordTypeId = rt.Id;
        acc.Type = 'Global Account';
        acc.Industry_Code_Description__c = 'Appliances';
        acc.LEVEL_1_INDUSTRY_CDE__c = '0283';
        acc.owner = u;
        acc.Account_Manager__c = u.Id;
        accList.add(acc); 
      
        insert accList;
       
        
        Opportunity oppy = new Opportunity();
        oppy.StageName = 'New';
        oppy.AccountId = acc.Id;
        oppy.Account = acc;
        oppy.Name = 'SandKing';
        oppy.CloseDate = date.today();
        oppy.Manufacturing_Start_Date__c = date.today().addMonths(1);
        oppy.RecordTypeId = rt2.Id;            
        oppy.currency_confirm__c = true;
        oppy.Mass_prod_Status__c = true;
        oppy.owner = u; 
        insert oppy;
        
        
        Opportunity_Partner__c oppPartner = new Opportunity_Partner__c();
        oppPartner.Opportunity__c = oppy.Id;
        oppPartner.Account__c = acc.Id;
        oppPartner.Allocation__c = 0;
        oppPartner.Partner_Role__c = 'Distributor';
        insert oppPartner;
        
       
        Opportunity_Partner__c oppPartner1 = new Opportunity_Partner__c();
        oppPartner1.Opportunity__c = oppy.Id;
        oppPartner1.Account__c = acc.Id;
        oppPartner1.Allocation__c = 0;
        oppPartner1.Partner_Role__c = 'Distributor';
        insert oppPartner1;
        
       delete oppPartner1;
       
        
        
        Test.stopTest();
    }
        
 
 
}