objects/AIT_Clean_Up_Date_range__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for clean up activity  batch classes  to get the Interest tag object and Activity stage old records.</description>
    <fields>
        <fullName>Months_old__c</fullName>
        <description>This field is to hold the number of months,such that batch job fetch this many months old records and delete.</description>
        <inlineHelpText>Enter the number of months( how many months old records need be to delete).
Ex:If you want delete the 6 months old record ,then please need to enter  &quot;6&quot;</inlineHelpText>
        <label>Months old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AIT Clean Up Date range</label>
</CustomObject>

objects/Batch_Email_message_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email_ID__c</fullName>
        <label>Email ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Email message Users</label>
</CustomObject>

objects/Key_Activity_Staging__c.object
<CustomObject>
    <description>Activities in this object are typically created by Eloqua and represent activities that need to get to the activity repository and activity dashboard in an expedited manner and/or activities that require special processing or mapping that Eloqua can&apos;t provide in its standard activity object.

These activities are picked up many times per day by a BODS job that writes them to the HANA activity repository and master, thereby making them visible in the activity dashboard.

The intention is to delete these records after they are a month old (could change), as this is just a staging area to get them to HANA.</description>
    <label>Key Activity Staging</label>
    <nameField>
        <label>Key Activity Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Activity Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ActivityStagingMonthlyCleanupBatch.cls
/**
* 
* This batch class is used to automated monthly cleanup process to clear Key Activity Staging records.
* 
* @author      Nagaraju Gorli
* @created     2017-07-19                                                          
*     
*/
global class ActivityStagingMonthlyCleanupBatch implements Database.Batchable<sObject>,Database.Stateful{   
    global list<String> toAddresses;
    global String Query;
    global String EmailBody;
    global integer totalActivityStageRecordsDeleted= 0;
    global ActivityStagingMonthlyCleanupBatch(){
        
        //create the query here from custom settings to get toaddress.
        EmailBody=null;
        Batch_Email_message_Users__c batchStatus= Batch_Email_message_Users__c.getValues('AITCleanUpActivity');
        toAddresses = new list<string>();
        string emailids=batchStatus.Email_ID__c;
        if(batchStatus.Email_ID__c != null && batchStatus.Email_ID__c.contains(';'))
            toAddresses = batchStatus.Email_ID__c.split(';');
        else    
            toAddresses.add(emailids);
        
        //create the query here from custom settings to get the date range.
        AIT_Clean_Up_Date_range__c dateRange=AIT_Clean_Up_Date_range__c.getValues('ActivityStage');
        
        //building the query to get the key activity staging
        query='SELECT Id ,CreatedDate  FROM Key_Activity_Staging__c WHERE '; 
        query +='CreatedDate<LAST_N_MONTHS:'+integer.valueOf(dateRange.Months_old__c);
        
        system.debug('==>'+dateRange.Months_old__c);
        if(Test.isRunningTest())
            query += ' limit 1';
        
    }
    global Database.QueryLocator start(Database.BatchableContext BC){  
        return Database.getQueryLocator(query);
        
    }
    // Execute Method Logic
    global void execute(  Database.BatchableContext BC,List<Key_Activity_Staging__c>scope){ 
        try {
            integer recordsdeleted = scope.size();           
            delete (scope);
            totalActivityStageRecordsDeleted += recordsdeleted;
            Database.emptyRecycleBin(scope);
            
        } catch(Exception e) {
            EmailBody = e.getMessage() +' at '+e.getStackTraceString();
            EmailSender('Something Went Wrong With Activity stage Deletion Batch..!!', toAddresses, EmailBody);
        }
    }  

    global void finish(Database.BatchableContext BC){
        //Send an email to the User after your batch completes 
        
        AsyncApexJob ajob= [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems 
                            FROM AsyncApexJob WHERE Id = :BC.getJobId()];  
        system.debug('===total==='+totalActivityStageRecordsDeleted);
        String EmailBody = '<html><body>';
        EmailBody+= 'Hi,<br/><br/>';
        EmailBody+='The batch apex job processed ' + ajob.TotalJobItems +' batches with '+ ajob.NumberOfErrors + ' failures.Total ' + totalActivityStageRecordsDeleted + ' record(s) are deleted.<br/><br/> ';
        EmailBody+='Thanks,<br/>';
        EmailBody+='TE Salesforce Team';
        EmailBody += '</p></body></html>';
        
        EmailSender('Activity stage old records deleted successfully ..!!!', toAddresses, EmailBody); 
    }
    
    global void EmailSender(string subject, list<string> toAddresses, string body ){ 

        List<User> EmailUsers = [SELECT Id FROM User WHERE email IN :toAddresses];
        List<Id> EmailUserIds = new List<Id>(new Map<Id, User>(EmailUsers).keySet());
    
        if(!EmailUsers.isEmpty()){
        	 for (Id emailuserid: EmailUserIds){
      				Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();         
            		email.setTargetObjectId(emailuserid);
			        email.saveAsActivity = false;
			        email.setSubject(subject);
			        email.setHtmlBody(body);
			        if(!Test.isRunningTest())
			            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});    			                    		
        	 }
        }
        else
        {
      			Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();         
             	email.setTargetObjectId(Userinfo.getuserId());
             	email.saveAsActivity = false;
			    email.setSubject(subject);
			    email.setHtmlBody(body);
			    if(!Test.isRunningTest())
			    	Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});               
        }

    }
}