objects/ANZ_Clause__c.object
<CustomObject>
    <fields>
        <fullName>ANZ_Clause_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ANZ Clause Master</label>
        <referenceTo>ANZ_Clause_Master__c</referenceTo>
        <relationshipName>ANZ_Clause</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Clause Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>ANZ_Clause1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportynity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tender</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>ANZ Contract</fullName>
                </value>
                <value>
                    <fullName>IR Special Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ANZ Clause</label>
    <nameField>
        <label>ANZ Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ANZ Clause</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ANZ_Clause_Master__c.object
<CustomObject>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Clause Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportynity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tender</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>ANZ Contract</fullName>
                </value>
                <value>
                    <fullName>IR Special Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ANZ Clause Master</label>
    <nameField>
        <label>ANZ Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ANZ Clause Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityResetClauses_Test.cls
/*------------------------------------------------------------
Author:        Yiming Shen <yiming.shen@capgemini.com>
Description:   A test class for OpportunityResetClauses.cls.
Inputs:        
Test Class:    
History
2017-11-30 Yiming Shen <yiming.shen@capgemini.com> Created
------------------------------------------------------------*/
@isTest
private class OpportunityResetClauses_Test {
	@testSetup static void createConfig(){
    	ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getTrigger_Configuration();
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ClsTestCustomSettingHelper.getOpportunity_Team_Default_Permission();
        ClsTestCustomSettingHelper.getQuoteValiditySetting();
        ClsTestCustomSettingHelper.getQuoteExpirationSetting();
        ClsTestHelp.createTestOrgWideSettings1();
        ClsTestCustomSettingHelper.getADMTerritoryCode();
        ClsTestHelp.createTestOPTG4(); 
    }
    
    static testMethod void myUnitTest() {
        Opportunity oppy = ClsTestHelp.createTestOpportunity();
        oppy.Name = 'testOppy2';
        oppy.RecordTypeId = ClsTestHelp.createTestRecordType32().Id;
        oppy.Quote_Type__c = 'Standard';
        insert oppy;
        
        ANZ_Clause_Master__c anzClsMaster = ClsTestHelp.createTestANZClauseMaster();
        anzClsMaster.Name = 'testMaster';
        anzClsMaster.Opportynity_Type__c = 'Quote';
        insert anzClsMaster;
        
        ANZ_Clause__c anzCls = ClsTestHelp.createTestANZClause();
        anzCls.Opportunity__c = oppy.Id;
        anzCls.Name = anzClsMaster.Name;
   		anzCls.ANZ_Clause_Master__c = anzClsMaster.Id;
   		anzCls.Insurance__c = anzClsMaster.Insurance__c;
   		anzCls.Opportynity_Type__c = anzClsMaster.Opportynity_Type__c;
   		anzCls.Sequence_No__c = anzClsMaster.Sequence_No__c;
        insert anzCls;
        
        Test.startTest();
        OpportunityResetClauses.resetClauses(oppy.Id,oppy.Quote_Type__c);
        Test.stopTest();
        List<ANZ_Clause__c> list_ANZClauses = [SELECT Id FROM ANZ_Clause__c WHERE Opportunity__c =: oppy.Id];
        System.assert(list_ANZClauses.size() > 0);
    }
}