objects/Apex_Helper_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for e.g. record type ids, profile ids, ... That no hardcodings in apex codes are needed.</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>This field contains Ids, developer names, ...</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Helper Settings</label>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ViewNDROpportunityPartController.cls
/**********************************************************************************************************************************************
*******
Name: ViewNDROpportunityPartController  
Copyright © 2013 TE Connectivity | Salesforce Instance : C2S Org
===============================================================================================================================================

Purpose: This controller checks the Opportunity Part is of type NDR OpportunityPart or not.If Yes then it will
         show the NDR Opportunity Part detail page else it will redirect to 'ExtOpportunityPartEntry' page
===============================================================================================================================================
REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                           
-----------------------------------------------------------------------------------------------------------------------------------------------
VERSION   AUTHOR              DATE          DETAIL                           
-----------------------------------------------------------------------------------------------------------------------------------------------
 1.0   Abhijeet Manepstil   05/16/2013    Controller                       
***********************************************************************************************************************************************
*****/

public class ViewNDROpportunityPartController {
/*------------------ D1 Variable Declaration ---------------------------*/
    public String vOpptyId{get;set;}
    public Opportunity_Part__c vOpptyPart{get;set;}
    public Apex_Helper_Settings__c vNDROppRT;
    public boolean vNDROppPart{get;set;}
    
    public ViewNDROpportunityPartController(ApexPages.StandardController controller) {
        vOpptyId = controller.getId(); 
        vOpptyPart = [select recordtypeid,Opportunity__c from Opportunity_Part__c where id =: vOpptyId ];  
         vNDROppRT  = Apex_Helper_Settings__c.getInstance('NDR Opportunity Parts');
    }
/*------------------- Redirect() method -------------------------------*/    
    public PageReference Redirect() {
        if((vOpptyPart.recordtypeid == vNDROppRT.Value__c  ) && (vOpptyPart.recordtypeid != null )){
            vNDROppPart = true;
            return null;

        }
        else{
            PageReference pgrf = new PageReference('/apex/ExtOpportunityPartEntry?Id='+vOpptyId);
            return pgrf;
        }
    }// End of Redirect() method
}// End of class
/*--------------------------------------------------------------------------*/