objects/Apex_Helper_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for e.g. record type ids, profile ids, ... That no hardcodings in apex codes are needed.</description>
    <label>Apex Helper Settings</label>
</CustomObject>

objects/Consumer_Device_Opportunity_Record_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Consumer Device Opportunity Record Types</description>
    <label>Consumer Device Opportunity Record Types</label>
</CustomObject>

objects/CSD_Sales_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Forecast__c</fullName>
        <label>Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_10_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -10 month.</description>
        <label>Previous -10 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_10_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -10 month</description>
        <label>Previous -10 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_11_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -11 month.</description>
        <label>Previous  -11 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_11_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -11 month</description>
        <label>Previous -11 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_1_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -1 month.</description>
        <label>Previous  -1 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_1_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -1 month</description>
        <label>Previous -1 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_2_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -2 month.</description>
        <label>Previous -2 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_2_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -2 month</description>
        <label>Previous -2 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_3_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -3 month.</description>
        <label>Previous -3 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_3_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -3 month</description>
        <label>Previous -3 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_4_Month_Forecast__c</fullName>
        <label>Previous -4 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_4_Month_Quantity__c</fullName>
        <description>Used to snapshot the forecast from previous -4 month.</description>
        <label>Previous -4 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_5_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -5 month.</description>
        <label>Previous -5 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_5_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -5 month</description>
        <label>Previous -5 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_6_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -6 month.</description>
        <label>Previous -6 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_6_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -6 month</description>
        <label>Previous -6 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_7_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -7 month.</description>
        <label>Previous -7 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_7_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -7 month</description>
        <label>Previous -7 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_8_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -8 month.</description>
        <label>Previous -8 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_8_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -8 month</description>
        <label>Previous -8 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_9_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous -9 month.</description>
        <label>Previous -9 Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_9_Month_Quantity__c</fullName>
        <description>Used to snapshot the quantity from previous -9 month</description>
        <label>Previous -9 Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Month_Forecast__c</fullName>
        <description>Used to snapshot the forecast from previous month.</description>
        <label>Previous Month Forecast</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_Month_Quantity__c</fullName>
        <label>Previous Month Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSD Sales Forecasts</relationshipLabel>
        <relationshipName>Sold_To_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CSD Sales Forecast</label>
    <nameField>
        <label>CSD Sales Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSD Sales Forecasts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Forecast__c.object
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <displayFormat>FCN-{000}</displayFormat>
        <label>Forecast Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSD_ClsBatch_calcForecastSnapshot_Test.cls
/**
*  This test class is for CSD_ClsBatch_calcForecastSnapshot.
*
@author Bin Yuan
@created 2014-12-09
@version 1.0
@since 30.0
*
@changelog
* 2014-12-09 Bin Yuan <bin.yuan@itbconsult.com>
* - Created
* - Test coverage 100%
*/
@isTest
private class CSD_ClsBatch_calcForecastSnapshot_Test {
    static testMethod void testMost() {
    	
    	Apex_Helper_Settings__c name1 = ClsTestHelp.createTestName1();
        Apex_Helper_Settings__c name2 = ClsTestHelp.createTestName2();
        Apex_Helper_Settings__c name3 = ClsTestHelp.createTestName3();
        Apex_Helper_Settings__c name4 = ClsTestHelp.createTestName4();
        Apex_Helper_Settings__c name5 = ClsTestHelp.createTestName5();
        Apex_Helper_Settings__c name6 = ClsTestHelp.createTestName6();
        Apex_Helper_Settings__c name7 = ClsTestHelp.createTestName7(); 
        Apex_Helper_Settings__c name8 = ClsTestHelp.createTestName8();
        Apex_Helper_Settings__c name9 = ClsTestHelp.createTestName9();
        
    	RecordType rt = ClsTestHelp.createTestRecordType8();
    	
    	Consumer_Device_Opportunity_Record_Types__c cdort1 = ClsTestHelp.createTestCSD1();
    	Consumer_Device_Opportunity_Record_Types__c cdort2 = ClsTestHelp.createTestCSD2();
    	Consumer_Device_Opportunity_Record_Types__c cdort3 = ClsTestHelp.createTestCSD3();
    	Consumer_Device_Opportunity_Record_Types__c cdort4 = ClsTestHelp.createTestCSD4();
    	Consumer_Device_Opportunity_Record_Types__c cdort5 = ClsTestHelp.createTestCSD5();
    	Consumer_Device_Opportunity_Record_Types__c cdort6 = ClsTestHelp.createTestCSD6();
    	Consumer_Device_Opportunity_Record_Types__c cdort7 = ClsTestHelp.createTestCSD7();
    	
    	
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.SALES_TERRITORY_CDE__c = 'A003153';
    	acc.Individually_Planned__c = true;
    	acc.Account_Manager__c = UserInfo.getUserId();
    	acc.CurrencyIsoCode = 'AED';
    	insert acc;
    	
    	Date currentFiscalDate = CSD_ClsUtils.getCurrentFiscalDate();
    	currentFiscalDate = currentFiscalDate.addDays(3);
    	CSD_Sales_Forecast__c csdFC1 = new CSD_Sales_Forecast__c();
    	csdFC1.Sold_To__c = acc.Id;
    	csdFC1.Fiscal_Year__c = String.valueOf(currentFiscalDate.year());
    	csdFC1.Fiscal_Month__c = String.valueOf(currentFiscalDate.month());
    	csdFC1.Forecast__c = 10;
    	csdFC1.Previous_Month_Forecast__c = 10;
    	csdFC1.Previous_1_Month_Forecast__c = 10;
    	csdFC1.Previous_2_Month_Forecast__c = 10;
    	csdFC1.Previous_3_Month_Forecast__c = 10;
    	csdFC1.Previous_4_Month_Forecast__c = 10;
    	csdFC1.Previous_5_Month_Forecast__c = 10;
    	csdFC1.Previous_6_Month_Forecast__c = 10;
    	csdFC1.Previous_7_Month_Forecast__c = 10;
    	csdFC1.Previous_8_Month_Forecast__c = 10;
    	csdFC1.Previous_9_Month_Forecast__c = 10;
    	csdFC1.Previous_10_Month_Forecast__c = 10;
    	csdFC1.Previous_11_Month_Forecast__c = 10;
    	csdFC1.Quantity__c = 10;
    	csdFC1.Previous_Month_Quantity__c = 10;
    	csdFC1.Previous_1_Month_Quantity__c = 10;
    	csdFC1.Previous_2_Month_Quantity__c = 10;
    	csdFC1.Previous_3_Month_Quantity__c = 10;
    	csdFC1.Previous_4_Month_Quantity__c = 10;
    	csdFC1.Previous_5_Month_Quantity__c = 10;
    	csdFC1.Previous_6_Month_Quantity__c = 10;
    	csdFC1.Previous_7_Month_Quantity__c = 10;
    	csdFC1.Previous_8_Month_Quantity__c = 10;
    	csdFC1.Previous_9_Month_Quantity__c = 10;
    	csdFC1.Previous_10_Month_Quantity__c = 10;
    	csdFC1.Previous_11_Month_Quantity__c = 10;
    	insert csdFC1;
    	Test.startTest();
    	list<CSD_Sales_Forecast__c> scrope = new list<CSD_Sales_Forecast__c>();
    	scrope.add(csdFC1);
    	
    	CSD_ClsBatch_calcForecastSnapshot cls = new CSD_ClsBatch_calcForecastSnapshot();
    	//ID batchprocessid = Database.executeBatch(cls);
        Database.BatchableContext bc;
		cls.start(bc);
        cls.execute(bc, scrope);
        cls.isFail = false;
        cls.finish(bc); 
    	Test.stopTest();
    }
    static testMethod void testFailureCase() {
    	
    	Apex_Helper_Settings__c name1 = ClsTestHelp.createTestName1();
        Apex_Helper_Settings__c name2 = ClsTestHelp.createTestName2();
        Apex_Helper_Settings__c name3 = ClsTestHelp.createTestName3();
        Apex_Helper_Settings__c name4 = ClsTestHelp.createTestName4();
        Apex_Helper_Settings__c name5 = ClsTestHelp.createTestName5();
        Apex_Helper_Settings__c name6 = ClsTestHelp.createTestName6();
        Apex_Helper_Settings__c name7 = ClsTestHelp.createTestName7(); 
        Apex_Helper_Settings__c name8 = ClsTestHelp.createTestName8();
        Apex_Helper_Settings__c name9 = ClsTestHelp.createTestName9();
        
    	RecordType rt = ClsTestHelp.createTestRecordType8();
    	
    	Consumer_Device_Opportunity_Record_Types__c cdort1 = ClsTestHelp.createTestCSD1();
    	Consumer_Device_Opportunity_Record_Types__c cdort2 = ClsTestHelp.createTestCSD2();
    	Consumer_Device_Opportunity_Record_Types__c cdort3 = ClsTestHelp.createTestCSD3();
    	Consumer_Device_Opportunity_Record_Types__c cdort4 = ClsTestHelp.createTestCSD4();
    	Consumer_Device_Opportunity_Record_Types__c cdort5 = ClsTestHelp.createTestCSD5();
    	Consumer_Device_Opportunity_Record_Types__c cdort6 = ClsTestHelp.createTestCSD6();
    	Consumer_Device_Opportunity_Record_Types__c cdort7 = ClsTestHelp.createTestCSD7();
    	
    	
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.SALES_TERRITORY_CDE__c = 'A003153';
    	acc.Individually_Planned__c = true;
    	acc.Account_Manager__c = UserInfo.getUserId();
    	acc.CurrencyIsoCode = 'AED';
    	insert acc;
    	
    	Date currentFiscalDate = CSD_ClsUtils.getCurrentFiscalDate();
    	currentFiscalDate = currentFiscalDate.addDays(3);
    	CSD_Sales_Forecast__c csdFC1 = new CSD_Sales_Forecast__c();
    	csdFC1.Sold_To__c = acc.Id;
    	csdFC1.Fiscal_Year__c = String.valueOf(currentFiscalDate.year());
    	csdFC1.Fiscal_Month__c = String.valueOf(currentFiscalDate.month());
    	csdFC1.Forecast__c = 10;
    	csdFC1.Previous_Month_Forecast__c = 10;
    	csdFC1.Previous_1_Month_Forecast__c = 10;
    	csdFC1.Previous_2_Month_Forecast__c = 10;
    	csdFC1.Previous_3_Month_Forecast__c = 10;
    	csdFC1.Previous_4_Month_Forecast__c = 10;
    	csdFC1.Previous_5_Month_Forecast__c = 10;
    	csdFC1.Previous_6_Month_Forecast__c = 10;
    	csdFC1.Previous_7_Month_Forecast__c = 10;
    	csdFC1.Previous_8_Month_Forecast__c = 10;
    	csdFC1.Previous_9_Month_Forecast__c = 10;
    	csdFC1.Previous_10_Month_Forecast__c = 10;
    	csdFC1.Previous_11_Month_Forecast__c = 10;
    	csdFC1.Quantity__c = 10;
    	csdFC1.Previous_Month_Quantity__c = 10;
    	csdFC1.Previous_1_Month_Quantity__c = 10;
    	csdFC1.Previous_2_Month_Quantity__c = 10;
    	csdFC1.Previous_3_Month_Quantity__c = 10;
    	csdFC1.Previous_4_Month_Quantity__c = 10;
    	csdFC1.Previous_5_Month_Quantity__c = 10;
    	csdFC1.Previous_6_Month_Quantity__c = 10;
    	csdFC1.Previous_7_Month_Quantity__c = 10;
    	csdFC1.Previous_8_Month_Quantity__c = 10;
    	csdFC1.Previous_9_Month_Quantity__c = 10;
    	csdFC1.Previous_10_Month_Quantity__c = 10;
    	csdFC1.Previous_11_Month_Quantity__c = 10;
    	insert csdFC1;
    	Test.startTest();
    	list<CSD_Sales_Forecast__c> scrope = new list<CSD_Sales_Forecast__c>();
    	scrope.add(csdFC1);
    	
    	CSD_ClsBatch_calcForecastSnapshot cls = new CSD_ClsBatch_calcForecastSnapshot();
    	//ID batchprocessid = Database.executeBatch(cls);
        Database.BatchableContext bc;
		cls.start(bc);
        cls.execute(bc, scrope);
        cls.isFail = true;
        cls.finish(bc); 
    	Test.stopTest();
    }
}