objects/Apex_Helper_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for e.g. record type ids, profile ids, ... That no hardcodings in apex codes are needed.</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>This field contains Ids, developer names, ...</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Helper Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>APAC_Office__c</fullName>
        <label>APAC Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Kawasaki</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>malaysia</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Taiwan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GIBU__c</fullName>
        <description>Used to help with tallying license counts and things like that.</description>
        <inlineHelpText>Select the GIBU/BU this user is from.</inlineHelpText>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>GATD</fullName>
                </value>
                <value>
                    <fullName>ICT (Ind Comm Transport)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIC</fullName>
                </value>
                <value>
                    <fullName>Sensors</fullName>
                </value>
                <value>
                    <fullName>TEIS</fullName>
                </value>
                <value>
                    <fullName>TEIS Engineering Portfolio Mgmt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#0B6FCE</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>India</fullName>
                    <color>#E27001</color>
                    <label>India</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <color>#419249</color>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>China</fullName>
                    <color>#00CCCC</color>
                    <label>China</label>
                </value>
                <value>
                    <fullName>Japan</fullName>
                    <color>#CC0000</color>
                    <label>Japan</label>
                </value>
                <value>
                    <fullName>Asia Pacific</fullName>
                    <color>#641CCF</color>
                    <label>Asia Pacific</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <color>#AFCADF</color>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/changeInOwnerfromCaseQueuetoUser_Test.cls
/**************************************************************************************************************************************************
Name: changeInOwnerfromCaseQueuetoUser_Test
Copyright © 2011 TE Connectivity
===================================================================================================================================================
Purpose: This class contain Test Methods to cover UpdateCaseRecord,customerSurvey class and keepescalationastrue trigger on case
---------------------------------------------------------------------------------------------------------------------------------------------------       
                                                          
                                                     
---------------------------------------------------------------------------------------------------------------------------------------------------
Version Developer          Date       Detail                                  Mercury Request #
---------------------------------------------------------------------------------------------------------------------------------------------------
  1.0 Narasimha Narra    03/12/2013    Initial Development                      1453487                                   
**************************************************************************************************************************************************/
@isTest(seeAllData=true)
public class changeInOwnerfromCaseQueuetoUser_Test
{
    static testmethod void chkUpdateCaseRecord()
    {
        test.startTest();
        Apex_Helper_Settings__c QueueType = Apex_Helper_Settings__c.getInstance('APAC Channel Team');
        Apex_Helper_Settings__c vCaseRT_CCP = Apex_Helper_Settings__c.getInstance('Customer Care Cloud');
        Profile p1 = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User usr = new User(Alias = 'stand', Email='ram1@testorg.com', EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p1.Id, TimeZoneSidKey='America/Los_Angeles', UserName='std456@testorg.com', Region__c ='Asia Pacific', GIBU__c = 'Appliances', APAC_Office__c ='Singapore');
        insert usr;
        //insert account
        Account acc =  ClsTestHelp.createTestAccounts();
        insert acc;
        Contact con;
        con = ClsTestHelp.createTestContacts();
        con.email='test@org.com';
        insert con;
        //insert Case
        Case Cs = new Case();
        cs.OwnerId=QueueType.value__c;
        Cs.Origin = 'Email-cip1';
        Cs.Inquiry_Type__c = 'Cancellation';
        Cs.Status= 'In Progress';
        Cs.Description = 'Test Description';
        Cs.AccountId = acc.id;
        cs.contactId=con.Id;
        insert cs;
        CaseUtil_CCP.KeepEscationtrueboolean = false;
        cs.OwnerId=userInfo.getUserId();
        Cs.Status= 'Closed';
        update cs;
        CaseUtil_CCP.KeepEscationBeforeInsert =false;

        Case Cs1 = new Case();
        Cs1.OwnerId=usr.id;
        Cs1.Origin = 'Email-cip1';
        Cs1.Inquiry_Type__c = 'Cancellation';
        Cs1.Status= 'In Progress';        
        Cs1.Description = 'Test Description';
        Cs1.AccountId = acc.id;
        Cs1.contactId=con.Id;
        Cs1.RecordTypeId = vCaseRT_CCP.value__c;
        insert Cs1;
        test.stopTest();
    }
    
    static testmethod void chkUpdateforPIC()
    {
        test.startTest();
        Apex_Helper_Settings__c vCaseRT_PIC = Apex_Helper_Settings__c.getInstance('PIC Service Cloud');
        Profile p1 = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User usr = new User(Alias = 'stand', Email='ram1@testorg.com', EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p1.Id, TimeZoneSidKey='America/Los_Angeles', UserName='std456@testorg.com', Region__c ='Asia Pacific', GIBU__c = 'Appliances', APAC_Office__c ='Singapore');
        insert usr;
        //insert account
        Account acc =  ClsTestHelp.createTestAccounts();
        insert acc;
        Contact con;
        con = ClsTestHelp.createTestContacts();
        con.email='test@org.com';
        insert con;
        
        //insert Case
        
        Case Cs1 = new Case();
        Cs1.OwnerId=usr.id;
        Cs1.Origin = 'Email-cip1';
        Cs1.Inquiry_Type__c = 'Cancellation';
        Cs1.Status= 'In Progress';
        
        Cs1.Description = 'Test Description';
        Cs1.AccountId = acc.id;
        Cs1.contactId=con.Id;
        //Cs1.RecordTypeId = vCaseRT_CCP.value__c; Commented for Case# 00901186 by Subramanian
        Cs1.RecordTypeId = vCaseRT_PIC.value__c;
        insert Cs1;
        
        Cs1.Status= 'Closed';
        update Cs1;
        test.stopTest();
    }
}