objects/APL_Sales_Forecast__c.object
<CustomObject>
    <description>Sales forecast for appliances</description>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Part</description>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>APL Sales Forecasts</relationshipLabel>
        <relationshipName>Part</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Only for type “Relay”</description>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>APL Sales Forecast</label>
    <nameField>
        <displayFormat>ASF-{000000}</displayFormat>
        <label>APL Sales Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APL Sales Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSD_CFT_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Region__c</fullName>
        <label>Billing Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OEM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OEM</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSD CFT Forecasts (OEM)</relationshipLabel>
        <relationshipName>CSD_CFT_Forecasts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>CSD CFT Forecasts</relationshipLabel>
        <relationshipName>CSD_CFT_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold_To_Name__c</fullName>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Number__c</fullName>
        <label>Sold To Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSD CFT Forecast</label>
    <nameField>
        <label>CSD CFT Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSD CFT Forecasts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CtrlCSDImportCFTForecast_Test.cls
/**
*   This test class is for CtrlCSDExportCSVFile.
*
@author Minghao Li
@created 2014-09-24
@version 1.0
@since 30.0
*
@changelog
* 2014-09-24 Minghao Li <minghao.li@itbconsult.com>
* - Created
* - Test coverage 76%
* - 02/09/2016 Rajendra <Shahane rajendra.shahane@zensar.com>
* - Modified
* - Class covered : CtrlCSDImportCFTForecast
* - Coverage 88%
*/
@isTest
private class CtrlCSDImportCFTForecast_Test {

    static testMethod void myUnitTest() {
        CtrlCSDImportCFTForecast c = new CtrlCSDImportCFTForecast();
        c.deleteObject();
    }
    
    static testMethod void remoteActionTest() {

        CtrlCSDImportCFTForecast.CustomCFTForecast fc = new CtrlCSDImportCFTForecast.CustomCFTForecast();
        fc.soldToName = '';
        fc.oemName = '';
        fc.partName = '';
        fc.fYear = '2014';
        fc.fMonth = '6';
        fc.qty = 205555;
        fc.list_qty = new list<CtrlCSDImportCFTForecast.CustomCFTForecast>();
        list<CtrlCSDImportCFTForecast.CustomCFTForecast> list_fc = new list<CtrlCSDImportCFTForecast.CustomCFTForecast>();
        list_fc.add(fc);
        insert new CSD_CFT_Forecast__c();
        String q = 'select Id,Sold_To_Number__c,Billing_Region__c,Sold_To_Name__c,Fiscal_Month__c,Fiscal_Year__c,OEM__r.Name,OEM__c,Part__c,Part__r.Name,Quantity__c,LastModifiedDate from CSD_CFT_Forecast__c';
        CtrlCSDImportCFTForecast.runReportData(q);
        CtrlCSDImportCFTForecast.runFilterReportData(q);
        CtrlCSDImportCFTForecast.runAllReportData(q);
        
        CtrlCSDImportCFTForecast.upsertListCFTForecast( Json.serialize(list_fc) );
        
        CtrlCSDImportCFTForecast.CustomCFTFilter oCustomCFTFilter = new CtrlCSDImportCFTForecast.CustomCFTFilter('', '', '');
        fc.accName = '';
        fc.LastModifiedDate = system.today();
        fc.externalKey = '';
        fc.billingRegion = '';
        
        CtrlCSDImportCFTForecast.CustomReport oCustomReport = new CtrlCSDImportCFTForecast.CustomReport('', new list<CtrlCSDImportCFTForecast.CustomCFTForecast>());
        
    }
}