objects/APL_Sales_Forecast__c.object
<CustomObject>
    <description>Sales forecast for appliances</description>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Part</description>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>APL Sales Forecasts</relationshipLabel>
        <relationshipName>Part</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Only for type “Relay”</description>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>APL Sales Forecast</label>
    <nameField>
        <displayFormat>ASF-{000000}</displayFormat>
        <label>APL Sales Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APL Sales Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Forecast__c.object
<CustomObject>
    <description>This object contains the project forecast numbers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>Opportunity__r.X18_Digit_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Forecast</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Forecasts</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Part</fullName>
        <active>true</active>
        <label>Part</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Forecast_Staging__c.object
<CustomObject>
    <description>To Delete duplicate forecast records</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Created by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Forecast_Stagings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Modified_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Forecast_Stagings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marked_As_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marked for Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Forecast_Id__c</fullName>
        <label>Opportunity Forecast Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Forecast_Name__c</fullName>
        <label>Opportunity Forecast Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <label>Opportunity Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Forecast_Stagings2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Part_Id__c</fullName>
        <label>Opportunity Part Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Part_Name__c</fullName>
        <label>Opportunity Part Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Region__c</fullName>
        <label>Opportunity Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Forecast Staging</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Opportunity Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Forecast Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_owner__c</fullName>
        <formula>Opportunity__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClsBatch_FindDuplicateForecast.cls
/** 
*    Batch class to Find Duplicate Forecast record and storing into Staging Object
*
*    Description: Batch to fetch all duplicate Forecast record at Opportunity and Part level and checking which one holding
*                 oldest modified date. Oldest modified date record will be marked as delete and storing into a staging Object.
*
*    @author Subramanian Jayaram
*    @created 2015-03-16 
*    @version 1.0
**/

global class ClsBatch_FindDuplicateForecast implements Database.Batchable<sObject>, Database.stateful, Database.AllowsCallouts{
  
   // global Map<Id, Opportunity_Forecast_Staging__c> insertOppForecastStaging = NULL;
    
    global opportunity_forecast__c previousOppForecast = NULL;
    
    global Boolean isDuplicate = FALSE;
    
    global Database.QueryLocator start(Database.BatchableContext BC){ 
        
        //Query to get all Forecast Record
        String query = 'Select id, Name, opportunity__c, opportunity__r.Opportunity_Number__c, opportunity__r.Amount, opportunity__r.Ownerid, opportunity__r.Region_Design__c, part__c, Part__r.Name, recordtypeid, date__c, Quantity__c, Amount__c,';
         
        query += ' Createddate, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Id from opportunity_forecast__c'; 
        
        query += ' Where Date__c != NULL';
        
        query += ' order by opportunity__c, part__c, recordtypeid, date__c, lastmodifieddate';
        
        if(Test.isrunningtest()){
            query += ' LIMIT 2000';
        }
        
        system.debug(' query ::: ' + query);
        
        return Database.getQueryLocator(query);         
    }
    
    global void execute(Database.BatchableContext BC, list<Opportunity_Forecast__c> OppForecast){           
        
        Map<Id, Opportunity_Forecast_Staging__c> insertOppForecastStaging = new Map<Id, Opportunity_Forecast_Staging__c>();
        
        // Looping Forecast record
        for( Opportunity_Forecast__c OppF : OppForecast )  
        {    
            system.debug('OppForecast =>' + OppForecast);
             // Checking previous Forecast record not empty
             if( previousOppForecast != NULL )
             {
                 // Checking Previous and current Forecast Record are under same Opportunity and Opportunity Part
                if( previousOppForecast.Opportunity__c == OppF.Opportunity__c && previousOppForecast.Part__c == OppF.Part__c && previousOppForecast.Date__c == OppF.Date__c)
                {
                    // Adding Forecast Record containing oldest modified date to a list to insert into Staging Object and mark as to delete 
                    if(previousOppForecast.lastmodifieddate <= OppF.lastmodifieddate)
                    {                    
                        insertOppForecastStaging.put( previousOppForecast.Id, FieldMapping( previousOppForecast, TRUE ) );
                        previousOppForecast = OppF;
                    }else{
                        insertOppForecastStaging.put( OppF.Id, FieldMapping( OppF, TRUE ) );
                    }
                    
                    // Flag to indicate duplicate record for this Oportunit, Part & Date combination 
                    isDuplicate = TRUE;
                }else{
                    
                    // If the duplicate record found for particular Opportunity Part, then latest modified duplicate record need not mark as delete
                    if( isDuplicate )
                    {
                        insertOppForecastStaging.put( previousOppForecast.Id, FieldMapping( previousOppForecast, FALSE ) );
                    }
                    
                    // Storing current record in a variable, to compare for next loop
                    previousOppForecast = OppF;                    
                    isDuplicate = FALSE;
                }
            }else{
                // Storing current record in a variable, to compare for next loop
                previousOppForecast = OppF;
            }
        }
        
        // Inserting Opportunity Forecast record into Staging Object
        insert insertOppForecastStaging.Values();
        
    }      
    
    // Mapping Forecast fields with Staging fields
    global Opportunity_Forecast_Staging__c FieldMapping(opportunity_forecast__c OppForcast, Boolean isDeleted){
        
        Opportunity_Forecast_Staging__c staging  =     new Opportunity_Forecast_Staging__c();
        
        staging.Opportunity_Id__c                =     OppForcast.Opportunity__c;
        staging.Opportunity_Number__c            =     OppForcast.Opportunity__r.Opportunity_Number__c;
        staging.Opportunity_Owner__c             =     OppForcast.opportunity__r.Ownerid;
        staging.Opportunity_Region__c            =     OppForcast.opportunity__r.Region_Design__c;
        staging.Opportunity_Amount__c            =     OppForcast.opportunity__r.Amount;
        staging.Opportunity_Part_Id__c           =     OppForcast.Part__c;
        staging.Opportunity_Part_Name__c         =     OppForcast.Part__r.Name;
        staging.Opportunity_Forecast_Id__c       =     OppForcast.Id;
        staging.Opportunity_Forecast_Name__c     =     OppForcast.Name;
        staging.Date__c                          =     String.ValueOf(OppForcast.Date__c);
        staging.Quantity__c                      =     String.ValueOf(OppForcast.Quantity__c);
        staging.Amount__c                        =     String.ValueOf(OppForcast.Amount__c);        
        staging.Last_Modified_by__c              =     OppForcast.LastModifiedBy.Id;
        staging.Created_by__c                    =     OppForcast.CreatedBy.Id;
        staging.Created_Date__c                  =     String.ValueOf(OppForcast.Createddate);
        staging.Last_Modified_Date__c            =     String.ValueOf(OppForcast.Lastmodifieddate);
        staging.Marked_As_Deleted__c             =     isDeleted;
        
        return staging;
    }    
    
    global void finish(Database.BatchableContext BC){
      /* Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
       String[] toAddresses = new String[] {'subramanian.jairam@te.com'};
       mail.setToAddresses(toAddresses);
       mail.setSubject('Record Clean Up Status: ');
       mail.setPlainTextBody(''+insertOppForecastStaging.KeySet());
       Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        */        
    }
}