objects/APL_Sales_Forecast__c.object
<CustomObject>
    <description>Sales forecast for appliances</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>APL Sales Forecasts</relationshipLabel>
        <relationshipName>APL_Sales_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Part</description>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>APL Sales Forecasts</relationshipLabel>
        <relationshipName>Part</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>APL Sales Forecast</label>
    <nameField>
        <displayFormat>ASF-{000000}</displayFormat>
        <label>APL Sales Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APL Sales Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BBB_Month_Bill_Book_Cust_PN__c.object
<CustomObject>
    <description>Monthly bookings and billings by customer (Account) and part for CSD, includes direct only</description>
    <fields>
        <fullName>Bill_Amount_USD__c</fullName>
        <label>Bill Amount - USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Monthly_Billings_by_Part</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipName>Monthly_Billings_by_Part</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WWCORPACCT__c</fullName>
        <formula>Value(Customer__r.WWCORPACCT__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Worldwide Account Number</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Billings/Bookings by Part</label>
    <nameField>
        <displayFormat>MBBP-{0}</displayFormat>
        <label>Monthly Billing by Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Billings/Bookings by Part</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OEM_Details__c.object
<CustomObject>
    <description>This object will be used to list Consumer Device OEM details by fiscal month.</description>
    <fields>
        <fullName>Cutoff_Date__c</fullName>
        <description>System will automatic to create a snapshot in cutoff date, the billing of this month will use this snapshot to make refresh.</description>
        <label>Cutoff Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                    <default>true</default>
                    <label>24</label>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>31</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <inlineHelpText>1 = Oct
2 = Nov
3 = Dec
4 = Jan
5 = Feb
6 = Mar
7 = Apr
8 = May
9 = Jun
10 = Jul
11 = Aug
12 = Sep</inlineHelpText>
        <label>Fiscal Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>01</label>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OEM__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OEM Details</relationshipLabel>
        <relationshipName>OEM_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>OEM Detail</label>
    <nameField>
        <displayFormat>OEMD-{YY}{MM}{DD}#{00000000}</displayFormat>
        <label>OEM Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OEM_Mapping_Rule__c.object
<CustomObject>
    <description>OEM Mapping Rule for Consumer Device</description>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <inlineHelpText>1 = Oct
2 = Nov
3 = Dec
4 = Jan
5 = Feb
6 = Mar
7 = Apr
8 = May
9 = Jun
10 = Jul
11 = Aug
12 = Sep</inlineHelpText>
        <label>Fiscal Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>01</label>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2013</fullName>
                    <default>true</default>
                    <label>2013</label>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OEM__c</fullName>
        <label>OEM</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Fiscal_Year__c</field>
                <operation>equals</operation>
                <valueField>OEM_Details__c.Fiscal_Year__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Fiscal_Month__c</field>
                <operation>equals</operation>
                <valueField>OEM_Details__c.Fiscal_Month__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>OEM_Details__c</referenceTo>
        <relationshipLabel>OEM Mappings</relationshipLabel>
        <relationshipName>OEM_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipName>OEM_Mapping_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CSD OEM Mapping</label>
    <nameField>
        <displayFormat>CSD-OEM-{0000000000}</displayFormat>
        <label>OEM Mapping Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>CBC1_Description__c</fullName>
        <description>This field contains the CBC1 Description</description>
        <label>CBC1 Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CBC1__c</fullName>
        <description>This field contains the CBC1 code.</description>
        <label>CBC1</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ClsBatch_OEM_CreateNextFiscalMonthTest.cls
/**
Name:  ClsBatch_OEM_CreateNextFiscalMonthTest
Copyright © 2014 TE Connectivity
===================================================================================================================================================
Purpose: This class contain Test Methods for ClsBatch_OEM_CreateNextFiscalMonthRule 
---------------------------------------------------------------------------------------------------------------------------------------------------       
Related APEX Class : ClsBatch_OEM_CreateNextFiscalMonthRule                                                              
===================================================================================================================================================
History:                                                        
---------------------------------------------------------------------------------------------------------------------------------------------------
Version Developer          Date       Detail                               Mercury Request #
---------------------------------------------------------------------------------------------------------------------------------------------------
    1.0 Nelson Zheng   12/31/2014  Initial Development                                                       
***************************************************************************************************
 */
@isTest(SeeAllData=true)
private class ClsBatch_OEM_CreateNextFiscalMonthTest {

    static testMethod void myUnitTest() {
        
        account a = clstesthelp.createTestAccounts();
        a.AccountNumber ='0000:00000000';
        a.WWCORPACCT__c ='00000000';
        a.BillingCountry='CN';
        //a.name ='Test Account One';
        a.Account_Manager__c = UserInfo.getUserId();
        a.OwnerId = UserInfo.getUserId();
        
        insert a;
                
        // GPL or Product Hierarchy Record
        Product_Hierarchy__c prodH = new Product_Hierarchy__c();
        prodH.Name = 'A00';
        prodH.CBC1__c = '99999';
        prodH.CBC1_Description__c = 'Test Produce Hierarchy';
        insert prodH;
                
        // Part Records
        Part__c part1 = new Part__c();
        part1.Name = '0123456879';
        part1.Product_Hierarchy__c = prodH.id;
        insert part1;
        Part__c part2 = new Part__c();
        part2.Name = '9-9999999-9';
        part2.Product_Hierarchy__c = prodH.id;
        insert part2;
        
        if(ClsOEMUtil.CurrentFM == null)
        {
            ClsOEMUtil.setCurrentFiscalDateValues();
        }
        string FiscalMonth = string.valueOf(ClsOEMUtil.CurrentFM).leftpad(2).replace(' ', '0');
        string FiscalYear = string.valueOf(Integer.valueOf(ClsOEMUtil.CurrentFY) + 1);
        string PFiscalMonth;
        string PFiscalYear;        
        
        if(FiscalMonth == '01')
        {
            PFiscalMonth = '12';
            PFiscalYear = ClsOEMUtil.CurrentFY;
        }
        else
        {
            PFiscalMonth = String.valueOf(Integer.valueOf(FiscalMonth) - 1).leftpad(2).replace(' ', '0');
            PFiscalYear = FiscalYear;
        }        
        
        list<BBB_Month_Bill_Book_Cust_PN__c> bbbs = new list<BBB_Month_Bill_Book_Cust_PN__c>();
        
        for(Integer i=0;i < 10; i++)
        {
            BBB_Month_Bill_Book_Cust_PN__c temp = new BBB_Month_Bill_Book_Cust_PN__c();
            temp.Customer__c = a.id;
            temp.Customer__r = a;
            if(i < 5)
            {
                temp.Part__c = part1.id;
                temp.Part__r = part1;
            }
            else
            {
                temp.Part__c = part2.id;
                temp.Part__r = part2;                                               
            }
            temp.Bill_Amount_USD__c = i;
            temp.Fiscal_Year__c = FiscalYear;
            temp.Fiscal_Month__c = Integer.valueOf(FiscalMonth);
            
            bbbs.add(temp);
        }
        
        insert bbbs;
 
        account OemAcct = clstesthelp.createTestAccounts();
        //OemAcct.name ='OTHERS';
        OemAcct.Account_Manager__c = UserInfo.getUserId();
        OemAcct.OwnerId = UserInfo.getUserId();         
        
        insert OemAcct;
        
        OEM_Details__c dp = new OEM_Details__c();
        dp.Fiscal_Month__c = PFiscalMonth;
        dp.Fiscal_Year__c = PFiscalYear;
        dp.Cutoff_Date__c = '15';
        dp.OEM__c = OemAcct.id;
        dp.OEM__r = OemAcct;
        
        OEM_Details__c dc = new OEM_Details__c();
        dc.Fiscal_Month__c = FiscalMonth;
        dc.Fiscal_Year__c = FiscalYear;
        dc.Cutoff_Date__c = '15';
        dc.OEM__c = OemAcct.id;
        dc.OEM__r = OemAcct;        
        
        insert dp;
        insert dc;
        
        list<OEM_Mapping_Rule__c> mapsToInsert = new list<OEM_Mapping_Rule__c>();
        
        OEM_Mapping_Rule__c m1p1 = new OEM_Mapping_Rule__c();               
        m1p1.Part_Number__c = part1.id;
        m1p1.Sold_To_Account_Code__c = '00000000';
        m1p1.WWAC__c = '00000000';
        m1p1.Type__c = 'Customer+PN';       
        mapsToInsert.add(m1p1);
        
        OEM_Mapping_Rule__c m2p1 = new OEM_Mapping_Rule__c();               
        m2p1.Part_Number__c = part1.id;
        m2p1.WWAC__c = '00000000';
        m2p1.Type__c = 'WWAC+PN';
        mapsToInsert.add(m2p1);     

        OEM_Mapping_Rule__c m3p1 = new OEM_Mapping_Rule__c();               
        m3p1.Part_Number__c = part1.id;
        m3p1.Type__c = 'PN';
        mapsToInsert.add(m3p1);
        
        OEM_Mapping_Rule__c m4p1 = new OEM_Mapping_Rule__c();               
        m4p1.Sold_To_Account_Code__c = '00000000';
        m4p1.WWAC__c = '00000000';
        m4p1.Type__c = 'Customer';
        mapsToInsert.add(m4p1);
        
        OEM_Mapping_Rule__c m5p1 = new OEM_Mapping_Rule__c();               
        m5p1.WWAC__c = '00000000';
        m5p1.Type__c = 'WWAC';
        mapsToInsert.add(m5p1);
        
        OEM_Mapping_Rule__c m1p2 = new OEM_Mapping_Rule__c();               
        m1p2.Part_Number__c = part2.id;
        m1p2.Sold_To_Account_Code__c = '00000000';
        m1p2.Type__c = 'Customer+PN';       
        mapsToInsert.add(m1p2);                             

        OEM_Mapping_Rule__c m2p2 = new OEM_Mapping_Rule__c();               
        m2p2.Part_Number__c = part2.id;
        m2p2.Type__c = 'PN';        
        mapsToInsert.add(m2p2);

        for(OEM_Mapping_Rule__c m : mapsToInsert)
        {
            m.Allocation__c = 100;
            m.Active__c = true;
            m.Fiscal_Month__c = PFiscalMonth;
            m.Fiscal_Year__c = PFiscalYear;
            m.OEM__c = dp.id;
            m.OEM__r = dp;           
        }
        
        OEM_Mapping_Rule__c currentMap = new OEM_Mapping_Rule__c();               
        currentMap.Part_Number__c = part2.id;
        currentMap.Type__c = 'PN';
        currentMap.Allocation__c = 100;
        currentMap.Active__c = false;
        currentMap.Fiscal_Month__c = FiscalMonth;
        currentMap.Fiscal_Year__c = FiscalYear;
        currentMap.OEM__c = dc.id;
        currentMap.OEM__r = dc;                    
        mapsToInsert.add(currentMap);        
        
        insert mapsToInsert;
        Test.startTest();
               
        ClsBatch_OEM_CreateNextFiscalMonthRule oemMBBB = new ClsBatch_OEM_CreateNextFiscalMonthRule(string.valueOf(FiscalMonth).leftpad(2).replace(' ', '0'), FiscalYear);
        
        //Period comparePeriod = [SELECT PeriodLabel, FiscalYearSettings.Name FROM Period where type = 'Month' and startdate <= today and enddate >= today];
          
        //oemMBBB.compareDate = ClsOEMUtil.CalculateCalendarDate(FiscalMonth, FiscalYear, '10');     
        //oemMBBB.compareDate = date.newinstance(Integer.valueOf(FiscalYear), Integer.valueOf(ClsOEMUtil.MAP_MONTHCALENDARNUMBER.get(comparePeriod.PeriodLabel)), 10);   
        Database.executeBatch(oemMBBB);
        
        Test.stopTest();
    }
}