objects/APL_Billing_Result_of_Covnerted_Opp__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Partner__c</fullName>
        <label>Opportunity Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>APL Billing Result of Covnerted Opps</relationshipLabel>
        <relationshipName>APL_Billing_Result_of_Covnerted_Opps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>APL Billing Result of Covnerted Opps</relationshipLabel>
        <relationshipName>APL_Billing_Result_of_Covnerted_Opps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>APL Billing Result of Covnerted Opps</relationshipLabel>
        <relationshipName>APL_Billing_Result_of_Covnerted_Opps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>APL Billing Result of Covnerted Opp</label>
    <nameField>
        <displayFormat>BillResult-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APL Billing Result of Covnerted Opps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BBB_Year_Bill_Book_Cust_PN__c.object
<CustomObject>
    <description>Yearly bookings and billings by customer (Account) and part, includes direct and POS (indirect)</description>
    <fields>
        <fullName>APL_need_to_capture_billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APL need to capture billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Booking/Billings By Parts (Customer)</relationshipLabel>
        <relationshipName>Yearly_BBB_by_Part_and_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <label>TCPN</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipName>Yearly_BBB</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Yearly Booking/Billings By Part</label>
    <nameField>
        <displayFormat>YBBB-{0}</displayFormat>
        <label>Yearly BBB</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking/Billings By Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>APL_need_to_capture_billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APL need to capture billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Status__c</fullName>
        <label>Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concept</fullName>
                    <default>true</default>
                    <label>Concept</label>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Designed</fullName>
                </value>
                <value>
                    <fullName>Prototyped/Sampled</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Pre-prod</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Ramp-down</fullName>
                </value>
                <value>
                    <fullName>EOL</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>CM, Distributor, OEM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isAPLOpp__c</fullName>
        <formula>Opportunity__r.isAPLOpp__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isAPLOpp</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Opportunity Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>GIBU__c</fullName>
        <description>Used to help with tallying license counts and things like that.</description>
        <inlineHelpText>Select the GIBU/BU this user is from.</inlineHelpText>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>GATD</fullName>
                </value>
                <value>
                    <fullName>ICT (Ind Comm Transport)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIC</fullName>
                </value>
                <value>
                    <fullName>Sensors</fullName>
                </value>
                <value>
                    <fullName>TEIS</fullName>
                </value>
                <value>
                    <fullName>TEIS Engineering Portfolio Mgmt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/opportunityPartner_AIUDUD_calOppyAl_Test.cls
@isTest
private class opportunityPartner_AIUDUD_calOppyAl_Test {

    static testMethod void myUnitTest() {
    	
    	User user;
    	User user2;
    	for(User tempuser : [SELECT Id, GIBU__c, Profile.Name FROM User where ((Profile.Name = 'Appliance Standard User' and GIBU__c = 'Appliances') or Profile.name = 'System Administrator') and IsActive = true ]) {
    		if(user == null && tempuser.Profile.Name == 'Appliance Standard User' && tempuser.GIBU__c == 'Appliances') {
    			user = tempuser;
    		}
    		if(user2 == null && tempuser.Profile.Name == 'System Administrator') {
    			user2 = tempuser;
    		}
    		if(user != null && user2 != null) {
    			break;
    		}
    	}
      	//user user = [SELECT GIBU__c ,Profile.Name FROM User where Profile.Name = 'Appliance Standard User'and GIBU__c = 'Appliances' and IsActive = true limit 1 ];
    	//user user2 = [SELECT Profile.name FROM User where Profile.name = 'System Administrator' and IsActive = true limit 1 ];
    	
    	ClsTestCustomSettingHelper.getApex_Helper_Settings();
    	ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
    	ClsTestCustomSettingHelper.getOpportunity_Approvers();
    	ClsTestCustomSettingHelper.getTrigger_Configuration();
    	ClsTestCustomSettingHelper.getProfitBUCenterMapping();
    	ClsTestCustomSettingHelper.getOpportunity_Team_Default_Permission();
    	
    	Channelinsightdata_test.Channelinsightdata_test();
    	/*if (Type.forName('Channelinsight__CI_Configuration__c') != null) {
            Channelinsight__CI_Configuration__c c = new Channelinsight__CI_Configuration__c();
            c.Name = 'Default';
            c.Channelinsight__CONF_Stop_Matching_POS_to_Opportunity__c = 'Opportunity Is Closed';
            c.Channelinsight__CONF_Salesforce_Environment__c = 'Sandbox';
            c.Channelinsight__CONF_Reprocess_Reviewed__c = true;
            c.Channelinsight__CONF_Disable_Address_Type_Matching__c = true;  
            c.Channelinsight__CONF_Auto_mark_POS_Reviewed__c = false; 
            c.Channelinsight__CONF_Acct_Sales_Trending_Default_Address__c = 'Bill-to';
            insert c;
   		}*/
    	
    	test.startTest();
    	system.runAs(user2) {
    		
    		list<Account> list_accs = new list<Account>();
    		Account acct = new Account();
		 	acct.Name  = 'testAcct';
			acct.Account_Manager__c = user2.Id;
			acct.BillingCountry = 'China';
			list_accs.add(acct);
			
			Account acc = new Account();
		 	acc.Name  = 'testAcc';
			acc.Account_Manager__c = user2.Id;
			acc.BillingCountry = 'China';
			list_accs.add(acc);
			insert list_accs;
			
			RecordType rt = [SELECT Name, Id,BusinessProcessId FROM RecordType where SobjectType='Opportunity' and DeveloperName = 'IND_Engineering_project'];
        	
        	Opportunity oppy = ClsTestHelp.createTestOpportunity();
	        oppy.Type = 'CM';
	        oppy.RecordTypeId = rt.Id;
	        oppy.Approval_Status_PMV__c = 'New';
	        oppy.PMV_Type__c = 'IND Standard ENG opp';
	        oppy.StageName = 'On Hold';
	        oppy.OwnerId = user.Id;
	        oppy.PMV_Migration_Setup__c = 'OnHold';
	        oppy.Name = 'testqmx';
	        
	        insert oppy;
    		
    		Opportunity oppytemp = [SELECT Name, Id,isAPLOpp__c FROM Opportunity where Id= :oppy.Id ];
			system.debug('!@# oppytemp:'+oppytemp);
			
			Product_Hierarchy__c proHieray = new Product_Hierarchy__c();
			insert proHieray;
				
			Part__c part = new Part__c();
			part.Product_Hierarchy__c  = proHieray.Id;
			insert part;
			
			Opportunity_Part__c  oppyPart = new Opportunity_Part__c();
	    	oppyPart.opportunity__c = oppy.Id;
	    	oppyPart.Part__c = part.Id;
	    	oppyPart.Process_Status__c = 'Production';
	    	oppyPart.APL_need_to_capture_billing__c = false;
	    	insert oppyPart;
	    	Opportunity_Part__c  oppyPartSelect =  [select  id, opportunity__c, Part__c, APL_need_to_capture_billing__c from Opportunity_Part__c where opportunity__c =: oppy.Id and Part__c =:part.Id and APL_need_to_capture_billing__c = false limit 1];
	    	system.debug('!@# test oppyPartSelect:'+oppyPartSelect);
	    	
	    	BBB_Year_Bill_Book_Cust_PN__c test_bbb = new BBB_Year_Bill_Book_Cust_PN__c();
			test_bbb.Customer__c = acct.Id;
			test_bbb.Part__c = part.Id;
			test_bbb.APL_need_to_capture_billing__c = false;
			insert test_bbb;
			test_bbb.APL_need_to_capture_billing__c = false;
			update test_bbb;
			
			BBB_Year_Bill_Book_Cust_PN__c  bbb = [select id from BBB_Year_Bill_Book_Cust_PN__c where Id=:test_bbb.Id limit 1] ;
	    	system.debug('!@# test bbb:'+bbb);
	    	
	    	//oppyPartner2.Allocation__c = 50;
	    	//oppyPartner2.Account__c = acc.Id;
	    	//update oppyPartner2;
	    	
	    	APL_Billing_Result_of_Covnerted_Opp__c aplBill = new APL_Billing_Result_of_Covnerted_Opp__c ();
	        aplBill.opportunity__c = oppy.Id;
	        aplBill.Part__c = part.Id;
	        aplBill.Opportunity_Partner__c = acct.Id;
	        insert aplBill;
			
			
			
    		list<Opportunity_Partner__c> list_partner = new  list<Opportunity_Partner__c>();
    		Opportunity_Partner__c oppyPartner = new Opportunity_Partner__c();
	    	oppyPartner.Opportunity__c = oppy.Id;
	    	oppyPartner.Allocation__c = 100;
	    	oppyPartner.Account__c = acct.Id;
	    	//oppyPartner.isAPLOpp__c = true;
	    	list_partner.add(oppyPartner);
	    	
	    	Opportunity_Partner__c oppyPartner2 = new Opportunity_Partner__c();
	    	oppyPartner2.Opportunity__c = oppy.Id;
	    	oppyPartner2.Allocation__c = 0;
	    	oppyPartner2.Account__c = acct.Id;
	    	//oppyPartner.isAPLOpp__c = true;
	    	list_partner.add(oppyPartner2);
	    	insert list_partner;
			
			ClsOppyPartUtil.needCriteria = false;
			
	    	oppyPartner.Account__c = acc.Id;
	    	update oppyPartner;
	    	
	    	
	    	Delete oppyPartner2;
	    	
    		
    	}
    }
}