objects/APL_Sales_Forecast__c.object
<CustomObject>
    <description>Sales forecast for appliances</description>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Only for type “Relay”</description>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>APL Sales Forecast</label>
    <nameField>
        <displayFormat>ASF-{000000}</displayFormat>
        <label>APL Sales Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APL Sales Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Part_Number__c.object
<CustomObject>
    <description>This object is created for the ANZ Project</description>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Customer Part Number</label>
    <nameField>
        <label>Customer Part Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Part Number</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Energy_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Energy Quotes</relationshipLabel>
        <relationshipName>Energy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Total_Price__c</fullName>
        <description>for quote reporting</description>
        <label>Actual Total Price</label>
        <summarizedField>Energy_Quote_Line_Item__c.TotalPrice__c</summarizedField>
        <summaryForeignKey>Energy_Quote_Line_Item__c.Energy_Quote_Name__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Energy Quotes</relationshipLabel>
        <relationshipName>Energy_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Energy Quotes (End Customer)</relationshipLabel>
        <relationshipName>Energy_Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Header_Level_Comments__c</fullName>
        <label>Header Level Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Energy Quotes</relationshipLabel>
        <relationshipName>Energy_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override_Incoterms_Details__c</fullName>
        <label>Override Incoterms Details</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <formula>if (isBlank(LegacyQuoteNumber__c),  
    if(isBlank(SAP_Quote_Number__c), 
        Auto_Quote_Number__c + &apos;-&apos; +  text(RevisionNum__c), 
        SAP_Quote_Number__c + &apos;-&apos; +  text(RevisionNum__c) ), 
    if (isBlank(RevisionNum__c), 
        if (Contains(LegacyQuoteNumber__c, &apos;RSQ&apos;), MID(LegacyQuoteNumber__c, 3, LEN(LegacyQuoteNumber__c)) , LegacyQuoteNumber__c), 
        if (Contains(LegacyQuoteNumber__c, &apos;RSQ&apos;), MID(LegacyQuoteNumber__c, 3, LEN(LegacyQuoteNumber__c)) , LegacyQuoteNumber__c) + &apos;-&apos; +  text(RevisionNum__c) ))</formula>
        <label>Quote Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <label>Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Meet Competitor Price</fullName>
                </value>
                <value>
                    <fullName>Blanket/Tender</fullName>
                </value>
                <value>
                    <fullName>One Time Tender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <summarizedField>Energy_Quote_Line_Item__c.TotalPrice__c</summarizedField>
        <summaryForeignKey>Energy_Quote_Line_Item__c.Energy_Quote_Name__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Valid_Days__c</fullName>
        <formula>Case( Days_prices_valid__c , 
&quot;30 Days&quot;,&quot;30&quot;, 
&quot;60 Days&quot;,&quot;60&quot;, 
&quot;90 Days&quot;,&quot;90&quot;,
&quot;120 Days&quot;,&quot;120&quot;,
&quot;180 Days&quot;,&quot;180&quot;, 
&quot;1 year&quot;,&quot;365&quot;,
&quot;2 years&quot;,&quot;730&quot;,
&quot;3 years&quot;,&quot;1096&quot;,
&quot;4 years&quot;,&quot;1461&quot;,
&quot;5 years&quot;, &quot;1826&quot;,
&quot;0&quot; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid Days</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <label>Energy Quote</label>
    <nameField>
        <label>Energy Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Energy Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Energy_Quote_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_Number__c</fullName>
        <label>Catalog Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_of_Origin__c</fullName>
        <label>Country of Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Line Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NDR_Delivery_Unit__c</fullName>
        <label>Delivery Unit</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDR_Minimum_Delivery_Quantity__c</fullName>
        <label>Minimum Delivery Quantity</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDR_Minimum_Order_Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDR_Unit_Package_Type__c</fullName>
        <label>Unit Package Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipLabel>Energy Quote Line Items</relationshipLabel>
        <relationshipName>Energy_Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <formula>if (isBlank( Past_RSQ__c ), Energy_Quote_Name__r.Quote_Number__c , Past_RSQ__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Energy Quote Line Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Energy Quote Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Energy Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Opportunity__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Comments about this Part for this Opportunity.</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Country_of_Origin__c</fullName>
        <label>Country of Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Energy_Quote_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Energy Quote Line Item</label>
        <referenceTo>Energy_Quote_Line_Item__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NDR_Delivery_Unit__c</fullName>
        <label>Delivery Unit</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDR_Minimum_Delivery_Quantity__c</fullName>
        <label>Minimum Delivery Quantity</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDR_Minimum_Order_Quantity__c</fullName>
        <label>Minimum Order Quantity</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDR_Unit_Package_Type__c</fullName>
        <label>Unit Package Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <description>This field contains the Part Number. It is used in Offline App.</description>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Sold_to_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Catalog_Number__c</fullName>
        <label>Catalog Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <formula>TEXT(Quantity)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ExtSAPQuotePdf.cls
/*------------------------------------------------------------
Author:        Yuan Yao <yuan.yao@capgemini.com>
Description:   Controller class to load quote and quote line item records in SAPQuotePdf.page.
               The user story number is W-00130.
Inputs:        "stdCtrl" - ApexPages.standardController of Energy_Quote__c
Test Class:    ExtSAPQuotePdf_Test
History
2017-09-18     Yuan Yao <yuan.yao@capgemini.com> Created
------------------------------------------------------------*/
public class ExtSAPQuotePdf {
    public List<Energy_Quote_Line_Item__c> quolineitem { get; set; }
    //public List<quotelineitem> allqli{get;set;}
    //public List<innerClass> allWrapperCls{get;set;}
    public Energy_Quote__c QuoteDetails{get;set;} 
    Public User u{get;set;}
    public String quoteLanguage{get;set;}
    ID i;
    public Datetime validityDateEnd{get;set;}
    public String validFrom {get;set;}
    public String acctSoldToBillingCity {get; set;}
    public String endCustomerBillingCity {get; set;}
   
    public ExtSAPQuotePdf(ApexPages.StandardController controller) {
        i=apexpages.currentpage().getparameters().get('id'); 
        QuoteDetails = [select CreatedById,id,CreatedDate ,Opportunity_Name__r.owner.name,Quote_Number__c,Name,CreatedBy.name,CreatedBy.phone,Quote_Type__c,
                            //modified by Tangyong Li 2018-02-08 by email Let's do some REAL coding again! 1)d)
                            //CreatedBy.Email, contact__r.Name,contact__r.email,contact__r.phone, Comments__c,Override_Incoterms_Details__c,Override_Payment_Terms_Description__c,
                            CreatedBy.Email, contact__r.Name,contact__r.email,contact__r.phone, Comments__c,Override_Incoterms_Details__c,
                            Account_name__r.name,Account_name__r.billingStreet,Account_name__r.billingCity,Account_name__r.billingcountry,
                            Account_name__r.billingState, Account_name__r.BillingPostalCode, Account_name__r.AccountNumber,
                            End_Customer__r.ShippingStreet,End_Customer__r.shippingCity, End_Customer__r.shippingState,End_Customer__r.Name,
                            End_Customer__r.ShippingPostalCode,End_Customer__r.AccountNumber,Valid_Days__c,Actual_Total_Price__c,CurrencyIsoCode,
                            Language__c, Valid_From__c,Account_Name__r.Incoterms_Details__c, Account_Name__r.Payment_terms_Desc__c,Header_Level_Comments__c,
                            End_Customer__r.billingStreet,End_Customer__r.billingCity,End_Customer__r.billingState,End_Customer__r.BillingPostalCode 
                            from Energy_Quote__c where id=:i];
        this.quoteLanguage = 'en';
        if(QuoteDetails.Language__c == 'English'){
            quoteLanguage = 'en';
        }else if(QuoteDetails.Language__c == 'Spanish'){
            quoteLanguage = 'es';
        }else if(QuoteDetails.Language__c == 'Portuguese'){
            quoteLanguage = 'pt-br';
        }
        System.debug('---quoteLanguage:::' + quoteLanguage);
        u = new User();
        u=[SELECT Id, Name, Email, Phone FROM User where id =: QuoteDetails.CreatedById]; 
        quolineitem=[select id,Name,Comment__c,Part_Number__c ,Catalog_Number__c,Unit_of_Measure__c,Country_of_Origin__c,
                     Description__c,NDR_Minimum_Order_Quantity__c,NDR_Unit_Package_Type__c,NDR_Delivery_Unit__c,NDR_Minimum_Delivery_Quantity__c,
                     UnitPrice__c,TotalPrice__c,Quantity__c,Opportunity_Part__r.NDR_Customer_Requested_Price_UOM__c,LineNumber__c,
                     Lead_time__c,Customer_Part_Number__c,Part__r.RPN_Part__c,Part__r.RPN_Description__c, Customer_Part_Number1__c,Customer_Part_Number1__r.Name,
                     NDR_Customer_Comments__c
                     from Energy_Quote_Line_Item__c where Energy_Quote_Name__c=:i ];    
            
        validFrom = QuoteDetails.CreatedDate.format('MM/dd/yyyy', String.valueOf(UserInfo.getTimeZone()));
        system.debug('valid from:::   ' + QuoteDetails.Valid_From__c);
        system.debug('valid from:::   ' + QuoteDetails.Valid_Days__c);
        if(QuoteDetails.Valid_Days__c != null && QuoteDetails.Valid_From__c != null){
            validityDateEnd = QuoteDetails.Valid_From__c.addDays(Integer.valueOf(QuoteDetails.Valid_Days__c));
        }
        //Modified by mei xing for Functional Testing Issues - 5/1 point 6 2018/5/2
        acctSoldToBillingCity = '';
        acctSoldToBillingCity += ((QuoteDetails.Account_name__c == null 
        						|| QuoteDetails.Account_name__r.billingCity == null
        						|| QuoteDetails.Account_name__r.billingCity == '')?'':QuoteDetails.Account_name__r.billingCity+',');
        
        endCustomerBillingCity = '';
        endCustomerBillingCity +=((QuoteDetails.End_Customer__c == null
        						|| QuoteDetails.End_Customer__r.billingCity == null
        						|| QuoteDetails.End_Customer__r.billingCity == '')?'':QuoteDetails.End_Customer__r.billingCity+',');
    }
}