objects/Batch_Email_message_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_ID__c</fullName>
        <label>Email ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch Email message Users</label>
</CustomObject>

objects/Forecast_Billing__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Filled by batch. This will have to have the sum of the quarter taken from the related Yearly record.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Forecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Forecast</label>
        <referenceTo>Opportunity_Forecast__c</referenceTo>
        <relationshipLabel>Forecast Billings</relationshipLabel>
        <relationshipName>Forecast_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To be populated for engineering parts.</description>
        <label>Opportunity Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipLabel>Forecast Billings</relationshipLabel>
        <relationshipName>Forecast_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Forecast Billing</label>
    <nameField>
        <label>Forecast Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast Billings</pluralLabel>
    <recordTypes>
        <fullName>Engineering</fullName>
        <active>true</active>
        <label>Engineering</label>
    </recordTypes>
    <recordTypes>
        <fullName>Regular</fullName>
        <active>true</active>
        <label>Regular</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Forecast__c.object
<CustomObject>
    <description>This object contains the project forecast numbers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <description>Populated by forecasting component in opportunity page to store fiscal quarter. Used in PLM integration to aggregate monthly data by quarter.</description>
        <label>Fiscal Quarter</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <description>Populated by forecasting component in opportunity page to store fiscal year. Used in PLM integration to aggregate monthly data by quarter.</description>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Forecast</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Forecasts</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Part</fullName>
        <active>true</active>
        <label>Part</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PLM_ID__c</fullName>
        <formula>Part__r.PLM_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PLM ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Confidence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>50/50</fullName>
                </value>
                <value>
                    <fullName>Likely</fullName>
                </value>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <recordTypes>
        <fullName>Extension</fullName>
        <active>true</active>
        <label>Extension</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Record_Type_Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Name__c</fullName>
        <description>API name of Record Type</description>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Record Type Groups</label>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PLM_ID__c</fullName>
        <description>this is a field for testing purposes.
Related to R 1460</description>
        <label>PLM ID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/IND_Scheduled_FCBvsFC_TestClass.cls
/*********************************************************************************************************************** 
 Name:  IND_Scheduled_FCBvsFC_TestClass
 Salesforce Instance : QA Sandbox
========================================================================================================================
 Purpose: This test class is covering the below class test coverage:
  1. INDBatch_Recal_Billing_AchievedClass: 100%
  2. IND_ScheduleForecastAttainmentClass: 100%
  3.IND_Recal_Billing_Achieved : 88%
========================================================================================================================
 REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                     
------------------------------------------------------------------------------------------------------------------------
 VERSION AUTHOR                DATE         DETAIL                                            Mercury Request #
------------------------------------------------------------------------------------------------------------------------
     1.0 Deepak               16 Jan 2017   Initial Development                                         



***********************************************************************************************************************/




@isTest()
class IND_Scheduled_FCBvsFC_TestClass {

   static testmethod void test() {
   Test.startTest();
      
       ClsTestCustomSettingHelper.getApex_Helper_Settings(); 
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getTrigger_Configuration();
        ClsTestCustomSettingHelper.getProfitBUCenterMapping();
        ChannelinsightData_test.ChannelinsightData_test();
        
       
        RecordType rt = ClsTestHelp.createTestRecordType();
        RecordType rt2 = ClsTestHelp.createTestRecordType16();
        id rt3 = Schema.SObjectType.Opportunity_Forecast__c.getRecordTypeInfosByName().get('Part').getRecordTypeId();
        id rt4 = Schema.SObjectType.Forecast_Billing__c.getRecordTypeInfosByName().get('Engineering').getRecordTypeId();
        id rt5 = Schema.SObjectType.Forecast_Billing__c.getRecordTypeInfosByName().get('Regular').getRecordTypeId();
        
        List<Opportunity_Record_Type_Groups__c> ListcusTemp = new List<Opportunity_Record_Type_Groups__c>();
        
       Opportunity_Record_Type_Groups__c cusTemp = new Opportunity_Record_Type_Groups__c();
       Opportunity_Record_Type_Groups__c cusTemp1 = new Opportunity_Record_Type_Groups__c();
        cusTemp.Active__c= True;
        cusTemp.name= 'Test';
        cusTemp.Group__c='Forecast Attainment Percentage Calculation';
        cusTemp.API_Name__c='tets_test';
        ListcusTemp.add(cusTemp);
       
        cusTemp1.Active__c= True;
        cusTemp1.name= 'Test1';
        cusTemp1.Group__c='Forecast Attainment Percentage Calculation';
        cusTemp1.API_Name__c='tets_test1';
        ListcusTemp.add(cusTemp1);       
       
       
       Insert ListcusTemp;
        
       Batch_Email_message_Users__c EmailmessageUsers =new Batch_Email_message_Users__c();
       EmailmessageUsers.name='INDBatch_Recal_Billing_AchievedClass';
       EmailmessageUsers.Email_ID__c='test@test.com';
       
       Insert EmailmessageUsers;
              
        Account acc = ClsTestHelp.createTestAccounts();
        acc.Type = 'CM';
        acc.Ownerid=userinfo.getUserId();
        acc.Billingcountry='DE';
        acc.DD1_Industry_Business_Name__c ='Industrial';
        insert acc;
        
        List<Opportunity> Listopp = new List<Opportunity>();
        
        Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
        oppy2.CloseDate =system.today()-31; 
        oppy2.Name = 'Pain of Queen';
        oppy2.Manufacturing_Start_Date__c=system.today()-31;
        oppy2.Request_Type__c = 'Extension';
        oppy2.RecordTypeId = '012E0000000fCzr';
        oppy2.StageName='New';
        oppy2.Ownerid = userinfo.getUserId();
       
        oppy2.PLM_Id__c='34drrgdg';
        Listopp.add(oppy2);  
        
        Opportunity oppy3 = ClsTestHelp.createTestOpportunity();
        oppy3.CloseDate =system.today()-31; 
        oppy3.Name = 'Pain of Queen';
        oppy3.Manufacturing_Start_Date__c=system.today()-31;
        oppy3.Request_Type__c = 'Extension';
        //oppy3.RecordTypeId = '012E0000000fCzr';
       
        
        oppy3.Project_Status_Level__c='OPEN (1)';
        oppy3.Ownerid = userinfo.getUserId();
         
        Listopp.add(oppy3); 
       
        Insert Listopp;
        
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial'; 
        insert ph;
        
        List<Part__c> Listpart =new List<Part__c>();
       
        Part__c part = new Part__c();
        part.Description__c = 'Sniper';
        part.Product_Hierarchy__c = ph.Id;
        Part.PLM_ID__c='34drrgdg';
        
        Listpart.add(part);
        
       Part__c part1 = new Part__c();
        part1.Description__c = 'Sniper';
        part1.Product_Hierarchy__c = ph.Id;
         Listpart.add(part1);
       
       insert Listpart;
      
        List< Opportunity_Part__c> Listoppypart = new  List<Opportunity_Part__c>();
       
        Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
        oppypart.Opportunity__c = oppy2.Id;
        oppypart.Part__c = part.Id;
        oppypart.Status__c='Won' ;
         Listoppypart.add(oppypart);
       
       
         
        Opportunity_Part__c oppypart1 = ClsTestHelp.createTestOpportunityPart();
        oppypart1.Opportunity__c = oppy3.Id;
        oppypart1.Part__c = part1.Id;
        oppypart1.Status__c='won' ;
         Listoppypart.add(oppypart1);
       
       insert Listoppypart;
       
        List<Opportunity_Forecast__c> Listfor = new List<Opportunity_Forecast__c>();
        
       
        
        Opportunity_Forecast__c oppyForecast2 = ClsTestHelp.createTestOpportunityForecasts();
        oppyForecast2.Opportunity__c = oppy2.Id;
        oppyForecast2.Quantity__c = 12;
        oppyForecast2.Part__c = Null;
        oppyForecast2.Date__c = system.today();
        oppyForecast2.Amount__c = 1;
        oppyForecast2.Fiscal_Year__c='2017'; 
        oppyForecast2.Fiscal_Quarter__c='01';
        oppyForecast2.RecordTypeid=rt3;
       
       
        Listfor.add(oppyForecast2);
       
       
        Opportunity_Forecast__c oppyForecast3 = ClsTestHelp.createTestOpportunityForecasts();
        oppyForecast3.Opportunity__c = oppy2.Id;
        oppyForecast3.Quantity__c = 12;
        oppyForecast3.Part__c = Null;
        oppyForecast3.Date__c = system.today();
        oppyForecast3.Amount__c = 1;
        oppyForecast3.Fiscal_Year__c='2016'; 
        oppyForecast3.Fiscal_Quarter__c='03';
        oppyForecast3.RecordTypeid=rt3;
       
       
        Listfor.add(oppyForecast3);
       
       
        Opportunity_Forecast__c oppyForecast4 = ClsTestHelp.createTestOpportunityForecasts();
        oppyForecast4.Opportunity__c = oppy3.Id;
        oppyForecast4.Quantity__c = 12;
        oppyForecast4.Part__c = Null;
        oppyForecast4.Date__c = system.today();
        oppyForecast4.Amount__c = 1;
        oppyForecast4.Fiscal_Year__c='2017'; 
        oppyForecast4.Fiscal_Quarter__c='02';
        oppyForecast4.RecordTypeid=rt3;
       
       
        Listfor.add(oppyForecast4);
       
        Opportunity_Forecast__c oppyForecast = ClsTestHelp.createTestOpportunityForecasts();
        oppyForecast.Opportunity__c = oppy3.Id;
        oppyForecast.Quantity__c = 12;
        oppyForecast.Part__c = null;
        oppyForecast.Date__c = system.today();
        oppyForecast.Amount__c = 1000;
        oppyForecast.Fiscal_Year__c='2017'; 
        oppyForecast.Fiscal_Quarter__c='01';
        oppyForecast.RecordTypeid=rt3;
        
        Listfor.add(oppyForecast); 
        
        Insert Listfor;
     
       List<Forecast_Billing__c> ListFCB = new List<Forecast_Billing__c>();
       
       Forecast_Billing__c FCB = new Forecast_Billing__c();
       FCB.Opportunity_Forecast__c=oppyForecast2.id;
       FCB.Opportunity_Part__c=oppypart.id;
       FCB.Date__c = system.today()-80;
       FCB.RecordTypeid=rt4;
       FCB.Amount__c=1000;
       ListFCB.add(FCB);
      
       Forecast_Billing__c FCB1 = new Forecast_Billing__c();
       FCB1.Opportunity_Forecast__c=oppyForecast.id;
       FCB1.Opportunity_Part__c=oppypart1.id;
       FCB1.Date__c = system.today()-80;
       FCB1.RecordTypeid=rt5;
       FCB1.Amount__c=1000;
       ListFCB.add(FCB1);
       
       Insert ListFCB;
       
      // Schedule the test job

      String jobId = System.schedule('testBasicScheduledApex',
      IND_ScheduleForecastAttainmentClass.CRON_EXP, 
         new IND_ScheduleForecastAttainmentClass());

      // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];

      // Verify the expressions are the same
      System.assertEquals(IND_ScheduleForecastAttainmentClass.CRON_EXP, 
         ct.CronExpression);

      // Verify the job has not run
      System.assertEquals(0, ct.TimesTriggered);

      // Verify the next time the job will run
      System.assertEquals('2022-09-03 00:00:00', 
         String.valueOf(ct.NextFireTime));
       
       map<string,double> Convertedrate;
        if(Convertedrate == null){
           Convertedrate= new  map<string,double>();
            for(currencytype cr:[SELECT conversionrate,isocode FROM currencytype]){
                Convertedrate.put(cr.isocode,cr.conversionrate);
              } 
          }
       IND_Recal_Billing_Achieved tempCott = New IND_Recal_Billing_Achieved(1,2017,Convertedrate);
       integer ih =tempCott.UpdateBillingOpp(Listopp);
       IND_Recal_Billing_Achieved tempCott1 = New IND_Recal_Billing_Achieved(2,2017,Convertedrate);
       integer ij =tempCott1.UpdateBillingOpp(Listopp);
       IND_Recal_Billing_Achieved tempCott2 = New IND_Recal_Billing_Achieved(3,2017,Convertedrate);
       integer ii =tempCott2.UpdateBillingOpp(Listopp);
       IND_Recal_Billing_Achieved tempCott3 = New IND_Recal_Billing_Achieved(4,2017,Convertedrate);
       integer ik =tempCott3.UpdateBillingOpp(Listopp);
       

   Test.stopTest();

   
   }
    
    
  
}