objects/BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c.object
<CustomObject>
    <description>Daily bookings, billings and backlog by customer (Account) and Part, includes Direct Sales / Distribution POS / CMA (Contract Manufacturer&apos;s Allocation)</description>
    <fields>
        <fullName>Customer__c</fullName>
        <inlineHelpText>TE Customer</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Daily Booking/Billing/Backlog By Parts</relationshipLabel>
        <relationshipName>Daily_BBBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Obsolete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to mark a record to be deleted. Any record marked true should not be used anywhere</description>
        <inlineHelpText>If checked the record will be deleted from the system</inlineHelpText>
        <label>Obsolete</label>
        <type>Checkbox</type>
    </fields>
    <label>Daily Booking/Billing/Backlog By Part</label>
    <nameField>
        <displayFormat>DBBB-{0}</displayFormat>
        <label>Daily BBB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Booking/Billing/Backlog By Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClsBatch_DeleteObsoleteDailySales.cls
global class ClsBatch_DeleteObsoleteDailySales implements Database.Batchable<SObject>, Database.Stateful{       

    global Database.QueryLocator start(Database.BatchableContext BC){
       
        String query = 'SELECT Id FROM BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c where isDeleted=false AND Obsolete__c=true order by Customer__c';
        return Database.getQueryLocator(query);     
    }
    
   
    global void execute(Database.BatchableContext BC, list<BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c> list_BBB){
        if(list_BBB != null && list_BBB.size()>0) {
            delete list_BBB;
            Database.emptyRecycleBin(list_BBB);
        }
    }
    
  
    global void finish(Database.BatchableContext info) {
      // Query the AsyncApexJob object to retrieve the current job's information. 
            AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =: info.getJobId()];
            
        // Send an email to the Apex job's submitter notifying of job completion. 
           Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
           String[] toAddresses = new String[] {'crmsupport@te.com'};
           mail.setToAddresses(toAddresses);
           mail.setSubject('Daily BBB Delete ' + a.Status);
           mail.setPlainTextBody('The batch Apex job for Daily BBB Delete processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.');
        
        if(!test.isRunningTest()) { 
           Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    } 
    

}