objects/BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c.object
<CustomObject>
    <description>Daily bookings, billings and backlog by customer (Account) and Part, includes Direct Sales / Distribution POS / CMA (Contract Manufacturer&apos;s Allocation)</description>
    <fields>
        <fullName>Backlog_Amount_USD__c</fullName>
        <inlineHelpText>Backlog Amount - Backlog Amount - C$</inlineHelpText>
        <label>Backlog Amount - USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_Amount_USD__c</fullName>
        <inlineHelpText>Constant TE Billing Amount</inlineHelpText>
        <label>Bill Amount - USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Book_Amount_USD__c</fullName>
        <inlineHelpText>Constant TE Booking Amount</inlineHelpText>
        <label>Book Amount - USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <inlineHelpText>TE Customer</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Daily Booking/Billing/Backlog By Parts</relationshipLabel>
        <relationshipName>Daily_BBBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <inlineHelpText>Identifies the TE Fiscal Month of the Sales</inlineHelpText>
        <label>Fiscal Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <inlineHelpText>Identifies the TE Fiscal Month of the Sale</inlineHelpText>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <description>Tyco Part Number</description>
        <inlineHelpText>Tyco Part Number</inlineHelpText>
        <label>TCPN</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Daily Booking/Billing/Backlog By Parts</relationshipLabel>
        <relationshipName>Daily_BBBs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Profit_Center__c</fullName>
        <inlineHelpText>TE Business Unit Profit Center for the Sale</inlineHelpText>
        <label>Profit Center</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Daily Booking/Billing/Backlog By Part</label>
    <nameField>
        <displayFormat>DBBB-{0}</displayFormat>
        <label>Daily BBB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Booking/Billing/Backlog By Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BBB_Month_Bill_Book_Cust_PN__c.object
<CustomObject>
    <description>Monthly bookings and billings by customer (Account) and part for CSD, includes direct only</description>
    <fields>
        <fullName>Bill_Amount_USD__c</fullName>
        <label>Bill Amount - USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Book_Amount_USD__c</fullName>
        <label>Book Amount - USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Monthly_Billings_by_Part</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <label>Fiscal Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipName>Monthly_Billings_by_Part</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Profit_Center__c</fullName>
        <label>Profit Center</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WWCORPACCT__c</fullName>
        <formula>Value(Customer__r.WWCORPACCT__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Worldwide Account Number</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Billings/Bookings by Part</label>
    <nameField>
        <displayFormat>MBBP-{0}</displayFormat>
        <label>Monthly Billing by Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Billings/Bookings by Part</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSD_OEM_Mapping_Daily_BBB__c.object
<CustomObject>
    <fields>
        <fullName>Profit_center__c</fullName>
        <formula>Daily_Booking_Billing_Backlog_By_Part__r.Profit_Center__c</formula>
        <label>Profit center</label>
        <type>Text</type>
    </fields>
    <label>CSD OEM Mapping Daily BBB</label>
    <nameField>
        <displayFormat>MDBBB-{0}</displayFormat>
        <label>CSD OEM Mapping Daily BBB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Mapping Daily BBB</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OEM_Details__c.object
<CustomObject>
    <description>This object will be used to list Consumer Device OEM details by fiscal month.</description>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <inlineHelpText>1 = Oct
2 = Nov
3 = Dec
4 = Jan
5 = Feb
6 = Mar
7 = Apr
8 = May
9 = Jun
10 = Jul
11 = Aug
12 = Sep</inlineHelpText>
        <label>Fiscal Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>01</label>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OEM__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OEM Details</relationshipLabel>
        <relationshipName>OEM_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>OEM Detail</label>
    <nameField>
        <displayFormat>OEMD-{YY}{MM}{DD}#{00000000}</displayFormat>
        <label>OEM Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OEM_Mapping_Rule__c.object
<CustomObject>
    <description>OEM Mapping Rule for Consumer Device</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation(%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <inlineHelpText>1 = Oct
2 = Nov
3 = Dec
4 = Jan
5 = Feb
6 = Mar
7 = Apr
8 = May
9 = Jun
10 = Jul
11 = Aug
12 = Sep</inlineHelpText>
        <label>Fiscal Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>01</label>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2013</fullName>
                    <default>true</default>
                    <label>2013</label>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OEM__c</fullName>
        <label>OEM</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Fiscal_Year__c</field>
                <operation>equals</operation>
                <valueField>OEM_Details__c.Fiscal_Year__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Fiscal_Month__c</field>
                <operation>equals</operation>
                <valueField>OEM_Details__c.Fiscal_Month__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>OEM_Details__c</referenceTo>
        <relationshipLabel>OEM Mappings</relationshipLabel>
        <relationshipName>OEM_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WWAC</fullName>
                    <default>true</default>
                    <label>WWAC</label>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>PN</fullName>
                </value>
                <value>
                    <fullName>WWAC+PN</fullName>
                </value>
                <value>
                    <fullName>Customer+PN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSD OEM Mapping</label>
    <nameField>
        <displayFormat>CSD-OEM-{0000000000}</displayFormat>
        <label>OEM Mapping Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/type_priority__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Define the priority of &quot;Type&quot;(wwac/Customer/PN/wwac+PN/Customer+PN).</description>
    <fields>
        <fullName>priority__c</fullName>
        <label>priority</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Type_Priority</label>
</CustomObject>

classes/ClsBatch_OEM_DailyBBBtoMapping.cls
/**
*   apex class: ClsBatch_OEM_DailyBBBtoMapping
*
@author Michael Cui
@version 1.0
*
@changelog
* 2014-09-04 Michael Cui
* update this for case 00733781 to ignore the DML query issue as total BBB query records was great than 50,000.

* 2015-04-14 Nelson Zheng
* rewrite the logic to fix the bug of "others" and to match the priority change of the type.
*/
global class ClsBatch_OEM_DailyBBBtoMapping implements Database.Batchable<SObject>,Database.Stateful{
    public String query;
    public String CurrentPeriodFMonth;
    public Integer iCurrentPeriodFMonth;
    public String CurrentPeriodFYear;
    public OEM_Mapping_Rule__c othersOEMMappingRule;

    public ClsBatch_OEM_DailyBBBtoMapping(String fiscalMonth, String fiscalYear){
        
        iCurrentPeriodFMonth = Integer.valueOf(fiscalMonth);
        CurrentPeriodFYear = fiscalYear;
        CurrentPeriodFMonth = fiscalMonth;
        
        //get the OEM_Mapping_Rule__c record of others in current fiscalMonth and fiscalYear
        List<OEM_Mapping_Rule__c> othersOEMMappingRuleList = [select Id from OEM_Mapping_Rule__c
                                                                where fiscal_month__c =: CurrentPeriodFMonth 
                                                                and fiscal_year__c =: CurrentPeriodFYear
                                                                and Active__c = true
                                                                and OEM__r.OEM__r.Name = 'NON OEM'
                                                                and type__c = 'Customer'
                                                                and Allocation__c = 100
                                                                limit 1];
        System.debug('---------------othersOEMMappingRuleList---------------'+othersOEMMappingRuleList);
        if(othersOEMMappingRuleList.size() > 0){
            othersOEMMappingRule = othersOEMMappingRuleList[0];
        }
                     
    }    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {             
        
       if (query == null || query == '')
       {
            query =   'Select Id, Book_Amount_USD__c, Backlog_Amount_USD__c ,Bill_Amount_USD__c , ' +
                      ' Customer__r.WWCORPACCT__c, Profit_Center__c, Customer__r.Tech_SoldToAccountCode__c,Customer__r.AccountNumber, Part__c ' +
                      ' from BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c ' +
                      ' where fiscal_month__c =: iCurrentPeriodFMonth and fiscal_year__c =: CurrentPeriodFYear' +
                      ' and IsDeleted = false and Profit_Center__c = \'DND\'';// +
                      //' and (customer__r.tech_soldtoaccountcode__c in: soldtoaccountcodeset ' +
                      //' or customer__r.WWCORPACCT__c in: wwCusNumset or ' +
                      //' part__c in: partnumberset) ';                                      
       }         
        return Database.getQueryLocator(query);         
    }

    global void execute(Database.BatchableContext BC, list<BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c> BBBList)
    {   
         //a list of CSD_OEM_Mapping_Daily_BBB__c that should be inserted finally
        List<CSD_OEM_Mapping_Daily_BBB__c> CSDOEMMappingDailyBBBList = new List<CSD_OEM_Mapping_Daily_BBB__c>();
        //get the priority of type from customer settings
        Map<String,Type_Priority__c> typePriortyMap = Type_Priority__c.getAll();
        
        //Declare three set to hold WWCORPACCT__c/Tech_SoldToAccountCode__c/Part__c
        Set<String> wwacCodeSet = new Set<String>();
        Set<String> soldToAccountCodeSet = new Set<String>();
        Set<String> partNumberSet = new Set<String>();   
        
        //add value to wwacCodeSet/soldToAccountCodeSet/partNumberSet
        for(BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c dailyBillBookCustPN : BBBList){
            if(dailyBillBookCustPN.Customer__r.WWCORPACCT__c != null && dailyBillBookCustPN.Customer__r.WWCORPACCT__c != ''){
                wwacCodeSet.add(dailyBillBookCustPN.Customer__r.WWCORPACCT__c);
            }
            
            if(dailyBillBookCustPN.Part__c != null){
                partNumberSet.add(dailyBillBookCustPN.Part__c);
            }
            //because Customer__r.AccountNumber contains org code , so we need to get the SoldToAccountCode only
            if(dailyBillBookCustPN.Customer__r.AccountNumber != null && dailyBillBookCustPN.Customer__r.AccountNumber != ''){
                System.debug('-----------dailyBillBookCustPN.Customer__r.AccountNumber---------------' + dailyBillBookCustPN.Customer__r.AccountNumber);
                if(dailyBillBookCustPN.Customer__r.AccountNumber.indexOf(':') > -1){
                    String[] accountCodeList = dailyBillBookCustPN.Customer__r.AccountNumber.split(':');
                    soldToAccountCodeSet.add(accountCodeList[1]);
                }else{
                    soldToAccountCodeSet.add(dailyBillBookCustPN.Customer__r.AccountNumber);
                }
            }
        }
        
        //select corresponding OEM_mapping_rule__c with wwacCodeSet/soldToAccountCodeSet/partNumberSet
        List<OEM_Mapping_Rule__c> OEMMappingRuleList = [select Id,OEM__c,Allocation__c,Part_Number__c,WWAC__c,Sold_To_Account_Code__c,Type__c,wwac_in_8__c
                                                         from OEM_Mapping_Rule__c 
                                                        where (Part_Number__c in: partNumberSet 
                                                        or wwac_in_8__c in: wwacCodeSet
                                                        or Sold_To_Account_Code_Add_0__c in: soldToAccountCodeSet)
                                                        and fiscal_month__c =: CurrentPeriodFMonth and fiscal_year__c =: CurrentPeriodFYear
                                                        and Active__c = true];
                                                        
        if(OEMMappingRuleList.size() == 0){
            //get last fiscal year and fiscal month
            Integer iLastPeriodFMonth = iCurrentPeriodFMonth - 1;
            Integer iLastPeriodFYear = Integer.valueOf(CurrentPeriodFYear);
            if(iLastPeriodFMonth == 0){
                iLastPeriodFMonth = 12;
                iLastPeriodFYear = iLastPeriodFYear - 1;
            }
            
            String lastPeriodFMonth = iLastPeriodFMonth + '';
            lastPeriodFMonth = lastPeriodFMonth.leftPad(2,'0');
            String lastPeriodFYear = iLastPeriodFYear + '';
            OEMMappingRuleList = [select Id,OEM__c,Allocation__c,Part_Number__c,WWAC__c,Sold_To_Account_Code__c,Type__c,wwac_in_8__c
                                                         from OEM_Mapping_Rule__c 
                                                        where (Part_Number__c in: partNumberSet 
                                                        or wwac_in_8__c in: wwacCodeSet
                                                        or Sold_To_Account_Code_Add_0__c in: soldToAccountCodeSet)
                                                        and fiscal_month__c =: lastPeriodFMonth and fiscal_year__c =: lastPeriodFYear
                                                        and Active__c = true];
        }
        
        //declare five list for type: wwac/Customer/PN/wwac+PN/Customer+PN
       List<OEM_Mapping_Rule__c> oemWwacList = new List<OEM_Mapping_Rule__c>();
       List<OEM_Mapping_Rule__c> oemCustomerList = new List<OEM_Mapping_Rule__c>();
       List<OEM_Mapping_Rule__c> oemPNList = new List<OEM_Mapping_Rule__c>();
       List<OEM_Mapping_Rule__c> oemWwacPNList = new List<OEM_Mapping_Rule__c>();
       List<OEM_Mapping_Rule__c> oemCustomerPNList = new List<OEM_Mapping_Rule__c>();
        
        //seperate OEMMappingRuleList into diferent map by type
       for(OEM_Mapping_Rule__c oemMappingRule : OEMMappingRuleList){
            String preType = '';//hold the old type before change to number
            preType = oemMappingRule.type__c;
            System.debug('------------preType-----------'+preType);
            //change type__c to number.for easy to compare.
            oemMappingRule.type__c = typePriortyMap.get(oemMappingRule.type__c).priority__c;
            System.debug('----------oemMappingRule.type__c------------'+oemMappingRule.type__c);
           //seperate OEM_Mapping_Rule__c to deferent list
           if(preType == 'WWAC'){
               oemWwacList.add(oemMappingRule);
           }else if(preType == 'Customer'){
               oemCustomerList.add(oemMappingRule);
           }else if(preType == 'PN'){
               oemPNList.add(oemMappingRule);
           }else if(preType == 'WWAC+PN'){
               oemWwacPNList.add(oemMappingRule);
           }else if(preType == 'Customer+PN'){
               oemCustomerPNList.add(oemMappingRule);
           }
       }
       
       for(BBB_Day_Direct_Bill_Book_Bklg_Cust_PN__c dailyBillBookCustPN : BBBList){
           //because one BBB_Month_Bill_Book_Cust_PN__c can match more than one OEM_Mapping_Rule__c 
           //so we need to get all of the match records
           //loop the list of BBB_Month_Bill_Book_Cust_PN__c to find whether the record is match wwac/Customer/PN/wwac+PN/Customer+PN
           List<OEM_Mapping_Rule__c> oemMappingRuleTempList = new List<OEM_Mapping_Rule__c>();
           Map<Id,OEM_Mapping_Rule__c> oemMappingRuleTempMap = new Map<Id,OEM_Mapping_Rule__c>();//use this map to remove lower priority type
           System.debug('----------------dailyBillBookCustPN.Id--------------------'+dailyBillBookCustPN.Id);
           //wwac
           for(OEM_Mapping_Rule__c oemMappingRuleTemp : oemWwacList){
               //just use wwac number to check if match or not
               
               if(dailyBillBookCustPN.Customer__r.WWCORPACCT__c == oemMappingRuleTemp.wwac_in_8__c){
                   oemMappingRuleTempList.add(oemMappingRuleTemp);
               }
           }
           
           //Customer
           for(OEM_Mapping_Rule__c oemMappingRuleTemp : oemCustomerList){
               //just use AccountNumber number to check if match or not
               //because Customer__r.AccountNumber contains org number. So we use indexOf() to check 
               //whether Customer__r.AccountNumber contains oemMappingRuleTemp.Sold_To_Account_Code__c or not
               
               if(dailyBillBookCustPN.Customer__r.AccountNumber.indexOf(oemMappingRuleTemp.Sold_To_Account_Code__c) > -1){
                   oemMappingRuleTempList.add(oemMappingRuleTemp);
               }
           }
           
           //pn
           for(OEM_Mapping_Rule__c oemMappingRuleTemp : oemPNList){
               //just use pn number to check if match or not
               
               if(dailyBillBookCustPN.Part__c == oemMappingRuleTemp.Part_Number__c){
                   oemMappingRuleTempList.add(oemMappingRuleTemp);
               }
           }
           
           //wwac+pn
           for(OEM_Mapping_Rule__c oemMappingRuleTemp : oemWwacPNList){
               //use wwac number and pn to check if match or not
               if(dailyBillBookCustPN.Customer__r.WWCORPACCT__c == oemMappingRuleTemp.wwac_in_8__c && dailyBillBookCustPN.Part__c == oemMappingRuleTemp.Part_Number__c){
                   oemMappingRuleTempList.add(oemMappingRuleTemp);
               }
           }
           
           //customer+pn
           for(OEM_Mapping_Rule__c oemMappingRuleTemp : oemCustomerPNList){
               //just use AccountNumber number and pn to check if match or not
               //because Customer__r.AccountNumber contains org number. So we use indexOf() to check 
               //whether Customer__r.AccountNumber contains oemMappingRuleTemp.Sold_To_Account_Code__c or not
               if(dailyBillBookCustPN.Customer__r.AccountNumber.indexOf(oemMappingRuleTemp.Sold_To_Account_Code__c) > -1
                    && dailyBillBookCustPN.Part__c == oemMappingRuleTemp.Part_Number__c
               ){
                   oemMappingRuleTempList.add(oemMappingRuleTemp);
               }
           }
           
           //now we have a list of OEM_Mapping_Rule__c that match the current BBB_Month_Bill_Book_Cust_PN__c
           //Then we should remove duplicate OEM__c and retain the highest priority type
           //one OEM__c should have only one record
           if(oemMappingRuleTempList.size() > 0){
               for(OEM_Mapping_Rule__c oemMappingRuleTemp : oemMappingRuleTempList){
                   OEM_Mapping_Rule__c oemMappingRuleTemp1 = new OEM_Mapping_Rule__c();//temp
                   if(oemMappingRuleTempMap.containskey(oemMappingRuleTemp.OEM__c)){
                       oemMappingRuleTemp1 = oemMappingRuleTempMap.get(oemMappingRuleTemp.OEM__c);
                       //compare the type priority
                       if(oemMappingRuleTemp.type__c > oemMappingRuleTemp1.type__c){
                           //if the type of oemMappingRuleTemp is bigger, then put oemMappingRuleTemp to the map
                           oemMappingRuleTempMap.put(oemMappingRuleTemp.OEM__c,oemMappingRuleTemp);
                       }
                   }else{
                       oemMappingRuleTempMap.put(oemMappingRuleTemp.OEM__c,oemMappingRuleTemp);
                   }
               }
               
               //sum allocation__c of oemMappingRuleTempMap.value, check total allocation__c is 100% or not
               //if not 100%, the rest should be "others"
               Double totalAllocation = 0.0;
               List<OEM_Mapping_Rule__c> oemMappingRuleTemp1List = new List<OEM_Mapping_Rule__c>();
               for(Id oem : oemMappingRuleTempMap.keySet()){
                   totalAllocation += oemMappingRuleTempMap.get(oem).Allocation__c;
                   
                   oemMappingRuleTemp1List.add(oemMappingRuleTempMap.get(oem));//if totalAllocation > 100, use this list to compare the type
               }
               
               if(totalAllocation > 100){
                   //more than 100, should check priority of type again, reserve the highest level type
                   Map<Double,OEM_Mapping_Rule__c> oemMappingRuleTemp1Map = new Map<Double,OEM_Mapping_Rule__c>();
                   for(OEM_Mapping_Rule__c oemMappingRuleTemp1 : oemMappingRuleTemp1List){
                       OEM_Mapping_Rule__c oemMappingRuleTemp2;//temp
                       if(oemMappingRuleTemp1Map.containskey(oemMappingRuleTemp1.Allocation__c)){
                           oemMappingRuleTemp2 = oemMappingRuleTemp1Map.get(oemMappingRuleTemp1.Allocation__c);
                           if(oemMappingRuleTemp1.type__c > oemMappingRuleTemp2.type__c){
                               oemMappingRuleTemp1Map.put(oemMappingRuleTemp1.Allocation__c,oemMappingRuleTemp1);
                           }
                       }else{
                           oemMappingRuleTemp1Map.put(oemMappingRuleTemp1.Allocation__c,oemMappingRuleTemp1);
                       }
                   }
                   
                   for(Double oemAllocation : oemMappingRuleTemp1Map.keySet()){
                       CSD_OEM_Mapping_Daily_BBB__c dailyBBB = new CSD_OEM_Mapping_Daily_BBB__c();
                       dailyBBB.CSD_OEM_Mapping__c = oemMappingRuleTemp1Map.get(oemAllocation).id;
                       dailyBBB.Daily_Booking_Billing_Backlog_By_Part__c = dailyBillBookCustPN.Id;
                       CSDOEMMappingDailyBBBList.add(dailyBBB);
                   }
               }else{
                   for(Id oem : oemMappingRuleTempMap.keySet()){
                       CSD_OEM_Mapping_Daily_BBB__c dailyBBB = new CSD_OEM_Mapping_Daily_BBB__c();
                       dailyBBB.CSD_OEM_Mapping__c = oemMappingRuleTempMap.get(oem).id;
                       dailyBBB.Daily_Booking_Billing_Backlog_By_Part__c = dailyBillBookCustPN.Id;
                       CSDOEMMappingDailyBBBList.add(dailyBBB);
                   }
               }
               
               if(totalAllocation < 100 && othersOEMMappingRule != null){
                   //add to others
                   CSD_OEM_Mapping_Daily_BBB__c dailyBBB = new CSD_OEM_Mapping_Daily_BBB__c();
                   dailyBBB.CSD_OEM_Mapping__c = othersOEMMappingRule.id;
                   dailyBBB.Daily_Booking_Billing_Backlog_By_Part__c = dailyBillBookCustPN.Id;
                   //for others we should set Allocation_For_Others__c
                   dailyBBB.Allocation_For_Others_c__c = 100 - totalAllocation;
                   CSDOEMMappingDailyBBBList.add(dailyBBB);
               }
           }else if(othersOEMMappingRule != null){
               //this part should be "others"
               CSD_OEM_Mapping_Daily_BBB__c dailyBBB = new CSD_OEM_Mapping_Daily_BBB__c();
               dailyBBB.CSD_OEM_Mapping__c = othersOEMMappingRule.id;
               dailyBBB.Daily_Booking_Billing_Backlog_By_Part__c = dailyBillBookCustPN.Id;
               //for others we should set Allocation_For_Others__c
               //because of no match OEM_Mapping__Rule__c, So the Allocation_For_Others__c should be 100
               dailyBBB.Allocation_For_Others_c__c = 100;
               CSDOEMMappingDailyBBBList.add(dailyBBB);
           }
           
       }
       
       for(CSD_OEM_Mapping_Daily_BBB__c dailyBBB : CSDOEMMappingDailyBBBList){
            dailyBBB.need_summary__c = true;
       }
       
       if(CSDOEMMappingDailyBBBList.size() > 0){
           insert CSDOEMMappingDailyBBBList;
       }
    }

    global void finish(Database.BatchableContext BC)
    { 
        
    }
}