objects/Budget__c.object
<CustomObject>
    <description>Annual Budget Planning</description>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Identifies round of budget planning. Ideally, the budget is generated in a first round and then saved as original budget. Then manager will report the bottom-up budget plan. Top-down a revised target is being communicated which will lead into a final budget. User should not be allowed to change back from Final to Original</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Original</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Each budget is determined for one A code (e.g. A001234) which defines one territory.</description>
        <label>Territory</label>
        <referenceTo>Sales_Hierarchy__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Budget_TBR_NY__c</fullName>
        <description>Total Budget based on Budget Rate of Next Year</description>
        <label>Total Budget TBR NY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Direct_Budget_TBR_NY__c</fullName>
        <description>Total Direct Budget based on Budget Rate of Next Year</description>
        <label>Total Direct Budget TBR NY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Stores fiscal year. Each budget entry is for a specific year.</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Hierarchy__c.object
<CustomObject>
    <description>Reflects the Sales Hierarchy.</description>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Level 7 territory code</inlineHelpText>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sales Hierarchy</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TrgBudget_BU_setBBBMonthlyValues_Test.cls
/**
*  This test class is for Budget_BU_setBBBMonthlyValues.
*
@author Di Chen
@created 2013-01-31
@version 1.0
@since 20.0
*
@changelog
* 2013-01-31 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 100%
*/
@isTest
private class TrgBudget_BU_setBBBMonthlyValues_Test {

    static testMethod void testBU() {
    	Sales_Hierarchy__c sh = new Sales_Hierarchy__c();
    	sh.Level_7_Territory_Code__c = 'A007357';
    	insert sh;
    	
    	Budget__c bg = new Budget__c();
    	bg.Year__c = '2012';
    	bg.Territory__c = sh.Id;
		bg.Total_Direct_Budget_TBR_NY__c = 11;
		bg.Total_Budget_TBR_NY__c = 12;
    	insert bg;
    	
    	Test.startTest();
    	
    	bg.Stage__c = 'Final';
    	update bg;
    	
    	system.assert(true);
    	Test.stopTest();
    }
}