objects/Budget__c.object
<CustomObject>
    <description>Annual Budget Planning</description>
    <fields>
        <fullName>Manager_CMA_Budget__c</fullName>
        <description>The field is the budget of CMA which the approver inputs.</description>
        <label>Manager CMA Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manager_Direct_Budget__c</fullName>
        <description>The field is the budget of Direct which the approver inputs.</description>
        <label>Manager Direct Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manager_POS_Budget__c</fullName>
        <description>The field is the budget of POS which the approver inputs.</description>
        <label>Manager POS Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains the Manager of the Budget Owner.</description>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_POS_Budget__c</fullName>
        <description>Keeps original budget for POS business. Copied via workflow when budget is approved and stage equals Original.</description>
        <label>Original POS Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Identifies round of budget planning. Ideally, the budget is generated in a first round and then saved as original budget. Then manager will report the bottom-up budget plan. Top-down a revised target is being communicated which will lead into a final budget. User should not be allowed to change back from Final to Original</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Original</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Draft means, user can maintain budget plan. Submitted means the user cannot change the budget plan any longer. Approved is a budget by manager. After approval, user or manager can change Stage to Final which will reset Status to Draft.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Each budget is determined for one A code (e.g. A001234) which defines one territory.</description>
        <label>Territory</label>
        <referenceTo>Sales_Hierarchy__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Budget_TBR_NY__c</fullName>
        <description>Total Budget based on Budget Rate of Next Year</description>
        <label>Total Budget TBR NY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Direct_Budget_TBR_NY__c</fullName>
        <description>Total Direct Budget based on Budget Rate of Next Year</description>
        <label>Total Direct Budget TBR NY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Stores fiscal year. Each budget entry is for a specific year.</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget_Detail__c.object
<CustomObject>
    <description>Budget Detail</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is the relationship to the Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget Details</relationshipLabel>
        <relationshipName>Budget_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billings_CYRR__c</fullName>
        <description>Billings current year run rate = Billings CYTD divided by the number of fiscal months of current year in monthly BBB table times 12 (= 12 months).

For direct, we use the number of months of direct business. For CMA/POS number of records with indirect business.

Value is calculated in Visualforce page when user changes its budget plan.</description>
        <inlineHelpText>calculated billings run rate for current year</inlineHelpText>
        <label>Billings RR CY $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billings_CYTD__c</fullName>
        <description>After each edit of the budget plan, billings of current year to date are calculated from TED imported data (monthly BBB by customer) and stored here for future reference, especially that the manager refers to the same value. Current year is defined by the fiscal year value given by Budget record.</description>
        <inlineHelpText>billings current year  to date</inlineHelpText>
        <label>Billings YTD CY $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billings_LY__c</fullName>
        <description>After each edit of the budget plan, billings of last year are calculated from TED imported data (monthly BBB by customer) and stored here for future reference, especially that the manager refers to the same value.</description>
        <inlineHelpText>billings previous fiscal year</inlineHelpText>
        <label>Billings LY $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>Parent relation to budget</description>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budget Details</relationshipLabel>
        <relationshipName>Budget_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Forecast_CY__c</fullName>
        <description>Updated forecast for current year, manually updated by user. Prepopulated with Billings CYRR on first time.</description>
        <inlineHelpText>estimated final current year adjusted by plan owner</inlineHelpText>
        <label>Estimated Final CY $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines type of business per budget detail record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>CMA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Detail</label>
    <nameField>
        <label>Budget Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Details</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>Defines if budget detail is related to dedicated account or for territory in general. Assumption: Only one rec-ord with record type Other per budget record</description>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Hierarchy__c.object
<CustomObject>
    <description>Reflects the Sales Hierarchy.</description>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Level 7 territory code</inlineHelpText>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sales Hierarchy</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CtrlManagerReview_Test.cls
/**
*	This test class is for CtrlManagerReview.
*
@author Di Chen
@created 2012-06-07
@version 1.0
@since 20.0
*
@changelog
* 2012-06-07 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 97%
*/
@isTest
private class CtrlManagerReview_Test {

    static testMethod void testMostMethods() {
    	
    	User u = ClsTestHelp.createTestUsers();
    	u.Email = 'helloMan@testCompany1233423.com';
    	u.Alias = 'dps';
    	u.CommunityNickname = 'ATM';
		insert u;
    	
    	system.runAs(u){
    	
	        RecordType rt = ClsTestHelp.createTestRecordType8();
	    	
	    	Account acc = ClsTestHelp.createTestAccounts();
	    	acc.RecordTypeId = rt.Id;
	    	acc.SALES_TERRITORY_CDE__c = 'A003153';
	    	acc.Individually_Planned__c = true;
	    	acc.Account_Manager__c = u.Id;
	    	insert acc;
	    	
	    	Sales_Hierarchy__c sh = new Sales_Hierarchy__c();
	    	sh.Level_7_Territory_Code__c = 'A007357';
	    	insert sh;
	    	
	    	Budget__c bg = new Budget__c();
	    	bg.Year__c = string.valueOf(date.today().year());
	    	bg.Territory__c = sh.Id;
			bg.Total_Direct_Budget_TBR_NY__c = 11;
			bg.Total_Budget_TBR_NY__c = 12;
			bg.Stage__c = 'Original';
			bg.Manager__c = u.Id;
			bg.Manager_CMA_Budget__c = 12;
			bg.Manager_Direct_Budget__c = 12;
			bg.Manager_POS_Budget__c = 12;
			bg.Original_POS_Budget__c = 12;
			bg.Status__c = 'Submitted';
	    	insert bg;
	    	
	    	Budget_Detail__c bd = ClsTestHelp.createTestBudgetDetail();
	    	bd.Account__c = acc.Id;
	    	bd.Budget__c = bg.Id;
	    	bd.Type__c = 'Total';
	    	insert bd;
	   
	   		CtrlManagerReview.BudgetReviewRecord ctrlBudget = new CtrlManagerReview.BudgetReviewRecord(bg,'Direct');
	   		ctrlBudget.isChecked = true;
	   		ctrlBudget.budget = bg;
	   		ctrlBudget.budgetDetail = bd;
	   		ctrlBudget.getGrowth();
	   		
	   		
	    	Test.startTest();
	    	
	    	CtrlManagerReview ctrl = new CtrlManagerReview();
	    	ctrl.totalBudgetReviewRecord = ctrlBudget;
	    	
	    	ctrl.getBudgetRecordViewByAM();
	    	ctrl.backToView();
	    	ctrl.getBugetReviewRecords();
	    	ctrl.save();
            for(CtrlManagerReview.BudgetReviewRecord rec:ctrl.map_budgetId_BudgetReviewRecords.values())
        	rec.ischecked = true;
	    	ctrl.saveAndApproval();
	    	ctrl.saveAndReject();
	    	ctrl.getViews();
    	}
    	system.assert(true);
    	Test.stopTest();
    }
	static testMethod void testMostMethods2() {
        RecordType rt = ClsTestHelp.createTestRecordType8();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.SALES_TERRITORY_CDE__c = 'A003153';
    	acc.Individually_Planned__c = true;
    	acc.Account_Manager__c = UserInfo.getUserId();
    	insert acc;
    	
    	Sales_Hierarchy__c sh = new Sales_Hierarchy__c();
    	sh.Level_7_Territory_Code__c = 'A007357';
    	insert sh;
    	
    	Budget__c bg = new Budget__c();
    	bg.Year__c = string.valueOf(date.today().year());
    	bg.Territory__c = sh.Id;
		bg.Total_Direct_Budget_TBR_NY__c = 11;
		bg.Total_Budget_TBR_NY__c = 12;
		bg.Stage__c = 'Original';
		bg.Manager__c = UserInfo.getUserId();
		bg.Manager_CMA_Budget__c = 12;
		bg.Manager_Direct_Budget__c = 12;
		bg.Manager_POS_Budget__c = 12;
		bg.Original_POS_Budget__c = 12;
    	insert bg;
    	
    	Budget_Detail__c bd = ClsTestHelp.createTestBudgetDetail();
    	bd.Account__c = acc.Id;
    	bd.Budget__c = bg.Id;
    	bd.Type__c = 'Total';
    	insert bd;
   
   		CtrlManagerReview.BudgetReviewRecord ctrlBudget = new CtrlManagerReview.BudgetReviewRecord(bg,'POS');
   		ctrlBudget.isChecked = true;
   		ctrlBudget.budget = bg;
   		ctrlBudget.budgetDetail = bd;
   		ctrlBudget.getGrowth();
   		
    	Test.startTest();
    	
    	CtrlManagerReview ctrl = new CtrlManagerReview();
    	ctrl.totalBudgetReviewRecord = ctrlBudget;
    	
    	ctrl.getBudgetRecordViewByAM();
    	ctrl.backToView();
    	ctrl.getBugetReviewRecords();
    	ctrl.save();
        for(CtrlManagerReview.BudgetReviewRecord rec:ctrl.map_budgetId_BudgetReviewRecords.values())
        rec.ischecked = true;
    	ctrl.saveAndApproval();
    	ctrl.saveAndReject();
    	ctrl.getViews();
    	
    	system.assert(true);
    	Test.stopTest();
    }
	static testMethod void testMostMethods3() {
        RecordType rt = ClsTestHelp.createTestRecordType8();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.SALES_TERRITORY_CDE__c = 'A003153';
    	acc.Individually_Planned__c = true;
    	acc.Account_Manager__c = UserInfo.getUserId();
    	insert acc;
    	
    	Sales_Hierarchy__c sh = new Sales_Hierarchy__c();
    	sh.Level_7_Territory_Code__c = 'A007357';
    	insert sh;
    	
    	Budget__c bg = new Budget__c();
    	bg.Year__c = string.valueOf(date.today().year());
    	bg.Territory__c = sh.Id;
		bg.Total_Direct_Budget_TBR_NY__c = 11;
		bg.Total_Budget_TBR_NY__c = 12;
		bg.Stage__c = 'Original';
		bg.Manager__c = UserInfo.getUserId();
		bg.Manager_CMA_Budget__c = 12;
		bg.Manager_Direct_Budget__c = 12;
		bg.Manager_POS_Budget__c = 12;
		bg.Original_POS_Budget__c = 12;
    	insert bg;
    	
    	Budget_Detail__c bd = ClsTestHelp.createTestBudgetDetail();
    	bd.Account__c = acc.Id;
    	bd.Budget__c = bg.Id;
    	bd.Type__c = 'Total';
    	bd.Billings_LY__c = 11;
    	bd.Billings_CYTD__c = 11;
    	bd.Billings_CYRR__c = 11;
    	bd.Forecast_CY__c = 12;
    	insert bd;
   
   		CtrlManagerReview.BudgetReviewRecord ctrlBudget = new CtrlManagerReview.BudgetReviewRecord(bg,'CMA');
   		ctrlBudget.isChecked = true;
   		ctrlBudget.budget = bg;
   		ctrlBudget.budgetDetail = bd;
   		ctrlBudget.getGrowth();
   		
    	Test.startTest();
    	
    	CtrlManagerReview ctrl = new CtrlManagerReview();
    	ctrl.totalBudgetReviewRecord = ctrlBudget;
    	ctrl.view = 'Total';
    	
    	ctrl.getBudgetRecordViewByAM();
    	ctrl.backToView();
    	ctrl.getBugetReviewRecords();
    	ctrl.save();
        for(CtrlManagerReview.BudgetReviewRecord rec:ctrl.map_budgetId_BudgetReviewRecords.values())
        rec.ischecked = true;
    	ctrl.saveAndApproval();
    	ctrl.saveAndReject();
    	ctrl.getViews();
    	
    	system.assert(true);
    	Test.stopTest();
    }
	static testMethod void testMostMethods4() {
        RecordType rt = ClsTestHelp.createTestRecordType8();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.SALES_TERRITORY_CDE__c = 'A003153';
    	acc.Individually_Planned__c = true;
    	acc.Account_Manager__c = UserInfo.getUserId();
    	insert acc;
    	
    	Sales_Hierarchy__c sh = new Sales_Hierarchy__c();
    	sh.Level_7_Territory_Code__c = 'A007357';
    	insert sh;
    	
    	Budget__c bg = new Budget__c();
    	bg.Year__c = string.valueOf(date.today().year());
    	bg.Territory__c = sh.Id;
		bg.Total_Direct_Budget_TBR_NY__c = 11;
		bg.Total_Budget_TBR_NY__c = 12;
		bg.Stage__c = 'Original';
		bg.Manager__c = UserInfo.getUserId();
		bg.Manager_CMA_Budget__c = 12;
		bg.Manager_Direct_Budget__c = 12;
		bg.Manager_POS_Budget__c = 12;
		bg.Original_POS_Budget__c = 12;
    	insert bg;
    	
    	Budget_Detail__c bd = ClsTestHelp.createTestBudgetDetail();
    	bd.Account__c = acc.Id;
    	bd.Budget__c = bg.Id;
    	bd.Type__c = 'Total';
    	bd.Billings_LY__c = 11;
    	bd.Billings_CYTD__c = 11;
    	bd.Billings_CYRR__c = 11;
    	bd.Forecast_CY__c = 12;
    	insert bd;
   
   		CtrlManagerReview.BudgetReviewRecord ctrlBudget = new CtrlManagerReview.BudgetReviewRecord(bg,'CMA');
   		ctrlBudget.isChecked = true;
   		ctrlBudget.budget = bg;
   		ctrlBudget.budgetDetail = bd;
   		ctrlBudget.getGrowth();
   		
    	Test.startTest();
    	
    	CtrlManagerReview ctrl = new CtrlManagerReview();
    	ctrl.totalBudgetReviewRecord = ctrlBudget;
    	ctrl.view = 'Total';
    	
    	ctrl.buildManagerReviewRcords();
    	
    	system.assert(true);
    	Test.stopTest();
    }
	static testMethod void testMostMethods5() {
        RecordType rt = ClsTestHelp.createTestRecordType8();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.SALES_TERRITORY_CDE__c = 'A003153';
    	acc.Individually_Planned__c = true;
    	acc.Account_Manager__c = UserInfo.getUserId();
    	insert acc;
    	
    	Sales_Hierarchy__c sh = new Sales_Hierarchy__c();
    	sh.Level_7_Territory_Code__c = 'A007357';
    	insert sh;
    	
    	Budget__c bg = new Budget__c();
    	bg.Year__c = string.valueOf(date.today().year());
    	bg.Territory__c = sh.Id;
		bg.Total_Direct_Budget_TBR_NY__c = 11;
		bg.Total_Budget_TBR_NY__c = 12;
		bg.Stage__c = 'Original';
		bg.Manager__c = UserInfo.getUserId();
		bg.Manager_CMA_Budget__c = 12;
		bg.Manager_Direct_Budget__c = 12;
		bg.Manager_POS_Budget__c = 12;
		bg.Original_POS_Budget__c = 12;
    	insert bg;
    	
    	Budget_Detail__c bd = ClsTestHelp.createTestBudgetDetail();
    	bd.Account__c = acc.Id;
    	bd.Budget__c = bg.Id;
    	bd.Type__c = 'Total';
    	bd.Billings_LY__c = 11;
    	bd.Billings_CYTD__c = 11;
    	bd.Billings_CYRR__c = 11;
    	bd.Forecast_CY__c = 12;
    	insert bd;
   
   		CtrlManagerReview.BudgetReviewRecord ctrlBudget = new CtrlManagerReview.BudgetReviewRecord(bg,'CMA');
   		ctrlBudget.isChecked = true;
   		ctrlBudget.budget = bg;
   		ctrlBudget.budgetDetail = bd;
   		ctrlBudget.getGrowth();
   		
    	Test.startTest();
    	
    	CtrlManagerReview ctrl = new CtrlManagerReview();
    	ctrl.totalBudgetReviewRecord = ctrlBudget;
    	ctrl.view = 'Direct';
    	
    	ctrl.buildManagerReviewRcords();
    	
    	system.assert(true);
    	Test.stopTest();
    }
	static testMethod void testMostMethods6() {
        RecordType rt = ClsTestHelp.createTestRecordType8();
    	
    	Account acc = ClsTestHelp.createTestAccounts();
    	acc.RecordTypeId = rt.Id;
    	acc.SALES_TERRITORY_CDE__c = 'A003153';
    	acc.Individually_Planned__c = true;
    	acc.Account_Manager__c = UserInfo.getUserId();
    	insert acc;
    	
    	Sales_Hierarchy__c sh = new Sales_Hierarchy__c();
    	sh.Level_7_Territory_Code__c = 'A007357';
    	insert sh;
    	
    	Budget__c bg = new Budget__c();
    	bg.Year__c = string.valueOf(date.today().year());
    	bg.Territory__c = sh.Id;
		bg.Total_Direct_Budget_TBR_NY__c = 11;
		bg.Total_Budget_TBR_NY__c = 12;
		bg.Stage__c = 'Original';
		bg.Manager__c = UserInfo.getUserId();
		bg.Manager_CMA_Budget__c = 12;
		bg.Manager_Direct_Budget__c = 12;
		bg.Manager_POS_Budget__c = 12;
		bg.Original_POS_Budget__c = 12;
    	insert bg;
    	
    	Budget_Detail__c bd = ClsTestHelp.createTestBudgetDetail();
    	bd.Account__c = acc.Id;
    	bd.Budget__c = bg.Id;
    	bd.Type__c = 'Total';
    	bd.Billings_LY__c = 11;
    	bd.Billings_CYTD__c = 11;
    	bd.Billings_CYRR__c = 11;
    	bd.Forecast_CY__c = 12;
    	insert bd;
   
   		CtrlManagerReview.BudgetReviewRecord ctrlBudget = new CtrlManagerReview.BudgetReviewRecord(bg,'CMA');
   		ctrlBudget.isChecked = true;
   		ctrlBudget.budget = bg;
   		ctrlBudget.budgetDetail = bd;
   		ctrlBudget.getGrowth();
   		
    	Test.startTest();
    	
    	CtrlManagerReview ctrl = new CtrlManagerReview();
    	ctrl.totalBudgetReviewRecord = ctrlBudget;
    	ctrl.view = 'CMA';
    	
    	ctrl.buildManagerReviewRcords();
    	
    	system.assert(true);
    	Test.stopTest();
    }
}