objects/Consumer_Device_Opportunity_Record_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Consumer Device Opportunity Record Types</description>
    <fields>
        <fullName>Record_Type_Id__c</fullName>
        <label>Record_Type_Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Consumer Device Opportunity Record Types</label>
</CustomObject>

objects/Forecast_Snapshot__c.object
<CustomObject>
    <description>This custom object is used to snapshot opportunity and part forecasting values.</description>
    <fields>
        <fullName>BU_Profit_Center__c</fullName>
        <formula>Part__r.BU_profit_center__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU Profit Center</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Master-Detail Relationship to Opportunity.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Forecast Snapshots</relationshipLabel>
        <relationshipName>Forecast_Snapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup Relationship to Opportunity Part.</description>
        <label>Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipLabel>Forecast Snapshots</relationshipLabel>
        <relationshipName>Forecast_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot_Type__c</fullName>
        <description>This field shows out of which snapshot the record was created.</description>
        <label>Snapshot Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>FY13 final</fullName>
                </value>
                <value>
                    <fullName>FY14 Final</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>FY15 Final</fullName>
                </value>
                <value>
                    <fullName>FY 16 Final</fullName>
                </value>
                <value>
                    <fullName>FY17 Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Date__c</fullName>
        <description>This field contains the Won Date of the related Oppy Part.</description>
        <label>Won Date</label>
        <type>Date</type>
    </fields>
    <label>Forecast Snapshot</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Forecast Snapshot</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Snapshots</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Part</fullName>
        <active>true</active>
        <label>Part</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>BU_profit_center__c</fullName>
        <description>used to calculate the BU profit center which will receive the profit for the opportunity.</description>
        <label>BU profit center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Order_Date__c</fullName>
        <label>Initial Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Text__c</fullName>
        <label>Lost Reason Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Approval criteria not met</fullName>
                </value>
                <value>
                    <fullName>Awaiting customer response</fullName>
                </value>
                <value>
                    <fullName>Awaiting qualification test results</fullName>
                </value>
                <value>
                    <fullName>Customer Program Change/Cancellation</fullName>
                </value>
                <value>
                    <fullName>Customer project on hold</fullName>
                </value>
                <value>
                    <fullName>Customer request</fullName>
                </value>
                <value>
                    <fullName>Lack of TE resources</fullName>
                </value>
                <value>
                    <fullName>Missing customer requirements</fullName>
                </value>
                <value>
                    <fullName>Missing TE requirements</fullName>
                </value>
                <value>
                    <fullName>No potential customer</fullName>
                </value>
                <value>
                    <fullName>PAC decision</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project transfer to different region</fullName>
                </value>
                <value>
                    <fullName>Quote sent, awaiting customer</fullName>
                </value>
                <value>
                    <fullName>TE Engineering resources</fullName>
                </value>
                <value>
                    <fullName>TE portfolio / priority decision</fullName>
                </value>
                <value>
                    <fullName>TE technical solution not competitive</fullName>
                </value>
                <value>
                    <fullName>Timeline</fullName>
                </value>
                <value>
                    <fullName>Customer cancellation</fullName>
                </value>
                <value>
                    <fullName>Replaced by other project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Duplicate part number</fullName>
                </value>
                <value>
                    <fullName>Customer Strategy Change</fullName>
                </value>
                <value>
                    <fullName>Engineering Rejected</fullName>
                </value>
                <value>
                    <fullName>Service/Responsiveness</fullName>
                </value>
                <value>
                    <fullName>Won by other TE Customer</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Price and Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Confidence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>50/50</fullName>
                </value>
                <value>
                    <fullName>Likely</fullName>
                </value>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Date__c</fullName>
        <description>The field is used to store the date of won and production.</description>
        <label>Won Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>need_recalculate_PartNPSMSGRevenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>need recalculate PartNPSMSGRevenue</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <recordTypes>
        <fullName>Extension</fullName>
        <active>true</active>
        <label>Extension</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL old</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts (GPL)</relationshipLabel>
        <relationshipName>Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Cls_BatchRecalculateForecastSnap_Test.cls
@isTest(SeeAllData=false)
private class Cls_BatchRecalculateForecastSnap_Test
{
    static testmethod void Cls_BatchRecalculateForecastSnap_TM()
    {
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Record_Type_Groups();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getProfit_BU_Center_Mapping_Rule2();
        ID oRTid = (Id)Consumer_Device_Opportunity_Record_Types__c.getInstance('Engineering_Opportunity_CSD').Record_Type_Id__c;
        
        Opportunity oppy = new Opportunity(CloseDate = date.today().addDays(5), recordtypeid = oRTid, name = 'Pain of Queen2', StageName = 'New', Type = 'CM', Request_Type__c = 'Extension', Method__c = 'BOM', Level__c = 'Yearly', Amount = 1, Five_Year_Revenue__c = 1, Currency_Confirm__c = true);
        insert oppy;

        oppy.stageName = 'Production';
        oppy.Won_Date__c = date.today();
        update oppy;
        
        oppy.stageName = 'Won';
        oppy.Won_Date__c = date.today();
        update oppy;

        oppy.stageName = 'Won - Closed';
        update oppy;

        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial';
        insert ph;
          
        Part__c part = new Part__c();
        part.Description__c = 'Sniper1';
        part.Product_Hierarchy__c = ph.Id;
        insert part;
        
        Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
        oppypart.Opportunity__c = oppy.Id;
        oppypart.Part__c = part.Id;
        oppypart.Status__c = 'Won';
        oppypart.Lost_Reason__c = 'Other';
        oppypart.Lost_Reason_Text__c = null;
        oppypart.GPL__c = ph.Id;
        oppypart.Initial_Order_Date__c = date.today();
        oppypart.need_recalculate_PartNPSMSGRevenue__c = true;
        oppypart.BU_profit_center__c = 'Appliances';
        insert oppypart;
        
        Forecast_Snapshot__c oFS = new Forecast_Snapshot__c(Snapshot_Type__c = 'Monthly', Opportunity__c = oppy.Id, Part__c = oppypart.ID);
        //Forecast_Snapshot__c oFS2 = new Forecast_Snapshot__c(Snapshot_Type__c = 'Won', Opportunity__c = oppy.Id, Part__c = oppypart.ID);
        insert new list<Forecast_Snapshot__c>{oFS};
        
        map<Id, DateTime> map_oppyId_wonDate = new map<Id, DateTime>{oppy.ID => date.today()};
        test.starttest();   
        
            Cls_BatchRecalculateForecastSnapshot_Won o = new Cls_BatchRecalculateForecastSnapshot_Won();
            database.executebatch(o);
            Database.BatchableContext BC;
            o.execute(BC, new list<opportunity>{oppy});    
            Cls_BatchRecalculateForecastSnapshot_Won.cloneMonthlySnapshot(new list<Forecast_Snapshot__c>{ofS}, map_oppyId_wonDate , DateTime.now(), '', new set<Id>());
        
        test.stoptest();
        
    }
}