objects/Customer_Focus_Team_Member__c.object
<CustomObject>
    <description>Object used to Organize Users into Customer Focus Teams (Teams specific to Large A&amp;B Customers) for DataComm and Industrial GIBUs.</description>
    <fields>
        <fullName>Global_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Global Account</label>
        <referenceTo>Global_Account__c</referenceTo>
        <relationshipLabel>Customer Focus Team Members</relationshipLabel>
        <relationshipName>Customer_Focus_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Text( Salesforce_User_Name__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Manager (AM)</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Distribution Application Engineer (DAE)</fullName>
                </value>
                <value>
                    <fullName>Distribution Market Manager (DMM)</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Executive</fullName>
                </value>
                <value>
                    <fullName>Field Engineer (FE)</fullName>
                </value>
                <value>
                    <fullName>Global Account Manager (GAM)</fullName>
                </value>
                <value>
                    <fullName>Industry Development</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Product Management</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Sales Engineer (SE)</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Core Team Leader (CTL)</fullName>
                </value>
                <value>
                    <fullName>Relay Field Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TE_Network_ID__c</fullName>
        <formula>Salesforce_User_Name__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TE Network ID</label>
        <type>Text</type>
    </fields>
    <label>Customer Focus Team Member</label>
    <nameField>
        <displayFormat>CFTID-{00000}</displayFormat>
        <label>ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Focus Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Global_Account__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Global Customer Description.</description>
        <inlineHelpText>Description of the Global Customer.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GAM_Name__c</fullName>
        <label>GAM Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GIBU__c</fullName>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>DataComm</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Lighting</fullName>
                </value>
                <value>
                    <fullName>Solar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Global Account</label>
    <nameField>
        <label>Global Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <description>Object used by Channel GIBU to group accounts, opportunities, contacts, and user sales teams into logical groupings. One Region can have many Markets can have many accounts, opportunities, contacts, and users on the sales team.</description>
    <fields>
        <fullName>GIBU__c</fullName>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Solar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>East Region</fullName>
                </value>
                <value>
                    <fullName>Central Region</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>West Region</fullName>
                </value>
                <value>
                    <fullName>Undetermined</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Partner_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click the magnifying glass to look up an account.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Roles</relationshipLabel>
        <relationshipName>Partner_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>Click the magnifying glass to look up an Opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partner Roles</relationshipLabel>
        <relationshipName>Partner_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>CM</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Partner Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Hierarchy__c.object
<CustomObject>
    <description>Reflects the Sales Hierarchy.</description>
    <fields>
        <fullName>Level_6_Assigned_User_Network_Ids__c</fullName>
        <description>List of TE Network Ids for users assigned to this hierarchy level on this territory.</description>
        <inlineHelpText>i.e: US012345;US056789;US010000... etc.</inlineHelpText>
        <label>Level 6 Assigned User Network Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level_7_Assigned_User_Network_Ids__c</fullName>
        <description>List of TE Network Ids for users assigned to this hierarchy level on this territory.</description>
        <inlineHelpText>i.e: US012345;US056789;US010000... etc.</inlineHelpText>
        <label>Level 7 Assigned User Network Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Level 7 territory code</inlineHelpText>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sales Hierarchy</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Team__c.object
<CustomObject>
    <description>Object used to Organize Users into Sales Teams (Teams specific to Markets) for Channel GIBU.</description>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Sales Team</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <displayFormat>ST-{0000000}</displayFormat>
        <label>Team Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>GIBU__c</fullName>
        <description>Used to help with tallying license counts and things like that.</description>
        <inlineHelpText>Select the GIBU/BU this user is from.</inlineHelpText>
        <label>GIBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD&amp;M</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Application Tooling</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Channel</fullName>
                </value>
                <value>
                    <fullName>Circuit Protection</fullName>
                </value>
                <value>
                    <fullName>Consumer Devices</fullName>
                </value>
                <value>
                    <fullName>Data &amp; Devices</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>GATD</fullName>
                </value>
                <value>
                    <fullName>ICT (Ind Comm Transport)</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PIC</fullName>
                </value>
                <value>
                    <fullName>Sensors</fullName>
                </value>
                <value>
                    <fullName>TEIS</fullName>
                </value>
                <value>
                    <fullName>TEIS Engineering Portfolio Mgmt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#0B6FCE</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>India</fullName>
                    <color>#E27001</color>
                    <label>India</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                    <color>#419249</color>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>China</fullName>
                    <color>#00CCCC</color>
                    <label>China</label>
                </value>
                <value>
                    <fullName>Japan</fullName>
                    <color>#CC0000</color>
                    <label>Japan</label>
                </value>
                <value>
                    <fullName>Asia Pacific</fullName>
                    <color>#641CCF</color>
                    <label>Asia Pacific</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <color>#AFCADF</color>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Te_Network_Id__c</fullName>
        <description>This field contains the users TE Network Id.</description>
        <label>Te Network Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CPMTestFactory.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CPMTestFactory 
{
    // Test the Global Account Trigger
  private static id CreateGlobalAccount() 
  {
    // create a new global account
    Global_Account__c ga;
    ga = new Global_Account__c();
    ga.Description__c = 'Test Description';
    ga.Name = 'Test GA';
    ga.GAM_Name__c = 'GAM Name';
    insert ga;
    return ga.id;
  }
  
  private static id CreateMarket() 
  {
    // create a new global account
    Market__c mkt = new Market__c();
    mkt.Name = 'Test Market';
    mkt.Region__c = 'Mexico';
    insert mkt;
    return mkt.id;
  }  
  
  static testMethod void TestUserUpdate()
  {
    CreateTestUser();
  }
  
  private static User u;
  private static User CreateTestUser()
  {
    if (u != null)
      return u;
     
    u = new User();
    u.FirstName = 'John';
    u.LastName = 'Doe';
    u.Email = 'John.Doe@te.com';
    u.GIBU__c = 'Industrial';
    u.Username = 'john.doe@te.com.cis';
    u.Alias = 'JDAlias';
    u.CommunityNickname = 'JohnDoe';
    u.EmailEncodingKey='ISO-8859-1';
    u.TimeZoneSidKey = 'America/New_York';
    u.LanguageLocaleKey='en_US';
    u.ProfileId=GetStandardUserProfileId();
    u.LocaleSidKey='en_US';
    u.EmployeeNumber = 'US099999'; 
    u.TE_Network_Id__c = 'US099999';       
    insert u;
    return u;
  }
   
  private static id GetStandardUserProfileId()
  {
    List<Profile> pl = new List<Profile>([select id, name from profile where name='Channel Standard User']);
    if (pl.size() > 0)
     return pl[0].id;
    else
     return null;
  }
  private static Id CreateAccount(Id GlobalAcctId)
  {
    Account a;
    a = ClsTestHelp.createTestAccounts();
    a.Name = 'Test Account';
    a.AnnualRevenue         = 2000000.11; 
  a.Legally_Restricted__c = false;  
  
  a.BillingCity          = 'Shanghai';  
  a.BillingCountry       = 'China';
  a.BillingState         = '000000';
  a.BillingStreet        = 'Changning';
  a.BillingPostalCode    = '200051';
    a.Global_Account__c = GlobalAcctId;
    insert a;
    return a.id;
  }
  
  static testMethod void TestAccountUpdate()
  {
    
  // First create a Global Account
    Id gaId = CreateGlobalAccount();
    //CreateAccount(gaId);
  }
  
  private static Opportunity CreateTestOppty(Id acctId)
  {
    RecordType rt2 = ClsTestHelp.createTestRecordType9();
    Opportunity opp = new Opportunity();
    opp.Name = 'Test Oppty';
    opp.AccountId = acctId;
    opp.currency_confirm__c= true;
    opp.CloseDate = Date.today() + 365;
    opp.StageName = 'Approved/Active';
    opp.RecordTypeId = rt2.Id;
    
    insert opp;
    return opp;
  }
  
  static testMethod void TestOpptyUpdate()
  {
    //CreateTestOppty(CreateAccount(CreateGlobalAccount()));
   // CreateTestOppty(CreateAccount(null)); added by di chen 2012/6/4
  }
  
  static testMethod void TestContactUpdate()
  {
    Id acctId = CreateAccount(CreateGlobalAccount());
    Contact c;
    c = new Contact();
    c.FirstName = 'Test';
    c.LastName = 'Contact';
    c.AccountId = acctId;
    insert c;   

        /*List<Global_Account__c> gams = new List<Global_Account__c>();  

        for(integer i = 0; i<1000; i++)
        {  
            gams.add(new Global_Account__c(Name = 'test gam ' + i));  
        } 
        
        insert gams;

        List<Account> accts = new List<Account>(); 
    
        for(integer j = 0; j<1000; j++)
        {  
            accts.add(new Account(Name = 'test account ' + j, Global_Account__c = gams.get(j).Id));  
        }
        
        insert accts;  

        List<Contact> contacts = new List<Contact>();
        
        Test.startTest();
        
        for(integer x = 0; x<1000; x++)
        {
            contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact ' + x, AccountId = accts.get(x).Id));              
        }
    
        insert contacts;
        
        Test.stopTest(); */
  }
  
  static testMethod void TestPartnerRoleUpdate()
  {
    Id OpptyID = CreateTestOppty(CreateAccount(CreateGlobalAccount())).id;
    Id AcctId;
    
    Account a;
    a = ClsTestHelp.createTestAccounts();
    User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
    System.runAs ( thisUser ) 
    {
    
        a.Name = 'Second Test Account';
        a.OwnerId = CreateTestUser().Id;
        a.BillingCity            = 'Shanghai';  
        a.BillingCountry         = 'China';
        a.BillingState           = '000000';
        a.BillingStreet          = 'Changning';
        a.BillingPostalCode      = '200051';
        insert a;
        
        Partner_Role__c pr = new Partner_Role__c();
        pr.Account__c = a.id;
        pr.Opportunity__c = OpptyId;
        system.debug('**** inserting pr');
        insert pr;
    }
  }
  
  static testMethod void TestSalesHierarchyUpdate()
  { 
    CreateTestUser();
    System.runAs ( u ) 
    {
        Sales_Hierarchy__c sh;
        sh = new Sales_Hierarchy__c();
        sh.Level_7_Territory_Code__c = 'Test';
        sh.Level_7_Assigned_User_Network_Ids__c = 'US099999';
        sh.Level_6_Assigned_User_Network_Ids__c = 'US099999';
        sh.Level_5_Assigned_User_Network_Ids__c = 'US099999';
        sh.Level_4_Assigned_User_Network_Ids__c = 'US099999';
        sh.Level_3_Assigned_User_Network_Ids__c = 'US099999';
        sh.Level_2_Assigned_User_Network_Ids__c = 'US099999';
        sh.Level_1_Assigned_User_Network_Ids__c = 'US099999';
        insert sh;
    }
  }
/*  
  static testMethod void TestCFTMemberUpdate()
  {
    CreateTestUser();
    User thisUser = [ select Id, EmployeeNumber from User where Id = :UserInfo.getUserId() ];   
    System.runAs ( u ) 
    {           
        Account a = new Account();
        a.Name = 'Test Account';
        a.Global_Account__c = CreateGlobalAccount();
        a.AnnualRevenue         = 2000000.11; 
        a.Legally_Restricted__c = false;   
        a.BillingCity            = 'Shanghai';  
        a.BillingCountry         = 'China';
        a.BillingState           = '000000';
        a.BillingStreet          = 'Changning';
        a.BillingPostalCode  = '200051';
        a.OwnerId = u.Id;
        insert a;

        Customer_Focus_Team_Member__c newMember;
        newMember = new Customer_Focus_Team_Member__c();
        //newMember.Name = 'John Doe';
       // newMember.Global_Account__c = a.Global_Account__c;
        //newMember.TE_Network_User_Id__c = u.EmployeeNumber;
       // insert newMember;
        
        newMember.Salesforce_User_Name__c = thisUser.Id;
        update newMember;
        newMember.Role__c = 'Quality';
        update newMember;
        
        //test cft member transfer on switching global account on account (account trigger)
        Customer_Focus_Team_Member__c anotherMember = new Customer_Focus_Team_Member__c();
        anotherMember.Global_Account__c = CreateGlobalAccount();
        anotherMember.TE_Network_User_Id__c = u.EmployeeNumber;
        insert anotherMember;
        
        a.Global_Account__c = anotherMember.Global_Account__c;
        update a;
        
        delete newMember;       
    }
  }
  */
  static testMethod void TestSalesTeamUpdate()
  {
    CreateTestUser();
    //User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];  
        Profile p = [Select Id, Name From Profile 
                                    where Name ='System Administrator' 
                                    or Name ='Systemadministrator' limit 1];
        User u2 = ClsTestHelp.createTestUsers();
        u2.Email = 'Liodfen@testCompany999.com';
        u2.Alias = 'SsF';
        u2.ProfileId = p.Id;
        u2.CommunityNickname = 'QPS15';
        u2.IsActive = true;
        insert u2;     
    System.runAs ( u2 ) 
    {           
        Account a = ClsTestHelp.createTestAccounts();
        a.Name = 'Test Account';
        a.Channel_Market__c = CreateMarket();
        a.OwnerId = u2.Id;
        insert a;
        system.debug('***** - ' + a);

        Sales_Team__c newMember;
        newMember = new Sales_Team__c();
        //newMember.Name = 'John Doe';
        newMember.Market__c = a.Channel_Market__c;
        newMember.Team_Member__c = u2.Id;
        insert newMember;
        
        newMember.Team_Member__c = u2.Id;
        update newMember;
        newMember.Team_Role__c = 'Distribution Market Manager (DMM)';
        update newMember;
        
        //test sales team member transfer on markets on account on account (account trigger)
        Sales_Team__c anotherMember = new Sales_Team__c();
        anotherMember.Market__c = CreateMarket();
        anotherMember.Team_Member__c = u2.Id;
        insert anotherMember;
        
        a.Channel_Market__c = anotherMember.Market__c;
        update a;
        
        delete newMember;       
    }
  }  
  
  static testMethod void TestEmailSend()
  {
    List<string> pToAddresses = new List<string>();
    pToAddresses.add('rob.dress@te.com');
    List<string> pCcAddresses = new List<string>();
    pCcAddresses.add('rob.dress@te.com');
    List<string> pBccAddresses = new List<string>();
    pBccAddresses.add('rob.dress@te.com');
    //SalesforceUtils.SendEmail(pToAddresses, pCcAddresses, pBccAddresses, 'TEst Subject', 'Test SenderName', 'testReplyTo@te.com', 'This is a test email.');
    //SalesforceUtils.SendEmail('rob.dress@te.com', 'testsubject', 'testbody');   
  }
  
  static testMethod void TestMisc()
  {
    OrgWideSettings__c cfgObj= SalesforceUtils.OrgSettings;
  }
 
   private static id GetChannelOppRecTypeId()
  {
    List<RecordType> rt = new List<RecordType>([select id, name from recordtype where name='Channel_Opportunity']);
    if (rt.size() > 0)
     return rt[0].id;
    else
     return null;
  }   
}