objects/Energy_Price_Book_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Energy Price Book Entry</relationshipLabel>
        <relationshipName>Energy_Price_Book_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Energy Price Book Entry</label>
    <nameField>
        <label>Energy Price Book Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Energy Price Book Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EnergyPriceBookEntryTriggerHandlerTest.cls
/**
 * Test class for EnergyPriceBookEntryTriggerHandler.
 * 
 * @author      Tangyong Li
 * @created     2017-10-25
 * @since       38.0 (Force.com ApiVersion)
 * @version     1.0
 * 
 * @changelog
 * 2017-10-25   Tangyong Li <tangyong.li@capgemini.com>
 * - Created
 */
@isTest
public class EnergyPriceBookEntryTriggerHandlerTest {
    
    static testMethod void mtUnitTest() {
        User u = ClsTestHelp.createTestUsers();
        insert u;
        System.runAs(u) {
        	Product_Hierarchy__c p = new Product_Hierarchy__c();
        	insert p;
        	
        	Part__c part = new Part__c();
        	part.Name = 'test';
        	part.Product_Hierarchy__c = p.Id;
        	insert part;
        	
        	Test.startTest();
        	Energy_Price_Book_Entry__c epbe = new Energy_Price_Book_Entry__c();
        	epbe.Name = 'test';
        	insert epbe;
        	
        	epbe = [SELECT Id, Part__c FROM Energy_Price_Book_Entry__c WHERE Id =: epbe.Id limit 1];
        	Test.stopTest();
        }
    }
    
}