objects/ErrorLog__c.object
<CustomObject>
    <description>Custom Exception Object to store the exception log. This object is part of generalized exception handling framework.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Name of the Web Service class, Broker Class, Batch Class, Schedule class, Trigger</description>
        <label>Class</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Category__c</fullName>
        <label>Error Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AsyncException</fullName>
                </value>
                <value>
                    <fullName>CalloutException</fullName>
                </value>
                <value>
                    <fullName>DmlException</fullName>
                </value>
                <value>
                    <fullName>EmailException</fullName>
                </value>
                <value>
                    <fullName>InvalidParameterValueException</fullName>
                </value>
                <value>
                    <fullName>ListException</fullName>
                </value>
                <value>
                    <fullName>MathException</fullName>
                </value>
                <value>
                    <fullName>NoAccessException</fullName>
                </value>
                <value>
                    <fullName>NoDataFoundException</fullName>
                </value>
                <value>
                    <fullName>NoSuchElementException</fullName>
                </value>
                <value>
                    <fullName>NullPointerException</fullName>
                </value>
                <value>
                    <fullName>QueryException</fullName>
                </value>
                <value>
                    <fullName>RequiredFeatureMissing</fullName>
                </value>
                <value>
                    <fullName>SearchException</fullName>
                </value>
                <value>
                    <fullName>SecurityException</fullName>
                </value>
                <value>
                    <fullName>SerializationException</fullName>
                </value>
                <value>
                    <fullName>SObjectException</fullName>
                </value>
                <value>
                    <fullName>StringException</fullName>
                </value>
                <value>
                    <fullName>TypeException</fullName>
                </value>
                <value>
                    <fullName>VisualforceException</fullName>
                </value>
                <value>
                    <fullName>XmlException</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <description>Capture Error Code from Web Service or any class</description>
        <label>Error Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>All iterative information / unit information is captured here</description>
        <label>Error Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Source__c</fullName>
        <label>Error Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <label>Error Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Time__c</fullName>
        <label>Log Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Record_Id__c</fullName>
        <label>SFDC Record Id</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Org_Info__c</fullName>
        <description>Salesforce Org name and Id</description>
        <label>SF Org Info</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>Range of values - 1 to 5. Default value will be 5 for API</description>
        <label>Severity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <description>It is used for identifying web service call out</description>
        <label>Transaction Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>Name of user receiving the error</description>
        <label>User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ErrorLog</label>
    <nameField>
        <displayFormat>ERR-{000000000}</displayFormat>
        <label>Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ErrorLogging.cls
public class ErrorLogging 
{
    
  public static void Log(Exception ex, string ClassName, string MethodName, string RecordId)
  {
    if (SalesforceUtils.OrgSettings.Enable_Error_Logging__c)
    {  
        ErrorLog__c newErrorObj = CreateLogObj(ex);
        newErrorObj.Class__c          = ClassName;
        newErrorObj.Method_Name__c    = MethodName;
        newErrorObj.SFDC_Record_Id__c = RecordId;
        newErrorObj.Error_Code__c     = '';
        newErrorObj.Error_Source__c   = '';
        newErrorObj.Service_Name__c   = '';
        newErrorObj.Severity__c       = '';
        newErrorObj.Transaction_Id__c = '';
      
        LogError(newErrorObj);
    } 
  }
 
  public static void Log(Exception ex)
  {
    if (SalesforceUtils.OrgSettings.Enable_Error_Logging__c)
      LogError(CreateLogObj(ex));   
  }
  
  /*************  Private Methods *********************************/
  private static ErrorLog__c CreateLogObj(Exception ex)
  {
    ErrorLog__c newErrorObj = new ErrorLog__c();
    newErrorObj.Error_Message__c = ex.getMessage();
    if (newErrorObj.Error_Message__c.length() > 32000)
      newErrorObj.Error_Message__c = newErrorObj.Error_Message__c.substring(0, 32000);
    newErrorObj.Error_Type__c = ex.getTypeName();
    newErrorObj.Log_Time__c = Datetime.now();
    newErrorObj.SF_Org_Info__c = UserInfo.getOrganizationId() + ' - ' + UserInfo.getOrganizationName();
    newErrorObj.User_Name__c = UserInfo.getUserName();
    newErrorObj.Error_Category__c = ex.getTypeName();
    newErrorObj.Line_Number__c = ex.getLineNumber() + '';
    newErrorObj.Stack_Trace__c = ex.getStackTraceString();
    
    return newErrorObj;
  }
  
  private static void LogError(ErrorLog__c newErrorLog)
  {
    Database.insert(newErrorLog);
    
    if (SalesforceUtils.OrgSettings.Send_Exception_Email__c)
    {
        // Now send the email
        string emailContent = '';
        emailContent += '<HTML><HEAD><TITLE>Salesforce Exception</TITLE><style>BODY,TD {font-family: Verdana;font-size:smaller;}</style></HEAD><BODY><TABLE border = "1" rules="rows" cellspacing = "0" cellpadding = "2">';
        
        emailContent += '<TR><TD><B>Salesforce Instance:</B></TD><TD>' + newErrorLog.SF_Org_Info__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Date/Time:</B></TD><TD>' + newErrorLog.Log_Time__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Severity:</B></TD><TD>' + SalesforceUtils.replaceNullStringWithEmpty(newErrorLog.Severity__c) + '</TD></TR>';
        emailContent += '<TR><TD><B>Type:</B></TD><TD>' + newErrorLog.Error_Type__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Category:</B></TD><TD>' + newErrorLog.Error_Category__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Apex Class:</B></TD><TD>' + newErrorLog.Class__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Method:</B></TD><TD>' + newErrorLog.Method_Name__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Line Number:</B></TD><TD>' + newErrorLog.Line_Number__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Message:</B></TD><TD>' + newErrorLog.Error_Message__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Source:</B></TD><TD>' + SalesforceUtils.replaceNullStringWithEmpty(newErrorLog.Error_Source__c) + '</TD></TR>';
        emailContent += '<TR><TD><B>Code:</B></TD><TD>' + SalesforceUtils.replaceNullStringWithEmpty(newErrorLog.Error_Code__c) + '</TD></TR>';
        emailContent += '<TR><TD><B>Service:</B></TD><TD>' + SalesforceUtils.replaceNullStringWithEmpty(newErrorLog.Service_Name__c) + '</TD></TR>';
        emailContent += '<TR><TD><B>Record Id:</B></TD><TD>' + SalesforceUtils.replaceNullStringWithEmpty(newErrorLog.SFDC_Record_Id__c) + '</TD></TR>';
        emailContent += '<TR><TD><B>Transaction Id:</B></TD><TD>' + SalesforceUtils.replaceNullStringWithEmpty(newErrorLog.Transaction_Id__c) + '</TD></TR>';
        emailContent += '<TR><TD><B>User:</B></TD><TD>' + newErrorLog.User_Name__c + '</TD></TR>';
        emailContent += '<TR><TD><B>Stack Trace:</B></TD><TD>' + newErrorLog.Stack_Trace__c + '</TD></TR>';
        
        emailContent += '</TABLE></BODY></HTML>';
        System.debug(emailContent);
        
        //SalesforceUtils.SendEmail(SalesforceUtils.OrgSettings.Error_Email_Recipients__c, 'Salesforce Exception', emailContent);
    } 
  }
}