objects/Global_Account__c.object
<CustomObject>
    <fields>
        <fullName>Pricebook_Id__c</fullName>
        <description>Salesforce Id of the Pricebook2 object for this Global Account</description>
        <label>Pricebook Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Global Account</label>
    <nameField>
        <label>Global Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <description>Object used by Channel GIBU to group accounts, opportunities, contacts, and user sales teams into logical groupings. One Region can have many Markets can have many accounts, opportunities, contacts, and users on the sales team.</description>
    <fields>
        <fullName>Pricebook_Id__c</fullName>
        <description>Salesforce Id of pricebook associated with this market</description>
        <inlineHelpText>Should be automatically created and populated by a trigger</inlineHelpText>
        <label>Pricebook Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PricebookUtils.cls
public without sharing class PricebookUtils 
{
  public static Map<Id, Account> GetPricebooksForAccounts(List<Id> accountIds)
  {
	  Map<Id, Account> results;
	  try
	  {
	   results = new Map<Id, Account> (
	    [SELECT id, global_account__c, global_account__r.Pricebook_Id__c
	     FROM account 
	     WHERE id in :accountIds]);
	  } 
	  catch (Exception ex)
	  {
	   System.debug('Exception in GetPricebooksForAccounts() : ' + ex.getMessage());
     ErrorLogging.Log(ex, 'PricebookUtils', 'GetPricebooksForAccounts', null);
	   results =  null;
	  } 
	  
	  return results;      	
  }
  
  public static Map<Id, Market__c> GetPricebooksForMarkets(List<Id> marketIds)
  {
	  Map<Id, Market__c> results;
	  try
	  {
	   results = new Map<Id, Market__c> (
	    [SELECT id, Pricebook_Id__c
	     FROM Market__c 
	     WHERE id in :marketIds]);
	  } 
	  catch (Exception ex)
	  {
	   System.debug('Exception in GetPricebooksForMarkets() : ' + ex.getMessage());
     ErrorLogging.Log(ex, 'PricebookUtils', 'GetPricebooksForMarkets', null);
	   results =  null;
	  } 
	  
	  return results;      	
  }  
  
  public static Id GetStandardPriceBookId()
  {
    Id results;
    try
    {
     results = 
      [SELECT id 
       FROM Pricebook2 
       WHERE IsActive=true 
            AND IsStandard = true][0].Id;
    } 
    catch (Exception ex)
    {
     System.debug('Exception in GetStandardPriceBookId() : ' + ex.getMessage());
     ErrorLogging.Log(ex, 'PricebookUtils', 'GetStandardPriceBookId', null);
     results =  null;
    } 
    
    return results;       
  }
}