objects/INFRA__Account_Forecast__c.object
<CustomObject>
    <description>Object to store Account Exception forecast published through JDA connector</description>
    <fields>
        <fullName>INFRA__Business_Unit__c</fullName>
        <description>BU identifier for which the forecast data is created. The value in this field should have the corresponding configuration in custom settings &quot;JDA Connector Config&quot;.</description>
        <inlineHelpText>Business Unit Abbreviation that is required by JDA bridge.</inlineHelpText>
        <label>Business Unit</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Forecast</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forecast #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INFRA__Part_Forecast__c.object
<CustomObject>
    <description>Object to store Part Forecast data that needs to be published to JDA Bridge. Data in this object will be populated by BU Forecasting Tool. This object will be part of the INFRA framework</description>
    <fields>
        <fullName>INFRA__Business_Unit__c</fullName>
        <description>BU identifier for which the forecast data is created. The value in this field should have the corresponding configuration in custom settings &quot;JDA Connector Config&quot;.</description>
        <inlineHelpText>Business Unit Abbreviation that is required by JDA bridge.</inlineHelpText>
        <label>Business Unit</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Part Forecast</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Forecast #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/INFRA_JDA_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>General settings for INFRA JDA batch classes</description>
    <fields>
        <fullName>N_th_Day_of_Fiscal_Month__c</fullName>
        <inlineHelpText>Give the exact (N)th day on which the batch class should run.</inlineHelpText>
        <label>(N)th Day of Fiscal Month</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>INFRA JDA Settings</label>
</CustomObject>

classes/Cls_SchedularDNDJDASchedular.cls
/***********************************************************************************************************************
      Name : Cls_SchedularDNDJDASchedular
       Org : C2S
 Copyright : © 2014 TE Connectivity 
========================================================================================================================
   Summary : This is a schedular for the Batch Cls_BatchDNDJDAPartForecast.
========================================================================================================================
 REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                           
________________________________________________________________________________________________________________________
 VERSION AUTHOR       DATE       DETAIL               User Story #                  
________________________________________________________________________________________________________________________
     1.0 Prabhanjan   08/13/2015 Initial Development                   
***********************************************************************************************************************/
global class Cls_SchedularDNDJDASchedular implements Schedulable{
    global void execute(SchedulableContext SC){
        
        /* Prabhanjan 14-Jun-16 Case:00901003  Commenting previous logic
         
        INFRA_JDA_Settings__c vConfig = INFRA_JDA_Settings__c.getValues('DND');
        Period vPeriod = [SELECT StartDate, EndDate 
                            FROM Period 
                           WHERE Type = 'Month' 
                             AND StartDate <= TODAY 
                             AND EndDate >= TODAY];
                             
        Date vFisaclStartDate = vPeriod.StartDate;
        system.debug(Date.Today());
        system.debug(vFisaclStartDate);
        system.debug(vConfig);
        system.debug(vConfig.N_th_Day_of_Fiscal_Month__c);
        
        system.debug(Integer.valueOf(vConfig.N_th_Day_of_Fiscal_Month__c-1));
        system.debug(vFisaclStartDate.addDays(Integer.valueOf(vConfig.N_th_Day_of_Fiscal_Month__c-1))); 
        system.debug(Test.isRunningTest());
        //
       // if(Date.Today() == vFisaclStartDate.addDays(Integer.valueOf(vConfig.N_th_Day_of_Fiscal_Month__c-1)) || Test.isRunningTest()){
       if(Test.isRunningTest()){
            //DELETE EXISTING RECORDS
             
            List<INFRA__Part_Forecast__c> vListINFRAPart = [SELECT Id FROM INFRA__Part_Forecast__c where INFRA__Business_Unit__c = 'DND' LIMIT 9999];
            List<INFRA__Account_Forecast__c> vListINFRAAccount = [SELECT Id FROM INFRA__Account_Forecast__c where INFRA__Business_Unit__c = 'DND' LIMIT 9999];
            
            if(!vListINFRAPart.isEmpty()){                DELETE vListINFRAPart;            }
            if(!vListINFRAAccount.isEmpty()){                DELETE vListINFRAAccount;            }
             
            //Commented by Sandeep
            //CREATE AN CONVERSION RATES MAP
            List<CurrencyType> currencyTypeList = [select IsoCode, ConversionRate from CurrencyType];
            Map<String, Decimal> vConversionMap = new Map<String, Decimal>();
            for(CurrencyType vTempCurrency : currencyTypeList){
                vConversionMap.put(vTempCurrency.IsoCode, vTempCurrency.ConversionRate);
            }*/
            //CALL THE PART FORECAST BATCH CLASS
        //}
        Cls_BatchDNDJDAPartForecast vBatch = new Cls_BatchDNDJDAPartForecast();
        Id batchInstanceId = Database.executeBatch(vBatch, 1000);  
        
    }   
}