objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ACTIVITY_NOTES__c</fullName>
        <description>from central org</description>
        <label>ACTIVITY NOTES</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Communities_Distributor__c</fullName>
        <inlineHelpText>Name of the distributor that has been assigned to the MQL, either manually or through automation. Can include distributors that are not on the partner community.</inlineHelpText>
        <label>Assigned Distributor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arrow</fullName>
                </value>
                <value>
                    <fullName>Avnet</fullName>
                </value>
                <value>
                    <fullName>Element14</fullName>
                </value>
                <value>
                    <fullName>Farnell E14</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>Heilind</fullName>
                </value>
                <value>
                    <fullName>Mapro</fullName>
                </value>
                <value>
                    <fullName>Newark</fullName>
                </value>
                <value>
                    <fullName>TTI</fullName>
                </value>
                <value>
                    <fullName>RS Components</fullName>
                </value>
                <value>
                    <fullName>Global Electronics Corp</fullName>
                </value>
                <value>
                    <fullName>Kanetsu</fullName>
                </value>
                <value>
                    <fullName>Kyoritsu Dengyo</fullName>
                </value>
                <value>
                    <fullName>Nihon Denka Kogyosyo</fullName>
                </value>
                <value>
                    <fullName>Suzuden</fullName>
                </value>
                <value>
                    <fullName>Takagi Shokai</fullName>
                </value>
                <value>
                    <fullName>Chip One Stop Inc</fullName>
                </value>
                <value>
                    <fullName>Compel International Oy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Distributor_Comments__c</fullName>
        <inlineHelpText>CONVERT:Project name, Project life-yrs, Distributor Salesperson Name &amp; Phone #,Initial Order &amp; Mfg start date,TE Part Numbers,Annual quantities,Target pricing,Region of Design,Mfg &amp; sales, TE Part Nos,Competitive info, Actions required to WIN</inlineHelpText>
        <label>Distributor Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributor_Response__c</fullName>
        <label>Distributor Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Distributor Response</fullName>
                </value>
                <value>
                    <fullName>Convert to opportunity</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROLE__c</fullName>
        <description>central org</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Engineer/Developer</fullName>
                </value>
                <value>
                    <fullName>Purchaser</fullName>
                </value>
                <value>
                    <fullName>Product Manager</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Component Engineer</fullName>
                </value>
                <value>
                    <fullName>Design Engineer</fullName>
                </value>
                <value>
                    <fullName>Distributor - Purchasing</fullName>
                </value>
                <value>
                    <fullName>Distributor - Sales</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Inventory Control</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SUGGESTED_SE__c</fullName>
        <label>SUGGESTED SE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LeadEditDetailController_Test.cls
@isTest(SeeAllData=true)
Public class LeadEditDetailController_Test{
static Lead led;
Static User testUser;

 static testMethod void testData_forEdit() {
 
  Profile p = [select id from profile where name='System Administrator'];
         testUser = new User(alias = 'u1', email='u1@testorg.com', emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
         localesidkey='en_US', profileid = p.Id, country='United States',timezonesidkey='America/Los_Angeles', username='wewew23232323232drex@gmail.com');
         insert testUser;         

led = new Lead();
        led.LastName= 'Test Lead';
        led.Company = 'Test Company';
        led.Status ='Passed to Distributor';
         led.Communities_Distributor__c ='Future Electronics';
         led.Phone= '23456';
         led.FirstName ='Test';
         led.Email = 'test.test@ymail.com';
         led.OwnerId = testUser.id;
         led.title ='Mr';
         led.ROLE__c='Other';
         led.MobilePhone = '123456789';
         led.Distributor_Response__c = 'Dead';
         led.Street = 'Acd';
         led.City = 'asd';
         led.State = 'aww';
         led.PostalCode = '2322';
         led.Country = 'acdd';
         led.website = 'ww.te.com';
         led.Distributor_Comments__c = 'test';
         led.ACTIVITY_NOTES__c = 'test' ;
         led.Description = 'test';
         led.SUGGESTED_SE__c = 'test';
         
         
        insert led;
        }
        
        static testMethod void UnitTestMethod() {
        testData_forEdit();
        PageReference ref = Page.DistributorLeadEditView; 
           Test.setCurrentPageReference(ref);
           ApexPages.StandardController stdController = new ApexPages.StandardController( led );             
           ApexPages.currentpage().getParameters().put('id',led.id); // set record(lead) id to vf page
           
           // Added by Anil inorder to cover Pdf Functionality
           ApexPages.currentpage().getParameters().put('pdf','true');
           ApexPages.currentpage().getParameters().put('force_download','true');
           ApexPages.currentpage().getParameters().put('filename','MyLeadDetail');
           
           LeadEditDetailController  cmc = new LeadEditDetailController (stdController);
                      
           cmc.SaveEdit();  
           cmc.editTo();
        
       
    }



}