objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CUSTOMER_CONTACTED__c</fullName>
        <defaultValue>false</defaultValue>
        <description>from central org</description>
        <label>CUSTOMER CONTACTED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type_of_company__c</fullName>
        <label>Type of company</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Contract Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>end consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Central_Lead</fullName>
        <active>true</active>
        <businessProcess>Central Lead Process</businessProcess>
        <description>Central Lead to display common fields for information received via S2S connections from the Central org within the Business Unit org</description>
        <label>Central Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead_Routing_Key__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>contains the queue names and the keywords for routing are stored here</description>
    <fields>
        <fullName>Keyword__c</fullName>
        <description>the keyword to route to queue</description>
        <label>Keyword</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>queue_name__c</fullName>
        <description>the name of the queue</description>
        <label>queue name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Lead Routing Keys</label>
</CustomObject>

classes/RouteLead_Test.cls
/*
 * Rajendra Shahane 03/29/2016  Modified for case - 900703
 */
@isTest(SeeAllData=false)
private class RouteLead_Test
{
    static testmethod void RouteLead_TM()
    {
         //Start: Rajendra Shahane Modified for case - 900703
        ClsTestCustomSettingHelper.getCCPTriggerSettings();
        //End: Rajendra Shahane Modified for case - 900703
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Record_Type_Groups();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getProfit_BU_Center_Mapping_Rule2();
        ClsTestCustomSettingHelper.getTE_Connection();
        Account testaccount = new Account(Name = 'Test TE Account', AnnualRevenue = 123456.01, Legally_Restricted__c = false, BillingCity = 'Middletown', BillingCountry = 'US', BillingState = 'PA', BillingStreet = '2800 Fulling Mill Road', BillingPostalCode = '17057');    
        insert testaccount;
    
        Contact testcontact = new Contact(AccountId = testaccount.Id, FirstName = 'Jasmine', LastName = 'Ver', Legally_Restricted__c = false, Email = 'jasmine.ver@test.com');
        insert testcontact;
        
        Id leadId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Central Lead').getRecordTypeId();//[select Id From RecordType Where SobjectType ='Lead' And DeveloperName = 'Central_Lead'].Id;

        Lead testlead1 = new lead(RecordTypeId = leadId,industry = 'testind', lastname='Tester', firstName='Unit', company ='TEIS', Status = 'Assigned Unaccepted', Rating = 'Hot', country='United States', email= testcontact.Email, description='unit test ignore', Type_of_company__c='testrecord', CUSTOMER_CONTACTED__C=False, LEADSOURCE='LDAP', phone='+1 1231231234', STATE='PA');
        Lead testlead2 = new lead( RecordTypeId = leadId,lastname='Tester', firstName='Unit', company ='TEIS', Status = 'Assigned Unaccepted', Rating = 'Hot', country='United States', email= testcontact.Email, description='unit test ignore', Type_of_company__c='testrecord', CUSTOMER_CONTACTED__C=False, LEADSOURCE='LDAP', phone='+1 1231231234', STATE='PA');
        Lead testlead3 = new lead( RecordTypeId = leadId,lastname='Tester', firstName='Unit', company ='TEIS', Status = 'Assigned Unaccepted', Rating = 'Hot', country='United States', email= testcontact.Email, description='unit test ignore', Type_of_company__c='Distributor', CUSTOMER_CONTACTED__C=False, LEADSOURCE='LDAP', phone='+1 1231231234', STATE='PA');

        insert new list<lead>{testlead1, testlead2, testlead3};

        insert new Lead_Routing_key__c(name = 'test', Keyword__c = 'testind', Queue_Name__c = 'AMER Arrow Team', Active__c = True);
        test.starttest();

            RouteLead cls = new RouteLead() ;
            RouteLead.Leadrouter(new List<string>{testlead1.Id, testlead2.id, testlead3.id});
        test.stoptest();
       
    }
}