objects/Learning_Response_Result__c.object
<CustomObject>
    <fields>
        <fullName>Active_Response_Result_Record__c</fullName>
        <formula>Training__r.Active__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active Response &amp; Result Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exam_Result__c</fullName>
        <label>Exam Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_time_Attempted_Exam__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Please Do not use this filed on page layout . this field is calculating how many times the exam is scheduled for the user. Due to miss-understanding i am changing the display name. I can not change the API as it is used in so many classes</description>
        <label>Number of time Exam Scheduled</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_of_Exam__c</fullName>
        <label>Status of Exam</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_of_Participant__c</fullName>
        <label>Status of Participant</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invited for Training</fullName>
                </value>
                <value>
                    <fullName>Signed for Training</fullName>
                </value>
                <value>
                    <fullName>Attended Training</fullName>
                </value>
                <value>
                    <fullName>Went through Training Slides</fullName>
                </value>
                <value>
                    <fullName>Taken Exam (Passed)</fullName>
                </value>
                <value>
                    <fullName>Taken Exam (Failed)</fullName>
                </value>
                <value>
                    <fullName>Feedback Requested</fullName>
                </value>
                <value>
                    <fullName>Feedback Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Record_ID__c</fullName>
        <label>User Record ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Learning Response &amp; Result</label>
    <nameField>
        <displayFormat>L&amp;R-{0000000000}</displayFormat>
        <label>Learning Response &amp; Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Response &amp; Result</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/spExams__Exam__c.object
<CustomObject>
    <fields>
        <fullName>spExams__Exam_Duration__c</fullName>
        <label>Exam Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>spExams__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Exam</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Exam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/spExams__User_Exam__c.object
<CustomObject>
    <fields>
        <fullName>Learning_Response_Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Response &amp; Result</label>
        <referenceTo>Learning_Response_Result__c</referenceTo>
        <relationshipLabel>User Exams</relationshipLabel>
        <relationshipName>User_Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_time_attempted_exam__c</fullName>
        <formula>Learning_Response_Result__r.Number_of_time_Attempted_Exam__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of time attempted exam</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>spExams__Exam__c</fullName>
        <label>Exam</label>
        <referenceTo>spExams__Exam__c</referenceTo>
        <relationshipLabel>User Exams</relationshipLabel>
        <relationshipName>User_Exams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>spExams__Passed__c</fullName>
        <formula>IF( spExams__Score__c &lt; spExams__Exam__r.spExams__Passing_Score__c , &apos;FAILED&apos;, &apos;PASS&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Passed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>spExams__Remaining_Time__c</fullName>
        <label>Remaining  Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>spExams__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>spExams__Submittion_Date__c</fullName>
        <label>Submission Date</label>
        <type>DateTime</type>
    </fields>
    <label>User Exam</label>
    <nameField>
        <displayFormat>{YY}{00000000}{MM}</displayFormat>
        <label>User Exam No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/spExams__User_Exam_Answer__c.object
<CustomObject>
    <fields>
        <fullName>spExams__User_Exam_Question__c</fullName>
        <label>User Exam Question</label>
        <referenceTo>spExams__User_Exam_Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>User_Exam_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Exam Answer</label>
    <nameField>
        <displayFormat>UEA-{0000000}</displayFormat>
        <label>User Exam Answer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Exam Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/spExams__User_Exam_Question__c.object
<CustomObject>
    <fields>
        <fullName>spExams__User_Exam__c</fullName>
        <label>User Exam</label>
        <referenceTo>spExams__User_Exam__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>User_Exam_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Exam Question</label>
    <nameField>
        <displayFormat>UEQ-{0000000}</displayFormat>
        <label>User Exam Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Exam Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/INDUpdateLRResFromUserExamTriggerClass.cls
public class INDUpdateLRResFromUserExamTriggerClass{

/*********************************************************************************************************************** 
 Name: INDUpdateLRResFromUserExamTriggerClass
 Salesforce Instance : Sandbox
========================================================================================================================
 Purpose: This class is called by trigger to Update the data from SPExam App to the Learning and Responce Object .                                                   
========================================================================================================================
 REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                     
------------------------------------------------------------------------------------------------------------------------
 VERSION AUTHOR                DATE         DETAIL                                            Mercury Request #
------------------------------------------------------------------------------------------------------------------------
     1.0 Deepak                16 March 2016   Initial Development                                         
***********************************************************************************************************************/
      Public static void initMethod(List<spExams__User_Exam__c> UserExam) 
      {
                           
          
          Set<ID> ids = New Set<id>();
          Set<ID> lrrids= New Set<id>();
          Set<ID> examids= New Set<id>();
          
          spExams__Exam__c exam;
          List<spExams__User_Exam_Answer__c> UQA;
          Learning_Response_Result__c llr;
          List<Learning_Response_Result__c> updatellr= new List<Learning_Response_Result__c>();
          
          
  
          
           for(spExams__User_Exam__c userE:UserExam)
            {
             ids.add(userE.id);
             lrrids.add(userE.Learning_Response_Result__c);
             examids.add(userE.spExams__Exam__c);
             
            }
          
          
          map<id,Learning_Response_Result__c> ListLRR = new map<id,Learning_Response_Result__c>([select id,Number_of_time_Attempted_Exam__c,Exam_Result__c,User_Record_ID__c,Status_of_Exam__c,Status_of_Participant__c, Active_Response_Result_Record__c from Learning_Response_Result__c where id IN :lrrids]);
          map<id,spExams__User_Exam_Question__c> ListUEQ = new  map<id,spExams__User_Exam_Question__c>([select id from spExams__User_Exam_Question__c where spExams__User_Exam__c IN :ids]);
          
          UQA = new List<spExams__User_Exam_Answer__c>([select id,spExams__User_Exam_Question__c from spExams__User_Exam_Answer__c where spExams__User_Exam_Question__c IN :ListUEQ.keyset()]);
          map<id,spExams__Exam__c> listexam= new map<id,spExams__Exam__c>([select id,spExams__Exam_Duration__c from spExams__Exam__c where id IN :examids]);


//**********************************resuchedule the Exam**********************************************************************************************    
     
  
    integer tempi=0;
   for(spExams__User_Exam__c ue:UserExam)
   {
   
   exam=new spExams__Exam__c();
   exam=listexam.get(ue.spExams__Exam__c);
   if(ue.Learning_Response_Result__c!=null && ue.spExams__Status__c=='Submitted' )
    {
    llr =New Learning_Response_Result__c();
    llr = ListLRR.get(ue.Learning_Response_Result__c);
    llr.Status_of_Exam__c=ue.spExams__Status__c;
    if(ue.spExams__Status__c=='Submitted' )
      {
       llr.Number_of_time_Attempted_Exam__c++;
      
       if(ue.spExams__Passed__c=='FAILED' && llr.Number_of_time_Attempted_Exam__c<4 && ue.spExams__Submittion_Date__c!=null)
        {
          //ue.spExams__Remaining_Time__c=exam.spExams__Exam_Duration__c;ue.spExams__Passed__c=='FAILED'&& 
          llr.Exam_Result__c='Failed';
          llr.Status_of_Exam__c=ue.spExams__Status__c;
          llr.Status_of_Participant__c='Taken Exam (Failed)';
         // llr.Admin_Rechedule_Flag__c=true;
         if(llr.Number_of_time_Attempted_Exam__c!=3)
           {
            
             tempi=1;
          
           }
          
        }
       else if(ue.spExams__Passed__c=='PASS' && llr.Number_of_time_Attempted_Exam__c<4 )
        {
          llr.Exam_Result__c='Passed';
          llr.Status_of_Exam__c=ue.spExams__Status__c;
          llr.Status_of_Participant__c='Taken Exam (Passed)';
        } 
       
     }
      
     
     updatellr.add(llr);
    }
    
   }
    Update updatellr;
    if (tempi==1)
    {
    delete UQA;
    tempi=0;
    }  
    
    
  }    

}