objects/Live_Agent_Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom is used to hold the org details(org id, url&apos;s etc)</description>
    <fields>
        <fullName>epdURl__c</fullName>
        <label>epdURl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Live Agent Org Settings</label>
</CustomObject>

classes/LiveChatHelperCls_test.cls
@isTest
private class LiveChatHelperCls_test {
     @isTest static void testCallout() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new liveChatHelperCls_testMock());
        
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        
        liveChatHelperCls obj = new liveChatHelperCls(Live_Agent_Org_Settings__c.getInstance().epdURl__c+'2a065f7b-f54f-4cc0-8d12-20fefd444594');
     }
}