objects/Load_Status__c.object
<CustomObject>
    <description>Shows load status for different data sources and is mainly used to identify last loaded fiscal periods.</description>
    <label>Load Status</label>
    <nameField>
        <label>Data Source</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Load Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SIP__c.object
<CustomObject>
    <description>object for Industrial to manage the sales incentive plans for the Industrial sales users - populated by a workflow</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person to approve the SIP PLan</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SIP1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The TE person who participates in the plan</description>
        <label>Plan Participant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SIP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Year__c</fullName>
        <description>the Plan Year</description>
        <label>Plan Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                    <default>true</default>
                    <label>2018</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prev_Year_YTD_Direct_billings__c</fullName>
        <defaultValue>0</defaultValue>
        <description>the year to date Direct Billings of Previous year ( Plan year -1)</description>
        <label>Prev Year YTD Direct billings</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SIP_master_record__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>defines the related master record which contains important information for the letter and the calculations</description>
        <label>plan master record</label>
        <referenceTo>SIP_master__c</referenceTo>
        <relationshipLabel>SIP</relationshipLabel>
        <relationshipName>SIP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SIP</label>
    <nameField>
        <label>SIP Plan</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIP</pluralLabel>
    <recordTypes>
        <fullName>FE_Plan</fullName>
        <active>true</active>
        <description>Plan for Field engineers</description>
        <label>FE Plan</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SIP_master__c.object
<CustomObject>
    <description>object related to the SIP object to store some common master data  like payout% per region or texts for the different templates</description>
    <label>SIP master</label>
    <nameField>
        <label>SIP master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIP masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Te_Network_Id__c</fullName>
        <description>This field contains the users TE Network Id.</description>
        <label>Te Network Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ClsScheduled_reCalcFESIPs_test.cls
/**
 * This class contains unit tests for validating the behavior of ClsScheduled_reCalcFESIPs
 *
 @author Bin Yuan
 @created 2014-01-08
 @version 1.0
 @since 29.0
 *
 @changelog
 * coverage 88% 
 * 
 * 2014-01-08 Bin Yuan <bin.yuan@itbconsult.com>
 * - Created
 */
@isTest
private class ClsScheduled_reCalcFESIPs_test{
    static testMethod void testSchedule() {
            
        
        DateTime currTime = DateTime.now();
        Integer min = currTime.minute();
        Integer hour = currTime.hour();
        String sch;
        if(min <= 58) {
            sch = '0 '+ (min + 1) + ' ' + hour + ' * * ? '+ currTime.year();
        }
        else {         
            sch = '0 0 '+ (hour + 1) + ' * * ? '+ currTime.year();
        }
        
        test.startTest(); 
        User user = new User();
        user=ClsTestHelp.createTestUsers();
        user.Te_Network_Id__c = 'testUser';
        insert user;
        
        Load_Status__c ls = new Load_Status__c();
        String recordTypeFE;
        for (RecordType recordType : [select Id, Name, DeveloperName from RecordType where SobjectType = 'SIP__c' and IsActive = true and DeveloperName = 'FE_Plan' ]) {		
            recordTypeFE = recordType.Id; 
        } 
        SIP_master__c sipMaster = new SIP_master__c();
        sipMaster.Name = 'Test Master';
        insert sipMaster;
        
        SIP__c sipFE = new SIP__c();
        sipFE.Plan_Participant__c = user.Id;
        sipFE.RecordTypeId = recordTypeFE;
        sipFE.Plan_Year__c = '2013';
        sipFE.Name = 'test FE';
        sipFE.Approver__c = user.Id;
        sipFE.SIP_master_record__c = sipMaster.Id;
        sipFE.Prev_Year_YTD_Direct_billings__c  = 100;
        insert sipFE;
        ClsScheduled_reCalcFESIPs cls = new ClsScheduled_reCalcFESIPs();
        String jobId = system.schedule('test', sch, cls); 
            
        Test.stopTest(); 
    }
}