objects/MTO_High_Runner__c.object
<CustomObject>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>MTO High Runner</label>
    <nameField>
        <label>MTO High Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MTO High Runner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Hierarchy__c.object
<CustomObject>
    <description>Reflects the Sales Hierarchy.</description>
    <fields>
        <fullName>Hierarchy_Type__c</fullName>
        <description>Describes which internal TE hierarchy this record&apos;s information is sourced from.</description>
        <label>Hierarchy Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Hierarchy (AM)</fullName>
                    <default>true</default>
                    <label>Sales Hierarchy (AM)</label>
                </value>
                <value>
                    <fullName>Account Manager Hierarchy (FE)</fullName>
                </value>
                <value>
                    <fullName>Global Account Manager Hierarchy (GAM)</fullName>
                </value>
                <value>
                    <fullName>Market Manager Hierarchy (MM)</fullName>
                </value>
                <value>
                    <fullName>Field Service Engineer Hierarchy (FSE)</fullName>
                </value>
                <value>
                    <fullName>Relay Specialist Hierarchy (IS)</fullName>
                </value>
                <value>
                    <fullName>IND KAM Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Sales Hierarchy (AT &amp; Sensors)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_7_Assigned_User_Network_Ids__c</fullName>
        <description>List of TE Network Ids for users assigned to this hierarchy level on this territory.</description>
        <inlineHelpText>i.e: US012345;US056789;US010000... etc.</inlineHelpText>
        <label>Level 7 Assigned User Network Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level_7_Assigned_Users__c</fullName>
        <description>List of Salesforce User Ids for users assigned to this hierarchy level on this territory.</description>
        <inlineHelpText>i.e: 005E0000000VsJB;005E0000000VsJ1;005E0000000VsJQ... etc.</inlineHelpText>
        <label>Level 7 Assigned Users</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level_7_Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Account Owner</description>
        <label>Level 7 Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Hierarchies_Level7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Level 7 territory code</inlineHelpText>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sales Hierarchy</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Te_Network_Id__c</fullName>
        <description>This field contains the users TE Network Id.</description>
        <label>Te Network Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ClsMTOHighRunnerTriggerHandlerTest.cls
/*------------------------------------------------------------
Author:        Buwen Guo <buwen.guo@capgemini.com>
Description:   test class for handle class: ClsMTOHighRunnerTriggerHandler.
			   The user story number is W-00152.
Inputs:        
History
2017-07-28 	Buwen Guo <buwen.guo@capgemini.com> created
------------------------------------------------------------*/
@isTest
public with sharing class ClsMTOHighRunnerTriggerHandlerTest {
    
    static testMethod void testMethod1() {
        User u = ClsTestHelp.createTestUsers();
        u.Te_Network_Id__c = '0529';
        insert u;
        System.runAs(u) {
            Sales_Hierarchy__c sh7 = ClsTestHelp.createTestSalesHierarchy();
            sh7.Level_7_Territory_Code__c = 'A007357';
            sh7.Hierarchy_Type__c = 'Sales Hierarchy (AM)';
            sh7.Level_7_Default_Owner__c = u.Id;
            sh7.Level_7_Assigned_Users__c = u.Id;
            sh7.Level_7_Assigned_User_Network_Ids__c = u.Te_Network_Id__c;
            insert sh7;
            
            Test.startTest();
    		MTO_High_Runner__c mto = ClsTestHelp.createTestMTOHighRunner();
            mto.Level_7_Territory_Code__c = 'A007357';
			insert mto;
            
            list<MTO_High_Runner__c> list_mto = new list<MTO_High_Runner__c>();
            ClsWrappers.TriggerContext trgCtx = new ClsWrappers.TriggerContext();
            trgCtx.isBefore = true;
            trgCtx.isInsert = true;
            trgCtx.newList = new List<MTO_High_Runner__c>{mto};
    
            
            ClsMTOHighRunnerTriggerHandler.populateOwnerFromSalesHierarchy(trgCtx);
    
            Test.stopTest();  
        }
    }
}