objects/OEM_Mapping_Rule__c.object
<CustomObject>
    <description>OEM Mapping Rule for Consumer Device</description>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <inlineHelpText>1 = Oct
2 = Nov
3 = Dec
4 = Jan
5 = Feb
6 = Mar
7 = Apr
8 = May
9 = Jun
10 = Jul
11 = Aug
12 = Sep</inlineHelpText>
        <label>Fiscal Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>01</label>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2013</fullName>
                    <default>true</default>
                    <label>2013</label>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OEM__c</fullName>
        <label>OEM</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Fiscal_Year__c</field>
                <operation>equals</operation>
                <valueField>OEM_Details__c.Fiscal_Year__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Fiscal_Month__c</field>
                <operation>equals</operation>
                <valueField>OEM_Details__c.Fiscal_Month__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>OEM_Details__c</referenceTo>
        <relationshipLabel>OEM Mappings</relationshipLabel>
        <relationshipName>OEM_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CSD OEM Mapping</label>
    <nameField>
        <displayFormat>CSD-OEM-{0000000000}</displayFormat>
        <label>OEM Mapping Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OEM Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/olmmappingcls.cls
/**********************************************************************************************************************************************
*******
Name: olmmappingcls
Copyright © 2013 TE Connectivity | Salesforce Instance : C2S Org
===============================================================================================================================================

Purpose: This controller prepopulate Fiscal Year and Fiscal Month from OEM Detail record.
===============================================================================================================================================
REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                           
-----------------------------------------------------------------------------------------------------------------------------------------------
VERSION   AUTHOR              DATE          DETAIL                           
-----------------------------------------------------------------------------------------------------------------------------------------------
 1.0      Padmaja       15/01/2014    Controller                       
***********************************************************************************************************************************************
*****/


public with sharing class olmmappingcls {
public OEM_Mapping_Rule__c omr{get;set;}
public id vVariableName{get;set;}
public string vVariableName1{get;set;}
    public olmmappingcls(){
    vVariableName=Apexpages.Currentpage().getParameters().get('vVariableName');
    vVariableName1=Apexpages.Currentpage().getParameters().get('vVariableName1');
    string dt=string.valueof(System.today().year());
    String mon=string.valueof(System.today().month());
        for(integer i=1;i<=9;i++)
        {
            if(mon==string.valueOf(i))
            {
                mon=string.valueof(i+3);
                omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
                i=10;

                
            }
        }
      /*  if(mon == '1'){
        mon='04';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '2'){
        mon='05';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '3'){
        mon='06';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        
        }
        else if(mon == '4'){
        mon='07';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '5'){
        mon='08';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '6'){
        mon='09';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '7'){
        mon='10';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '8'){
        mon='11';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '9'){
        mon='12';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }*/
        if(mon == '10'){
        mon='1';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon == '11'){
        mon='2';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
        else if(mon=='12'){
        mon='3';
        omr=new OEM_Mapping_Rule__c(OEM__c=vVariableName,Fiscal_Year__c = dt,Fiscal_Month__c = mon);
        }
    }
    public PageReference cancel() {
        pagereference ref=new pagereference('/'+vVariableName);    
        return ref;
      }
    
    public PageReference save() {
        try{    
        insert omr; 
        pagereference ref=new pagereference('/'+vVariableName);
        ref.setredirect(true); 
        return ref;
        }
        catch(Exception ex){
        System.debug('************error messages************'+ex.getMessage()); 
        if(ex.getMessage().contains('Please define World Wide Account Number:') ){     
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please define World Wide Account Number'));
        }  
        else if(ex.getMessage().contains('Please define  World Wide Account Number/Part Number:')){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please define World Wide Account Number/Part Number'));        
        }
        else if(ex.getMessage().contains('Please Define Sold To Account Code:')){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please Define Sold To Account Code'));
        }
        else if(ex.getMessage().contains('Please define Sold To Account Code/ Part Number:')){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please define Sold To Account Code/ Part Number'));
        } 
        else if(ex.getMessage().contains('Please define Part Number:')){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please define Part Number'));
        } 
        else if(ex.getMessage().contains('Allocation cannot exceed 100%!:')){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Allocation cannot exceed 100%!'));
        } 
        }
      return null;      
      }

}