objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Account_IBC_code__c</fullName>
        <formula>Opportunity__r.Account.INDUSTRY_BUSINESS_CDE__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account IBC code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU_profit_center__c</fullName>
        <description>used to calculate the BU profit center which will receive the profit for the opportunity.</description>
        <label>BU profit center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CBC5_Code__c</fullName>
        <formula>GPL__r.CBC5__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CBC5 code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <formula>TEXT(Opportunity__r.Distributor__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distributor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <description>This field contains the Part Number. It is used in Offline App.</description>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClsOppyTrgRefreshBUProfit.cls
/**
 * This class used to refresh Opportunity Part's BU Profit when Distributor on Opportunity is updated.
 * 
 * @author    Mrunal Parate
 * @created    2016-12-19
 * @since     37.0 (Force.com ApiVersion)
 * @version   1.0
 * 
 * @changelog
 * 2016-12-19 Mrunal Parate <Mrunal.Parate@te.com>
 * - Created
 * 
 */
public class ClsOppyTrgRefreshBUProfit {
    @Future
    public static void UpdateBUProfit(set<Id> oppId) {

        List<Opportunity_Part__c> OppParts= [Select Id,Opportunity__c,CBC5_Code__c,BU_profit_center__c, Account_IBC_code__c, Distributor__c,Part_Number__c  FROM Opportunity_Part__c WHERE Opportunity__c =: oppId];
        
        if (OppParts!=null && OppParts.size()>0){ClsOppyPartUtil.allocateBUProfitCenter(OppParts);
        Update OppParts;
        }
    }
}