objects/Opportunity_Forecast__c.object
<CustomObject>
    <description>This object contains the project forecast numbers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <description>Populated by forecasting component in opportunity page to store fiscal quarter. Used in PLM integration to aggregate monthly data by quarter.</description>
        <label>Fiscal Quarter</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <description>Populated by forecasting component in opportunity page to store fiscal year. Used in PLM integration to aggregate monthly data by quarter.</description>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Forecast</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Forecasts</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>CM, Distributor, OEM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Opportunity Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Overall_Measures__c.object
<CustomObject>
    <fields>
        <fullName>GAM_Code__c</fullName>
        <label>GAM Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_0__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Month 0</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAM Code</label>
        <referenceTo>Sales_Hierarchy__c</referenceTo>
        <relationshipLabel>Overall Measures</relationshipLabel>
        <relationshipName>Overall_Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Overall Measures</label>
    <nameField>
        <displayFormat>OM-{00000000}</displayFormat>
        <label>Overall Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overall Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Hierarchy__c.object
<CustomObject>
    <description>Reflects the Sales Hierarchy.</description>
    <fields>
        <fullName>Hierarchy_Type__c</fullName>
        <description>Describes which internal TE hierarchy this record&apos;s information is sourced from.</description>
        <label>Hierarchy Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Hierarchy (AM)</fullName>
                    <default>true</default>
                    <label>Sales Hierarchy (AM)</label>
                </value>
                <value>
                    <fullName>Account Manager Hierarchy (FE)</fullName>
                </value>
                <value>
                    <fullName>Global Account Manager Hierarchy (GAM)</fullName>
                </value>
                <value>
                    <fullName>Market Manager Hierarchy (MM)</fullName>
                </value>
                <value>
                    <fullName>Field Service Engineer Hierarchy (FSE)</fullName>
                </value>
                <value>
                    <fullName>Relay Specialist Hierarchy (IS)</fullName>
                </value>
                <value>
                    <fullName>IND KAM Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Sales Hierarchy (AT &amp; Sensors)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Level 7 territory code</inlineHelpText>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sales Hierarchy</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ClsBatch_buildOpportunityMeasures_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest (SeeAllData=true)
private class ClsBatch_buildOpportunityMeasures_Test {

    static testMethod void testQuarterBatch() {
        Test.startTest();
        
        list<Opportunity_Partner__c> oppyPartners = new list<Opportunity_Partner__c>();
        
        //Build some opportunities, parts, partners, and quarterly forecasts here
        Id ForecastRTOppy = [SELECT Id FROM RecordType WHERE DeveloperName = 'Opportunity' and SObjectType = 'Opportunity_Forecast__c' Limit 1].Id;
        
        //create account - set acct group code and gam code
        Account testAcct = new Account();
        testAcct = C2ForecastTestHelp.createTestAccounts();
        testAcct.ACCT_GROUP_CDE__c = '0001';
        testAcct.GAMCD__c = 'G000';
        testAcct.AccountNumber = 'Test account -0002';
        insert testAcct;
        //create sales hierarchy - set gam code and type
        Sales_Hierarchy__c testHier = C2ForecastTestHelp.createTestSalesHierarchy();
        testHier.Level_7_Territory_Code__c = 'G000';
        testHier.Hierarchy_Type__c = 'Global Account Manager Hierarchy (GAM)';
        insert testHier;
        //create opportunity - set mass prod status
        Opportunity testOpp = C2ForecastTestHelp.createTestOpportunity();
        testOpp.Mass_Prod_Status__c = true;
        testOpp.StageName = 'Won - Closed';
        testOpp.AccountId = testAcct.id;
        testOpp.Account = testAcct;
        testOpp.Probability = 10;
        insert testOpp;
        
        //create opportunity partner - set primary, allocation
        list<Opportunity_Partner__c> existingPartners = [SELECT Id, Opportunity__c, Account__c, Primary__c from Opportunity_Partner__c where opportunity__c =: testOpp.Id];
        Opportunity_Partner__c oppyPartner = existingPartners[0];//new Opportunity_Partner__c();        
        //oppyPartner.Opportunity__c = testOpp.Id;
        oppyPartner.Account__c = testAcct.Id;
        oppyPartner.Account__r = testAcct;
        //oppyPartner.Opportunity__r = testOpp;
        oppyPartner.Primary__c = true;
        oppyPartner.Allocation__c = 100;
        oppyPartner.CurrencyIsoCode = 'USD';
        update oppyPartner;        
        
        //create opportunity parts - proposal, stages
        Opportunity_Part__c oppyPart = new Opportunity_Part__c();
        oppyPart = C2ForecastTestHelp.createTestOpportunityPart();
        oppyPart.opportunity__c = testOpp.Id;
        insert oppyPart;
        
        list<String> years = new list<String>();
        years.add(string.valueOf(datetime.now().year()));
        years.add(string.valueOf(datetime.now().year() - 1));        
        years.add(string.valueOf(datetime.now().year() + 1));
        years.add(string.valueOf(datetime.now().year() + 2));                        
        
        list<Period> fcstPeriods = [SELECT startdate, FiscalYearSettings.Name from period where type = 'Quarter' and FiscalYearSettings.Name in: years order by startdate];
        //create opportunity forecasts - opportunity type - start date = current qtr start date     

        list<Opportunity_Forecast__c> fcstToAdd = new list<Opportunity_Forecast__c>();
        
        integer quarterCounter = 1;
        
        for(Period p : fcstPeriods)
        {
            Opportunity_Forecast__c newFcst = new Opportunity_Forecast__c();
            newFcst.date__c = p.startdate;
            newFcst.opportunity__c = testOpp.Id;
            newFcst.opportunity__r = testOpp;
            newFcst.Amount__c = 3;
            newFcst.Fiscal_Year__c = p.FiscalYearSettings.Name;
            newFcst.Fiscal_Quarter__c = ('0' + string.valueOf(quarterCounter));
            newFcst.CurrencyIsoCode = 'USD';
            newFcst.RecordTypeId = ForecastRTOppy;
            fcstToAdd.add(newFcst); 
            
            if(quarterCounter == 4)
            {
                quarterCounter = 1;
            }
            else
            {
                quarterCounter = quarterCounter+1;              
            }
        }       
        insert fcstToAdd;
        
        oppyPartners.add(oppyPartner);
        
        ClsBatch_buildOpportunityMeasures clsBatch1 = new ClsBatch_buildOpportunityMeasures();
        Database.BatchableContext BC1;
        clsBatch1.query = 'Select Id from Opportunity_Partner__c limit 1';
        clsBatch1.start(BC1);
        clsBatch1.execute(BC1, oppyPartners);
        clsBatch1.finish(BC1);
        
        list<Overall_Measures__c> testMeasure = [SELECT Id, Gam_Code__c, Month_0__c from Overall_Measures__c Where Gam_Code__c = 'G000' limit 1];
        
        system.assert(testMeasure[0].Month_0__c == 1, 'Monthly measure value does not match expected output');
        
        //Test where start month is not first month in quarter
        ClsBatch_buildOpportunityMeasures clsBatch2 = new ClsBatch_buildOpportunityMeasures();
        Database.BatchableContext BC2;
        clsBatch2.query = 'Select Id from Opportunity_Partner__c limit 1';
        clsBatch2.start(BC2);
        clsBatch2.StartMonthNumber = 3;
        clsBatch2.EndMonthNumber = 2;
        clsBatch2.execute(BC2, oppyPartners);
        clsBatch2.finish(BC2);
        
        ClsBatch_buildOpportunityMeasures clsBatch3 = new ClsBatch_buildOpportunityMeasures();
        Database.BatchableContext BC3;
        clsBatch3.query = 'Select Id from Opportunity_Partner__c limit 1';
        clsBatch3.start(BC3);
        clsBatch3.StartMonthNumber = 2;
        clsBatch3.EndMonthNumber = 1;
        clsBatch3.execute(BC3, oppyPartners);
        clsBatch3.finish(BC3); 
        
        Test.stopTest();
    }
    static testMethod void testMonthBatch() {
        
        Test.startTest();
        
        list<Opportunity_Partner__c> oppyPartners = new list<Opportunity_Partner__c>();
               
        //Build some opportunities, parts, partners, and monthly forecasts here
        Id ForecastRTOppy = [SELECT Id FROM RecordType WHERE DeveloperName = 'Opportunity' and SObjectType = 'Opportunity_Forecast__c' Limit 1].Id;
        
        //create account - set acct group code and gam code
        Account testAcct = new Account();
        testAcct = C2ForecastTestHelp.createTestAccounts();
        testAcct.ACCT_GROUP_CDE__c = '0001';
        testAcct.GAMCD__c = 'G000';
        testAcct.AccountNumber='Test Account -0001';
        insert testAcct;
        //create sales hierarchy - set gam code and type
        Sales_Hierarchy__c testHier = C2ForecastTestHelp.createTestSalesHierarchy();
        testHier.Level_7_Territory_Code__c = 'G000';
        testHier.Hierarchy_Type__c = 'Global Account Manager Hierarchy (GAM)';
        insert testHier;
        //create opportunity - set mass prod status
        Opportunity testOpp = C2ForecastTestHelp.createTestOpportunity();
        testOpp.mass_prod_status__c = true;
        testOpp.StageName = 'Won - Closed';
        testOpp.AccountId = testAcct.id;
        testOpp.Account = testAcct;
        testOpp.Probability = 10;
        insert testOpp;
        
        //create opportunity partner - set primary, allocation
        list<Opportunity_Partner__c> existingPartners = [SELECT Id, Opportunity__c, Account__c, Primary__c from Opportunity_Partner__c where opportunity__c =: testOpp.Id];
        Opportunity_Partner__c oppyPartner = existingPartners[0];//new Opportunity_Partner__c();        
        //oppyPartner.Opportunity__c = testOpp.Id;
        oppyPartner.Account__c = testAcct.Id;
        oppyPartner.Account__r = testAcct;
        //oppyPartner.Opportunity__r = testOpp;
        oppyPartner.Primary__c = true;
        oppyPartner.Allocation__c = 100;
        oppyPartner.CurrencyIsoCode = 'USD';
        update oppyPartner;        
        
        //create opportunity parts - proposal, stages
        Opportunity_Part__c oppyPart = new Opportunity_Part__c();
        oppyPart = C2ForecastTestHelp.createTestOpportunityPart();
        oppyPart.opportunity__c = testOpp.Id;
        insert oppyPart;
        
        list<String> years = new list<String>();
        years.add(string.valueOf(datetime.now().year()));
        years.add(string.valueOf(datetime.now().year() - 1));        
        years.add(string.valueOf(datetime.now().year() + 1));                
        
        list<Period> fcstPeriods = [SELECT startdate, FiscalYearSettings.Name from period where type = 'Month' and FiscalYearSettings.Name in: years order by startdate];
        //create opportunity forecasts - opportunity type - start date = current qtr start date     

        list<Opportunity_Forecast__c> fcstToAdd = new list<Opportunity_Forecast__c>();
        
        integer monthCounter = 1;
        
        for(Period p : fcstPeriods)
        {
            Opportunity_Forecast__c newFcst = new Opportunity_Forecast__c();
            newFcst.date__c = p.startdate;
            newFcst.opportunity__c = testOpp.Id;
            newFcst.opportunity__r = testOpp;
            newFcst.Amount__c = 1;
            newFcst.Fiscal_Year__c = p.FiscalYearSettings.Name;
            if(monthCounter <= 3)
            {
                newFcst.Fiscal_Quarter__c = '01';
            }   
            else if(monthCounter <= 6)
            {
                newFcst.Fiscal_Quarter__c = '02';
            }
            else if(monthCounter <= 9)
            {
                newFcst.Fiscal_Quarter__c = '03';
            }
            else
            {
                newFcst.Fiscal_Quarter__c = '04';
            }                               
            newFcst.CurrencyIsoCode = 'USD';
            newFcst.RecordTypeId = ForecastRTOppy;          
            fcstToAdd.add(newFcst); 
            
            if(monthCounter == 12) 
            {
                monthCounter = 1;
            }
            else
            {
                monthCounter = monthcounter+1;
            }           
        }       
        insert fcstToAdd;
        
        oppyPartners.add(oppyPartner);
        
        ClsBatch_buildOpportunityMeasures clsBatch = new ClsBatch_buildOpportunityMeasures();
        Database.BatchableContext BC;
        clsbatch.query = 'Select Id from Opportunity_Partner__c limit 1';        
        clsBatch.start(BC);
        clsBatch.execute(BC, oppyPartners);
        clsBatch.finish(BC);
                
        list<Overall_Measures__c> testMeasure = [SELECT Id, Gam_Code__c, Month_0__c from Overall_Measures__c Where Gam_Code__c = 'G000' limit 1];
        
        system.assert(testMeasure[0].Month_0__c == 1, 'Monthly measure value does not match expected output');
        Test.stopTest();
    }
}