objects/Opportunity_Forecast__c.object
<CustomObject>
    <description>This object contains the project forecast numbers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Five_Year_Amount__c</fullName>
        <label>Five Year Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Opportunity_Part__c</referenceTo>
        <relationshipName>Forecast</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <label>Opportunity Forecast</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Forecasts</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Part</fullName>
        <active>true</active>
        <label>Part</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Text__c</fullName>
        <label>Lost Reason Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Approval criteria not met</fullName>
                </value>
                <value>
                    <fullName>Awaiting customer response</fullName>
                </value>
                <value>
                    <fullName>Awaiting qualification test results</fullName>
                </value>
                <value>
                    <fullName>Customer Program Change/Cancellation</fullName>
                </value>
                <value>
                    <fullName>Customer project on hold</fullName>
                </value>
                <value>
                    <fullName>Customer request</fullName>
                </value>
                <value>
                    <fullName>Lack of TE resources</fullName>
                </value>
                <value>
                    <fullName>Missing customer requirements</fullName>
                </value>
                <value>
                    <fullName>Missing TE requirements</fullName>
                </value>
                <value>
                    <fullName>No potential customer</fullName>
                </value>
                <value>
                    <fullName>PAC decision</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project transfer to different region</fullName>
                </value>
                <value>
                    <fullName>Quote sent, awaiting customer</fullName>
                </value>
                <value>
                    <fullName>TE Engineering resources</fullName>
                </value>
                <value>
                    <fullName>TE portfolio / priority decision</fullName>
                </value>
                <value>
                    <fullName>TE technical solution not competitive</fullName>
                </value>
                <value>
                    <fullName>Timeline</fullName>
                </value>
                <value>
                    <fullName>Customer cancellation</fullName>
                </value>
                <value>
                    <fullName>Replaced by other project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Duplicate part number</fullName>
                </value>
                <value>
                    <fullName>Customer Strategy Change</fullName>
                </value>
                <value>
                    <fullName>Engineering Rejected</fullName>
                </value>
                <value>
                    <fullName>Service/Responsiveness</fullName>
                </value>
                <value>
                    <fullName>Won by other TE Customer</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Price and Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Confidence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>50/50</fullName>
                </value>
                <value>
                    <fullName>Likely</fullName>
                </value>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <recordTypes>
        <fullName>Extension</fullName>
        <active>true</active>
        <label>Extension</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>CM, Distributor, OEM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Opportunity Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL old</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts (GPL)</relationshipLabel>
        <relationshipName>Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TOPS_Forecast__c.object
<CustomObject>
    <description>This custom object is used to store the forecast data imported from old system.</description>
    <label>TOPS Forecast</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>TOPS Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TOPS Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClsOppyUtilAPL_Test.cls
/**
*   This test class is for ClsOppyUtilAPL.
*
@author Di Chen
@created 2012-02-23
@version 1.0
@since 20.0
*
@changelog
* 2012-02-23 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 88%

@changelog
* 2014-09-01 Padmaja D <padmaja.dadi@te.com>
* - Created
* - Test coverage 88%
*/
@isTest(SeeAllData=false)
private class ClsOppyUtilAPL_Test {
       
    static testMethod void oppyForeCastType() { 
        ClsTestCustomSettingHelper.getApex_Helper_Settings();
        ClsTestCustomSettingHelper.getConsumer_Device_Opportunity_Record_Types();
        ClsTestCustomSettingHelper.getOpportunity_Record_Type_Groups();
        ClsTestCustomSettingHelper.getOpportunity_Approvers();
        ClsTestCustomSettingHelper.getProfit_BU_Center_Mapping_Rule2();

        RecordType rt = ClsTestHelp.createTestRecordType();
        RecordType rt2 = ClsTestHelp.createTestRecordType16();
        
        Account acc = ClsTestHelp.createTestAccounts();
        acc.Type = 'CM';
        insert acc;
		Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
        oppy2.Program_level_Forecasting__c =true; 
        oppy2.Name = 'Pain of Queen';
        oppy2.RecordTypeId = rt2.Id;
        insert oppy2;          
        Opportunity oppy = ClsTestHelp.createTestOpportunity();
        oppy.Program__c = oppy2.Id;   
        oppy.Type = 'CM';
        oppy.Request_Type__c = 'Extension';
        oppy.Method__c = 'BOM';
        oppy.Level__c = 'Yearly';
        oppy.Amount = 1;
        oppy.CurrencyIsoCode = 'EUR';
        oppy.Five_Year_Revenue__c = 1;
        oppy.RecordTypeId = rt2.Id;
        insert oppy;
        
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial';
        insert ph;
        
        Part__c part = new Part__c();
        part.Description__c = 'Sniper';
        part.Product_Hierarchy__c = ph.Id;
        insert part;
        
        Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
        oppypart.Opportunity__c = oppy.Id;
        oppypart.Part__c = part.Id;
        //oppypart.Status__c = 'Lost1';
        //oppypart.Lost_Reason__c = 'Other';
        //oppypart.Lost_Reason_Text__c = null;
        oppypart.GPL__c = ph.Id;
        insert oppypart;
        
        Opportunity_Partner__c oppyPartner = ClsTestHelp.createTestOpportunityPartner();
        oppyPartner.Opportunity__c = oppy.Id;
        oppyPartner.Account__c = acc.Id;
        oppyPartner.Allocation__c = 100;
        insert oppyPartner;
        
        Opportunity_Forecast__c oppyForecast = ClsTestHelp.createTestOpportunityForecasts();
        oppyForecast.Opportunity__c = oppy.Id;
        oppyForecast.Quantity__c = 12;
        oppyForecast.Part__c = oppypart.Id;
        oppyForecast.Date__c = date.newInstance(2012, 09, 28);
        oppyForecast.Amount__c = 1;
        oppyForecast.Five_Year_Amount__c = 1000;
        oppyForecast.Sales_Price__c = 1;
        
        Opportunity_Forecast__c oppyForecast1 = ClsTestHelp.createTestOpportunityForecasts();
        oppyForecast1.Opportunity__c = oppy.Id;
        oppyForecast1.Quantity__c = 12;
        //oppyForecast.Part__c = oppypart.Id;
        oppyForecast1.Date__c = date.newInstance(2012, 09, 28);
        oppyForecast1.Amount__c = 1;
        oppyForecast1.Five_Year_Amount__c = 1000;
        oppyForecast1.Sales_Price__c = 1;
        insert new List<Opportunity_Forecast__c>{oppyForecast, oppyForecast1};
        
        Test.startTest();
        
        Set<String> set_forecastYears = new Set<String>();
        set_forecastYears.add('2012');
        
        ClsOppyUtilAPL.getYearList(set_forecastYears, true, 1);
        ClsOppyUtilAPL.getYearList(set_forecastYears, false, 1);
        ClsOppyUtilAPL.getAllPeriodYears();
        
        Map<Id, Id> map_partId_oppyId = new Map<Id, Id>();
        map_partId_oppyId.put(part.Id,oppy.Id);
        
        List<Id> list_partIds = new List<Id>();
        list_partIds.add(part.Id);
        
        Map<Id, Opportunity> map_oppyid_opportunity = new Map<Id, Opportunity>();
        map_oppyid_opportunity.put(oppy.Id,oppy);
        
        ClsOppyUtilAPL.getFiscalMonthStartDate('2012', '2');
        
        Set<Id> set_oppyIds = new Set<Id>();
        set_oppyIds.add(oppy.Id);
        ClsOppyUtilAPL.getOppyYearMap(set_oppyIds);
        
        ClsOppyUtilAPL.getLevelLabel('Monthly');
        ClsOppyUtilAPL.getLevelLabel('Yearly');
        ClsOppyUtilAPL.getLevelLabel('Quarterly');
        ClsOppyUtilAPL.getForecastLevelNoYear();
        ClsOppyUtilAPL.getForecastLevel();
        ClsOppyUtilAPL.getYearNumber();
        
        Date inputDate = date.today();
        ClsOppyUtilAPL.getForecastMonth(inputDate);
        ClsOppyUtilAPL.getForecastYear(inputDate);
        
        ClsOppyUtilAPL.getFiscalQuarterStartDate('2012', '3');
        ClsOppyUtilAPL.getPartIdsByOppyId(set_oppyIds);
        
        
        List<Opportunity_Forecast__c> list_oppyForecasts = new List<Opportunity_Forecast__c>();
        list_oppyForecasts.add(oppyForecast);
        Map<Id, List<Opportunity_Forecast__c>> partFCs = new  Map<Id, List<Opportunity_Forecast__c>>();
        partFCs.put(part.Id,list_oppyForecasts);
        
        List<ClsOpportunityForecastStructure.ForecastItemStructure> monthForecasts = new List<ClsOpportunityForecastStructure.ForecastItemStructure>();
        ClsOpportunityForecastStructure.ForecastItemStructure monthClsFore = new ClsOpportunityForecastStructure.ForecastItemStructure('Monthly', part.Id, oppy.Id, rt.Id);
        
        
        List<ClsOpportunityForecastStructure.ForecastItemStructure> quarterForecasts = new List<ClsOpportunityForecastStructure.ForecastItemStructure>();
        ClsOpportunityForecastStructure.ForecastItemStructure QuarterlyClsFs = new ClsOpportunityForecastStructure.ForecastItemStructure('Quarterly', part.Id, oppy.Id, rt.Id);
        
        ClsOppyUtilAPL.getOpportunitysByProgramId(oppy.Id);
        ClsOppyUtilAPL.getStatusItems();
        
        ClsOppyUtilAPL.buildAllPartForeCastMap(oppy.Id);
        
        ClsOppyUtilAPL.getPartsByOppyId(set_oppyIds);
        ClsOppyUtilAPL.getAllPartsByProgramId(oppy.Id);
        ClsOppyUtilAPL.buildProgramAllPartForeCastMap(oppy2.Id);
        //ClsOppyUtilAPL.buildAllPartForeCastMap(oppy.Id, oppyForecast);
        
        map<Id, String> map_oppyPartId_isoCode = new map<Id, String>();
        map_oppyPartId_isoCode.put(oppypart.Id,'EUR');
        
        List<Opportunity_Part__c> list_parts = new List<Opportunity_Part__c>();
        list_parts.add(oppypart);        
        
        List<ClsOpportunityForecastStructure> list_forecastStructures = new List<ClsOpportunityForecastStructure>();
        
        List<Opportunity_Forecast__c> oppyForecasts = new List<Opportunity_Forecast__c>();
        oppyForecasts.add(oppyForecast);
        
        Map<Id, List<Opportunity_Forecast__c>> partFCs1 = new Map<Id, List<Opportunity_Forecast__c>>();
        partFCs1.put(part.Id,oppyForecasts);
        
        Map<Id, Id> map_partId_oppyId1 = new Map<Id, Id>();
        map_partId_oppyId1.put(part.Id,oppy.Id);
        
        List<Id> list_partIds1 = new List<Id>();
        list_partIds1.add(part.Id);
        ClsOpportunityForecastStructure cls = new ClsOpportunityForecastStructure(map_oppyPartId_isoCode,'EUR',oppyForecasts,partFCs,'2012',oppy.Id,map_partId_oppyId,rt.Id,rt.Id,'Monthly',list_partIds);
        cls.year = '2012';
        list_forecastStructures.add(cls);
        
        List<String> list_years = new List<String>();
        list_years.add('2012');
        Map<String, List<Opportunity_Forecast__c>> map_year_oppyForecast = new Map<String, List<Opportunity_Forecast__c>>();
        map_year_oppyForecast.put('2012',oppyForecasts);
        
        Map<String, Map<Id, List<Opportunity_Forecast__c>>> map_year_map_partId_oppyForecast = new Map<String, Map<Id, List<Opportunity_Forecast__c>>>();
        map_year_map_partId_oppyForecast.put('2012',partFCs1);
        
        Date inputDate1 = date.newInstance(2010, 09, 24); 
        ClsOppyUtilAPL.getForecastQuarter(inputDate1);
        
        map<Id,Id> map_oppId_accId_new = new map<Id,Id>();
        map_oppId_accId_new.put(oppy.Id,acc.Id);
        
        map<Id,Id> map_oppId_accId_old = new map<Id,Id>();
        map_oppId_accId_old.put(oppy.Id,acc.Id);
        
        //  ClsOppyUtilAPL.PopulateOpptyPartner('INSERT', map_oppId_accId_new, map_oppId_accId_old);
        //  ClsOppyUtilAPL.startDate(list_forecastStructures);
        ClsOppyUtilAPL.buildOppyForeCastMapByYear(oppyForecasts);
        ClsOppyUtilAPL.buildOppyForeCastMap(oppy.Id);
        ClsOppyUtilAPL.getForecastMonthNum(date.today());
        
        set<Id> set_uId = new set<Id>();
        set_uId.add(userinfo.getUserId());
        
        map<Id,set<Id>> map_oppyId_userId = new map<Id,set<Id>>();
        map_oppyId_userId.put(oppy.Id,set_uId);
        
        ClsOppyUtilAPL.grantAccess(map_oppyId_userId);
        
        list<Opportunity> oppys = new list<Opportunity>();
        oppys.add(oppy);
        
        ClsOppyUtilAPL.checkProgramOppyMethod('123', oppys);
        
        List<ClsOpportunityForecastStructure> list_forecastStructures2 = new List<ClsOpportunityForecastStructure>();
        
        //ClsOppyUtilAPL.ValidateApproverPM(list_parts); 
        
        ClsOppyUtilAPL.recalculateRevenue(map_oppyid_opportunity, 'BOM', 'Yearly', date.newInstance(2012, 05, 06));
        
        set<Date> set_startDate = new set<Date>();
        set_startDate.add(date.newInstance(2012, 05, 06));
        ClsOppyUtilAPL.getFiveYearsInternal(set_startDate);
        ClsOppyUtilAPL.getFiveYearsInternal(date.newInstance(2012, 05, 06), 'Yearly');
        
        ClsOppyUtilAPL.updateOpportunityAmounts(map_oppyid_opportunity, 'BOM', 'Yearly', oppy);
        
        set<Opportunity> set_programOppys = new set<Opportunity>();
        set_programOppys.add(oppy);
        ClsOppyUtilAPL.updateProgramTotalFiveYearsAmount(oppy, set_programOppys);
        
        ClsOppyUtilAPL.addOppyOneYear(map_oppyPartId_isoCode, 'EUR', list_forecastStructures2, list_years, '2010', map_partId_oppyId, list_partIds, oppy.Id, rt.Id, rt.Id, 'Monthly');
        ClsOppyUtilAPL.addOppyOneYear(map_oppyPartId_isoCode, 'EUR', list_forecastStructures, list_years, '2010', map_partId_oppyId, list_partIds, oppy.Id, rt.Id, rt.Id, 'Monthly');
        ClsOppyUtilAPL.addOppyOneYear(map_oppyPartId_isoCode, 'EUR', list_forecastStructures, list_years, '2011', map_partId_oppyId, list_partIds, oppy.Id, rt.Id, rt.Id, 'Monthly');
		
        ClsOppyUtilAPL.getIsConvertVal();
        ClsOppyUtilAPL.getOpportunityById(oppy.Id);
		 
        ClsOppyUtilAPL.getOtherYears(list_years);
        ClsOppyUtilAPL.transformIsoCode(1, 'EUR', 'EUR');
        ClsOppyUtilAPL.getOppyForeCastMap(set_oppyIds);
        ClsOppyUtilAPL.calStartDate(list_forecastStructures, 'Monthly');
        ClsOppyUtilAPL.calStartYear(list_forecastStructures);
        ClsOppyUtilAPL.addOppyYears(map_oppyPartId_isoCode, 'EUR',list_forecastStructures, list_years, 2012, map_partId_oppyId, list_partIds, oppy.Id, rt.Id, rt.Id, 'Monthly');
        ClsOppyUtilAPL.addAllOppyYears(map_oppyPartId_isoCode, 'EUR', list_forecastStructures, list_years, 2012, map_partId_oppyId, list_partIds, oppy.Id, rt.Id, rt.Id, 'Monthly');
        Map<Id, Opportunity_Part__c> map_parts = new Map<Id, Opportunity_Part__c>();
        map_parts.put(part.Id,oppypart);
        ClsOpportunityForecastStructure.ForecastItemStructure clsF1 = new ClsOpportunityForecastStructure.ForecastItemStructure('Monthly',part.Id,oppy.Id,rt.Id);
        clsF1.forecast = oppyForecast;
        clsF1.label = 'FM01 Oct';
        clsF1.level = 'Monthly';
        
        ClsOpportunityForecastStructure.ForecastItemStructure clsF2 = new ClsOpportunityForecastStructure.ForecastItemStructure('Yearly',part.Id,oppy.Id,rt.Id);
        clsF2.forecast = oppyForecast;
        clsF2.level = 'Yearly';
        
        ClsOpportunityForecastStructure.ForecastItemStructure clsF3 = new ClsOpportunityForecastStructure.ForecastItemStructure('Yearly',part.Id,oppy.Id,rt.Id);
        clsF3.forecast = oppyForecast;
        clsF3.level = 'Quarterly';
        
        ClsOpportunityForecastStructure.ForecastItemStructure clsF4 = new ClsOpportunityForecastStructure.ForecastItemStructure('Yearly',part.Id,oppy.Id,rt.Id);
        clsF4.forecast = oppyForecast;
        clsF4.level = 'Quarterly';
        
        List<ClsOpportunityForecastStructure.ForecastItemStructure> list_editForecasts = new List<ClsOpportunityForecastStructure.ForecastItemStructure>();
        list_editForecasts.add(clsF1);
        list_editForecasts.add(clsF2);
        list_editForecasts.add(clsF3); 
        list_editForecasts.add(clsF4); 
        ClsOpportunityForecastStructure.ForecastStructure fcs = new ClsOpportunityForecastStructure.ForecastStructure('EUR','EUR',oppyForecasts,oppy.Id,part.Id,'2012',rt.Id,'Monthly');         
        fcs.getEditForecasts();
        fcs.getSalesPriceOF();
        fcs.list_editForecasts = list_editForecasts;
        ClsOppyUtilAPL.transferAllStructures(list_forecastStructures, 'Monthly', 'BOM', map_parts);
        ClsOppyUtilAPL.transferStructure(fcs, 'Monthly');
        ClsOppyUtilAPL.transferStructure(fcs, 'Yearly');
        ClsOppyUtilAPL.transferStructure(fcs, 'Quarterly');
        
        ClsOppyUtilAPL.transferStructureFromOppy(fcs, list_editForecasts, 1.0, 'Monthly');
         list_editForecasts.add(clsF1);
        list_editForecasts.add(clsF2);
        list_editForecasts.add(clsF3); 
        list_editForecasts.add(clsF4);
        List<ClsOpportunityForecastStructure.ForecastStructure> list_pfcs = new List<ClsOpportunityForecastStructure.ForecastStructure>();          
        ClsOpportunityForecastStructure.ForecastStructure fcs1 = new ClsOpportunityForecastStructure.ForecastStructure('EUR','EUR',oppyForecasts,oppy.Id,part.Id,'2012',rt.Id,'Monthly');         
        fcs1.list_editForecasts = list_editForecasts;
        list_pfcs.add(fcs1);
        
        ClsOppyUtilAPL.transferStructureFromPart(fcs1, list_pfcs, 'Monthly');
        ClsOppyUtilAPL.transferStructureFromPart(fcs1, list_pfcs, 'Yearly');
        ClsOppyUtilAPL.transferStructureFromPart(fcs1, list_pfcs, 'Quarterly');
        list_editForecasts.add(clsF1);
        list_editForecasts.add(clsF2);
        list_editForecasts.add(clsF3); 
        list_editForecasts.add(clsF4); 
        fcs1.list_editForecasts = list_editForecasts;
        ClsOppyUtilAPL.convertStructure(fcs1, 'Yearly');
        ClsOppyUtilAPL.updateOpportunityFromForecast(oppy2.Id, rt2.Id);
        ClsOppyUtilAPL.initOppyForecastStructures(map_oppyPartId_isoCode, 'EUR', map_partId_oppyId, list_forecastStructures, list_years, map_year_oppyForecast, map_year_map_partId_oppyForecast, 'Monthly', oppy.Id, rt.Id, rt.Id, list_partIds);
        ClsOpportunityForecastStructure.ForecastStructure inputFS = new ClsOpportunityForecastStructure.ForecastStructure('EUR','EUR',oppyForecasts,oppy.Id,part.Id,'2012',rt2.Id,'Monthly');
        Map<String, ClsOpportunityForecastStructure> map_year_structure = new Map<String, ClsOpportunityForecastStructure>();
        
        map_year_structure.put('2012',cls);
        ClsOppyUtilAPL.resetForecastByMoveDate('2012', inputFS, 1, map_year_structure, 'Monthly', 'Oppy', 1, list_years);
        ClsOppyUtilAPL.yearListIndex(list_years, '2009');
        ClsOppyUtilAPL.yearByIndex(list_years, '2009', 0);
        ClsOppyUtilAPL.yearByIndex(list_years, '2009', -2);
        TOPS_Forecast__c tf = new TOPS_Forecast__c();
        Map<String, List<Opportunity_Forecast__c>> map_yearQuarter_oppyForecasts = new Map<String, List<Opportunity_Forecast__c>>();
        map_yearQuarter_oppyForecasts.put('2012',oppyForecasts);
        ClsOppyUtilAPL.generateForecasts(tf, oppy.Id, oppypart.Id, '2012', 'CY', '', map_yearQuarter_oppyForecasts, 'EUR',rt2.Id);
        ClsOppyUtilAPL.opportunityApprovalFuture(set_oppyIds);
        map<Id,string> map_accId_industry = new map<Id,string>();
            map_accId_industry.put(acc.Id,'bu');
        map<Id,Opportunity> map_oppyId_oppy = new map<Id,Opportunity>();
            map_oppyId_oppy.put(oppy.Id,oppy);
        ClsOppyUtilAPL.checkCrossBu(map_oppyId_oppy, map_accId_industry);
        ClsOppyUtilAPL.recalculateConnectedProgram(new List<Opportunity>{oppy}, null, 'Update',new List<Opportunity>() );
        ClsOppyUtilAPL.recalculateProgramStage(oppy, new Set<String>{'Won'},  new Set<String>{'Won'});
        Set<Id> set_partIds = new Set<Id>();
        set_partIds.add(oppypart.Id);
        ClsOppyUtilAPL.deleteForecastUpdateOppys(set_partIds);
        
        oppypart.Status__c = 'Lost';
        oppypart.Lost_Reason__c = 'Other';
        oppypart.Lost_Reason_Text__c = null;
        update oppypart;
        
        ClsOppyUtilAPL.deleteForecastUpdateOppys(new Set<Id>{oppypart.Id});
        ClsOppyUtilAPL.deleteOppyYear(list_forecastStructures, '2012');
        system.assert(true);
        Test.stopTest();
        
    }

}