objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>Lost_Reason_Text__c</fullName>
        <label>Lost Reason Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Approval criteria not met</fullName>
                </value>
                <value>
                    <fullName>Awaiting customer response</fullName>
                </value>
                <value>
                    <fullName>Awaiting qualification test results</fullName>
                </value>
                <value>
                    <fullName>Customer Program Change/Cancellation</fullName>
                </value>
                <value>
                    <fullName>Customer project on hold</fullName>
                </value>
                <value>
                    <fullName>Customer request</fullName>
                </value>
                <value>
                    <fullName>Lack of TE resources</fullName>
                </value>
                <value>
                    <fullName>Missing customer requirements</fullName>
                </value>
                <value>
                    <fullName>Missing TE requirements</fullName>
                </value>
                <value>
                    <fullName>No potential customer</fullName>
                </value>
                <value>
                    <fullName>PAC decision</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project transfer to different region</fullName>
                </value>
                <value>
                    <fullName>Quote sent, awaiting customer</fullName>
                </value>
                <value>
                    <fullName>TE Engineering resources</fullName>
                </value>
                <value>
                    <fullName>TE portfolio / priority decision</fullName>
                </value>
                <value>
                    <fullName>TE technical solution not competitive</fullName>
                </value>
                <value>
                    <fullName>Timeline</fullName>
                </value>
                <value>
                    <fullName>Customer cancellation</fullName>
                </value>
                <value>
                    <fullName>Replaced by other project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Duplicate part number</fullName>
                </value>
                <value>
                    <fullName>Customer Strategy Change</fullName>
                </value>
                <value>
                    <fullName>Engineering Rejected</fullName>
                </value>
                <value>
                    <fullName>Service/Responsiveness</fullName>
                </value>
                <value>
                    <fullName>Won by other TE Customer</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Price and Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CtrlOppyPartLookupPage_Test.cls
/**
*	This test class is for CtrlOppyPartLookupPage.
*
@author Di Chen
@created 2012-03-14
@version 1.0
@since 20.0
*
@changelog
* 2012-03-14 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 92%
*/
@isTest
private class CtrlOppyPartLookupPage_Test {

    
    
    static testMethod void TestCtrl() {
        
        Account acc = ClsTestHelp.createTestAccounts();
        acc.Name = 'Shadow Fiend';
        acc.Type = 'competitor';
        insert acc;
        
        Opportunity oppy = ClsTestHelp.createTestOpportunity();
        insert oppy;
    	  
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial';
        insert ph;
        
        Part__c p = new Part__c();
    	p.Description__c = 'Sniper';
    	p.Product_Hierarchy__c = ph.Id;
    	insert p;
    	
    	Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
    	oppypart.Opportunity__c = oppy.Id;
    	oppypart.Part__c = p.Id;
    	oppypart.Lost_Reason__c = 'Other';
    	oppypart.Lost_Reason_Text__c = '11';
    	insert oppypart;
    	
        Test.startTest();
        ApexPages.currentPage().getParameters().put('partId',oppypart.Id);
        ApexPages.currentPage().getParameters().put('reason',oppypart.Lost_Reason__c);
        ApexPages.currentPage().getParameters().put('reasonText',oppypart.Lost_Reason_Text__c);
        ApexPages.currentPage().getParameters().put('reasonCompetitor','');
        
        CtrlOppyPartLookupPage ctrl = new CtrlOppyPartLookupPage();
        ctrl.partId = oppypart.Id;
        ctrl.part = oppypart;
        
        CtrlOppyPartLookupPage.competitorValid('Shadow Fiend');
        system.assert(true);
        Test.stopTest();
    }
	static testMethod void TestElse() {
        
        Account acc = ClsTestHelp.createTestAccounts();
        acc.Name = 'Shadow Fiend';
        acc.Type = 'competitor';
       // insert acc;
        
        Account acc2 = ClsTestHelp.createTestAccounts();
        acc2.Name = 'Scofield';
        acc2.Type = 'competitor';
      //  insert acc2;
        
        Account acc3 = ClsTestHelp.createTestAccounts();
        acc3.Name = 'Scofield';
        acc3.Type = 'competitor';
      
        insert new list<account>{acc,acc2,acc3};
            
        Opportunity oppy = ClsTestHelp.createTestOpportunity();
        insert oppy;
    	  
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'CBC1';
        ph.Description__c = 'Industrial';
        insert ph;
        
        Part__c p = new Part__c();
    	p.Description__c = 'Sniper';
    	p.Product_Hierarchy__c = ph.Id;
    	insert p;
    	
    	Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
    	oppypart.Opportunity__c = oppy.Id;
    	oppypart.Part__c = p.Id;
    	oppypart.Lost_Reason__c = 'Other';
    	oppypart.Lost_Reason_Text__c = '11';
    	insert oppypart;
    	
        Test.startTest();
        ApexPages.currentPage().getParameters().put('partId',oppypart.Id);
        ApexPages.currentPage().getParameters().put('reason',oppypart.Lost_Reason__c);
        ApexPages.currentPage().getParameters().put('reasonText',oppypart.Lost_Reason_Text__c);
        
        CtrlOppyPartLookupPage ctrl = new CtrlOppyPartLookupPage();
        ctrl.partId = oppypart.Id;
        ctrl.part = oppypart;
        ctrl.isADM='false';
        
        CtrlOppyPartLookupPage.competitorValid('Scofield');
        system.assert(true);
        
        //testing exception :
        try{
        ApexPages.currentPage().getParameters().put('partId','006123123123123');
        ApexPages.currentPage().getParameters().put('reason',oppypart.Lost_Reason__c);
        ApexPages.currentPage().getParameters().put('reasonText',oppypart.Lost_Reason_Text__c);
        
        CtrlOppyPartLookupPage ctrl1 = new CtrlOppyPartLookupPage();
        ctrl1.partId = oppypart.Id; 
        }
        catch(exception e){
            system.debug(e.getMessage()+' at '+ e.getStackTraceString());
        }
        
        
        
        Test.stopTest();
    }
}