objects/Opportunity_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>CM, Distributor, OEM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Partners</relationshipLabel>
        <relationshipName>Opportunity_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Manager__c</fullName>
        <formula>Account__r.Account_Manager_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Account Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Name__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Number__c</fullName>
        <formula>Account__r.AccountNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <description>Account Information for the selected Partner Account</description>
        <formula>Account__r.Account_Combined_Data__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Account Information for the selected Partner Account</inlineHelpText>
        <label>Partner Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_City__c</fullName>
        <formula>Account__r.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Country__c</fullName>
        <formula>Account__r.BillingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Region__c</fullName>
        <formula>Account__r.Customer_Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Role__c</fullName>
        <label>Partner Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>CM</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Associate</fullName>
                </value>
                <value>
                    <fullName>Contractor (Electrical)</fullName>
                </value>
                <value>
                    <fullName>Contractor (General)</fullName>
                </value>
                <value>
                    <fullName>Owner / Developer</fullName>
                </value>
                <value>
                    <fullName>Engineer / Architect</fullName>
                </value>
                <value>
                    <fullName>Engineer / Procurement / Construction</fullName>
                </value>
                <value>
                    <fullName>Rep Firm</fullName>
                </value>
                <value>
                    <fullName>VAD (Value Added Distributor)</fullName>
                </value>
                <value>
                    <fullName>Utility - IOU</fullName>
                </value>
                <value>
                    <fullName>Utility - Municipal</fullName>
                </value>
                <value>
                    <fullName>Utility - Cooperative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Street__c</fullName>
        <formula>Account__r.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Street</label>
        <type>Text</type>
    </fields>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP-{000000}</displayFormat>
        <label>Opportunity Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Partner_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click the magnifying glass to look up an account.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Roles</relationshipLabel>
        <relationshipName>Partner_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>Click the magnifying glass to look up an Opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partner Roles</relationshipLabel>
        <relationshipName>Partner_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Role</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Partner Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/POSDetails_Extn.cls
public class POSDetails_Extn {

public Opportunity_Partner__c POS {get;set;}
public Boolean NoneFound {get;set;}

    public POSDetails_Extn(ApexPages.StandardController controller) {
        string oppId = apexpages.currentpage().getparameters().get('id');
        POS = new Opportunity_Partner__c();
        NoneFound = true;
        datetime dCreateddate;
        for(Opportunity_Partner__c OP:[select id, name,Account__c, Partner_Account_Number__c, Partner_Street__c,Partner_Account__c,Partner_City__c,
            Partner_Account_Manager__c,Partner_Account_Name__c,Partner_Country__c,Partner_Region__c, Opportunity__r.createddate from Opportunity_Partner__c 
            where Opportunity__c = :oppId and Partner_Role__c='POS'] ){
            NoneFound = false;
            POS = OP;
            dCreateddate = OP.Opportunity__r.createddate;
        }
        if(NoneFound){
            if(dCreateddate >= date.newinstance(6, 7, 2016) )
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please Create POS customer By Clicking on \'Add/ Change POS Customer\' Button')); 
        }
     
    } 

}