objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Order_Date__c</fullName>
        <label>Initial Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Text__c</fullName>
        <label>Lost Reason Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Approval criteria not met</fullName>
                </value>
                <value>
                    <fullName>Awaiting customer response</fullName>
                </value>
                <value>
                    <fullName>Awaiting qualification test results</fullName>
                </value>
                <value>
                    <fullName>Customer Program Change/Cancellation</fullName>
                </value>
                <value>
                    <fullName>Customer project on hold</fullName>
                </value>
                <value>
                    <fullName>Customer request</fullName>
                </value>
                <value>
                    <fullName>Lack of TE resources</fullName>
                </value>
                <value>
                    <fullName>Missing customer requirements</fullName>
                </value>
                <value>
                    <fullName>Missing TE requirements</fullName>
                </value>
                <value>
                    <fullName>No potential customer</fullName>
                </value>
                <value>
                    <fullName>PAC decision</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project transfer to different region</fullName>
                </value>
                <value>
                    <fullName>Quote sent, awaiting customer</fullName>
                </value>
                <value>
                    <fullName>TE Engineering resources</fullName>
                </value>
                <value>
                    <fullName>TE portfolio / priority decision</fullName>
                </value>
                <value>
                    <fullName>TE technical solution not competitive</fullName>
                </value>
                <value>
                    <fullName>Timeline</fullName>
                </value>
                <value>
                    <fullName>Customer cancellation</fullName>
                </value>
                <value>
                    <fullName>Replaced by other project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Duplicate part number</fullName>
                </value>
                <value>
                    <fullName>Customer Strategy Change</fullName>
                </value>
                <value>
                    <fullName>Engineering Rejected</fullName>
                </value>
                <value>
                    <fullName>Service/Responsiveness</fullName>
                </value>
                <value>
                    <fullName>Won by other TE Customer</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Price and Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Confidence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>50/50</fullName>
                </value>
                <value>
                    <fullName>Likely</fullName>
                </value>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <recordTypes>
        <fullName>Extension</fullName>
        <active>true</active>
        <label>Extension</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL old</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts (GPL)</relationshipLabel>
        <relationshipName>Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TrgOppyPart_AIUDUD_getOppyPCD_Test.cls
/**
*	This test class is for opportunityPart_AIUDUD_getOppyProgramCloseDate.
*
@author Di Chen
@created 2012-09-12
@version 1.0
@since 20.0
*
@changelog
* 2012-09-12 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 100%
*/
@isTest(seealldata = true)
private class TrgOppyPart_AIUDUD_getOppyPCD_Test {

    static testMethod void testInsert() {
        
        Profile p = [Select Id, Name From Profile 
     								where Name = 'Production Support' 
     								or Name = 'Service Account' 
     								or Name ='System Administrator' 
     								or Name ='Systemadministrator' limit 1];
     	User u = ClsTestHelp.createTestUsers();
    	u.Email = 'helloManesfd@testCompany1233423.com';
    	u.Alias = 'dpse';
    	u.CommunityNickname = 'TMD';
    	u.ProfileId = p.Id;
		insert u;
    	
    	system.runAs(u){ 
    		
			RecordType rt = ClsTestHelp.createTestRecordType();
			RecordType rt2 = ClsTestHelp.createTestRecordType16();
			
			Account acc = ClsTestHelp.createTestAccounts();
			acc.Type = 'CM';
			insert acc;
	  
	        Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
	        oppy2.Program_level_Forecasting__c =true; 
	        oppy2.Name = 'Pain of Queen';
	        oppy2.Type = 'CM';
	        oppy2.Request_Type__c = 'Extension';
	        oppy2.RecordTypeId = rt2.Id;
	        insert oppy2;  
	        
	        Opportunity oppy = ClsTestHelp.createTestOpportunity();
	        oppy.Program__c = oppy2.Id;   
	        oppy.Type = 'CM';
	        oppy.Request_Type__c = 'Extension';
	        oppy.Method__c = 'BOM';
	        oppy.Level__c = 'Yearly';
	        oppy.Amount = 1;
	        oppy.CurrencyIsoCode = 'EUR';
	        oppy.Five_Year_Revenue__c = 1;
	        oppy2.RecordTypeId = rt2.Id;
	        insert oppy;
	        
	        Product_Hierarchy__c ph = new Product_Hierarchy__c();
	        ph.Hierarchy_Level_Type__c = 'CBC1';
	        ph.Description__c = 'Industrial';
	        insert ph;
	        
	        Part__c part = new Part__c();
	    	part.Description__c = 'Sniper';
	    	part.Product_Hierarchy__c = ph.Id;
	    	insert part;
	    	
	    	Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
	    	oppypart.Opportunity__c = oppy.Id;
	    	oppypart.Part__c = part.Id;
	        oppypart.Status__c = 'Lost';
	    	oppypart.Lost_Reason__c = 'Other';
	    	oppypart.Lost_Reason_Text__c = null;
	    	oppypart.GPL__c = ph.Id;
	    	oppypart.Initial_Order_Date__c = date.today();
	    	
	    	
        	Test.startTest();
        	
    		insert oppypart;
    		
    		oppypart.Status__c = 'Won';
    		update oppypart;
    		
    		delete oppypart;
    		
    		undelete oppypart;
    		
    		Opportunity_Part__c oppypart2 = [select Id,Status__c from Opportunity_Part__c where Id =: oppypart.Id];
        	system.assertEquals('Won', oppypart2.Status__c);
       		Test.stopTest();
        }
    }
}