objects/Opportunity_Part__c.object
<CustomObject>
    <description>This custom object is used instead of standard opportunity product to link products to an opportunity.</description>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Text__c</fullName>
        <label>Lost Reason Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Approval criteria not met</fullName>
                </value>
                <value>
                    <fullName>Awaiting customer response</fullName>
                </value>
                <value>
                    <fullName>Awaiting qualification test results</fullName>
                </value>
                <value>
                    <fullName>Customer Program Change/Cancellation</fullName>
                </value>
                <value>
                    <fullName>Customer project on hold</fullName>
                </value>
                <value>
                    <fullName>Customer request</fullName>
                </value>
                <value>
                    <fullName>Lack of TE resources</fullName>
                </value>
                <value>
                    <fullName>Missing customer requirements</fullName>
                </value>
                <value>
                    <fullName>Missing TE requirements</fullName>
                </value>
                <value>
                    <fullName>No potential customer</fullName>
                </value>
                <value>
                    <fullName>PAC decision</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project transfer to different region</fullName>
                </value>
                <value>
                    <fullName>Quote sent, awaiting customer</fullName>
                </value>
                <value>
                    <fullName>TE Engineering resources</fullName>
                </value>
                <value>
                    <fullName>TE portfolio / priority decision</fullName>
                </value>
                <value>
                    <fullName>TE technical solution not competitive</fullName>
                </value>
                <value>
                    <fullName>Timeline</fullName>
                </value>
                <value>
                    <fullName>Customer cancellation</fullName>
                </value>
                <value>
                    <fullName>Replaced by other project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Duplicate part number</fullName>
                </value>
                <value>
                    <fullName>Customer Strategy Change</fullName>
                </value>
                <value>
                    <fullName>Engineering Rejected</fullName>
                </value>
                <value>
                    <fullName>Service/Responsiveness</fullName>
                </value>
                <value>
                    <fullName>Won by other TE Customer</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Price and Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts</relationshipLabel>
        <relationshipName>Opportunity_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Similar_TE_Part_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Similar TE Part Number</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Opportunity Parts (Similar TE Part Number)</relationshipLabel>
        <relationshipName>Opportunity_Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Confidence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>50/50</fullName>
                </value>
                <value>
                    <fullName>Likely</fullName>
                </value>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Part</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Part Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Part__c.object
<CustomObject>
    <description>This custom object is used for TE Parts instead of standard object &quot;Product2&quot;.</description>
    <fields>
        <fullName>Description__c</fullName>
        <externalId>true</externalId>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GPL old</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts (GPL)</relationshipLabel>
        <relationshipName>Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>GPL</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>This objects contains the product hierarchy from GPL to CBC1.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level_Type__c</fullName>
        <label>Hierarchy Level Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPL</fullName>
                </value>
                <value>
                    <fullName>CBC5</fullName>
                </value>
                <value>
                    <fullName>CBC4</fullName>
                </value>
                <value>
                    <fullName>CBC3</fullName>
                </value>
                <value>
                    <fullName>CBC2</fullName>
                </value>
                <value>
                    <fullName>CBC1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>GPL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CtrlSalesPartPopupPage_Test.cls
/**
*	This test class is for CtrlSalesPartPopupPage.
*
@author Di Chen
@created 2012-03-14
@version 1.0
@since 20.0
*
@changelog
* 2012-03-14 Di Chen <di.chen@itbconsult.com>
* - Created
* - Test coverage 82%
*/
@isTest
private class CtrlSalesPartPopupPage_Test {

    static testMethod void testMostMethods() {
    	
        RecordType rt = ClsTestHelp.createTestRecordType();

		Account acc = ClsTestHelp.createTestAccounts();
		acc.Type = 'CM';
		insert acc;
 
        Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
        oppy2.Program_level_Forecasting__c =true; 
        oppy2.Name = 'Pain of Queen';
        oppy2.Type = 'CM';
        insert oppy2;  
        
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'GPL';
        ph.Description__c = 'Industrial';
        insert ph;
        
        Part__c part = new Part__c();
    	part.Description__c = 'Proposal Part';
    	part.Product_Hierarchy__c = ph.Id;
    	insert part;
    	
    	Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
    	oppypart.Opportunity__c = oppy2.Id;
    	oppypart.Part__c = part.Id;
        oppypart.Status__c = 'Lost';
    	oppypart.Lost_Reason__c = 'Other';
    	oppypart.Lost_Reason_Text__c = null;
    	oppypart.Similar_TE_Part_Number__c = part.Id;
    	oppypart.GPL__c = ph.Id;
    	insert oppypart;
    	
        List<Part__c> list_selectedParts = new List<Part__c>();
        list_selectedParts.add(part);
        
        List<Opportunity_Part__c> list_opportunityPartsProposal = new List<Opportunity_Part__c>();
        list_opportunityPartsProposal.add(oppypart);
        
        List<Opportunity_Part__c> list_savedOppPartsProposal = new List<Opportunity_Part__c>();
        list_savedOppPartsProposal.add(oppypart);
        
        List<CtrlSalesPartPopupPage.SelectPartWrapper> list_selectablePartList = new List<CtrlSalesPartPopupPage.SelectPartWrapper>();
        CtrlSalesPartPopupPage.SelectPartWrapper extSelect = new CtrlSalesPartPopupPage.SelectPartWrapper(part);
        extSelect.part = part;
        extSelect.selected = true;
        list_selectablePartList.add(extSelect);
        
        List<CtrlSalesPartPopupPage.OpportunityPartWrapper> list_singlePageOpportunityParts = new List<CtrlSalesPartPopupPage.OpportunityPartWrapper>();
        CtrlSalesPartPopupPage.OpportunityPartWrapper ctrlOppyPart = new CtrlSalesPartPopupPage.OpportunityPartWrapper(oppypart,1,'TE1','TE2');
        ctrlOppyPart.index = 1;
        ctrlOppyPart.opportunityPart = oppypart;
        ctrlOppyPart.TembPartName = 'TE1';
        ctrlOppyPart.TembSimilarName = 'TE2';
        list_singlePageOpportunityParts.add(ctrlOppyPart);
        
        Test.startTest();
        
        CtrlSalesPartPopupPage ctrl = new CtrlSalesPartPopupPage();
        ctrl.oppPart = oppypart;
        ctrl.searchResultsPageNumber = 1;
        ctrl.list_selectedParts = list_selectedParts;
        ctrl.list_selectablePartList = list_selectablePartList;
        ctrl.list_singlePageOpportunityParts = list_singlePageOpportunityParts;
        ctrl.list_opportunityPartsProposal = list_opportunityPartsProposal;
        ctrl.list_savedOppPartsProposal = list_savedOppPartsProposal;
        
        ctrl.searchResultsPageNumber = 1;
    	ctrl.searchPartNumber = '%1%';
    	ctrl.searchPartDesc = '%11%';
    	ctrl.searchGPL = '%111%';
    	ctrl.searchGPLDesc = '%1111%';
    	ctrl.searchPartNumberLOOKUP = '%2%';
    	ctrl.searchPartDescLOOKUP= '%22%';
    	ctrl.searchGPLLOOKUP = '%222%';
    	ctrl.searchGPLDescLOOKUP = '%2222%';
    	ctrl.searchSOSLLOOKUP = 'Description__c';
    	ctrl.searchSOSL = 'Description__c';
    	ctrl.deleteOpportunityPartIndex = 1;
    	ctrl.deleteOpportunityPartIndexProposal = 1;
    	ctrl.oppPartListPageNumberProposal = 2;
    	ctrl.oppPartListLastPageProposal = 1;
    	
        ctrl.getAmounts();
        ctrl.NewAddProposalParts();
        ctrl.DoAddProposalParts();
        ctrl.AddResultToPartList();
        ctrl.DoAdvancedSearch();
        ctrl.DoSOSLSearch();
        ctrl.DoAdvancedSearchLOOKUP();
        ctrl.DoSOSLSearchLOOKUP();
        ctrl.DoPartNbrSearchLOOKUP();
        ctrl.DoPartNbrSearch();
        ctrl.ClearAllCheckboxes();
        ctrl.SelectAllCheckboxes();
        ctrl.ClearAdvancedSearch();
        ctrl.ClearPartNbrSearch();
        ctrl.OppPartListPreviousPage();
        ctrl.OppPartListNextPage();
        ctrl.OppPartListPreviousPageProposal();
        ctrl.OppPartListNextPageProposal();
        ctrl.JumpToOppPartListPage();
        ctrl.JumpToSearchResultsPage();
        ctrl.GenerateSelectedPartId();
        ctrl.SearchResultsNextPage();
        ctrl.SearchResultsPreviousPage();
        ctrl.ClearAdvancedSearchLOOKUP();
        ctrl.ClearPartNbrSearchLOOKUP();
        ctrl.JumpToOppPartListPageProposal();
        ctrl.DeleteOpportunityParts();
        ctrl.DeleteOpportunityPartsProposal();
        ctrl.SaveOpportunityParts();
        ctrl.SelectSimilarParts();
        ctrl.GotoOpportunity();
        ctrl.DoSaveAndReturn();
        ctrl.DoSearchResultsSort();
        
        CtrlSalesPartPopupPage.SalesOnlyRecordTypeId();
        CtrlSalesPartPopupPage.proposalPartId();
        CtrlSalesPartPopupPage.oppRTId('cap');
        CtrlSalesPartPopupPage.oppRTId('sp');
        CtrlSalesPartPopupPage.oppRTId('nd');
        CtrlSalesPartPopupPage.oppRTId('e');
        
        system.assert(true);
        Test.stopTest();
    }
    
	static testMethod void testLeastMethods() {
    	
        RecordType rt = ClsTestHelp.createTestRecordType();

		Account acc = ClsTestHelp.createTestAccounts();
		acc.Type = 'CM';
		insert acc;
 
        Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
        oppy2.Program_level_Forecasting__c =true; 
        oppy2.Name = 'Pain of Queen';
        oppy2.Type = 'CM';
        insert oppy2;  
        
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'GPL';
        ph.Description__c = 'Industrial';
        insert ph;
        
        Part__c part = new Part__c();
    	part.Description__c = 'Proposal Part';
    	part.Product_Hierarchy__c = ph.Id;
    	insert part;
    	
    	Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
    	oppypart.Opportunity__c = oppy2.Id;
    	oppypart.Part__c = part.Id;
        oppypart.Status__c = 'Lost';
    	oppypart.Lost_Reason__c = 'Other';
    	oppypart.Lost_Reason_Text__c = null;
    	oppypart.Similar_TE_Part_Number__c = null;
    	oppypart.GPL__c = null;
    //	insert oppypart;
    	
        List<Part__c> list_selectedParts = new List<Part__c>();
        list_selectedParts.add(part);
        
        List<CtrlSalesPartPopupPage.SelectPartWrapper> list_selectablePartList = new List<CtrlSalesPartPopupPage.SelectPartWrapper>();
        CtrlSalesPartPopupPage.SelectPartWrapper extSelect = new CtrlSalesPartPopupPage.SelectPartWrapper(part);
        extSelect.part = part;
        extSelect.selected = true;
        list_selectablePartList.add(extSelect);
        
        List<CtrlSalesPartPopupPage.OpportunityPartWrapper> list_singlePageOpportunityParts = new List<CtrlSalesPartPopupPage.OpportunityPartWrapper>();
        CtrlSalesPartPopupPage.OpportunityPartWrapper ctrlOppyPart = new CtrlSalesPartPopupPage.OpportunityPartWrapper(oppypart,1,'TE1','TE2');
        ctrlOppyPart.index = 1;
        ctrlOppyPart.opportunityPart = oppypart;
        ctrlOppyPart.TembPartName = 'TE1';
        ctrlOppyPart.TembSimilarName = 'TE2';
        list_singlePageOpportunityParts.add(ctrlOppyPart);
        
        List<Opportunity_Part__c> list_opportunityPartsProposal = new List<Opportunity_Part__c>();
        list_opportunityPartsProposal.add(oppypart);
        
        List<Opportunity_Part__c> list_savedOppPartsProposal = new List<Opportunity_Part__c>();
        list_savedOppPartsProposal.add(oppypart);
        
        Test.startTest();
        
        CtrlSalesPartPopupPage ctrl = new CtrlSalesPartPopupPage();
        ctrl.oppPart = oppypart;
        ctrl.searchResultsPageNumber = 1;
        ctrl.list_selectedParts = list_selectedParts;
        ctrl.list_selectablePartList = list_selectablePartList;
        ctrl.list_singlePageOpportunityParts = list_singlePageOpportunityParts;
    	ctrl.list_opportunityPartsProposal = list_opportunityPartsProposal;
        ctrl.list_savedOppPartsProposal = list_savedOppPartsProposal;
        
        ctrl.DoSaveAndReturn();
        ctrl.SaveOpportunityParts();
        system.assert(true);
        Test.stopTest();
    }
	static testMethod void testLeastMethods2() {
    	
        RecordType rt = ClsTestHelp.createTestRecordType();

		Account acc = ClsTestHelp.createTestAccounts();
		acc.Type = 'CM';
		insert acc;
 
        Opportunity oppy2 = ClsTestHelp.createTestOpportunity();
        oppy2.Program_level_Forecasting__c =true; 
        oppy2.Name = 'Pain of Queen';
        oppy2.Type = 'CM';
        insert oppy2;  
        
        Product_Hierarchy__c ph = new Product_Hierarchy__c();
        ph.Hierarchy_Level_Type__c = 'GPL';
        ph.Description__c = 'Industrial';
        insert ph;
        
        Part__c part = new Part__c();
    	part.Description__c = 'Proposal Part';
    	part.Product_Hierarchy__c = ph.Id;
    	insert part;
    	
    	Opportunity_Part__c oppypart = ClsTestHelp.createTestOpportunityPart();
    	oppypart.Opportunity__c = oppy2.Id;
    	oppypart.Part__c = part.Id;
        oppypart.Status__c = 'Lost';
    	oppypart.Lost_Reason__c = 'Other';
    	oppypart.Lost_Reason_Text__c = null;
    	oppypart.Similar_TE_Part_Number__c = part.Id;
    	oppypart.GPL__c = ph.Id;
    	insert oppypart;
    	
        List<Part__c> list_selectedParts = new List<Part__c>();
        list_selectedParts.add(part);
        
        List<CtrlSalesPartPopupPage.SelectPartWrapper> list_selectablePartList = new List<CtrlSalesPartPopupPage.SelectPartWrapper>();
        CtrlSalesPartPopupPage.SelectPartWrapper extSelect = new CtrlSalesPartPopupPage.SelectPartWrapper(part);
        extSelect.part = part;
        extSelect.selected = true;
        list_selectablePartList.add(extSelect);
        
        List<CtrlSalesPartPopupPage.OpportunityPartWrapper> list_singlePageOpportunityParts = new List<CtrlSalesPartPopupPage.OpportunityPartWrapper>();
        CtrlSalesPartPopupPage.OpportunityPartWrapper ctrlOppyPart = new CtrlSalesPartPopupPage.OpportunityPartWrapper(oppypart,1,'TE1','TE2');
        ctrlOppyPart.index = 1;
        ctrlOppyPart.opportunityPart = oppypart;
        ctrlOppyPart.TembPartName = 'TE1';
        ctrlOppyPart.TembSimilarName = 'TE2';
        list_singlePageOpportunityParts.add(ctrlOppyPart);
        
        List<Opportunity_Part__c> list_opportunityPartsProposal = new List<Opportunity_Part__c>();
        list_opportunityPartsProposal.add(oppypart);
        
        List<Opportunity_Part__c> list_savedOppPartsProposal = new List<Opportunity_Part__c>();
        list_savedOppPartsProposal.add(oppypart);
        
        Test.startTest();
        
        CtrlSalesPartPopupPage ctrl = new CtrlSalesPartPopupPage();
        ctrl.oppPart = oppypart;
        ctrl.searchResultsPageNumber = 1;
        ctrl.list_selectedParts = list_selectedParts;
        ctrl.list_selectablePartList = list_selectablePartList;
        ctrl.list_singlePageOpportunityParts = list_singlePageOpportunityParts;
    	ctrl.list_opportunityPartsProposal = list_opportunityPartsProposal;
        ctrl.list_savedOppPartsProposal = list_savedOppPartsProposal;
        ctrl.isSaveComplete = false;
        
        ctrl.DoSaveAndReturn();
        system.assert(true);
        Test.stopTest();
    }
}