objects/Overall_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>GAM_Code__c</fullName>
        <label>GAM Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAM Code</label>
        <referenceTo>Sales_Hierarchy__c</referenceTo>
        <relationshipLabel>Overall Forecasts</relationshipLabel>
        <relationshipName>Overall_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Overall Forecast</label>
    <nameField>
        <displayFormat>OverallForecast-{000000000}</displayFormat>
        <label>Overall Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overall Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Overall_Measures__c.object
<CustomObject>
    <fields>
        <fullName>GAM_Code__c</fullName>
        <label>GAM Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Forecast__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Overall Forecast</label>
        <referenceTo>Overall_Forecast__c</referenceTo>
        <relationshipLabel>Overall Measures</relationshipLabel>
        <relationshipName>Overall_Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAM Code</label>
        <referenceTo>Sales_Hierarchy__c</referenceTo>
        <relationshipLabel>Overall Measures</relationshipLabel>
        <relationshipName>Overall_Measures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Total Run Rate</fullName>
                </value>
                <value>
                    <fullName>Remaining Accounts Run Rate</fullName>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Statistical</fullName>
                </value>
                <value>
                    <fullName>Consensus</fullName>
                </value>
                <value>
                    <fullName>Billing (historic)</fullName>
                </value>
                <value>
                    <fullName>Schedule Agreement</fullName>
                </value>
                <value>
                    <fullName>Booking (historic)</fullName>
                </value>
                <value>
                    <fullName>Total Opportunities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Overall Measures</label>
    <nameField>
        <displayFormat>OM-{00000000}</displayFormat>
        <label>Overall Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overall Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Hierarchy__c.object
<CustomObject>
    <description>Reflects the Sales Hierarchy.</description>
    <fields>
        <fullName>Level_7_Assigned_User_Network_Ids__c</fullName>
        <description>List of TE Network Ids for users assigned to this hierarchy level on this territory.</description>
        <inlineHelpText>i.e: US012345;US056789;US010000... etc.</inlineHelpText>
        <label>Level 7 Assigned User Network Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level_7_Assigned_Users__c</fullName>
        <description>List of Salesforce User Ids for users assigned to this hierarchy level on this territory.</description>
        <inlineHelpText>i.e: 005E0000000VsJB;005E0000000VsJ1;005E0000000VsJQ... etc.</inlineHelpText>
        <label>Level 7 Assigned Users</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level_7_Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Default Account Owner</description>
        <label>Level 7 Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Hierarchies_Level7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_7_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Level 7 territory code</inlineHelpText>
        <label>Level 7 Territory Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_7_Territory_Name__c</fullName>
        <label>Level 7 Territory Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Sales Hierarchy</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Hierarchies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UpdateAmountsInOverallMeasures_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest (SeeAllData=true)
private class UpdateAmountsInOverallMeasures_Test {

    static testMethod void TestMethod1() {
        String testGamCode = 'G444TEST';
        
         User me = [ select Id from User where Id = :UserInfo.getUserId() ];
    	User usr = C2ForecastTestHelp.createTestUsers();
    	Sales_Hierarchy__c sh = C2ForecastTestHelp.createTestSalesHierarchy();
    	   
		System.runAs ( me ) {
	    	usr.isActive = true;
	    	insert usr;
		

    	system.debug(' testGamCode ' +testGamCode);
    	sh.Name = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Name__c = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Code__c = testGamCode;
    	sh.Level_7_Assigned_User_Network_Ids__c = usr.EmployeeNumber;
    	//sh.Level_7_Assigned_Users__c = usr.id;
    	sh.Level_7_Default_Owner__c = usr.id;
	    insert sh;

		Account acc = C2ForecastTestHelp.createTestAccounts();
    	acc.recordType = C2ForecastTestHelp.createTestRecordType();
		acc.GAMCD__c = testGamCode;
		acc.accountNumber = '4455:44445555';
		insert acc;

    	Overall_Forecast__c ovF = C2ForecastTestHelp.CreateTestOverallForecast();
    	ovF.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovF.Sales_Hierarchy__c = sh.Id;
    	insert ovF;
    	
    	list<Overall_Measures__c> lst_ovmMesures = new list<Overall_Measures__c>();
   
    	Overall_Measures__c ovMTotalRunRate = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMTotalRunRate.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMTotalRunRate.Sales_Hierarchy__c = sh.Id;
    	ovMTotalRunRate.Type__c ='Total Run Rate';
    	ovMTotalRunRate.Overall_Forecast__c =ovF.Id;
    	insert ovMTotalRunRate;
    	
    	Overall_Measures__c ovMRemainingAccountsRunRate = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMRemainingAccountsRunRate.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMRemainingAccountsRunRate.Sales_Hierarchy__c = sh.Id;
    	ovMRemainingAccountsRunRate.Type__c ='Remaining Accounts Run Rate';
    	ovMRemainingAccountsRunRate.Overall_Forecast__c =ovF.Id;
    	insert ovMRemainingAccountsRunRate;
    	
    	Overall_Measures__c ovMTotalOpportunities = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMTotalOpportunities.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMTotalOpportunities.Sales_Hierarchy__c = sh.Id;
    	ovMTotalOpportunities.Type__c ='Total Opportunities';
    	ovMTotalOpportunities.Overall_Forecast__c =ovF.Id;
    	insert ovMTotalOpportunities;

		set<String> set_gamCode = new set <String>();
		set_gamCode.add(sh.Level_7_Territory_Code__c);
        
        UpdateAmountsInOverallMeasures.getOvForecast(ovMTotalOpportunities);
        UpdateAmountsInOverallMeasures.CaluclateRemainingRunrate(Set_gamCode);
        UpdateAmountsInOverallMeasures.CaluclateTotalRunrate(Set_gamCode);
        }
	}
	 static testMethod void TestMethod2() {
        String testGamCode = 'G444TEST';
        
         User me = [ select Id from User where Id = :UserInfo.getUserId() ];
    	User usr = C2ForecastTestHelp.createTestUsers();
    	Sales_Hierarchy__c sh = C2ForecastTestHelp.createTestSalesHierarchy();
    	   
		System.runAs ( me ) {
	    	usr.isActive = true;
	    	insert usr;
		

    	system.debug(' testGamCode ' +testGamCode);
    	sh.Name = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Name__c = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Code__c = testGamCode;
    	sh.Level_7_Assigned_User_Network_Ids__c = usr.EmployeeNumber;
    	//sh.Level_7_Assigned_Users__c = usr.id;
    	sh.Level_7_Default_Owner__c = usr.id;
	    insert sh;

		Account acc = C2ForecastTestHelp.createTestAccounts();
    	acc.recordType = C2ForecastTestHelp.createTestRecordType();
		acc.GAMCD__c = testGamCode;
		acc.accountNumber = '4455:44445555';
		insert acc;

    	Overall_Forecast__c ovF = C2ForecastTestHelp.CreateTestOverallForecast();
    	ovF.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovF.Sales_Hierarchy__c = sh.Id;
    	insert ovF;
    	
    	list<Overall_Measures__c> lst_ovmMesures = new list<Overall_Measures__c>();
   
    	Overall_Measures__c ovMTotalRunRate = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMTotalRunRate.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMTotalRunRate.Sales_Hierarchy__c = sh.Id;
    	ovMTotalRunRate.Type__c ='Total Run Rate';
    	ovMTotalRunRate.Overall_Forecast__c =ovF.Id;
    	insert ovMTotalRunRate;
    	
    	Overall_Measures__c ovMTotalOpportunities = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMTotalOpportunities.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMTotalOpportunities.Sales_Hierarchy__c = sh.Id;
    	ovMTotalOpportunities.Type__c ='Total Opportunities';
    	ovMTotalOpportunities.Overall_Forecast__c =ovF.Id;
    	insert ovMTotalOpportunities;

		set<String> set_gamCode = new set <String>();
		set_gamCode.add(sh.Level_7_Territory_Code__c);
        
        UpdateAmountsInOverallMeasures.getOvForecast(ovMTotalOpportunities);
        UpdateAmountsInOverallMeasures.CaluclateRemainingRunrate(Set_gamCode);
        UpdateAmountsInOverallMeasures.CaluclateTotalRunrate(Set_gamCode);
        }
	}
	    static testMethod void TestMethod3() {
        String testGamCode = 'G444TEST';
        
         User me = [ select Id from User where Id = :UserInfo.getUserId() ];
    	User usr = C2ForecastTestHelp.createTestUsers();
    	Sales_Hierarchy__c sh = C2ForecastTestHelp.createTestSalesHierarchy();
    	   
		System.runAs ( me ) {
	    	usr.isActive = true;
	    	insert usr;
		

    	system.debug(' testGamCode ' +testGamCode);
    	sh.Name = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Name__c = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Code__c = testGamCode;
    	sh.Level_7_Assigned_User_Network_Ids__c = usr.EmployeeNumber;
    	//sh.Level_7_Assigned_Users__c = usr.id;
    	sh.Level_7_Default_Owner__c = usr.id;
	    insert sh;

		Account acc = C2ForecastTestHelp.createTestAccounts();
    	acc.recordType = C2ForecastTestHelp.createTestRecordType();
		acc.GAMCD__c = testGamCode;
		acc.accountNumber = '4455:44445555';
		insert acc;

    	Overall_Forecast__c ovF = C2ForecastTestHelp.CreateTestOverallForecast();
    	ovF.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovF.Sales_Hierarchy__c = sh.Id;
    	insert ovF;
    	
    	list<Overall_Measures__c> lst_ovmMesures = new list<Overall_Measures__c>();
   
    	
    	Overall_Measures__c ovMRemainingAccountsRunRate = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMRemainingAccountsRunRate.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMRemainingAccountsRunRate.Sales_Hierarchy__c = sh.Id;
    	ovMRemainingAccountsRunRate.Type__c ='Remaining Accounts Run Rate';
    	ovMRemainingAccountsRunRate.Overall_Forecast__c =ovF.Id;
    	insert ovMRemainingAccountsRunRate;
    	
    	Overall_Measures__c ovMTotalOpportunities = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMTotalOpportunities.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMTotalOpportunities.Sales_Hierarchy__c = sh.Id;
    	ovMTotalOpportunities.Type__c ='Total Opportunities';
    	ovMTotalOpportunities.Overall_Forecast__c =ovF.Id;
    	insert ovMTotalOpportunities;

		set<String> set_gamCode = new set <String>();
		set_gamCode.add(sh.Level_7_Territory_Code__c);
        
        UpdateAmountsInOverallMeasures.getOvForecast(ovMTotalOpportunities);
        UpdateAmountsInOverallMeasures.CaluclateRemainingRunrate(Set_gamCode);
        UpdateAmountsInOverallMeasures.CaluclateTotalRunrate(Set_gamCode);
        }
	}
	static testMethod void TestMethod4() {
        String testGamCode = 'G444TEST';
        
         User me = [ select Id from User where Id = :UserInfo.getUserId() ];
    	User usr = C2ForecastTestHelp.createTestUsers();
    	Sales_Hierarchy__c sh = C2ForecastTestHelp.createTestSalesHierarchy();
    	   
		System.runAs ( me ) {
	    	usr.isActive = true;
	    	insert usr;
		

    	system.debug(' testGamCode ' +testGamCode);
    	sh.Name = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Name__c = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Code__c = testGamCode;
    	sh.Level_7_Assigned_User_Network_Ids__c = usr.EmployeeNumber;
    	//sh.Level_7_Assigned_Users__c = usr.id;
    	sh.Level_7_Default_Owner__c = usr.id;
	    insert sh;

		Account acc = C2ForecastTestHelp.createTestAccounts();
    	acc.recordType = C2ForecastTestHelp.createTestRecordType();
		acc.GAMCD__c = testGamCode;
		acc.accountNumber = '4455:44445555';
		insert acc;

    	Overall_Forecast__c ovF = C2ForecastTestHelp.CreateTestOverallForecast();
    	ovF.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovF.Sales_Hierarchy__c = sh.Id;
    	insert ovF;
    	
    	list<Overall_Measures__c> lst_ovmMesures = new list<Overall_Measures__c>();
   
    	set<String> set_gamCode = new set <String>();
		set_gamCode.add(sh.Level_7_Territory_Code__c);
        
     //   UpdateAmountsInOverallMeasures.getOvForecast(ovMTotalOpportunities);
        UpdateAmountsInOverallMeasures.CaluclateRemainingRunrate(Set_gamCode);
        UpdateAmountsInOverallMeasures.CaluclateTotalRunrate(Set_gamCode);
        }
	}
	static testMethod void TestMethod5() {
        String testGamCode = 'G444TEST';
        
         User me = [ select Id from User where Id = :UserInfo.getUserId() ];
    	User usr = C2ForecastTestHelp.createTestUsers();
    	Sales_Hierarchy__c sh = C2ForecastTestHelp.createTestSalesHierarchy();
    	   
		System.runAs ( me ) {
	    	usr.isActive = true;
	    	insert usr;
		

    	system.debug(' testGamCode ' +testGamCode);
    	sh.Name = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Name__c = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Code__c = testGamCode;
    	sh.Level_7_Assigned_User_Network_Ids__c = usr.EmployeeNumber;
    	//sh.Level_7_Assigned_Users__c = usr.id;
    	sh.Level_7_Default_Owner__c = usr.id;
	    insert sh;

		Account acc = C2ForecastTestHelp.createTestAccounts();
    	acc.recordType = C2ForecastTestHelp.createTestRecordType();
		acc.GAMCD__c = testGamCode;
		acc.accountNumber = '4455:44445555';
		insert acc;

    	Overall_Forecast__c ovF = C2ForecastTestHelp.CreateTestOverallForecast();
    	ovF.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovF.Sales_Hierarchy__c = sh.Id;
    	insert ovF;
    	
    	list<Overall_Measures__c> lst_ovmMesures = new list<Overall_Measures__c>();
   
    	Overall_Measures__c ovMTotalRunRate = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMTotalRunRate.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMTotalRunRate.Sales_Hierarchy__c = sh.Id;
    	ovMTotalRunRate.Type__c ='Total Run Rate';
    	ovMTotalRunRate.Overall_Forecast__c =ovF.Id;
    	insert ovMTotalRunRate;
    	
    	

		set<String> set_gamCode = new set <String>();
		set_gamCode.add(sh.Level_7_Territory_Code__c);
        
        UpdateAmountsInOverallMeasures.getOvForecast(ovMTotalRunRate);
        UpdateAmountsInOverallMeasures.CaluclateRemainingRunrate(Set_gamCode);
        UpdateAmountsInOverallMeasures.CaluclateTotalRunrate(Set_gamCode);
        }
	}
	static testMethod void TestMethod6() {
        String testGamCode = 'G444TEST';
        
         User me = [ select Id from User where Id = :UserInfo.getUserId() ];
    	User usr = C2ForecastTestHelp.createTestUsers();
    	Sales_Hierarchy__c sh = C2ForecastTestHelp.createTestSalesHierarchy();
    	   
		System.runAs ( me ) {
	    	usr.isActive = true;
	    	insert usr;
		

    	system.debug(' testGamCode ' +testGamCode);
    	sh.Name = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Name__c = 'nameOfTestRecord'+testGamCode;
    	sh.Level_7_Territory_Code__c = testGamCode;
    	sh.Level_7_Assigned_User_Network_Ids__c = usr.EmployeeNumber;
    	//sh.Level_7_Assigned_Users__c = usr.id;
    	sh.Level_7_Default_Owner__c = usr.id;
	    insert sh;

		Account acc = C2ForecastTestHelp.createTestAccounts();
    	acc.recordType = C2ForecastTestHelp.createTestRecordType();
		acc.GAMCD__c = testGamCode;
		acc.accountNumber = '4455:44445555';
		insert acc;

    	Overall_Forecast__c ovF = C2ForecastTestHelp.CreateTestOverallForecast();
    	ovF.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovF.Sales_Hierarchy__c = sh.Id;
    	insert ovF;
    	
    	list<Overall_Measures__c> lst_ovmMesures = new list<Overall_Measures__c>();
   
    	
    	
    	Overall_Measures__c ovMRemainingAccountsRunRate = C2ForecastTestHelp.CreateTestOverallMeasures();
    	ovMRemainingAccountsRunRate.Gam_Code__c = sh.Level_7_Territory_Code__c;
    	ovMRemainingAccountsRunRate.Sales_Hierarchy__c = sh.Id;
    	ovMRemainingAccountsRunRate.Type__c ='Remaining Accounts Run Rate';
    	ovMRemainingAccountsRunRate.Overall_Forecast__c =ovF.Id;
    	insert ovMRemainingAccountsRunRate;
    	
    	

		set<String> set_gamCode = new set <String>();
		set_gamCode.add(sh.Level_7_Territory_Code__c);
        
        UpdateAmountsInOverallMeasures.getOvForecast(ovMRemainingAccountsRunRate);
        UpdateAmountsInOverallMeasures.CaluclateRemainingRunrate(Set_gamCode);
        UpdateAmountsInOverallMeasures.CaluclateTotalRunrate(Set_gamCode);
        }
	}
	
}