objects/Overall_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>GAM_Code__c</fullName>
        <label>GAM Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Overall Forecast</label>
    <nameField>
        <displayFormat>OverallForecast-{000000000}</displayFormat>
        <label>Overall Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overall Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClsSchedule_UpdateAmountsInOVM.cls
global class ClsSchedule_UpdateAmountsInOVM implements Schedulable {
	list <Period> PeriodObj = [select id , StartDate, Type from Period Where Type = 'Month'];
    list<Date> StartDate = new list<Date>();
    public Date todayDate = Date.Today();
    list <Overall_Forecast__c> lst_ovf = [select id, Gam_Code__c from Overall_Forecast__c];
    set <string> set_GamCode = new set <String>();
	global void execute(SchedulableContext sc) {
		for (Period p: PeriodObj){
        Startdate.add(p.StartDate);
    }
    for (Overall_Forecast__c ovf: lst_ovf){
        set_GamCode.add(ovf.Gam_Code__c);
    }
    for (Date dt: Startdate){
        if (todayDate == dt){
        	UpdateAmountsInOverallMeasures.CaluclateTotalRunrate(set_GamCode);
        	UpdateAmountsInOverallMeasures.CaluclateRemainingRunrate(set_GamCode);
        	}
        }	
	}

}