objects/Part_Activation_Configuration__c.object
<CustomObject>
    <description>This custom object holds one of the record from custom setting for which Batch Job is running.</description>
    <fields>
        <fullName>Conditional_Query__c</fullName>
        <description>This field holds the Query extension string that is appended to the Query in the Batch class. This is initialized from Custom Setting.</description>
        <inlineHelpText>This field holds the Query extension string that is appended to the Query in the Batch class.</inlineHelpText>
        <label>Conditional Query</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_Statement__c</fullName>
        <description>This field holds the CRON Statement. This value is used to schedule the next run of the batch class. Value is updated via Trigger.</description>
        <inlineHelpText>This field holds the CRON Statement.</inlineHelpText>
        <label>Cron Statement</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Object_Number__c</fullName>
        <description>This field holds the index number of Object for which the batch is executing.</description>
        <inlineHelpText>This field holds the index number of Object for which the batch is executing.</inlineHelpText>
        <label>Current Object Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Number_of_Objects__c</fullName>
        <description>This number is the maximum number of Objects on which batch will execute.</description>
        <inlineHelpText>Put a number equal to last index number in the Custom setting OR the number up to which you want to execute the batch class.</inlineHelpText>
        <label>Max Number of Objects</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>This is the API name of the Object on which currently the batch is executing.</description>
        <inlineHelpText>This is the API name of the Object on which currently the batch is executing.</inlineHelpText>
        <label>Object API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Field_API_Name__c</fullName>
        <description>This is the API name of the Object&apos;s field on which currently the batch is executing.</description>
        <inlineHelpText>This is the API name of the Object&apos;s field on which currently the batch is executing.</inlineHelpText>
        <label>Object Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Part Activation Configuration</label>
    <nameField>
        <label>Part Activation Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Activation Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Parts_Activation_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Takes the list of Object API name and Field API name related to Part__c</description>
    <fields>
        <fullName>Conditional_Query__c</fullName>
        <description>This field holds the Query extension string that is appended to the Query in the Batch class.</description>
        <inlineHelpText>This field holds the Query extension string that is appended to the Query in the Batch class.</inlineHelpText>
        <label>Conditional Query</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>Contains the API name of the Object</description>
        <inlineHelpText>Contains the API name of the Object</inlineHelpText>
        <label>Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Field_API_Name__c</fullName>
        <description>Takes the value of the API name of the fields which are the lookup to the Part__c</description>
        <inlineHelpText>Enter the API Name of the Filed which is the Lookup to the Part__c Object</inlineHelpText>
        <label>Object Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Parts Activation Settings</label>
</CustomObject>

classes/Cls_RefreshPartConfig.cls
/***********************************************************************************************************************
      Name : Cls_RefreshPartConfig
       Org : C2S
 Copyright : © 2013 TE Connectivity 
========================================================================================================================
   Summary : This Class gets called from a Custom button which updates the Part Custom Object with Part Custom Setting.
========================================================================================================================
 REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                           
________________________________________________________________________________________________________________________
 VERSION AUTHOR       DATE       DETAIL               User Story #                  
________________________________________________________________________________________________________________________
     1.0 Shantinath   06/19/2013 Initial Development  1177                      
***********************************************************************************************************************/
global class Cls_RefreshPartConfig {
    public static boolean vConfigRefresh = True;
    //METHOD TO REFRESH THE CUSTOM OBJECT RECORD WITH THE CUSTOM SETTING
    webservice static void processDetails(){
        Part_Activation_Configuration__c vPartActiveObj = [SELECT Id, 
                                                                  Current_Object_Number__c,
                                                                  Max_Number_of_Objects__c,
                                                                  Object_API_Name__c,
                                                                  Object_Field_API_Name__c,
                                                                  Cron_Statement__c
                                                             FROM Part_Activation_Configuration__c
                                                            LIMIT 1];
        Parts_Activation_Settings__c vConfig    = Parts_Activation_Settings__c.getValues('1');
        vPartActiveObj.Current_Object_Number__c = Decimal.ValueOf('1');
        vPartActiveObj.Object_API_Name__c       = vConfig.Object_API_Name__c;
        vPartActiveObj.Object_Field_API_Name__c = vConfig.Object_Field_API_Name__c;
        vPartActiveObj.Conditional_Query__c     = vConfig.Conditional_Query__c;
        try {
            vConfigRefresh = false;
            update vPartActiveObj;
        }catch(Exception e) {
            System.debug('Exception in Updating PartConfig '+e);
        }    
    }
    //METHOD TO DELETE OLDER NOTE RECORDS RELATED TO CONFIGURATION RECORD
    webservice static void deleteOldLogs(Id pConfigRecordId){
        if(pConfigRecordId != NULL){
            List<Note> vListNote = [SELECT Id
                                      FROM Note
                                     WHERE ParentId =: pConfigRecordId
                                  ORDER BY CreatedDate DESC
                                    OFFSET 10];  
            if(!vListNote.isEmpty()){
                Delete vListNote;
            }
        }
    }
}