objects/Product_Line_Design__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object helps developers in creating multiple records according to the no.of picklist values in the details object.</description>
    <fields>
        <fullName>PAM__c</fullName>
        <defaultValue>4000</defaultValue>
        <label>PAM per carriage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TAM__c</fullName>
        <defaultValue>8000</defaultValue>
        <label>TAM per Carriage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product Line Design Settings</label>
</CustomObject>

objects/Tender__c.object
<CustomObject>
    <description>This object is used for logging tenders and is the basis for marketing-based reports</description>
    <fields>
        <fullName>Country_of_Service__c</fullName>
        <description>A field for the two-digit code for country</description>
        <inlineHelpText>Please enter the 2-digit country code (e.g. CN for China)</inlineHelpText>
        <label>Country of Service</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Train_Carriages__c</fullName>
        <label>Number of Cars</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Trains__c</fullName>
        <label>Number of Trains</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tender</label>
    <nameField>
        <label>Tender Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tender_Details__c.object
<CustomObject>
    <fields>
        <fullName>PAM__c</fullName>
        <label>PAM per carriage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable Assemblies</fullName>
                </value>
                <value>
                    <fullName>Cable Ident</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics</fullName>
                </value>
                <value>
                    <fullName>Datanet Connectors &amp;  Fiber Optics</fullName>
                </value>
                <value>
                    <fullName>DC Switching Devices</fullName>
                </value>
                <value>
                    <fullName>High Voltage</fullName>
                </value>
                <value>
                    <fullName>Labeling</fullName>
                </value>
                <value>
                    <fullName>Magnetics</fullName>
                </value>
                <value>
                    <fullName>Plastic/Composite Detail Connectors</fullName>
                </value>
                <value>
                    <fullName>Relays &amp; Contactors</fullName>
                </value>
                <value>
                    <fullName>Resistors</fullName>
                </value>
                <value>
                    <fullName>Ruggedized Connectors</fullName>
                </value>
                <value>
                    <fullName>Tubing &amp; Molded Parts</fullName>
                </value>
                <value>
                    <fullName>Wire &amp; Cable</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Signal Connectors</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics Connectors</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics Switching</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TAM__c</fullName>
        <label>TAM per Carriage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tender__c</fullName>
        <label>Tender</label>
        <referenceTo>Tender__c</referenceTo>
        <relationshipLabel>Tender Details</relationshipLabel>
        <relationshipName>Tender_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tender Details</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tender Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TenderDetail_DupCheck_Test.cls
/***********************************************************************************************************************
      Name : TenderDetail_DupCheck_Test
       Org : C2S
 Copyright : © 2013 TE Connectivity 
========================================================================================================================
   Summary : Test class for "TenderDetail_DupCheck" class
========================================================================================================================
 REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                           
________________________________________________________________________________________________________________________
 VERSION AUTHOR       DATE        DETAIL               User Story #                  
________________________________________________________________________________________________________________________
     1.0 Ravi    07/15/2013  Initial Development         1206                     
***********************************************************************************************************************/



@isTest (seealldata=true)
Public Class TenderDetail_DupCheck_Test
{
    public static testMethod void TenderDetail_DupCheck_TestMath()
    {
        List<Product_Line_Design__c> DesignList = new List<Product_Line_Design__c>();
        Product_Line_Design__c NewDesign;
        for(integer ins=0; ins<=14; ins++){
            NewDesign=new Product_Line_Design__c();
            NewDesign.Name='Test Stage'+ins;
            NewDesign.PAM__c=500;
            NewDesign.TAM__c=500;
            DesignList.add(NewDesign);
        }
        insert DesignList;

        List<tender__c> lstTender = new List<tender__c>();
        tender__c t1 = new tender__c();
        t1.name = 'test';
        t1.Country_of_Service__c ='us';
        t1.Number_of_Trains__c=2;
        t1.Number_of_Train_Carriages__c=3;
        lstTender.add(t1);
        
        tender__c t2 = new tender__c();
        t2.name = 'test';
        t2.Country_of_Service__c ='us';
        t2.Number_of_Trains__c=2;
        t2.Number_of_Train_Carriages__c=3;
        lstTender.add(t2);
        insert lstTender;
        
        List<Tender_Details__c> TDSList = new List<Tender_Details__c>();
        Tender_Details__c T;
        for(Integer ins=0; ins<=DesignList.size()-1; ins++){
            T=new Tender_Details__c();
            T.Product_Line__c=DesignList[ins].Name;
            T.PAM__c=DesignList[ins].PAM__c;            
            T.TAM__c=DesignList[ins].TAM__c;
            T.Tender__c=lstTender[0].id;
            TDSList.add(T);     
            
            T=new Tender_Details__c();
            T.Product_Line__c=DesignList[ins].Name;
            T.PAM__c=DesignList[ins].PAM__c;            
            T.TAM__c=DesignList[ins].TAM__c;
            T.Tender__c=lstTender[1].id;
            TDSList.add(T);     
        }
        insert TDSList;

        
        //ApexPages.StandardController controller = new ApexPages.StandardController(t1);
        //Tenderdetailpickedlist TenderDetailAct=new Tenderdetailpickedlist(controller);
        Test.starttest();
        TenderDetail_DupCheck.FindDuplicateDetailsIns(TDSList);
        Test.stoptest();
    }    
}