objects/SIP__c.object
<CustomObject>
    <description>object for Industrial to manage the sales incentive plans for the Industrial sales users - populated by a workflow</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person to approve the SIP PLan</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SIP1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The TE person who participates in the plan</description>
        <label>Plan Participant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SIP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Year__c</fullName>
        <description>the Plan Year</description>
        <label>Plan Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                    <default>true</default>
                    <label>2018</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIP_master_record__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>defines the related master record which contains important information for the letter and the calculations</description>
        <label>plan master record</label>
        <referenceTo>SIP_master__c</referenceTo>
        <relationshipLabel>SIP</relationshipLabel>
        <relationshipName>SIP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>SIP</label>
    <nameField>
        <label>SIP Plan</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIP</pluralLabel>
    <recordTypes>
        <fullName>AM_Plan</fullName>
        <active>true</active>
        <description>Plan for Account Managers</description>
        <label>AM Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>FE_Plan</fullName>
        <active>true</active>
        <description>Plan for Field engineers</description>
        <label>FE Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>GAM_Plan</fullName>
        <active>true</active>
        <description>plan for GAM&apos;s</description>
        <label>GAM Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sales_Manager_Plan</fullName>
        <active>true</active>
        <description>Plan for Sales Managers</description>
        <label>Sales Manager Plan</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SIP_master__c.object
<CustomObject>
    <description>object related to the SIP object to store some common master data  like payout% per region or texts for the different templates</description>
    <label>SIP master</label>
    <nameField>
        <label>SIP master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIP masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Te_Network_Id__c</fullName>
        <description>This field contains the users TE Network Id.</description>
        <label>Te Network Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TrgSIP_AI_Test.cls
/**
*  This test class used to test class ExtRecalculateBudget.
*
@author Lili Zhao
@created 2013-08-28
@version 1.0
@since 27.0
*
@changelog
* coverage 81% 
* 
* 
2013-08-28 Lili Zhao <lili.zhao@itbconsult.com>
* - Created
*/
@isTest 
private class TrgSIP_AI_Test {

    static testMethod void myUnitTest() {
    	test.startTest(); 
    	User user = new User();
		user=ClsTestHelp.createTestUsers();
		user.Te_Network_Id__c = 'testUser';
		insert user;
		
		String recordTypeAM;
		String recordTypeFE;
		String recordTypeGAM;
		String recordTypeMM;
		
		for (RecordType recordType : [select Id, Name, DeveloperName from RecordType where SobjectType = 'SIP__c' and IsActive = true and (DeveloperName = 'AM_plan' or DeveloperName = 'FE_Plan' or DeveloperName = 'GAM_plan' or DeveloperName = 'Sales_Manager_Plan')]) {
			if(recordType.DeveloperName == 'AM_plan'){
				recordTypeAM = recordType.Id;				
			} else if(recordType.DeveloperName == 'FE_Plan') {				
				recordTypeFE = recordType.Id;
			}else if (recordType.DeveloperName == 'GAM_plan') {				
				recordTypeGAM = recordType.Id;
			}else {			
				recordTypeMM = recordType.Id;
			}
		}
		
		SIP_master__c sipMaster = new SIP_master__c();
		sipMaster.Name = 'Test Master';
		insert sipMaster;
		
    	SIP__c sipAM = new SIP__c();
		sipAM.Plan_Participant__c = user.Id;
		sipAM.RecordTypeId = recordTypeAM;
		sipAM.Plan_Year__c = '2013';
		sipAM.Name = 'test AM';
		sipAM.Approver__c = user.Id;
		sipAM.SIP_master_record__c = sipMaster.Id;
		
		insert sipAM;
    	test.stopTest();       
    }
    static testMethod void myUnitTest2() {
    	test.startTest(); 
    	User user = new User();
		user=ClsTestHelp.createTestUsers();
		user.Te_Network_Id__c = 'testUser';
		user.ManagerId = UserInfo.getUserId();
		insert user;
		
		String recordTypeAM;
		String recordTypeFE;
		String recordTypeGAM;
		String recordTypeMM;
		
		for (RecordType recordType : [select Id, Name, DeveloperName from RecordType where SobjectType = 'SIP__c' and IsActive = true and (DeveloperName = 'AM_plan' or DeveloperName = 'FE_Plan' or DeveloperName = 'GAM_plan' or DeveloperName = 'Sales_Manager_Plan')]) {
			if(recordType.DeveloperName == 'AM_plan'){
				recordTypeAM = recordType.Id;				
			} else if(recordType.DeveloperName == 'FE_Plan') {				
				recordTypeFE = recordType.Id;
			}else if (recordType.DeveloperName == 'GAM_plan') {				
				recordTypeGAM = recordType.Id;
			}else {			
				recordTypeMM = recordType.Id;
			}
		}
		
		SIP_master__c sipMaster = new SIP_master__c();
		sipMaster.Name = 'Test Master';
		insert sipMaster;
		
    	SIP__c sipAM = new SIP__c();
		sipAM.Plan_Participant__c = user.Id;
		sipAM.RecordTypeId = recordTypeAM;
		sipAM.Plan_Year__c = '2013';
		sipAM.Name = 'test AM';
		sipAM.SIP_master_record__c = sipMaster.Id;
		
		insert sipAM;
    	test.stopTest();
        
    }
}