objects/Task__x.object
<CustomObject>
    <externalDataSource>TSOrg_ScheduleBatch</externalDataSource>
    <externalName>Task</externalName>
    <fields>
        <fullName>LastModifiedDate__c</fullName>
        <externalDeveloperName>LastModifiedDate</externalDeveloperName>
        <label>Last Modified Date</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OpportunityID_of_C2S_c__c</fullName>
        <externalDeveloperName>OpportunityID_of_C2S__c</externalDeveloperName>
        <label>OpportunityID of C2S</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage_c__c</fullName>
        <externalDeveloperName>Opportunity_Stage__c</externalDeveloperName>
        <label>Opportunity Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Value_c__c</fullName>
        <externalDeveloperName>Opportunity_Value__c</externalDeveloperName>
        <label>Opportunity Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <externalDeveloperName>OpportunityID_of_C2S__c</externalDeveloperName>
        <label>Opportunity</label>
        <length>255</length>
        <referenceTargetField>Opportunity.TS_TaskId__c</referenceTargetField>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks1</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_c__c</fullName>
        <externalDeveloperName>Opportunity__c</externalDeveloperName>
        <label>Opportunity$</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Task</label>
    <pluralLabel>Tasks</pluralLabel>
</CustomObject>

classes/ICT_CreateTaskInC2S.cls
global class ICT_CreateTaskInC2S implements Database.Batchable<sObject>{ 
    
    global ICT_CreateTaskInC2S(){ 
        
    } 
    List<Opportunity> oplist = new List<Opportunity>();
    List<Task> tsklist = new List<Task>();
    List<string> opliststr = new List<string>();
    List<integer> tsklistintr = new List<integer>();
    List<string> opliststr1 = new List<string>();
    List<integer> tsklistintr2 = new List<integer>();
    List<string> opliststr3 = new List<string>();
    List<integer> tsklistintr4 = new List<integer>();
    List<string> opliststr5 = new List<string>();
    List<integer> tsklistintr6 = new List<integer>();
    List<string> opliststr7 = new List<string>();
    List<integer> tsklistintr8 = new List<integer>();
    List<string> opliststr9 = new List<string>();
    List<integer> tsklistintr10 = new List<integer>();
    
    
    
    
    global Iterable<SObject> start(Database.BatchableContext BC){ 
        
        return Database.getQueryLocator('select id,TS_TaskId__c, StageName,Amount from Opportunity where TS_TaskId__c!=null'); 
    } 
    
    
    global void execute(Database.BatchableContext BC, List<Opportunity> scope) { 
        List<Task__x> tslist =new List<Task__x>();
        
        tslist = [select OpportunityID_of_C2S_c__c,Opportunity_c__c, Opportunity_Value_c__c,Opportunity_Stage_c__c,Opportunity__c from Task__x where OpportunityID_of_C2S_c__c <> '' and Lastmodifieddate__c=today];
        
        
        for(Opportunity t: scope)
        {
            system.debug('t.id...'+t.Id);
            for(Task__x ts : tslist){
            
                
               // if((String.valueOf(t.Id).substring(0, 15)).equals(ts.OpportunityID_of_C2S_c__c)){
                if(t.Id.equals(ts.OpportunityID_of_C2S_c__c))
                   {
                        if(ts.Opportunity_c__c!=null)
                        {
                        
                       
                       t.Amount = ts.Opportunity_c__c;
                       }
                      
                      if(ts.Opportunity_Stage_c__c !=null)
                      {
                        t.StageName = ts.Opportunity_Stage_c__c; 
                        
                      }
                     oplist.add(t);
                    
                    
                    
                  
                }
            }     
        }
        
        try
        {
            update oplist; 
            
        }
        catch(Exception e) 
        {
            system.debug('An Error has Occured. Error:' +e); 
            
        } 
    }
    
    global void finish(Database.BatchableContext BC){ 
    
       
        
    }  
}