objects/Tender__c.object
<CustomObject>
    <description>This object is used for logging tenders and is the basis for marketing-based reports</description>
    <label>Tender</label>
    <nameField>
        <label>Tender Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenders</pluralLabel>
    <recordTypes>
        <fullName>Tender</fullName>
        <active>true</active>
        <label>Tender</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tender_Competitor__c.object
<CustomObject>
    <description>This object is used to define the main competitors in a Tender</description>
    <fields>
        <fullName>Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field is used for the entering Allocation percentage valule for the competitor</description>
        <label>Allocation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_line__c</fullName>
        <description>contains Product line values</description>
        <label>Product line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable Ident</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics Connectors</fullName>
                </value>
                <value>
                    <fullName>DC Switching Devices</fullName>
                </value>
                <value>
                    <fullName>High Voltage</fullName>
                </value>
                <value>
                    <fullName>Relays &amp; Contactors</fullName>
                </value>
                <value>
                    <fullName>Resistors</fullName>
                </value>
                <value>
                    <fullName>Ruggedized Connectors</fullName>
                </value>
                <value>
                    <fullName>Wire &amp; Cable</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics Switching</fullName>
                </value>
                <value>
                    <fullName>Signal Connectors</fullName>
                </value>
                <value>
                    <fullName>Tubing &amp; Molded Parts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TAM_Per_Car__c</fullName>
        <description>contains the value TAM Per Car(from Tender details)*Allocation value</description>
        <label>TAM Per Car</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TAM_Tender_Total__c</fullName>
        <description>Contains The value TAM _Tender_Total(from tender details) * Allocation</description>
        <label>TAM Tender Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tender__c</fullName>
        <description>Lookup to Tender</description>
        <label>Tender</label>
        <referenceTo>Tender__c</referenceTo>
        <relationshipLabel>Tender Competitors</relationshipLabel>
        <relationshipName>Tender_Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tender Competitor</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Tender Competitor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tender Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tender_Details__c.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable Assemblies</fullName>
                </value>
                <value>
                    <fullName>Cable Ident</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics</fullName>
                </value>
                <value>
                    <fullName>Datanet Connectors &amp;  Fiber Optics</fullName>
                </value>
                <value>
                    <fullName>DC Switching Devices</fullName>
                </value>
                <value>
                    <fullName>High Voltage</fullName>
                </value>
                <value>
                    <fullName>Labeling</fullName>
                </value>
                <value>
                    <fullName>Magnetics</fullName>
                </value>
                <value>
                    <fullName>Plastic/Composite Detail Connectors</fullName>
                </value>
                <value>
                    <fullName>Relays &amp; Contactors</fullName>
                </value>
                <value>
                    <fullName>Resistors</fullName>
                </value>
                <value>
                    <fullName>Ruggedized Connectors</fullName>
                </value>
                <value>
                    <fullName>Tubing &amp; Molded Parts</fullName>
                </value>
                <value>
                    <fullName>Wire &amp; Cable</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Signal Connectors</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics Connectors</fullName>
                </value>
                <value>
                    <fullName>Datanet &amp; Fiber Optics Switching</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tender__c</fullName>
        <label>Tender</label>
        <referenceTo>Tender__c</referenceTo>
        <relationshipLabel>Tender Details</relationshipLabel>
        <relationshipName>Tender_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tender Details</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tender Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Cls_tender_details_update.cls
/***********************************************************************************************************************
      Name : Cls_tender_details_update
       Org : C2S
 Copyright : © 2013 TE Connectivity 
========================================================================================================================
   Summary : This Class updates the Tender Competitor fields based on the  tender detail fields And Called by 
              TenderDetail_BIU Trigger 
========================================================================================================================
 REQUIREMENT INFORMATION & DEVELOPMENT INFORMATION:                                                           
________________________________________________________________________________________________________________________
 VERSION AUTHOR       DATE        DETAIL               User Story #                  
________________________________________________________________________________________________________________________
     1.0 Ravi    08/14/2013   Initial Development         Tender Competitor
***********************************************************************************************************************/


public class Cls_tender_details_update
{
    public static void update_tender_Competitor(List<Tender_Details__c > lst_td)
    { 
        set<Id> tenderIds = new set<Id>();
        set<string> picklist = new set<string>();
    
    for(Tender_Details__c td:lst_td)
    {
        tenderIds.add(td.tender__C);
        picklist.add(td.Product_Line__c);
    
    }
        list<Tender_Competitor__c> updatetc = [select Id,Product_Line__c,TAM_Per_Car__c,TAM_Tender_Total__c,tender__C,Allocation__c 
        from Tender_Competitor__c where tender__C in:tenderIds and Product_Line__c in:picklist];
    
    if(!updatetc.isempty())
        
        update updatetc;
    
    }
}